// Related: yangglue.go -- the generator these tests call as a function

package yangglue

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fixture builds a checkout holding two yang/ directories, one excluded tree
// and the registry package the generator must never write into.
func fixture(t *testing.T) string {
	t.Helper()

	root := t.TempDir()
	write(t, root, "go.mod", "module example.test/glue\n\ngo 1.26\n")
	write(t, root, "feature-gates.txt", "")
	write(t, root, "internal/plugins/host/yang/ze-host-cmd.yang", "module ze-host-cmd {}\n")
	write(t, root, "internal/plugins/host/yang/ze-host.yang", "module ze-host {}\n")
	write(t, root, "internal/component/bgp/yang/ze-bgp.yang", "module ze-bgp {}\n")
	// The registry package: it holds a .yang file and is still not a schema
	// package, so a walk that writes into it would rewrite the registry.
	write(t, root, "internal/component/config/yang/ze-registry.yang", "module ze-registry {}\n")
	// internal/test/ is fixture data for the test suites, never a schema.
	write(t, root, "internal/test/fake/yang/ze-fake.yang", "module ze-fake {}\n")
	// Any testdata subtree is parser input even when its fixture path contains
	// an internal/component/.../yang shape.
	write(t, root, "internal/le/migration/testdata/case/internal/component/demo/yang/ze-demo.yang",
		"module ze-demo {}\n")

	return root
}

func write(t *testing.T, root, rel, content string) {
	t.Helper()

	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("create the fixture directory for %s: %v", rel, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write the fixture %s: %v", rel, err)
	}
}

// VALIDATES: the walk finds every yang/ directory holding a .yang file, and
// excludes the registry package and both fixture tree shapes.
// PREVENTS: glue generated into internal/component/config/yang, which is the
// registry the glue registers into, or into parser fixtures that are data
// rather than schema.
func TestDiscoverFindsSchemaDirectoriesAndExcludesTwo(t *testing.T) {
	root := fixture(t)

	dirs, err := discover(root)
	if err != nil {
		t.Fatalf("discover: %v", err)
	}

	got := make([]string, 0, len(dirs))
	for _, dir := range dirs {
		rel, relErr := filepath.Rel(root, dir)
		if relErr != nil {
			t.Fatalf("relativize %s: %v", dir, relErr)
		}
		got = append(got, filepath.ToSlash(rel))
	}

	want := []string{"internal/component/bgp/yang", "internal/plugins/host/yang"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("the walk found %v, want %v", got, want)
	}
}

// VALIDATES: the generated embed.go and register.go carry the exact bytes the
// committed glue holds.
// PREVENTS: a rewritten generator that regenerates every schema package in the
// tree on its first run, which turns one edit into a 200-file diff.
func TestGeneratedGlueIsByteExact(t *testing.T) {
	files := []string{"ze-host-cmd.yang", "ze-host.yang"}

	wantEmbed := "// Code generated by ./le yang-glue write; DO NOT EDIT.\n" +
		"\npackage yang\n\nimport _ \"embed\"\n" +
		"\n//go:embed ze-host-cmd.yang\nvar ZeHostCmdYANG string\n" +
		"\n//go:embed ze-host.yang\nvar ZeHostYANG string\n"
	if got := string(embedSource(files)); got != wantEmbed {
		t.Errorf("embed.go is\n%q\nwant\n%q", got, wantEmbed)
	}

	wantRegister := "// Code generated by ./le yang-glue write; DO NOT EDIT.\n" +
		"\npackage yang\n\nimport (\n\tconfigyang \"example.test/glue/internal/component/config/yang\"\n)\n" +
		"\nfunc init() {\n" +
		"\tconfigyang.RegisterModule(\"ze-host-cmd.yang\", ZeHostCmdYANG)\n" +
		"\tconfigyang.RegisterModule(\"ze-host.yang\", ZeHostYANG)\n}\n"
	if got := string(registerSource(files, "example.test/glue")); got != wantRegister {
		t.Errorf("register.go is\n%q\nwant\n%q", got, wantRegister)
	}
}

// VALIDATES: a file name becomes the Go variable name the acronym table
// declares, and an unlisted word is title-cased.
// PREVENTS: a renamed variable, which breaks the embed directive that names it
// and every RegisterModule call beside it.
func TestVarNameReadsTheAcronymTable(t *testing.T) {
	cases := map[string]string{
		"ze-host-cmd.yang":   "ZeHostCmdYANG",
		"ze-bgp.yang":        "ZeBGPYANG",
		"ze-ospfv3.yang":     "ZeOSPFv3YANG",
		"ze-flowexport.yang": "ZeFlowExportYANG",
		"ze-.yang":           "ZeYANG",
	}
	for name, want := range cases {
		if got := varName(name); got != want {
			t.Errorf("%s becomes %s, want %s", name, got, want)
		}
	}
}

// VALIDATES: check reports every generated file that disagrees with its
// sources, naming it relative to the tree, and answers 1.
// PREVENTS: a check that reports a count without saying which file, which leaves
// a developer running the generator to find out.
func TestCheckNamesEveryStaleFile(t *testing.T) {
	root := fixture(t)

	report, code := runCheck(root)
	if code != 1 {
		t.Fatalf("check over an ungenerated tree answered %d, want 1", code)
	}
	if report.Dirs != 2 {
		t.Errorf("check read %d directories, want 2", report.Dirs)
	}
	want := []string{
		"internal/component/bgp/yang/embed.go",
		"internal/component/bgp/yang/register.go",
		"internal/plugins/host/yang/embed.go",
		"internal/plugins/host/yang/register.go",
	}
	if strings.Join(report.Stale, ",") != strings.Join(want, ",") {
		t.Fatalf("check named %v, want %v", report.Stale, want)
	}
}

// VALIDATES: check writes nothing.
// PREVENTS: a verification gate that repairs the tree it is judging, so the
// second run passes and nobody learns the first one was stale.
func TestCheckWritesNothing(t *testing.T) {
	root := fixture(t)

	if _, code := runCheck(root); code != 1 {
		t.Fatalf("check answered %d, want 1", code)
	}
	if _, err := os.Stat(filepath.Join(root, "internal", "plugins", "host", "yang", "embed.go")); !os.IsNotExist(err) {
		t.Fatalf("check created embed.go: %v", err)
	}
}

// VALIDATES: write generates the glue, and check then passes over the same tree.
// PREVENTS: a generator whose output its own check rejects, which is the pair
// disagreeing about what current means.
func TestWriteThenCheckAgree(t *testing.T) {
	root := fixture(t)

	written, code := runWrite(root)
	if code != 0 {
		t.Fatalf("write answered %d, want 0", code)
	}
	if len(written.Written) != 4 {
		t.Errorf("write reported %d files, want 4: %v", len(written.Written), written.Written)
	}

	report, code := runCheck(root)
	if code != 0 {
		t.Fatalf("check after write answered %d, want 0; stale: %v", code, report.Stale)
	}
}

// VALIDATES: write skips a file whose bytes already agree, so a second run
// reports nothing written.
// PREVENTS: a generator that rewrites every file on every run, which makes
// `./le yang-glue write` touch mtimes the build cache reads.
func TestWriteIsIdempotent(t *testing.T) {
	root := fixture(t)

	if _, code := runWrite(root); code != 0 {
		t.Fatal("the first write failed")
	}
	again, code := runWrite(root)
	if code != 0 {
		t.Fatalf("the second write answered %d, want 0", code)
	}
	if len(again.Written) != 0 {
		t.Errorf("the second write rewrote %v, want nothing", again.Written)
	}
}

// VALIDATES: a tree the walk cannot read stops the run and answers 1, rather
// than reporting that no schema package needs glue.
// PREVENTS: the fail-open a --check invites. A walk that reads nothing and a
// tree that owes nothing produce the same empty answer, and only one of them is
// a pass.
func TestATreeTheWalkCannotReadStopsTheRun(t *testing.T) {
	// A checkout with no internal/ at all. WalkDir hands the callback the
	// Lstat error, which is permission-independent, so this reddens for root
	// as well. It is the tree a tool reaches when it is pointed at the wrong
	// directory, and it must not look like a tree that owes no glue.
	root := t.TempDir()
	write(t, root, "go.mod", "module example.test/gone\n\ngo 1.26\n")

	if _, err := discover(root); err == nil {
		t.Fatal("the walk answered no error for a tree it could not read")
	}

	report, code := runCheck(root)
	if code != 1 {
		t.Fatalf("check over an unreadable tree answered %d, want 1", code)
	}
	if report.Dirs != 0 || len(report.Stale) != 0 {
		t.Errorf("check answered a report for a tree it could not read: %+v", report)
	}
}

// VALIDATES: a tree holding no schema package is reported and answers 0, which
// is what the script does.
// PREVENTS: a behavior change nobody asked for. The port's job is to move the
// tool, and this is the one branch where the answer looks like a hole.
func TestATreeWithNoSchemaPackageIsReported(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", "module example.test/empty\n\ngo 1.26\n")
	write(t, root, "internal/component/keep.go", "package component\n")

	report, code := runCheck(root)
	if code != 0 {
		t.Fatalf("a tree with no schema package answered %d, want 0", code)
	}
	if report.Dirs != 0 {
		t.Errorf("the check read %d directories, want 0", report.Dirs)
	}
	if !strings.Contains(report.Text(), "no yang/ directories with .yang files found") {
		t.Errorf("the report does not say the tree holds no schema package:\n%s", report.Text())
	}
}

// VALIDATES: both answers render themselves as actionable native verdicts.
// PREVENTS: a report a developer cannot read at a terminal, which is what a bare
// table of a struct is for a two-field verdict.
func TestBothReportsRenderNativeWording(t *testing.T) {
	current := CheckReport{Dirs: 12}
	if got := current.Text(); got != "./le yang-glue check: 12 yang/ directories are current\n" {
		t.Errorf("a current check renders %q", got)
	}

	stale := CheckReport{Dirs: 2, Stale: []string{"a/embed.go", "b/register.go"}}
	want := "stale: a/embed.go\nstale: b/register.go\n./le yang-glue check: 2 generated files are stale; run ./le yang-glue write\n"
	if got := stale.Text(); got != want {
		t.Errorf("a stale check renders\n%q\nwant\n%q", got, want)
	}

	written := WriteReport{Dirs: 3, Written: []string{"a/embed.go"}}
	if got := written.Text(); got != "./le yang-glue write: generated glue for 3 yang/ directories\n" {
		t.Errorf("a write renders %q", got)
	}
}
