// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import (
	// The packages registering the modules these modules import.
	_ "github.com/ze-software/ze/internal/component/bgp/yang"

	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-bmp-cmd.yang", ZeBMPCmdYANG)
	configyang.RegisterModule("ze-bmp-conf.yang", ZeBMPConfYANG)
}
