// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-firewall-irr-cmd.yang
var ZeFirewallIrrCmdYANG string

//go:embed ze-firewall-irr.yang
var ZeFirewallIrrYANG string
