// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import (
	// The packages registering the modules these modules import.
	_ "github.com/ze-software/ze/internal/component/cmd/clear/yang"
	_ "github.com/ze-software/ze/internal/component/cmd/show/yang"
	_ "github.com/ze-software/ze/internal/component/iface/yang"

	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-vrrp-cmd.yang", ZeVrrpCmdYANG)
	configyang.RegisterModule("ze-vrrp-conf.yang", ZeVrrpConfYANG)
}
