// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import (
	configyang "codeberg.org/thomas-mangin/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-vrrp-cmd.yang", ZeVrrpCmdYANG)
	configyang.RegisterModule("ze-vrrp-conf.yang", ZeVrrpConfYANG)
}
