// Design: docs/architecture/config/transaction-protocol.md -- config transaction event types
// Related: orchestrator.go -- uses these event types for stream emit/subscribe
// Related: types.go -- event payload types delivered with these event types

// Package transaction implements the stream-based config transaction protocol.
// It defines event type constants, event payload types, and the transaction
// orchestrator that coordinates verify/apply/rollback across plugins via the
// stream system in internal/component/plugin/server/dispatch.go.
package transaction

import (
	"fmt"
	"strings"

	"codeberg.org/thomas-mangin/ze/internal/component/plugin"
)

// Namespace re-exported for transaction code clarity.
const Namespace = plugin.NamespaceConfig

// Engine -> plugin event type bases. Per-plugin variants are registered
// dynamically at plugin start as "<base>-<plugin>" (e.g. "verify-bgp").
const (
	EventVerify   = plugin.EventConfigVerify
	EventApply    = plugin.EventConfigApply
	EventRollback = plugin.EventConfigRollback
)

// Engine -> plugins broadcast event types.
const (
	EventVerifyAbort = plugin.EventConfigVerifyAbort
	EventCommitted   = plugin.EventConfigCommitted
	EventApplied     = plugin.EventConfigApplied
	EventRolledBack  = plugin.EventConfigRolledBack
)

// Plugin -> engine ack event types.
const (
	EventVerifyOK     = plugin.EventConfigVerifyOK
	EventVerifyFailed = plugin.EventConfigVerifyFailed
	EventApplyOK      = plugin.EventConfigApplyOK
	EventApplyFailed  = plugin.EventConfigApplyFailed
	EventRollbackOK   = plugin.EventConfigRollbackOK
)

// ReservedPluginNames are plugin names that would cause per-plugin event
// types generated by EventVerifyFor/EventApplyFor to collide with broadcast
// or ack event types. Engine MUST reject plugin registration with these
// names before calling EventVerifyFor or EventApplyFor.
//
// Collision map:
//
//	"ok"     -> verify-ok, apply-ok, rollback-ok  (ack events)
//	"failed" -> verify-failed, apply-failed       (ack events)
//	"abort"  -> verify-abort                      (broadcast event)
var ReservedPluginNames = map[string]bool{
	"ok":     true,
	"failed": true,
	"abort":  true,
}

// ValidatePluginName returns an error if name cannot be used as a per-plugin
// event type suffix. Phase 4 orchestrator wiring MUST call this before
// invoking EventVerifyFor or EventApplyFor so that broadcast/ack event types
// and per-plugin event types cannot collide in the stream system event
// registry.
func ValidatePluginName(name string) error {
	if name == "" {
		return fmt.Errorf("plugin name must not be empty")
	}
	if strings.ContainsAny(name, " \t\n\r") {
		return fmt.Errorf("plugin name %q must not contain whitespace", name)
	}
	if ReservedPluginNames[name] {
		return fmt.Errorf("plugin name %q is reserved: collides with a broadcast or ack event type", name)
	}
	return nil
}

// EventVerifyFor returns the per-plugin verify event type for the named plugin.
// Engine registers this dynamically when the plugin starts.
// Caller MUST call ValidatePluginName(name) first; passing a reserved name
// produces a string that collides with a broadcast or ack event type.
func EventVerifyFor(name string) string {
	return EventVerify + "-" + name
}

// EventApplyFor returns the per-plugin apply event type for the named plugin.
// Engine registers this dynamically when the plugin starts.
// Caller MUST call ValidatePluginName(name) first; passing a reserved name
// produces a string that collides with a broadcast or ack event type.
func EventApplyFor(name string) string {
	return EventApply + "-" + name
}

// Failure codes for transaction ack events.
// Plugins include a code in their ack to indicate the severity of failure.
const (
	CodeOK        = "ok"        // Success.
	CodeTimeout   = "timeout"   // Plugin did not respond in time (set by engine).
	CodeTransient = "transient" // Temporary failure, retry may succeed.
	CodeError     = "error"     // Permanent failure, rollback needed.
	CodeBroken    = "broken"    // Plugin state is corrupt, restart needed.
)

// MaxBudgetSeconds is the maximum allowed verify or apply budget.
// Budgets exceeding this are capped to this value.
const MaxBudgetSeconds = 600
