// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-rib-cmd.yang
var ZeRibCmdYANG string

//go:embed ze-rib-poolstats-cmd.yang
var ZeRibPoolStatsCmdYANG string
