package config

import (
	// Schema packages for YANG module registration needed by config tests.
	// Import schemas directly (not plugin/all) to avoid import cycles
	// with cmd packages that import plugin/server which imports config.
	_ "codeberg.org/thomas-mangin/ze/internal/component/api/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/authz/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/adj_rib_in/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/cmd/monitor/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/cmd/peer/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/cmd/raw/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/cmd/rib/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/cmd/update/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/filter_community/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/gr/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/healthcheck/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/hostname/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/llnh/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/rib/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/role/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/route_refresh/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/rpki/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/rpki_decorator/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/plugins/softver/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/cache/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/commit/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/del/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/log/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/meta/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/metrics/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/set/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/show/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/subscribe/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/cmd/update/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/config/system/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/hub/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/iface/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/lg/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/mcp/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/plugin/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/resolve/cmd/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/resolve/dns/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/ssh/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/telemetry/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/component/web/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/core/ipc/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/fibkernel/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/fibp4/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/sysrib/schema"
)
