// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-bgp-cmd-peer-api.yang
var ZeBGPCmdPeerAPIYANG string

//go:embed ze-peer-cmd.yang
var ZePeerCmdYANG string
