// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-traffic-cmd.yang", ZeTrafficCmdYANG)
}
