global_defs {
    router_id KEEPALIVED_DEMO
    enable_script_security
}

vrrp_instance gateway {
    state BACKUP
    interface eth0
    virtual_router_id 10
    priority 100
    advert_int 1
    use_vmac vrrp.10
    virtual_ipaddress {
        192.0.2.1/24
    }
}
