environment {
    ssh {
        enabled enable
        server main { ip 127.0.0.1; port 2222; }
    }
}

interface {
    backend netlink
    ethernet eth0 {
        unit 0 {
            ipv4 {
                address [ 192.0.2.251/24 ]
                vrrp {
                    group gateway {
                        vrid 10
                        virtual-address [ 192.0.2.1 ]
                        priority 200
                        advertise-interval-milliseconds 1000
                    }
                }
            }
        }
    }
}
