//go:build linux

// Design: docs/architecture/config/syntax.md -- resolv.conf generation

package system

import (
	"fmt"
	"os"
	"strings"

	"github.com/ze-software/ze/internal/core/textbuf"
)

// WriteResolvConf writes DNS server addresses to the given path.
// The file is written atomically (write tmp + rename) to avoid partial
// reads by other processes. Each server becomes a "nameserver" line.
// Does nothing if servers is empty or path is empty.
func WriteResolvConf(path string, servers []string) error {
	if len(servers) == 0 || path == "" {
		return nil
	}

	var b textbuf.Buffer
	b.Reset()
	b.Str("# Generated by ze\n")
	for _, s := range servers {
		if strings.ContainsAny(s, "\n\r") {
			continue
		}
		b.Str("nameserver ").Str(s).Byte('\n')
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, b.Bytes(), 0o644); err != nil { //nolint:gosec // resolv.conf is world-readable by convention
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename %s -> %s: %w", tmp, path, err)
	}
	return nil
}
