//go:build linux

package system

import (
	"fmt"
	"os"
	"strings"
)

// WriteResolvConf writes DNS server addresses to the given path.
// The file is written atomically (write tmp + rename) to avoid partial
// reads by other processes. Each server becomes a "nameserver" line.
// Does nothing if servers is empty or path is empty.
func WriteResolvConf(path string, servers []string) error {
	if len(servers) == 0 || path == "" {
		return nil
	}

	var b strings.Builder
	b.WriteString("# Generated by ze\n")
	for _, s := range servers {
		if strings.ContainsAny(s, "\n\r") {
			continue
		}
		fmt.Fprintf(&b, "nameserver %s\n", s)
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil { //nolint:gosec // resolv.conf is world-readable by convention
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename %s -> %s: %w", tmp, path, err)
	}
	return nil
}
