// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-pppoe-api.yang
var ZePPPoEAPIYANG string

//go:embed ze-pppoe-conf.yang
var ZePPPoEConfYANG string
