# Fuzz tests: Go fuzzing targets
#
# Quick reference:
#   make ze-fuzz-test                        All targets, 10s each
#   make ze-fuzz-one FUZZ=FuzzName PKG=path  Single target, 30s default

.PHONY: ze-fuzz-test ze-fuzz-one

# Run ze fuzz tests (all targets, 10s each)
# Note: multiple fuzz tests per package require individual enumeration (-fuzz=. fails with "matches more than one").
# Exact package paths avoid Go fuzz's "multiple packages" error where a tree has subpackages.
ze-fuzz-test:
	@echo "Running ze fuzz tests..."
	$(GO_TEST) -fuzz=FuzzParseOrigin -fuzztime=10s -timeout=60s ./internal/core/bgp/attribute/...
	$(GO_TEST) -fuzz=FuzzParseMED -fuzztime=10s -timeout=60s ./internal/core/bgp/attribute/...
	$(GO_TEST) -fuzz=FuzzParseLocalPref -fuzztime=10s -timeout=60s ./internal/core/bgp/attribute/...
	$(GO_TEST) -fuzz=FuzzParseASPath -fuzztime=10s -timeout=60s ./internal/core/bgp/attribute/...
	$(GO_TEST) -fuzz=FuzzParseCommunity -fuzztime=10s -timeout=60s ./internal/core/bgp/attribute/...
	$(GO_TEST) -fuzz=FuzzParseLargeCommunity -fuzztime=10s -timeout=60s ./internal/core/bgp/attribute/...
	$(GO_TEST) -fuzz=FuzzParseExtCommunity -fuzztime=10s -timeout=60s ./internal/core/bgp/attribute/...
	$(GO_TEST) -fuzz=FuzzRewriteASPath -fuzztime=10s -timeout=60s ./internal/component/bgp/wireu/...
	$(GO_TEST) -fuzz=FuzzParseNLRIs -fuzztime=10s -timeout=60s ./internal/component/bgp/wireu/...
	$(GO_TEST) -fuzz=FuzzParseAttributes -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/rib/storage/...
	$(GO_TEST) -fuzz=FuzzHandleRoundTrip -fuzztime=10s -timeout=60s ./internal/component/bgp/attrpool/...
	$(GO_TEST) -fuzz=FuzzInvalidHandle -fuzztime=10s -timeout=60s ./internal/component/bgp/attrpool/...
	$(GO_TEST) -fuzz=FuzzParseHeader -fuzztime=10s -timeout=60s ./internal/component/bgp/message/...
	$(GO_TEST) -fuzz=FuzzUnpackOpen -fuzztime=10s -timeout=60s ./internal/component/bgp/message/...
	$(GO_TEST) -fuzz=FuzzUnpackUpdate -fuzztime=10s -timeout=60s ./internal/component/bgp/message/...
	$(GO_TEST) -fuzz=FuzzUnpackNotification -fuzztime=10s -timeout=60s ./internal/component/bgp/message/...
	$(GO_TEST) -fuzz=FuzzUnpackRouteRefresh -fuzztime=10s -timeout=60s ./internal/component/bgp/message/...
	$(GO_TEST) -fuzz=FuzzChunkMPNLRI -fuzztime=10s -timeout=60s ./internal/component/bgp/message/...
	$(GO_TEST) -fuzz=FuzzParseIPv4Prefixes -fuzztime=10s -timeout=60s ./internal/component/bgp/wireu/...
	$(GO_TEST) -fuzz=FuzzParseIPv6Prefixes -fuzztime=10s -timeout=60s ./internal/component/bgp/wireu/...
	$(GO_TEST) -fuzz=FuzzParsePrefixes -fuzztime=10s -timeout=60s ./internal/component/bgp/wireu/...
	$(GO_TEST) -fuzz=FuzzParseRouteDistinguisher -fuzztime=10s -timeout=60s ./internal/core/bgp/nlri
	$(GO_TEST) -fuzz=FuzzParseRDString -fuzztime=10s -timeout=60s ./internal/core/bgp/nlri
	$(GO_TEST) -fuzz=FuzzParseLabelStack -fuzztime=10s -timeout=60s ./internal/core/bgp/nlri
	$(GO_TEST) -fuzz=FuzzParseVPN$$ -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/vpn/...
	$(GO_TEST) -fuzz=FuzzParseVPNAddPath -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/vpn/...
	$(GO_TEST) -fuzz=FuzzParseEVPN -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/evpn/...
	$(GO_TEST) -fuzz=FuzzParseFlowSpec$$ -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/flowspec/...
	$(GO_TEST) -fuzz=FuzzParseFlowSpecIPv6 -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/flowspec/...
	$(GO_TEST) -fuzz=FuzzParseFlowSpecVPN -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/flowspec/...
	$(GO_TEST) -fuzz=FuzzParseBGPLS$$ -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/ls/...
	$(GO_TEST) -fuzz=FuzzParseBGPLSWithRest -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/ls/...
	$(GO_TEST) -fuzz=FuzzParseMUP -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/mup/...
	$(GO_TEST) -fuzz=FuzzParseMVPN -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/mvpn/...
	$(GO_TEST) -fuzz=FuzzParseRTC -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/rtc/...
	$(GO_TEST) -fuzz=FuzzParseVPLS -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/vpls/...
	$(GO_TEST) -fuzz=FuzzScanner -fuzztime=10s -timeout=60s ./internal/component/bgp/textparse/...
	$(GO_TEST) -fuzz=FuzzConfigParser -fuzztime=10s -timeout=60s ./internal/component/config
	$(GO_TEST) -fuzz=FuzzTokenizer -fuzztime=10s -timeout=60s ./internal/component/config
	$(GO_TEST) -fuzz=FuzzParseMessageHeader -fuzztime=10s -timeout=60s ./internal/component/l2tp
	$(GO_TEST) -fuzz=FuzzAVPIterator -fuzztime=10s -timeout=60s ./internal/component/l2tp
	$(GO_TEST) -fuzz=FuzzHiddenDecrypt -fuzztime=10s -timeout=60s ./internal/component/l2tp
	$(GO_TEST) -fuzz=FuzzOnReceiveSequence -fuzztime=10s -timeout=60s ./internal/component/l2tp
	$(GO_TEST) -fuzz=FuzzAttrTLVParse -fuzztime=10s -timeout=60s ./internal/component/bgp/plugins/nlri/ls/...
	$(GO_TEST) -fuzz=FuzzAuthDigest -fuzztime=10s -timeout=60s ./internal/component/bfd/auth/...
	$(GO_TEST) -fuzz=FuzzParseControl -fuzztime=10s -timeout=60s ./internal/component/bfd/packet/...
	$(GO_TEST) -fuzz=FuzzParseAuth -fuzztime=10s -timeout=60s ./internal/component/bfd/packet/...
	$(GO_TEST) -fuzz=FuzzEncodeDecode -fuzztime=10s -timeout=60s ./internal/component/config/secret/...
	$(GO_TEST) -fuzz=FuzzParseFrame -fuzztime=10s -timeout=60s ./internal/component/l2tp/ppp/...
	$(GO_TEST) -fuzz=FuzzParseLCPPacket -fuzztime=10s -timeout=60s ./internal/component/l2tp/ppp/...
	$(GO_TEST) -fuzz=FuzzParseLCPOptions -fuzztime=10s -timeout=60s ./internal/component/l2tp/ppp/...
	$(GO_TEST) -fuzz=FuzzParseLCPEchoMagic -fuzztime=10s -timeout=60s ./internal/component/l2tp/ppp/...
	$(GO_TEST) -fuzz=FuzzParseCHAPResponse -fuzztime=10s -timeout=60s ./internal/component/l2tp/ppp/...
	$(GO_TEST) -fuzz=FuzzParsePAPRequest -fuzztime=10s -timeout=60s ./internal/component/l2tp/ppp/...
	$(GO_TEST) -fuzz=FuzzParseMSCHAPv2Response -fuzztime=10s -timeout=60s ./internal/component/l2tp/ppp/...
	$(GO_TEST) -fuzz=FuzzTacacsPacketUnmarshal -fuzztime=10s -timeout=60s ./internal/component/tacacs
	$(GO_TEST) -fuzz=FuzzTacacsEncryptDecrypt -fuzztime=10s -timeout=60s ./internal/component/tacacs
	$(GO_TEST) -fuzz=FuzzFSMEventSequence -fuzztime=10s -timeout=60s ./internal/component/bgp/fsm
	$(GO_TEST) -fuzz=FuzzDecode -fuzztime=10s -timeout=60s ./internal/plugins/vrrp/packet/...

# Run a single fuzz target for longer (usage: make ze-fuzz-one FUZZ=FuzzParseNLRIs PKG=./internal/component/bgp/wireu/... TIME=30s)
FUZZ ?= FuzzParseNLRIs
PKG  ?= ./internal/component/bgp/wireu/...
TIME ?= 30s

ze-fuzz-one:
	$(GO_TEST) -fuzz=$(FUZZ) -fuzztime=$(TIME) $(PKG)
