// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import (
	// The packages registering the modules these modules import.
	_ "github.com/ze-software/ze/internal/component/traffic/yang"

	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-traffic-usage-cmd.yang", ZeTrafficUsageCmdYANG)
	configyang.RegisterModule("ze-traffic-usage-conf.yang", ZeTrafficUsageConfYANG)
}
