environment {
    ssh {
        enabled enable
        server main {
            ip 127.0.0.1
            port 2222
        }
    }
}

plugin {
    internal bgp-rib {
        use bgp-rib
    }
}

bgp {
    router-id 192.0.2.1
    session {
        asn {
            local 65000
        }
    }
    peer stale-prefix-data {
        connection {
            remote {
                ip 127.0.0.2
                port 1179
            }
            local {
                ip 127.0.0.1
            }
        }
        session {
            asn {
                local 65000
                remote 65001
            }
            family {
                ipv4/unicast {
                    prefix {
                        maximum 10000
                        updated 2024-01-01
                    }
                }
            }
            capability {
                graceful-restart disable
            }
        }
        behavior {
            group-updates disable
        }
        attach process bgp-rib {
            receive [ update state refresh ]
            send [ update ]
        }
    }
}
