// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-iface-api.yang
var ZeIfaceAPIYANG string

//go:embed ze-iface-cmd.yang
var ZeIfaceCmdYANG string

//go:embed ze-iface-conf.yang
var ZeIfaceConfYANG string

//go:embed ze-iface-interface-cmd.yang
var ZeIfaceInterfaceCmdYANG string

//go:embed ze-iface-monitor-cmd.yang
var ZeIfaceMonitorCmdYANG string

//go:embed ze-iface-show-cmd.yang
var ZeIfaceShowCmdYANG string
