#!/usr/bin/env python3

import time

from zebgp_api import ready, send, wait_for_shutdown


def main() -> None:
    ready()

    messages = [
        'neighbor 127.0.0.1 update text nhop set 101.1.101.1 nlri ipv4/unicast add 1.1.0.0/24',
        'neighbor 127.0.0.1 router-id 1.2.3.4, neighbor 127.0.0.1 update text nhop set 101.1.101.1 nlri ipv4/unicast add 1.1.0.0/25',
        'update text nlri ipv4/unicast del 1.1.0.0/24',
    ]

    for message in messages:
        send(message)
        time.sleep(0.2)

    wait_for_shutdown()


if __name__ == '__main__':
    main()
