#!/usr/bin/env python3

import time

from exabgp_api import ready, send, wait_for_ack, wait_for_shutdown


def main() -> None:
    ready()

    messages = [
        'neighbor 127.0.0.1 update text nhop set self nlri ipv4/unicast add 1.1.0.0/16',
        'update text nhop set self nlri ipv4/unicast add 2.2.0.0/16',
        'update text nhop set 127.0.0.1 nlri ipv4/unicast add 2.2.0.1/32',
        'update text nhop set self nlri ipv4/unicast add 2.2.0.1/32',
        'update text nhop set self nlri ipv4/unicast add 2.2.0.1/32',
        'update text nhop set self nlri ipv4/unicast add 3.3.0.3/32',  # Non duplicate route, signals server that test is over
    ]

    for message in messages:
        send(message)
        time.sleep(0.2)

    wait_for_ack(expected_count=6)
    wait_for_shutdown()


if __name__ == '__main__':
    main()
