#!/usr/bin/env python3

import time

from zebgp_api import ready, send, wait_for_ack, wait_for_shutdown


def main() -> None:
    ready()

    messages = [
        'update text nhop set 4.0.0.0 nlri ipv4/unicast add 3.0.0.0/24',
    ]

    for message in messages:
        send(message)
        time.sleep(0.2)

    wait_for_ack(expected_count=1)
    wait_for_shutdown()


if __name__ == '__main__':
    main()
