// Design: docs/features/interfaces.md -- DNS resolver config from DHCP
// Overview: dhcp_linux.go -- DHCP client types and lifecycle

//go:build linux

package ifacedhcp

import (
	"fmt"
	"os"
	"strings"
)

// resolvConfPath is the path to the resolv.conf file written by DHCP.
// /tmp is used because gokrazy's rootfs is read-only SquashFS and /etc
// is not writable. On non-gokrazy Linux systems, /tmp/resolv.conf still
// works but is not the standard location (/etc/resolv.conf). A future
// YANG leaf under dhcp could make this configurable.
const resolvConfPath = "/tmp/resolv.conf"

// writeResolvConf writes the given DNS server addresses to the default
// resolv.conf path. Delegates to writeResolvConfTo for testability.
func writeResolvConf(servers []string) error {
	return writeResolvConfTo(resolvConfPath, servers)
}

// writeResolvConfTo writes DNS server addresses to the given path.
// The file is written atomically (write tmp + rename) to avoid partial
// reads by other processes. Each server becomes a "nameserver" line.
func writeResolvConfTo(path string, servers []string) error {
	if len(servers) == 0 {
		return nil
	}

	var b strings.Builder
	b.WriteString("# Generated by ze DHCP client\n")
	for _, s := range servers {
		fmt.Fprintf(&b, "nameserver %s\n", s)
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil { //nolint:gosec // resolv.conf is world-readable by convention
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename %s -> %s: %w", tmp, path, err)
	}
	return nil
}

// clearResolvConfAt removes the resolv.conf at the given path. Missing
// files are not an error. Used by tests; production code does not clear
// resolv.conf on individual lease expiry (stale DNS is better than no DNS
// when multiple interfaces may have active leases).
func clearResolvConfAt(path string) error {
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove %s: %w", path, err)
	}
	return nil
}
