// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-ospf-cmd.yang", ZeOSPFCmdYANG)
	configyang.RegisterModule("ze-ospf-conf.yang", ZeOSPFConfYANG)
}
