environment {
    ssh {
        enabled enable
        server main {
            ip 127.0.0.1
            port 2222
        }
    }
}

plugin {
    internal bgp-adj-rib-in {
        use bgp-adj-rib-in
    }
    internal bgp-rpki {
        use bgp-rpki
    }
}

bgp {
    router-id 192.0.2.1
    session {
        asn {
            local 65000
        }
    }
    rpki {
        cache-server 127.0.0.3 {
            port 3323
        }
        validation-timeout 5
        action {
            invalid reject
            not-found accept
        }
    }
    peer rpki-source {
        connection {
            remote {
                ip 127.0.0.2
                port 1179
            }
            local {
                ip 127.0.0.1
            }
        }
        session {
            asn {
                local 65000
                remote 65001
            }
            family {
                ipv4/unicast {
                    prefix {
                        maximum 100
                    }
                }
            }
        }
        process bgp-rpki {
            receive [ update ]
        }
        process bgp-adj-rib-in {
            receive [ update state ]
        }
    }
}
