frr defaults traditional
hostname frr-bfd
service integrated-vtysh-config
log file /tmp/frr-bfd.log informational
!
interface eth0
!
bfd
 profile fast
  transmit-interval 300
  receive-interval 300
  detect-multiplier 3
 !
 peer 172.30.0.2
  profile fast
 !
!
