environment {
    ssh {
        enabled enable
        server main { ip 127.0.0.1; port 2222; }
    }
}

bfd {
    enabled true
    profile fast {
        detect-multiplier 3
        desired-min-tx-us 300000
        required-min-rx-us 300000
    }
}

bgp {
    peer edge-peer {
        connection {
            remote { ip 172.30.0.3; port 1179; }
            local { ip 172.30.0.2; accept false; }
            bfd {
                enabled true
                mode single-hop
                profile fast
            }
        }
        timer { receive-hold-time 300; }
        session {
            asn { local 65001; remote 65002; }
            router-id 172.30.0.2
            family { ipv4/unicast { prefix { maximum 10000; } } }
            capability { graceful-restart disable; }
        }
        behavior { group-updates disable; }
    }
}
