// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-refresh-cmd.yang", ZeRefreshCmdYANG)
	configyang.RegisterModule("ze-route-refresh-api.yang", ZeRouteRefreshAPIYANG)
	configyang.RegisterModule("ze-route-refresh.yang", ZeRouteRefreshYANG)
}
