environment {
    cli {
        format {
            default table
        }
    }
    ssh {
        enabled enable
        server main {
            ip 127.0.0.1
            port 2222
        }
    }
}

system {
    host edge-01
    domain lab.example
}

plugin {
    internal bgp-rib {
        use bgp-rib
    }
}

bgp {
    router-id 192.0.2.1
    session {
        asn {
            local 65000
        }
    }
    peer transit-a {
        connection {
            remote {
                ip 192.0.2.2
            }
            local {
                ip 192.0.2.1
            }
        }
        session {
            asn {
                local 65000
                remote 65001
            }
            family {
                ipv4/unicast {
                    prefix {
                        maximum 1000000
                    }
                }
            }
        }
        process bgp-rib {
            receive [ update state ]
        }
    }
    peer transit-b {
        connection {
            remote {
                ip 198.51.100.2
            }
            local {
                ip 198.51.100.1
            }
        }
        session {
            asn {
                local 65000
                remote 65002
            }
            family {
                ipv4/unicast {
                    prefix {
                        maximum 1000000
                    }
                }
            }
        }
        process bgp-rib {
            receive [ update state ]
        }
    }
}
