// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-host-cmd.yang
var ZeHostCmdYANG string

//go:embed ze-host-set-cmd.yang
var ZeHostSetCmdYANG string
