// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-host-cmd.yang", ZeHostCmdYANG)
	configyang.RegisterModule("ze-host-set-cmd.yang", ZeHostSetCmdYANG)
}
