// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import (
	configyang "codeberg.org/thomas-mangin/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-bgp-cmd-subscribe-api.yang", ZeBGPCmdSubscribeAPIYANG)
	configyang.RegisterModule("ze-cli-subscribe-cmd.yang", ZeCliSubscribeCmdYANG)
}
