# Ze IKE image for IPsec interop lab.
# Expects a pre-built linux binary at test/ipsec-interop/ze-linux.
# Build with: CGO_ENABLED=0 GOOS=linux go build -o test/ipsec-interop/ze-linux ./cmd/ze

FROM alpine:3.21

RUN apk add --no-cache tini iproute2

COPY test/ipsec-interop/ze-linux /usr/local/bin/ze

ENTRYPOINT ["tini", "--", "ze"]
