// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-cli-show-api.yang
var ZeCliShowAPIYANG string

//go:embed ze-cli-show-cmd.yang
var ZeCliShowCmdYANG string
