// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-cli-show-api.yang", ZeCliShowAPIYANG)
	configyang.RegisterModule("ze-cli-show-cmd.yang", ZeCliShowCmdYANG)
}
