//go:build integration && linux

// Design: docs/guide/rsvp-te.md, independent RSVP-TE peer carrier.
//
// freeRouter originates the LSP and forwards its ICMP echo replies over it to
// Ze's Linux egress. The echo requests use ordinary IP in the other direction.
// Disabling MPLS input must prevent delivery despite captured labelled replies;
// enabling it must deliver every reply with the label advertised in Ze's RESV.
// Removing the peer tunnel must send PathTear and withdraw Ze's pop route before
// the advertised soft-state lifetime. No RSVP packet is generated by this test.
//
// The reverse signalling direction is deliberately not claimed. The pinned
// peer requires SESSION_ATTRIBUTE on PATH and ADSPEC on PathTear, which Ze's
// ordinary local tunnel does not emit. See test/interop-rsvpte/ and the guide.
package rsvpte

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/vishvananda/netlink"
	"github.com/vishvananda/netns"
	"golang.org/x/sys/unix"
)

const rsvpFreeRevision = "6c295d8ae79c834ef631d3d21d373c335fb05328"
const rsvpFreeLocal = "198.18.0.1"
const rsvpFreePeer = "198.18.0.2"
const rsvpFreeData = "198.18.1.1"

var rsvpFreePeerDir = flag.String("rsvp-freertr-peer-dir", "", "Explicit directory exported from test/interop-rsvpte/Dockerfile.freertr")
var rsvpFreeZe = flag.String("rsvp-freertr-ze", "", "Explicit current Linux Ze daemon for freeRouter RSVP interoperability")
var rsvpFreeJava = flag.String("rsvp-freertr-java", "", "Java 21+ executable for freeRouter (defaults to PATH java after opt-in)")

// VALIDATES: an independent ingress negotiates an IPv4 point-to-point LSP,
// uses the negotiated label for delivered traffic, and withdraws its state.
// PREVENTS: counting a RESV or a visible MPLS frame as successful forwarding,
// ordinary-IP fallback satisfying the delivery assertion, and expiry hiding a
// broken peer-driven PathTear path. This does not establish transit or FRR.
func TestRSVPFreeRouterInterop(t *testing.T) {
	if *rsvpFreePeerDir == "" && *rsvpFreeZe == "" && *rsvpFreeJava == "" {
		t.Skip("opt in with -rsvp-freertr-peer-dir and -rsvp-freertr-ze; see docs/guide/rsvp-te.md")
	}
	if *rsvpFreePeerDir == "" || *rsvpFreeZe == "" {
		t.Fatal("both -rsvp-freertr-peer-dir and -rsvp-freertr-ze are required after opting in")
	}
	startedAt := time.Now()
	lab := newRSVPFreeLab(t)
	path, label := lab.reservation(t)
	lab.wait(t, "Ze egress pop route", 10*time.Second, func() bool { return lab.hasPop(t, label) })
	lab.wait(t, "peer return route through its established tunnel", 15*time.Second, func() bool {
		return strings.Contains(lab.console(t, "show ipv4 route v1"), ";"+rsvpFreeData+"/32;")
	})

	// The peer must already have accepted RESV and be forwarding replies. A
	// failed ping alone would also pass if signalling or the peer were broken.
	lab.input(t, false)
	lab.ping(t, label, 1, false)
	lab.input(t, true)
	lab.ping(t, label, 3, true)

	before := lab.capture.count()
	withdrawnAt := time.Now()
	for _, command := range []string{"configure terminal", "no interface tunnel1", "end"} {
		lab.console(t, command)
	}
	var tear *ParsedMessage
	lab.wait(t, "peer PathTear for the established LSP", 5*time.Second, func() bool {
		for _, frame := range lab.capture.since(t, before) {
			msg := rsvpFreeMessage(frame)
			if msg != nil && msg.Header.MsgType == MsgTypePathTear && msg.Session == path.Session && msg.SenderTemplate == path.SenderTemplate && msg.Hop == path.Hop {
				tear = msg
				return true
			}
		}
		return false
	})
	if tear == nil {
		t.Fatal("missing peer tear")
	}
	lab.wait(t, "withdrawn Ze egress label", 5*time.Second, func() bool { return !lab.hasPop(t, label) })
	// Ze uses the received TIME_VALUES with refresh-multiplier=3. The peer
	// normally advertises 60 seconds; require cleanup well before that deadline.
	lifetime := time.Duration(path.TimeValues.RefreshPeriod) * time.Millisecond * 3
	if age := time.Since(startedAt); lifetime <= age+5*time.Second {
		t.Fatalf("the entire carrier has run for %s with peer lifetime %s; expiry cannot be excluded", age, lifetime)
	}
	lab.wait(t, "withdrawn peer RSVP state", 5*time.Second, func() bool {
		show := lab.console(t, "show ipv4 rsvp v1 summary")
		return !strings.Contains(show, rsvpFreePeer+";") && strings.Contains(show, "source;id;")
	})
	lab.pingWithdrawn(t)
	lab.alive(t)
	t.Logf("freeRouter %s -> Ze: PATH/RESV label %d; input-disabled reply blocked; three labelled replies delivered; matching PathTear removed label in %s", rsvpFreeRevision, label, time.Since(withdrawnAt))
}

type rsvpFreeLab struct {
	ns       string
	dir      string
	ip       string
	h        *netlink.Handle
	capture  *rsvpFreeCapture
	children []*rsvpFreeProcess
	peer     *rsvpFreeProcess
}

func newRSVPFreeLab(t *testing.T) *rsvpFreeLab {
	t.Helper()
	peerDir, err := filepath.Abs(*rsvpFreePeerDir)
	if err != nil {
		t.Fatal(err)
	}
	rsvpFreeArtifacts(t, peerDir)
	ze := rsvpFreeExecutable(t, *rsvpFreeZe)
	javaName := *rsvpFreeJava
	if javaName == "" {
		javaName = "java"
	}
	java := rsvpFreeExecutable(t, javaName)
	ip := rsvpFreeExecutable(t, "ip")
	_ = rsvpFreeExecutable(t, "ping")
	_ = rsvpFreeExecutable(t, "sysctl")
	if os.Geteuid() != 0 {
		t.Fatal("opted-in RSVP carrier requires root and CAP_SYS_ADMIN/CAP_NET_ADMIN/CAP_NET_RAW")
	}
	if _, err := os.Stat("/dev/net/tun"); err != nil {
		t.Fatalf("TAP prerequisite: %v", err)
	}
	lab := &rsvpFreeLab{ns: fmt.Sprintf("rsvp-fr-%d-%s", os.Getpid(), rand.Text()[:8]), dir: t.TempDir(), ip: ip}
	rsvpFreeCommand(t, 5*time.Second, ip, "netns", "add", lab.ns)
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		out, err := exec.CommandContext(ctx, ip, "netns", "del", lab.ns).CombinedOutput()
		if err != nil {
			t.Errorf("remove owned namespace %s: %v: %s", lab.ns, err, out)
		}
	})
	lab.run(t, "ip", "link", "set", "lo", "up")
	lab.run(t, "ip", "addr", "add", rsvpFreeLocal+"/32", "dev", "lo")
	lab.run(t, "ip", "addr", "add", rsvpFreeData+"/32", "dev", "lo")
	// The module must already be available in the guest. A supplied carrier
	// never turns a missing MPLS kernel feature into a skip.
	// Local MPLS pop re-enters IPv4 on the existing loopback interface.
	// Changing default.rp_filter does not change that interface.
	lab.run(t, "sysctl", "-w", "net.mpls.platform_labels=1048575", "net.ipv4.ip_forward=1", "net.ipv4.conf.all.rp_filter=0", "net.ipv4.conf.default.rp_filter=0", "net.ipv4.conf.lo.rp_filter=0")

	// UDP ports are fixed only inside this unique namespace. The upstream
	// helper creates tap0 and transports full Ethernet frames to the JAR.
	// Start Java first: tapInt's connected UDP reader exits on ICMP port-unreachable.
	rsvpFreeWrite(t, filepath.Join(lab.dir, "peer-hw.txt"), "int eth1 eth 0200.0000.0002 127.0.0.1 24001 127.0.0.1 24002\n")
	rsvpFreeWrite(t, filepath.Join(lab.dir, "peer-sw.txt"), rsvpFreePeerConfig)
	lab.peer = lab.start(t, "freertr", java, "-Xms32m", "-Xmx256m", "-jar", filepath.Join(peerDir, "rtr.jar"), "routerc", filepath.Join(lab.dir, "peer-"))
	lab.wait(t, "freeRouter hardware UDP socket", 30*time.Second, func() bool {
		data, err := os.ReadFile(fmt.Sprintf("/proc/%d/net/udp", lab.peer.cmd.Process.Pid))
		if err != nil {
			return false
		}
		return strings.Contains(string(data), "0100007F:5DC1") // 24001, namespace loopback
	})
	lab.start(t, "tap", filepath.Join(peerDir, "tapInt.bin"), "tap0", "24002", "127.0.0.1", "24001", "127.0.0.1")
	lab.wait(t, "upstream TAP interface", 10*time.Second, func() bool {
		ctx, cancel := context.WithTimeout(t.Context(), time.Second)
		defer cancel()
		return exec.CommandContext(ctx, ip, "-n", lab.ns, "link", "show", "tap0").Run() == nil
	})
	lab.run(t, "ip", "addr", "add", "192.0.2.1/30", "dev", "tap0")
	lab.run(t, "ip", "link", "set", "tap0", "up")
	lab.run(t, "ip", "route", "add", "198.18.0.0/24", "via", "192.0.2.2", "dev", "tap0")
	lab.run(t, "ip", "neigh", "replace", "192.0.2.2", "lladdr", "02:00:00:00:00:02", "nud", "permanent", "dev", "tap0")
	lab.run(t, "sysctl", "-w", "net.ipv4.conf.tap0.rp_filter=0", "net.mpls.conf.tap0.input=0")
	ns, err := netns.GetFromName(lab.ns)
	if err != nil {
		t.Fatal(err)
	}
	defer ns.Close()
	lab.h, err = netlink.NewHandleAt(ns, unix.NETLINK_ROUTE)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(lab.h.Close)
	func() {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
		original, err := netns.Get()
		if err != nil {
			t.Fatal(err)
		}
		defer original.Close()
		if err := netns.Set(ns); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := netns.Set(original); err != nil {
				t.Errorf("restore namespace: %v", err)
			}
		}()
		link, err := lab.h.LinkByName("tap0")
		if err != nil {
			t.Fatal(err)
		}
		lab.capture = rsvpFreeStartCapture(t, rsvpWireCapture(t, link.Attrs().Index))
	}()
	// CR activates the upstream console; each later command is fenced by its
	// returned prompt. No telnet server or management listener is exposed.
	lab.console(t, "")
	lab.console(t, "show version brief")
	zeDir := filepath.Join(lab.dir, "ze")
	if err := os.Mkdir(zeDir, 0o700); err != nil {
		t.Fatal(err)
	}
	rsvpFreeWrite(t, filepath.Join(zeDir, "ze.conf"), rsvpFreeZeConfig)
	lab.start(t, "ze", ze, "start", filepath.Join(zeDir, "ze.conf"))
	return lab
}

const rsvpFreePeerConfig = `hostname peer
console0
 exec height 0
 exec width 512
 exec tablemode raw
 exec colorize normal
 no exec banner
 no exec title
 exit
vrf definition v1
 rd 1:1
 exit
interface loopback0
 vrf forwarding v1
 ipv4 address 198.18.0.2 255.255.255.255
 mpls rsvp4
 exit
interface ethernet1
 vrf forwarding v1
 ipv4 address 192.0.2.2 255.255.255.252
 mpls enable
 mpls rsvp4
 exit
ipv4 route v1 198.18.0.1 255.255.255.255 192.0.2.1
interface tunnel1
 tunnel source loopback0
 tunnel destination 198.18.0.1
 tunnel vrf v1
 tunnel mode p2pte
 vrf forwarding v1
 ipv4 address 10.254.0.2 255.255.255.252
 exit
ipv4 route v1 198.18.1.1 255.255.255.255 10.254.0.1
`

const rsvpFreeZeConfig = `plugin {
 internal rsvp-te { use rsvp-te; }
 internal fib-kernel { use fib-kernel; }
}
rsvp-te {
 router-id 198.18.0.1
 refresh-period 2
 refresh-multiplier 3
 interface tap0 {
  address 192.0.2.1/30
  max-bandwidth 1000000000
  max-reservable-bandwidth 1000000000
 }
}
`

func rsvpFreeArtifacts(t *testing.T, dir string) {
	t.Helper()
	revision, err := os.ReadFile(filepath.Join(dir, "REVISION"))
	if err != nil || strings.TrimSpace(string(revision)) != rsvpFreeRevision {
		t.Fatalf("peer REVISION must be %s: %q: %v", rsvpFreeRevision, revision, err)
	}
	manifest, err := os.ReadFile(filepath.Join(dir, "SHA256SUMS"))
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"rtr.jar", "tapInt.bin"} {
		var expected string
		for _, line := range strings.Split(string(manifest), "\n") {
			fields := strings.Fields(line)
			if len(fields) == 2 && fields[1] == name {
				expected = fields[0]
			}
		}
		f, err := os.Open(filepath.Join(dir, name))
		if err != nil {
			t.Fatal(err)
		}
		h := sha256.New()
		_, copyErr := io.Copy(h, f)
		closeErr := f.Close()
		if copyErr != nil || closeErr != nil {
			t.Fatalf("hash %s: %v / %v", name, copyErr, closeErr)
		}
		if actual := hex.EncodeToString(h.Sum(nil)); len(expected) != 64 || actual != expected {
			t.Fatalf("peer %s SHA256 mismatch: expected %q, got %s", name, expected, actual)
		}
	}
	_ = rsvpFreeExecutable(t, filepath.Join(dir, "tapInt.bin"))
}

func rsvpFreeExecutable(t *testing.T, name string) string {
	t.Helper()
	path, err := exec.LookPath(name)
	if err != nil {
		t.Fatalf("required executable %q: %v", name, err)
	}
	path, err = filepath.Abs(path)
	if err != nil {
		t.Fatal(err)
	}
	return path
}

func rsvpFreeWrite(t *testing.T, path, value string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(value), 0o600); err != nil {
		t.Fatal(err)
	}
}

func rsvpFreeCommand(t *testing.T, timeout time.Duration, binary string, args ...string) []byte {
	t.Helper()
	ctx, cancel := context.WithTimeout(t.Context(), timeout)
	defer cancel()
	out, err := exec.CommandContext(ctx, binary, args...).CombinedOutput()
	if err != nil {
		t.Fatalf("%s %v: %v\n%s", binary, args, err, out)
	}
	return out
}

func (l *rsvpFreeLab) run(t *testing.T, args ...string) []byte {
	t.Helper()
	return rsvpFreeCommand(t, 5*time.Second, l.ip, append([]string{"netns", "exec", l.ns}, args...)...)
}

func (l *rsvpFreeLab) input(t *testing.T, enabled bool) {
	t.Helper()
	value := "0"
	if enabled {
		value = "1"
	}
	l.run(t, "sysctl", "-w", "net.mpls.conf.tap0.input="+value)
}

func (l *rsvpFreeLab) hasPop(t *testing.T, label uint32) bool {
	t.Helper()
	routes, err := l.h.RouteList(nil, unix.AF_MPLS)
	if err != nil {
		t.Fatal(err)
	}
	for _, route := range routes {
		if route.MPLSDst != nil && uint32(*route.MPLSDst) == label {
			lo, err := l.h.LinkByName("lo")
			if err != nil {
				t.Fatal(err)
			}
			if route.NewDst != nil || route.LinkIndex != lo.Attrs().Index {
				t.Fatalf("label %d is not an egress pop: %+v", label, route)
			}
			return true
		}
	}
	return false
}

func (l *rsvpFreeLab) reservation(t *testing.T) (*ParsedMessage, uint32) {
	t.Helper()
	var path *ParsedMessage
	var label uint32
	l.wait(t, "freeRouter PATH and matching Ze RESV", 60*time.Second, func() bool {
		frames := l.capture.since(t, 0)
		for _, frame := range frames {
			msg := rsvpFreeMessage(frame)
			if msg != nil && msg.Header.MsgType == MsgTypePath && msg.Session.TunnelEndpoint.String() == rsvpFreeLocal && msg.SenderTemplate.SenderAddr.String() == rsvpFreePeer {
				path = msg
			}
		}
		if path == nil {
			return false
		}
		for _, frame := range frames {
			msg := rsvpFreeMessage(frame)
			if msg == nil || msg.Header.MsgType != MsgTypeResv || msg.Session != path.Session {
				continue
			}
			for _, descriptor := range msg.FlowDescriptors {
				for _, filter := range descriptor.Filters {
					if filter.Filter == path.SenderTemplate && filter.HasLabel {
						label = filter.Label.Label
					}
				}
			}
		}
		return label >= 16 && label <= MaxLabel
	})
	if !path.HasERO || !path.HasTimeValues {
		t.Fatalf("peer PATH lacks ERO/TIME_VALUES: %+v", path)
	}
	return path, label
}

func rsvpFreeMessage(frame []byte) *ParsedMessage {
	_, ip := rsvpWireIP(frame)
	if len(ip) < 20 || ip[0]>>4 != 4 || ip[9] != 46 {
		return nil
	}
	header := int(ip[0]&15) * 4
	total := int(binary.BigEndian.Uint16(ip[2:4]))
	if header < 20 || total > len(ip) || total < header+8 {
		return nil
	}
	msg, err := DecodeMessage(ip[header:total])
	if err != nil {
		return nil
	}
	return msg
}

type rsvpFreeEcho struct {
	id       uint16
	sequence uint16
	payload  string
}

// echoes matches the entire ICMP identity and payload in both directions. A
// same-label background frame or a captured request cannot stand in for a reply.
func (l *rsvpFreeLab) echoes(t *testing.T, start, count int, label uint32) bool {
	t.Helper()
	requests := map[rsvpFreeEcho]bool{}
	replies := map[rsvpFreeEcho]bool{}
	for _, frame := range l.capture.since(t, start) {
		labels, ip := rsvpWireIP(frame)
		if len(ip) < 20 || ip[0]>>4 != 4 || ip[9] != 1 {
			continue
		}
		h := int(ip[0]&15) * 4
		n := int(binary.BigEndian.Uint16(ip[2:4]))
		if h < 20 || n > len(ip) || n < h+8 {
			continue
		}
		src := netip.AddrFrom4([4]byte(ip[12:16]))
		dst := netip.AddrFrom4([4]byte(ip[16:20]))
		icmp := ip[h:n]
		key := rsvpFreeEcho{binary.BigEndian.Uint16(icmp[4:6]), binary.BigEndian.Uint16(icmp[6:8]), string(icmp[8:])}
		if icmp[0] == 8 && src.String() == rsvpFreeData && dst.String() == rsvpFreePeer {
			if len(labels) != 0 {
				t.Fatal("request unexpectedly used MPLS; this carrier claims only peer-to-Ze labelled delivery")
			}
			requests[key] = true
		}
		if icmp[0] == 0 && src.String() == rsvpFreePeer && dst.String() == rsvpFreeData {
			if len(labels) != 1 || labels[0] != label {
				t.Fatalf("echo reply used labels %v, want negotiated [%d]; ordinary IP fallback is forbidden", labels, label)
			}
			replies[key] = true
		}
	}
	if len(requests) != count || len(replies) != count {
		return false
	}
	for key := range requests {
		if !replies[key] {
			return false
		}
	}
	return true
}

func (l *rsvpFreeLab) ping(t *testing.T, label uint32, count int, delivered bool) {
	t.Helper()
	start := l.capture.count()
	ctx, cancel := context.WithTimeout(t.Context(), 12*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, l.ip, "netns", "exec", l.ns, "ping", "-n", "-c", strconv.Itoa(count), "-W", "2", "-I", rsvpFreeData, rsvpFreePeer).CombinedOutput()
	if ctx.Err() != nil {
		t.Fatalf("bounded ping expired: %v: %s", ctx.Err(), out)
	}
	if delivered {
		if err != nil {
			t.Fatalf("labelled reply was not delivered to ping: %v\n%s", err, out)
		}
		// iputils and BusyBox both report loss; exit zero alone allows partial loss.
		if !strings.Contains(string(out), " 0% packet loss") {
			t.Fatalf("not every ping reply was delivered:\n%s", out)
		}
	} else {
		var exit *exec.ExitError
		if !errors.As(err, &exit) || exit.ExitCode() != 1 || !strings.Contains(string(out), "100% packet loss") {
			t.Fatalf("MPLS-disabled negative control did not lose every reply: %v\n%s", err, out)
		}
	}
	l.wait(t, "matching labelled echo replies on TAP", 3*time.Second, func() bool { return l.echoes(t, start, count, label) })
}

func (l *rsvpFreeLab) pingWithdrawn(t *testing.T) {
	t.Helper()
	ctx, cancel := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, l.ip, "netns", "exec", l.ns, "ping", "-n", "-c", "1", "-W", "2", "-I", rsvpFreeData, rsvpFreePeer).CombinedOutput()
	var exit *exec.ExitError
	if ctx.Err() != nil || !errors.As(err, &exit) || exit.ExitCode() != 1 || !strings.Contains(string(out), "100% packet loss") {
		t.Fatalf("traffic survived peer tunnel withdrawal: %v\n%s", err, out)
	}
}

type rsvpFreeProcess struct {
	cmd    *exec.Cmd
	stdin  io.WriteCloser
	log    *os.File
	done   chan struct{}
	err    error
	cancel context.CancelFunc
}

func (l *rsvpFreeLab) start(t *testing.T, name, binary string, args ...string) *rsvpFreeProcess {
	t.Helper()
	log, err := os.Create(filepath.Join(l.dir, name+".log"))
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	cmd := exec.CommandContext(ctx, l.ip, append([]string{"netns", "exec", l.ns, binary}, args...)...)
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	cmd.Cancel = func() error { return syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL) }
	cmd.WaitDelay = 3 * time.Second
	cmd.Stdout, cmd.Stderr = log, log
	cmd.Env = []string{"PATH=" + os.Getenv("PATH"), "HOME=" + l.dir, "USER=root", "LANG=C", "TERM=dumb", "ZE_CONFIG_DIR=" + filepath.Join(l.dir, "ze"), "ZE_LOG_RSVP_TE=debug", "ZE_LOG_FIB_KERNEL=debug"}
	stdin, err := cmd.StdinPipe()
	if err != nil {
		cancel()
		_ = log.Close()
		t.Fatal(err)
	}
	if err := cmd.Start(); err != nil {
		cancel()
		_ = stdin.Close()
		_ = log.Close()
		t.Fatal(err)
	}
	p := &rsvpFreeProcess{cmd: cmd, stdin: stdin, log: log, done: make(chan struct{}), cancel: cancel}
	go func() { p.err = cmd.Wait(); close(p.done) }()
	l.children = append(l.children, p)
	t.Cleanup(func() {
		select {
		case <-p.done:
			t.Errorf("%s exited before cleanup: %v", name, p.err)
		default:
			if err := syscall.Kill(-cmd.Process.Pid, syscall.SIGTERM); err != nil {
				t.Errorf("stop %s: %v", name, err)
			}
			select {
			case <-p.done:
			case <-time.After(5 * time.Second):
				cancel()
				select {
				case <-p.done:
					t.Errorf("%s required SIGKILL after SIGTERM", name)
				case <-time.After(5 * time.Second):
					t.Errorf("%s did not reap after SIGKILL", name)
				}
			}
		}
		cancel()
		_ = stdin.Close()
		if t.Failed() {
			data, _ := os.ReadFile(log.Name())
			t.Logf("%s:\n%s", name, data)
		}
		if err := log.Close(); err != nil {
			t.Errorf("close %s log: %v", name, err)
		}
	})
	return p
}

func (l *rsvpFreeLab) alive(t *testing.T) {
	t.Helper()
	for _, child := range l.children {
		select {
		case <-child.done:
			data, _ := os.ReadFile(child.log.Name())
			t.Fatalf("child %s exited: %v\n%s", child.cmd.Args, child.err, data)
		default:
		}
	}
}

func (l *rsvpFreeLab) wait(t *testing.T, what string, timeout time.Duration, ready func() bool) {
	t.Helper()
	ctx, cancel := context.WithTimeout(t.Context(), timeout)
	defer cancel()
	ticker := time.NewTicker(25 * time.Millisecond)
	defer ticker.Stop()
	for {
		l.alive(t)
		if ready() {
			return
		}
		select {
		case <-ctx.Done():
			t.Fatalf("waiting for %s: %v", what, ctx.Err())
		case <-ticker.C:
		}
	}
}

var rsvpFreeANSI = regexp.MustCompile(`\x1b\[[0-?]*[ -/]*[@-~]`)

func (l *rsvpFreeLab) console(t *testing.T, command string) string {
	t.Helper()
	stat, err := l.peer.log.Stat()
	if err != nil {
		t.Fatal(err)
	}
	if _, err := io.WriteString(l.peer.stdin, command+"\r"); err != nil {
		t.Fatal(err)
	}
	var text string
	l.wait(t, "freeRouter command "+command, 15*time.Second, func() bool {
		data, err := os.ReadFile(l.peer.log.Name())
		if err != nil {
			t.Fatal(err)
		}
		if int64(len(data)) <= stat.Size() {
			return false
		}
		text = string(rsvpFreeANSI.ReplaceAll(data[stat.Size():], nil))
		return strings.HasSuffix(strings.TrimSpace(text), "#")
	})
	for _, failure := range []string{"bad command", "unknown command", "invalid command", "no such interface"} {
		if strings.Contains(strings.ToLower(text), failure) {
			t.Fatalf("freeRouter command %q failed:\n%s", command, text)
		}
	}
	return text
}

type rsvpFreeCapture struct {
	mu     sync.Mutex
	frames [][]byte
	err    error
}

func rsvpFreeStartCapture(t *testing.T, fd int) *rsvpFreeCapture {
	t.Helper()
	c := &rsvpFreeCapture{}
	ctx, cancel := context.WithCancel(context.Background())
	done := make(chan struct{})
	go func() {
		defer close(done)
		var buffer [9216]byte
		for ctx.Err() == nil {
			poll := []unix.PollFd{{Fd: int32(fd), Events: unix.POLLIN}}
			n, err := unix.Poll(poll, 100)
			if errors.Is(err, unix.EINTR) {
				continue
			}
			if err != nil {
				c.mu.Lock()
				c.err = err
				c.mu.Unlock()
				return
			}
			if n == 0 {
				continue
			}
			n, _, err = unix.Recvfrom(fd, buffer[:], unix.MSG_DONTWAIT)
			if errors.Is(err, unix.EAGAIN) || errors.Is(err, unix.EINTR) {
				continue
			}
			if err != nil {
				c.mu.Lock()
				c.err = err
				c.mu.Unlock()
				return
			}
			_, ip := rsvpWireIP(buffer[:n])
			if len(ip) < 20 || ip[0]>>4 != 4 || ip[9] != 46 && ip[9] != 1 {
				continue
			}
			c.mu.Lock()
			if len(c.frames) == 4096 {
				c.err = errors.New("capture exceeded 4096 RSVP/ICMP frames")
				c.mu.Unlock()
				return
			}
			c.frames = append(c.frames, bytes.Clone(buffer[:n]))
			c.mu.Unlock()
		}
	}()
	t.Cleanup(func() { cancel(); <-done })
	return c
}

func (c *rsvpFreeCapture) count() int { c.mu.Lock(); defer c.mu.Unlock(); return len(c.frames) }

func (c *rsvpFreeCapture) since(t *testing.T, start int) [][]byte {
	t.Helper()
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.err != nil {
		t.Fatal(c.err)
	}
	return append([][]byte(nil), c.frames[start:]...)
}
