// Design: docs/architecture/testing/interop.md -- RFC 5082 evidence read on a foreign receiver's side.
// Related: check_rfc_predicate.go -- the pure counter readings this body calls.
// Related: check_special.go -- the registry that dispatches this checker.
package bgp

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/ze-software/ze/internal/le/interoplab"
)

// checkGTSMRelatedICMPTTL reads RFC 5082 Section 3 on the receiver's side: "The
// TTL field in all IP packets used for transmission of messages associated with
// GTSM-enabled protocol sessions MUST be set to 255. This also applies to the
// related ICMP error handling messages." FRR 10.3.1 is the GTSM receiver, and
// its Linux kernel is what performs FRR's check: bgpd sets IPV6_MINHOPCOUNT 255
// on the session socket, and tcp_v6_err (net/ipv6/tcp_ipv6.c) drops a related
// ICMPv6 error whose own hop limit is below it, counting the drop in
// TCPMinTTLDrop. So the counters of the FRR container's namespace are a foreign
// implementation's reading of the hop limit ze put on the wire.
//
// The stimulus is one nftables reject rule installed in ze's container that
// answers ONE TCP segment of the session from FRR with an ICMPv6 Destination
// Unreachable. That error is generated by ze's kernel, so its hop limit is the
// one ze's host route to the peer carries (installHopLimitRoute,
// internal/component/gtsm/route_linux.go), and it quotes FRR's own segment, so
// FRR's kernel matches it to the BGP session's socket before the hop-limit
// floor is applied. The segment is retransmitted by TCP and the session
// survives, which the last assertion reads.
//
// Without the RTAX_HOPLIMIT metric the error leaves at the interface default
// of 64, and the verdict's TCPMinTTLDrop clause is what goes red.
func checkGTSMRelatedICMPTTL(ctx context.Context, check *interoplab.CheckContext) error {
	const (
		name      = "gtsm-related-icmp-ttl"
		labTable  = "gtsmlab"
		labChain  = "input"
		errorWait = 30 * time.Second
	)
	fail := func(assertion int, cause error) error {
		return checkerFailure(ctx, check.Lab, name, assertion, cause)
	}
	if !check.Network.IPv6.IsValid() {
		return fail(1, errors.New("GTSM related-ICMP scenario has no selected IPv6 network"))
	}
	zeAddress := networkHostAddress6(check.Network, 2)
	frrAddress := networkHostAddress6(check.Network, 3)

	// Assertion 1. The GTSM session, read from FRR.
	session := operation{kind: opFRRSession, argument: zeAddress}
	if err := runOperation(ctx, check.Network, check.Lab, &session); err != nil {
		return fail(1, err)
	}

	// Assertion 2. FRR armed the floor. Without ttl-security FRR's kernel holds
	// no min hop count, the drop counter can never move, and every reading
	// below passes whatever hop limit ze sends.
	neighbor, err := check.Lab.Query(ctx, peerFRR, []string{cmdVtysh, "-c", "show bgp neighbor " + zeAddress + " json"}, nil)
	if err != nil {
		return fail(2, err)
	}
	hops, err := frrGTSMHops(neighbor)
	if err != nil {
		return fail(2, err)
	}
	if hops != 1 {
		return fail(2, fmt.Errorf("FRR applies ttl-security hops %d, want 1", hops))
	}

	// Assertion 3. The receiver's counters before the stimulus.
	readCounters := func(probeCtx context.Context) (string, error) {
		return check.Lab.Query(probeCtx, peerFRR, []string{"cat", "/proc/net/netstat", "/proc/net/snmp6"}, nil)
	}
	beforeText, err := readCounters(ctx)
	if err != nil {
		return fail(3, err)
	}
	before, err := parseGTSMPeerCounters(beforeText)
	if err != nil {
		return fail(3, err)
	}

	// Assertion 4. One segment from FRR is rejected with an ICMPv6 error. The
	// limit admits one packet and then no more for an hour, so the session
	// loses exactly one segment to the retransmit timer. The table is ze's
	// container's own, outside the ze_ prefix, so ze's firewall never sweeps it.
	defer func() {
		_, _ = check.Lab.Exec(context.WithoutCancel(ctx), "ze", []string{"nft", "delete", "table", "inet", labTable}, nil)
	}()
	for _, argv := range [][]string{
		{"nft", "add", "table", "inet", labTable},
		{"nft", "add", "chain", "inet", labTable, labChain, "{ type filter hook input priority -300; policy accept; }"},
		{"nft", "add", "rule", "inet", labTable, labChain,
			"ip6", "saddr", frrAddress, "ip6", "daddr", zeAddress, "meta", "l4proto", "tcp",
			"limit", "rate", "1/hour", "burst", "1", "packets", "counter",
			"reject", "with", "icmpv6", "type", "admin-prohibited"},
	} {
		if _, err := check.Lab.Exec(ctx, "ze", argv, nil); err != nil {
			return fail(4, err)
		}
	}
	if err := waitContains(ctx, check.Lab, "ze", []string{"nft", "list", "chain", "inet", labTable, labChain}, errorWait, "counter packets 1 "); err != nil {
		return fail(4, err)
	}

	// Assertion 5. The error reached FRR, was matched to the session, and was
	// not dropped below the floor. The wait is on arrival alone; the verdict
	// reads all three counters of the same answer.
	afterText, _, err := interoplab.Wait(ctx, interoplab.WaitOptions{
		Timeout:     errorWait,
		Interval:    time.Second,
		Description: "FRR ICMPv6 counters",
	}, readCounters, func(text string) bool {
		after, parseErr := parseGTSMPeerCounters(text)
		return parseErr == nil && gtsmErrorArrived(before, after)
	})
	if err != nil {
		return fail(5, withLastOutput(err, afterText))
	}
	after, err := parseGTSMPeerCounters(afterText)
	if err != nil {
		return fail(5, err)
	}
	if err := requireRelatedICMPAccepted(before, after); err != nil {
		return fail(5, err)
	}

	// Assertion 6. The session survived the one rejected segment.
	if err := runOperation(ctx, check.Network, check.Lab, &session); err != nil {
		return fail(6, err)
	}
	return nil
}
