// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-geodns-cmd.yang", ZeGeodnsCmdYANG)
	configyang.RegisterModule("ze-geodns-conf.yang", ZeGeodnsConfYANG)
}
