// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-ddos-detect-conf.yang", ZeDdosDetectConfYANG)
}
