// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-static-cmd.yang
var ZeStaticCmdYANG string

//go:embed ze-static-conf.yang
var ZeStaticConfYANG string
