// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_web

// Package all (ze_web group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_web is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/component/web/yang"
)

