// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_as112

// Package all (ze_as112 group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_as112 is absent (per-feature compile-out).
package all

import (
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/as112"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/as112/yang"
)

