// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_gnmi

// Package all (ze_gnmi group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_gnmi is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/component/gnmi"
	_ "github.com/ze-software/ze/internal/component/gnmi/yang"
	_ "github.com/ze-software/ze/internal/plugins/gnmi-cmd/yang"
)

