// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_policyroute

// Package all (ze_policyroute group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_policyroute is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/plugins/policyroute"
	_ "github.com/ze-software/ze/internal/plugins/policyroute/yang"
)

