// Design: ai/rules/plugins.md -- feature-gated plugin composition
//
// Code generated by ./le plugin-imports write; DO NOT EDIT.

//go:build ze_mrt

// Package all (ze_mrt group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_mrt is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/plugins/mrt"
	_ "github.com/ze-software/ze/internal/plugins/mrt/yang"
)
