// Design: ai/rules/plugins.md -- feature-gated plugin composition
//
// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_vrrp

// Package all (ze_vrrp group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_vrrp is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/plugins/vrrp"
	_ "github.com/ze-software/ze/internal/plugins/vrrp/transport"
	_ "github.com/ze-software/ze/internal/plugins/vrrp/yang"
)
