// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_bfd

// Package all (ze_bfd group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_bfd is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/component/bfd"
	_ "github.com/ze-software/ze/internal/component/bfd/cmd"
	_ "github.com/ze-software/ze/internal/component/bfd/yang"
)

