// Design: ai/rules/plugins.md -- feature-gated plugin composition
//
// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_rest

// Package all (ze_rest group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_rest is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/component/api/rest/yang"
)
