// Design: ai/rules/plugins.md -- feature-gated plugin composition
//
// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_tacacs

// Package all (ze_tacacs group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_tacacs is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/component/tacacs/yang"
)
