// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_ospf

// Package all (ze_ospf group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_ospf is absent (per-feature compile-out).
package all

import (
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/ospf"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/ospf/cli"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/ospf/transport"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/ospf/v3/transport"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/ospf/yang"
)

