// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_flowexport

// Package all (ze_flowexport group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_flowexport is absent (per-feature compile-out).
package all

import (
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/flowexport"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/flowexport-cmd/yang"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/flowexport/ipfix"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/flowexport/netflow9"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/flowexport/sflow"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/flowexport/yang"
)

