// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_copp

// Package all (ze_copp group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_copp is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/plugins/copp"
	_ "github.com/ze-software/ze/internal/plugins/copp/yang"
)
