// Design: ai/rules/plugins.md -- feature-gated plugin composition
//
// Code generated by ./le plugin-imports write; DO NOT EDIT.

//go:build ze_rsvpte

// Package all (ze_rsvpte group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_rsvpte is absent (per-feature compile-out).
package all

import (
	_ "github.com/ze-software/ze/internal/plugins/rsvpte"
	_ "github.com/ze-software/ze/internal/plugins/rsvpte/yang"
)
