// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_vrrp

// Package all (ze_vrrp group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_vrrp is absent (per-feature compile-out).
package all

import (
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/vrrp"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/vrrp/transport"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/vrrp/yang"
)

