// Code generated by scripts/codegen/plugin_imports.go; DO NOT EDIT.

//go:build ze_anomaly

// Package all (ze_anomaly group): build-tag-gated plugin/schema imports,
// dropped from the binary when ze_anomaly is absent (per-feature compile-out).
package all

import (
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/anomaly/detect"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/anomaly/detect/cmd/yang"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/anomaly/detect/yang"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/anomaly/shape"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/anomaly/shape/cmd/yang"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/anomaly/shape/yang"
)

