// Design: docs/architecture/core-design.md -- the rfc area, as one command
// Overview: meta.go -- the one declaration these three files are generated from
// Detail: write.go -- the gate that emits every generated page
//
// render_ledger.go is the ONE producer of rfc/enrolled.txt, rfc/not-enrolled.txt
// and docs/features/rfc-status.md.
//
// All three were authored until 2026-09-01, and each held a fact its RFC's own
// summary did not: whether that RFC was gated, and what the public page claimed
// for it. A second copy is not a convenience, it is a future disagreement with
// nothing to arbitrate it, so five of this package's refusals existed only to
// compare copies. The summary's Meta table is now the one declaration and these
// three files derive from it.
package rfc

import (
	"sort"
	"strconv"
	"strings"

	"github.com/ze-software/ze/internal/core/textbuf"
)

// statusSectionSpec is one `##` section of the public page.
//
// The section list is the renderer's own declaration, not a fact about any RFC.
// A summary names its section by KEY and the heading is written once here, so a
// heading reworded on the page cannot disagree with 158 summaries naming it.
type statusSectionSpec struct {
	Key     string
	Heading string
	// Intro is the prose between the heading and the table, empty for a
	// section that goes straight to its rows.
	Intro string
	// Brief marks the four-column shape: the last section holds standards
	// that are not RFCs, and it states a Note where the others state
	// implemented coverage and a remainder.
	Brief bool
}

// statusSections is the page's section order, and the ONE place each heading is
// written.
var statusSections = []statusSectionSpec{
	{Key: "bgp-base", Heading: "BGP base protocol, capabilities, and session safety"},
	{Key: "bgp-attributes", Heading: "BGP attributes, families, policy, and NLRI"},
	{Key: "bgp-operations", Heading: "BGP operations, telemetry, RPKI, and BFD-adjacent standards"},
	{Key: "igp-mpls", Heading: "IS-IS, OSPF, MPLS, and traffic engineering"},
	{Key: "fhrp", Heading: "First-hop redundancy"},
	{Key: "access-aaa", Heading: "Access, AAA, PPP, and subscriber services"},
	{Key: "ipsec", Heading: "IPsec, IKE, EAP, and kernel security associations"},
	{Key: "dns-telemetry", Heading: "DNS, provisioning, MRT, and flow telemetry"},
	{Key: "drafts", Heading: "Drafts and non-RFC standards tracked near RFC work", Brief: true,
		Intro: "These are not RFCs, but they sit next to RFC implementation status and are useful when reading the tables above."},
}

// statusSection answers one section by key, or nil for a key nothing declares.
func statusSection(key string) *statusSectionSpec {
	for index := range statusSections {
		if statusSections[index].Key == key {
			return &statusSections[index]
		}
	}
	return nil
}

// statusSectionKeys answers every key sorted, for a refusal that names the set.
func statusSectionKeys() []string {
	out := make([]string, 0, len(statusSections))
	for _, section := range statusSections {
		out = append(out, section.Key)
	}
	sort.Strings(out)
	return out
}

// generatedBanner is the do-not-edit line every file here opens with, in the
// comment syntax its format uses.
func generatedBanner(comment, by string) string {
	var tb textbuf.Buffer
	return tb.Str(comment).Str(" GENERATED by `").Str(by).
		Str("` from the `## Meta` table of each rfc/short/*.md. Do not edit.").String()
}

// share renders a count with the population it is drawn from.
//
// Every count these three files state carries its denominator and its
// percentage (owner directive, 2026-09-01). An absolute number alone reads as
// an achievement: "3,256 gated MUSTs" counts obligations JUDGED and is read as
// obligations MET. The percentage is what makes the population visible, and the
// population is what the reader is actually being told about.
func share(count, total int, population string) string {
	var tb textbuf.Buffer
	tb.Int(int64(count)).Str(" of ").Int(int64(total)).Byte(' ').Str(population)
	if total <= 0 {
		return tb.Str(" (no population)").String()
	}
	percent := strconv.FormatFloat(100*float64(count)/float64(total), 'f', 1, 64)
	return tb.Str(" (").Str(percent).Str("%)").String()
}

// LedgerFiles is the three generated files, keyed by their repo-relative path.
//
// One producer for all three, because they answer one question between them --
// which summaries are gated, why the rest are not, and what the product claims
// in public -- and three producers over one declaration could each read it
// differently.
func LedgerFiles(metas map[string]Meta) (map[string]string, error) {
	page, err := renderStatusPage(metas)
	if err != nil {
		return nil, err
	}
	return map[string]string{
		enrolledRel:    renderEnrolled(metas),
		notEnrolledRel: renderNotEnrolled(metas),
		statusRel:      page,
	}, nil
}

// renderEnrolled emits rfc/enrolled.txt: the gated set and the reason each row
// states, sorted by stem.
func renderEnrolled(metas map[string]Meta) string {
	stems := sortMetaStems(metas)
	var enrolled []string
	for _, stem := range stems {
		if metas[stem].Enrolled() {
			enrolled = append(enrolled, stem)
		}
	}
	var tb textbuf.Buffer
	tb.Str(generatedBanner("#", "./le rfc index-update")).Byte('\n')
	tb.Str("#\n")
	tb.Str("# The gate's scope: ").Str(share(len(enrolled), len(stems), "summaries")).
		Str(" declare `| Enrolment | enrolled |`.\n")
	tb.Str("#\n")
	tb.Str("# columns: <rfc-stem>\\t<why this RFC is enrolled>\n")
	tb.Str("#\n")
	tb.Str("# An enrolled RFC has EVERY MUST-level requirement in rfc/short/<stem>.md either\n")
	tb.Str("#   (a) covered by a positive AND a negative test tagged `RFC requirement: <ID> <polarity>`, or\n")
	tb.Str("#   (b) annotated in the summary with a reason: {not-applicable: why} / {gap: why} /\n")
	tb.Str("#       {single-polarity: <polarity>; why}\n")
	tb.Str("# `./le rfc check` enforces this. See ai/skills/ze-rfc.md.\n")
	tb.Str("#\n")
	tb.Str("# To enrol an RFC, edit its summary and nothing else: set `| Enrolment | enrolled |`\n")
	tb.Str("# and `| Enrolment reason | ... |` in its `## Meta` table, then run `./le rfc index-update`.\n")
	tb.Str("# Enrolment REQUIRES the RFC's own text at rfc/full/<stem>.txt or rfc/drafts/<stem>.txt,\n")
	tb.Str("# and an extraction sign-off at rfc/extraction/<stem>.json. `checkEnrolment` refuses\n")
	tb.Str("# without them, and enrolment is monotonic: an RFC whose MUSTs were gated cannot stop\n")
	tb.Str("# being gated.\n")
	tb.Byte('\n')
	for _, stem := range enrolled {
		tb.Str(stem).Byte('\t').Str(metas[stem].EnrolmentReason).Byte('\n')
	}
	return tb.String()
}

// renderNotEnrolled emits rfc/not-enrolled.txt: the declared remainder.
func renderNotEnrolled(metas map[string]Meta) string {
	stems := sortMetaStems(metas)
	var declared []string
	byKind := map[string]int{}
	for _, stem := range stems {
		meta := metas[stem]
		if meta.Enrolled() {
			continue
		}
		declared = append(declared, stem)
		byKind[meta.Enrolment]++
	}
	var tb textbuf.Buffer
	tb.Str(generatedBanner("#", "./le rfc index-update")).Byte('\n')
	tb.Str("#\n")
	tb.Str("# The declared remainder: ").Str(share(len(declared), len(stems), "summaries")).
		Str(" are not enrolled, and each states why in its own `## Meta` table.\n")
	tb.Str("#\n")
	tb.Str("# columns: <rfc-stem>\\t<kind>\\t<why>\n")
	tb.Str("#\n")
	tb.Str("# KINDS -- a closed set. The counts run in kind order; the rows at the end run in\n")
	tb.Str("# stem order.\n")
	tb.Str("#\n")
	for _, kind := range enrolmentKindNames() {
		if kind == enrolmentEnrolled {
			continue
		}
		tb.Str("#   ").Str(kind).Str(": ").Str(share(byKind[kind], len(stems), "summaries")).Byte('\n')
	}
	tb.Str("#\n")
	// The meanings are derived from the same closed set as the counts above,
	// and each one is named rather than placed. A header saying "the first two
	// are claims" is a claim about the ORDER, and the order is sorted, so a
	// sixth kind renames every ordinal in a sentence nothing re-reads. An
	// independent review caught exactly that on 2026-09-02, one commit after
	// the counts stopped being hand-written.
	for _, kind := range enrolmentKindNames() {
		if kind == enrolmentEnrolled {
			continue
		}
		meaning, held := DispositionKindMeaning(kind)
		if !held {
			meaning = "no meaning is recorded for this kind, which is itself a defect"
		}
		tb.Str("#   ").Str(kind).Str("\n")
		for _, line := range wrapComment(meaning, 76) {
			tb.Str("#       ").Str(line).Byte('\n')
		}
	}
	tb.Str("#\n")
	tb.Str("# backlog and blocked render as **DEBT** in ai/RFC-REQUIREMENTS.md (\"Declared not\n")
	tb.Str("# enrolled\"). Neither asserts anything about conformance, and neither can silence a\n")
	tb.Str("# public support claim.\n")
	tb.Byte('\n')
	for _, stem := range declared {
		meta := metas[stem]
		tb.Str(stem).Byte('\t').Str(meta.Enrolment).Byte('\t').Str(meta.EnrolmentReason).Byte('\n')
	}
	return tb.String()
}

// renderStatusPage emits docs/features/rfc-status.md: the public support claim,
// one row per summary that declares a section.
//
// The four authored cells are moved verbatim from the summary that owns them.
// Nothing on this page is synthesized: a support claim is a product judgement,
// and a generator that wrote the prose would be inventing the claim it exists
// to publish. What IS derived is every count, the row order inside a section,
// and the section headings themselves.
func renderStatusPage(metas map[string]Meta) (string, error) {
	placed, err := placeRows(metas)
	if err != nil {
		return "", err
	}
	rowed := 0
	for _, rows := range placed {
		rowed += len(rows)
	}
	var tb textbuf.Buffer
	tb.Str(generatedBanner("<!--", "./le rfc index-update")).Str(" -->\n\n")
	tb.Str("# RFC Implementation Status\n\n")
	tb.Str(statusPageIntro(len(metas)-rowed, len(metas)))
	for _, section := range statusSections {
		rows := placed[section.Key]
		if len(rows) == 0 {
			continue
		}
		tb.Str("\n## ").Str(section.Heading).Str("\n\n")
		if section.Intro != "" {
			tb.Str(section.Intro).Str("\n\n")
		}
		if section.Brief {
			tb.Str("| Standard | Area | Status | Note |\n")
			tb.Str("|----------|------|--------|------|\n")
		} else {
			tb.Str("| RFC | Area | Status | Implemented coverage | Remaining if not complete |\n")
			tb.Str("|-----|------|--------|----------------------|---------------------------|\n")
		}
		for _, row := range rows {
			tb.Str("| ").Str(RowName(row.Stem, row.Meta)).Str(" | ").Str(row.Meta.Area).
				Str(" | ").Str(row.Meta.Status).Str(" | ").Str(row.Meta.Coverage)
			if !section.Brief {
				tb.Str(" | ").Str(row.Meta.Remaining)
			}
			tb.Str(" |\n")
		}
	}
	tb.Str("\n<!-- source: docs/features.md -- feature status vocabulary and draft-backed feature rows -->\n")
	tb.Str("<!-- source: docs/features/bgp-protocol.md -- draft-backed BGP capability rows -->\n")
	tb.Str("<!-- source: docs/guide/rpki.md -- ASPA draft verification behavior -->\n")
	return tb.String(), nil
}

// statusRow is one placed row: the summary that declares it, and what it
// declares.
type statusRow struct {
	Stem string
	Meta Meta
}

// placeRows groups every summary that declares a section, in the rank order the
// summaries themselves state.
//
// A duplicate rank inside one section is REFUSED rather than broken by stem.
// Two rows with the same rank have no order, and a tie-break invented here
// would put the page's reading order in the renderer where the summaries are
// meant to own it.
func placeRows(metas map[string]Meta) (map[string][]statusRow, error) {
	out := map[string][]statusRow{}
	ranks := map[string]map[int]string{}
	for _, stem := range sortMetaStems(metas) {
		meta := metas[stem]
		if !meta.HasRow() {
			continue
		}
		if ranks[meta.Support] == nil {
			ranks[meta.Support] = map[int]string{}
		}
		if taken, held := ranks[meta.Support][meta.Rank]; held {
			var tb textbuf.Buffer
			return nil, parseErr(tb.Str(summaryRel).Byte('/').Str(stem).
				Str(".md and ").Str(summaryRel).Byte('/').Str(taken).
				Str(".md both claim rank ").Int(int64(meta.Rank)).Str(" of section ").
				Str(pyRepr(meta.Support)).Str(" on ").Str(statusRel).
				Str(". Two rows with one rank have no order, and inventing a tie-break here ").
				Str("would move the page's reading order out of the summaries that own it"))
		}
		ranks[meta.Support][meta.Rank] = stem
		out[meta.Support] = append(out[meta.Support], statusRow{Stem: stem, Meta: meta})
	}
	for key := range out {
		rows := out[key]
		sort.Slice(rows, func(i, j int) bool { return rows[i].Meta.Rank < rows[j].Meta.Rank })
	}
	return out, nil
}

// statusPageIntro is the page's own prose, with its one count derived.
//
// Held here rather than in the file it renders, because the file is generated:
// prose left in the output would be overwritten by the next run and an author
// editing it would lose the edit with nothing saying so.
func statusPageIntro(unrowed, summaries int) string {
	var tb textbuf.Buffer
	tb.Str("This page is Ze's public standards status page. It lists RFCs that Ze implements, ")
	tb.Str("partially implements, has deferred, or has explicitly decided not to implement. It is ")
	tb.Str("a product support view rather than a formal IETF compliance certificate: `Supported` ")
	tb.Str("means the behavior is implemented and tied to current source anchors; `Experimental` ")
	tb.Str("means implemented but still needs deployment evidence or hardening before production ")
	tb.Str("claims; `Partial` means a named subset is missing, intentionally skipped, or not ")
	tb.Str("proven; `Unsupported` means Ze explicitly does not implement it; `Future` means ")
	tb.Str("tracked but not shipped.\n\n")
	tb.Str("Every row below is declared by the RFC's own summary, in the `## Meta` table of ")
	tb.Str("`rfc/short/<stem>.md`. A row belongs here only when current docs, source code, tests, ")
	tb.Str("or learned closure notes tie the RFC to a Ze feature, and a summary that ties to none ")
	tb.Str("writes `| Support | - |` instead.\n\n")
	tb.Str("This page is the product view. The per-requirement detail behind it is published at ")
	tb.Str("`/quality/rfc-compliance/<stem>/`, one page for every summary under `rfc/short/`, ")
	tb.Str("naming each requirement, the tests bound to it, the audit verdict a reader recorded, ")
	tb.Str("and every gap and untested MUST under its own requirement id. The ")
	tb.Str(share(unrowed, summaries, "summaries"))
	tb.Str(" with no row on this page are published there too, and the index at ")
	tb.Str("`/quality/rfc-compliance/` links all of them.\n\n")
	tb.Str("**How strong the proof behind a row is.** Every requirement's evidence is listed in ")
	tb.Str("that RFC's own file under `rfc/requirements/`, with a `kind/tier` cell per test link. ")
	tb.Str("`kind` is the layer the test exercises (`unit`, `functional`, `editor`, `interop`); ")
	tb.Str("`tier` is whether anything executes it. `verify` means it runs in ")
	tb.Str("`./le verify current mode full` on every push. `interop/nightly` runs only in the ")
	tb.Str("scheduled, advisory `evidence-nightly` workflow -- so a requirement whose evidence is ")
	tb.Str("entirely nightly-tier is marked `**nightly-only**` on its row there, and counted in ")
	tb.Str("its own column of the coverage rollup in `ai/RFC-REQUIREMENTS.md`, and a row here ")
	tb.Str("backed only by such evidence is not proven on the merge path. A tag in a suite no ")
	tb.Str("pipeline runs is refused outright rather than published with a caveat.\n")
	tb.Str("<!-- source: internal/le/rfc/actions.go -- Answer -->\n\n")
	tb.Str("**What on this page a machine checks, and what stays a human judgement.** ")
	tb.Str("`./le rfc check` enforces exactly three properties of the tables below.\n\n")
	tb.Str("- **Gap-count agreement.** A `Support remaining` cell can spell a number immediately ")
	tb.Str("before MUST or SHALL. That number must equal the count of `{gap}` annotations in the ")
	tb.Str("same summary.\n")
	tb.Str("- **Disclosure under a `{gap}`.** A summary can privately admit an unmet MUST. Its row ")
	tb.Str("here must then say so, in the Status cell or in the Remaining cell.\n")
	tb.Str("- **A support claim rests on something.** A row claiming anything but `Unsupported` or ")
	tb.Str("`Future` over a summary that declares no MUST-level requirement is refused, unless the ")
	tb.Str("summary declares itself non-normative or carries a manual-walk extraction sign-off.\n\n")
	tb.Str("Row presence needs no check any more. A row exists exactly where a summary declares a ")
	tb.Str("section, so an enrolled RFC with no row, a row naming an RFC with no summary, and two ")
	tb.Str("rows for one RFC are each unrepresentable rather than refused.\n\n")
	tb.Str("Everything else in the table is editorial and no gate reads it. **Status** is a ")
	tb.Str("product-support judgement. It is neither the RFC's IETF category nor a derived value. ")
	tb.Str("**Area** is a hand-written label. **Implemented coverage** is source-anchored prose.\n\n")
	tb.Str("One coverage limit is worth stating outright. A Remaining cell that spells its count ")
	tb.Str("in digits is not judged, and neither is one that puts words between the number and ")
	tb.Str("MUST. That is deliberate: the page uses a second convention where a number NEAR the ")
	tb.Str("word MUST is the not-applicable count.\n")
	tb.Str("<!-- source: internal/le/rfc/actions.go -- Answer -->\n")
	return tb.String()
}

// LedgerPaths answers the three generated files, in a fixed order.
//
// The ONE producer of that set. The write emits it, the freshness check
// compares against it, and a caller that spelled the three paths itself could
// name a file neither of them owns.
func LedgerPaths() []string { return []string{enrolledRel, notEnrolledRel, statusRel} }

// wrapComment breaks one sentence into lines no wider than width, without
// breaking a word, so a derived meaning renders as a comment block rather than
// as one line nobody can read.
func wrapComment(text string, width int) []string {
	var out []string
	var line string
	for word := range strings.FieldsSeq(text) {
		switch {
		case line == "":
			line = word
		case len(line)+1+len(word) <= width:
			line = line + " " + word
		default:
			out = append(out, line)
			line = word
		}
	}
	if line != "" {
		out = append(out, line)
	}
	return out
}
