package rfc

import (
	"regexp"
	"strings"
	"testing"

	"github.com/ze-software/ze/internal/le/lepath"
)

// ledgerFixture answers the three generated files over this checkout.
func ledgerFixture(t *testing.T) (map[string]string, map[string]Meta, string) {
	t.Helper()
	root, err := lepath.Root()
	if err != nil {
		t.Fatalf("resolve checkout: %v", err)
	}
	metas, err := summaryMetas(root, nil)
	if err != nil {
		t.Fatalf("read the summaries: %v", err)
	}
	files, err := LedgerFiles(metas)
	if err != nil {
		t.Fatalf("render the ledger files: %v", err)
	}
	return files, metas, root
}

// VALIDATES: AC-5 -- generation reproduces the enrolment the authored files
// held, stem for stem and reason for reason.
// PREVENTS: risk R-4, a migration that silently changes an enrolment while no
// ratchet is watching. The deleting commit is the one commit whose baseline the
// ratchets cannot read in the old shape, so the set has to be compared directly
// rather than trusted to a gate.
//
// The comparison is over the SET and the REASON, not over the bytes. The
// authored rfc/enrolled.txt was in append order, which is enrolment history and
// carries no editorial meaning, and the generated file is sorted by stem like
// every other generated ledger here. A row that changed hands would show up in
// either comparison; a reordering shows up only in the byte one, and is not a
// defect.
func TestGeneratedEnrolmentMatchesTheAuthoredFiles(t *testing.T) {
	_, metas, root := ledgerFixture(t)

	// HEAD, never the working tree. The tree's copies are GENERATED now, so
	// comparing against them would compare the render with itself. The
	// migration's question is whether the authored files that HEAD still
	// carries said the same thing.
	blobs, known := gitCatBlobs(root, headRevision, []string{enrolledRel, notEnrolledRel})
	if !known {
		t.Skip("git cannot answer for HEAD, so there is no authored side to compare")
	}
	authored := map[string]string{}
	kinds := map[string]string{}
	for _, one := range []struct {
		rel   string
		kind  string
		cells int
	}{{enrolledRel, enrolmentEnrolled, 2}, {notEnrolledRel, "", 3}} {
		text, held := blobs[one.rel]
		if !held || strings.Contains(text, "GENERATED by") {
			t.Skipf("%s is already generated at HEAD", one.rel)
		}
		for line := range strings.SplitSeq(text, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			fields := strings.SplitN(line, "\t", one.cells)
			stem := strings.TrimSpace(fields[0])
			kind := one.kind
			reason := ""
			if one.cells == 3 && len(fields) == 3 {
				kind, reason = strings.TrimSpace(fields[1]), strings.TrimSpace(fields[2])
			} else if len(fields) > 1 {
				reason = strings.TrimSpace(fields[1])
			}
			authored[stem] = reason
			kinds[stem] = kind
		}
	}

	for stem, reason := range authored {
		meta, held := metas[stem]
		if !held {
			t.Errorf("%s was declared in the authored files and has no summary", stem)
			continue
		}
		if meta.Enrolment != kinds[stem] {
			t.Errorf("%s was %q and is now %q", stem, kinds[stem], meta.Enrolment)
		}
		if unescapePipes(meta.EnrolmentReason) != reason {
			t.Errorf("%s changed its reason:\n authored: %s\n declared: %s",
				stem, reason, meta.EnrolmentReason)
		}
	}
	for stem, meta := range metas {
		if _, held := authored[stem]; !held && meta.Enrolled() {
			t.Errorf("%s is enrolled now and was not declared before", stem)
		}
	}
}

// unescapePipes undoes the markdown escape a Meta cell carries, so a cell can
// be compared against the plain text the authored file held.
func unescapePipes(text string) string { return strings.ReplaceAll(text, `\|`, "|") }

// VALIDATES: AC-5 for the public page -- every authored row survives generation
// with its four cells intact.
// PREVENTS: the same risk on the surface that is published. One authored row,
// RFC 1994, carried an unescaped `MD5(id||secret||challenge)` in its coverage
// cell, so the page's own parser split it into nine cells, truncated the
// coverage and DISCARDED the remainder. A comparison that read the page with
// that parser would have called the loss a match.
func TestGeneratedStatusRowsMatchTheAuthoredPage(t *testing.T) {
	_, metas, root := ledgerFixture(t)
	blobs, known := gitCatBlobs(root, headRevision, []string{statusRel})
	if !known {
		t.Skip("git cannot answer for HEAD, so there is no authored side to compare")
	}
	page, held := blobs[statusRel]
	if !held || strings.Contains(page, "GENERATED by") {
		t.Skip("the page is already generated at HEAD, so there is no authored side to compare")
	}

	rows := 0
	for line := range strings.SplitSeq(page, "\n") {
		if !strings.HasPrefix(line, "|") {
			continue
		}
		cells := authoredRowCells(line)
		if len(cells) < 3 || cells[0] == "RFC" || cells[0] == "Standard" ||
			strings.HasPrefix(cells[0], "---") {
			continue
		}
		stem := authoredRowStem(cells[0])
		meta, held := metas[stem]
		if !held {
			t.Errorf("the page carries a row for %q and no summary declares it", cells[0])
			continue
		}
		rows++
		if !meta.HasRow() {
			t.Errorf("%s has a row on the page and declares `| Support | - |`", stem)
			continue
		}
		if migrationExempt[stem] {
			continue
		}
		if RowName(stem, meta) != cells[0] {
			t.Errorf("%s renders its first cell as %q, want %q", stem, RowName(stem, meta), cells[0])
		}
		for index, want := range []string{cells[1], cells[2]} {
			got := []string{meta.Area, meta.Status}[index]
			if unescapePipes(got) != want {
				t.Errorf("%s cell %d: %q, want %q", stem, index+1, got, want)
			}
		}
		if unescapePipes(meta.Coverage) != cells[3] {
			t.Errorf("%s coverage:\n authored: %s\n declared: %s", stem, cells[3], meta.Coverage)
		}
		remaining := "-"
		if len(cells) > 4 {
			remaining = cells[4]
		}
		if unescapePipes(meta.Remaining) != remaining {
			t.Errorf("%s remaining:\n authored: %s\n declared: %s", stem, remaining, meta.Remaining)
		}
	}
	declared := 0
	for _, meta := range metas {
		if meta.HasRow() {
			declared++
		}
	}
	if rows != declared {
		t.Errorf("the authored page carries %d row(s) and the summaries declare %d", rows, declared)
	}
}

// migrationExempt is the two rows whose cells legitimately differ from what the
// authored page held, each named with its reason so a THIRD divergence fails.
//
// This map is not a mechanism, it is a record of one migration. The whole test
// retires with the authored page: once HEAD carries the generated file there is
// no authored side left and the skip above takes over.
var migrationExempt = map[string]bool{
	// The authored coverage cell wrote `MD5(id||secret||challenge)` with the
	// pipes unescaped, so the page's own parser cut the row into nine cells,
	// truncated the coverage and DISCARDED the remainder -- taking its
	// "Three MUST gaps" out of checkGapCountAgreement's population. The Meta
	// cell escapes them, the page renders `\|`, and the row is whole again.
	"rfc1994": true,
	// Lowered from `Supported in IPsec` to `Partial in IPsec` in
	// rfc/short/rfc3748.md by another session on 2026-09-01, after the
	// declaration moved and before this comparison ran. That is the new
	// mechanism working: one edit to one summary, and the public page
	// followed. Nothing about it is a migration defect.
	"rfc3748": true,
	// Both cited a retired path from inside an authored cell: rfc7999 said
	// "Enrolled in `rfc/enrolled.txt` on 2026-08-13" and rfc1035 said
	// "Declared `backlog` in `rfc/not-enrolled.txt`". Naming a file that is
	// now generated FROM this very cell is a loop a reader cannot follow, so
	// the citation went and the claim stayed.
	"rfc7999": true,
	"rfc1035": true,
	// Both were marked out-of-scope on the owner's decision of 2026-09-01,
	// which lowered each row to `Future` and rewrote its two prose cells. The
	// authored page still carries the `Partial` and `Experimental` those rows
	// claimed before either RFC had a summary to check the claim against.
	"rfc6514": true,
	"rfc8362": true,
}

// authoredRowCells cuts one row of the AUTHORED page into its five cells.
//
// The page was markdown a naive split could not read: one row wrote an
// unescaped pipe inside a cell, so a plain split answered nine cells and the
// last four were read as the wrong columns. The middle is glued back here,
// which is what the migration itself did, so this comparison sees the row the
// author wrote rather than the row the old parser saw.
func authoredRowCells(line string) []string {
	cells := strings.Split(strings.Trim(strings.TrimSpace(line), "|"), "|")
	for i := range cells {
		cells[i] = strings.TrimSpace(cells[i])
	}
	if len(cells) <= 5 {
		return cells
	}
	glued := append([]string{}, cells[:3]...)
	glued = append(glued, strings.Join(cells[3:len(cells)-1], "|"))
	return append(glued, cells[len(cells)-1])
}

// authoredRowStem keys one authored row the way the retired page parser did,
// falling back to a slug for the one row it could not key at all.
func authoredRowStem(cell string) string {
	if found := regexp.MustCompile(`\ARFC\s*(\d+)\z`).FindStringSubmatch(cell); found != nil {
		return "rfc" + found[1]
	}
	if regexp.MustCompile(`\A[a-z][a-z0-9]*(-[a-z0-9.]+)+\z`).MatchString(cell) {
		return cell
	}
	return strings.Trim(regexp.MustCompile(`[^a-z0-9]+`).
		ReplaceAllString(strings.ToLower(cell), "-"), "-")
}

// VALIDATES: AC-11 -- every count the generated files state carries its
// denominator and its percentage.
// PREVENTS: an absolute number reading as an achievement. "3,256 gated MUSTs"
// counts obligations JUDGED and is read as obligations MET; the percentage is
// what makes the population visible, and the population is what the reader is
// being told about.
//
// The scan is over the prose the RENDERER writes, never over the authored cells
// it quotes. A support claim is editorial prose moved verbatim, and rewriting a
// number inside one would both invent a claim and break the gap-count reader,
// which matches a spelled number sitting immediately before MUST or SHALL.
func TestEveryGeneratedCountCarriesItsDenominator(t *testing.T) {
	files, _, _ := ledgerFixture(t)

	for _, rel := range []string{enrolledRel, notEnrolledRel} {
		for _, line := range strings.Split(files[rel], "\n") {
			if !strings.HasPrefix(line, "#") {
				continue
			}
			if bare := bareCount(line); bare != "" {
				t.Errorf("%s states a bare count %q with no population:\n%s", rel, bare, line)
			}
		}
	}
	head, _, _ := strings.Cut(files[statusRel], "\n## ")
	if bare := bareCount(head); bare != "" {
		t.Errorf("the page's generated prose states a bare count %q", bare)
	}
}

// The two shapes a number legitimately takes in generated prose, removed before
// anything is called a bare count: a share, which is the form AC-11 requires,
// and a reference to a numbered standard, which names a document rather than
// counting anything.
var (
	sharePhraseRE = regexp.MustCompile(`\b\d[\d,]* of \d[\d,]* [a-z]+(?: \(\d+\.\d+%\)| \(no population\))?`)
	standardRefRE = regexp.MustCompile(`\b(?:RFC|BCP|STD|ISO|IEC)\s*\d+`)
	countRE       = regexp.MustCompile(`\b\d[\d,]*\b`)
)

// bareCount answers the first count in generated prose that names no
// population, or "" when every number is a share or a standard reference.
func bareCount(text string) string {
	text = sharePhraseRE.ReplaceAllString(text, " ")
	text = standardRefRE.ReplaceAllString(text, " ")
	return countRE.FindString(text)
}

// VALIDATES: AC-12 and risk R-7 -- the gap-count check still reads a count from
// the rows it read before the move.
// PREVENTS: the population emptying in silence. gapCountRE matches a spelled
// number IMMEDIATELY before MUST or SHALL, so appending a denominator inside a
// Remaining cell -- "Fifteen of 219 MUST-level rows" -- stops it matching, the
// row leaves the check without a word of complaint, and the gate reads greener
// than it did.
func TestGapCountPopulationSurvivesTheMove(t *testing.T) {
	_, metas, _ := ledgerFixture(t)
	rows := rowsFrom(metas)
	counted := 0
	for _, row := range rows {
		if _, held := spelledGapCount(row.Remaining); held {
			counted++
		}
	}
	// 57, not the 56 measured before this move. The authored page's parser
	// split on every pipe, and RFC 1994's coverage cell writes an unescaped
	// `MD5(id||secret||challenge)`, so that row came back with nine cells, a
	// truncated coverage and an EMPTY remainder -- and its "Three MUST gaps"
	// was outside the check. The cell is escaped in the Meta table and the
	// row rejoins the population it always belonged to.
	if counted != 57 {
		t.Errorf("checkGapCountAgreement reads a gap count from %d of %d row(s), want 57",
			counted, len(rows))
	}
}
