// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-pki-api.yang", ZePKIAPIYANG)
	configyang.RegisterModule("ze-pki-conf.yang", ZePKIConfYANG)
}
