// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-cli-delete-api.yang
var ZeCliDeleteAPIYANG string

//go:embed ze-cli-delete-cmd.yang
var ZeCliDeleteCmdYANG string
