// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import (
	configyang "codeberg.org/thomas-mangin/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-cli-delete-api.yang", ZeCliDeleteAPIYANG)
	configyang.RegisterModule("ze-cli-delete-cmd.yang", ZeCliDeleteCmdYANG)
}
