// Design: docs/architecture/isis/isis-6-lsdb.md -- own-LSP origination and sequence state.
// Related: lsdb_wiring.go -- originate(), the coalescing guard this file bypasses
// Related: dis_wiring.go -- the pseudo-node origination this file re-arms
// Related: lsdb/lsdb.go -- ownConflictResult, which detects the conflict
//
// This file owns ONE rule: when another system claims a sequence number for an
// LSP ID that belongs to this node, this node answers by re-originating that LSP
// above the claim. Nothing else can answer it -- a system is the only authority
// for its own LSP IDs, so a claim it does not supersede simply stands.
//
// ISO/IEC 10589 clause 7.3.16.1 and clause 7.3.16.4 c). The clause text is quoted
// on reoriginateAboveClaim below, from the identical wording of RFC 1142 (the
// IETF republication of the same protocol specification); the ISO text itself is
// not redistributable, so this repository holds no copy of it (iso/README.md).

package isis

import (
	"github.com/ze-software/ze/internal/plugins/isis/lsdb"
	"github.com/ze-software/ze/internal/plugins/isis/types"
)

// reoriginateAboveClaim answers another system's claim on one of THIS node's own
// LSP IDs: it raises the origination sequence floor above the claimed sequence and
// re-originates that LSP, so the regenerated copy strictly supersedes the claim
// and floods on every eligible circuit.
//
// ISO/IEC 10589 clause 7.3.16.4, quoted from the identical text of RFC 1142
// section 7.3.16.4:
//
//	"c) If this system (or pseudonode) is S and there is an un-expired LSP from
//	    S (i.e. its own LSP) in memory, then the IS:
//	    1) shall not overwrite with the received LSP, but
//	    2) shall change the sequence number of the un-expired LSP from S as
//	       described in 7.3.16.1,
//	    3) generate a new LSP; and
//	    4) set SRMflag on all circuits."
//
// and clause 7.3.16.1, which c-2 defers to:
//
//	"If an Intermediate system R somewhere in the domain has information that
//	 the current sequence number for source S is greater than that held by S, R
//	 will return to S a Link State PDU for S with R's value for the sequence
//	 number. When S receives this LSP it shall change its sequence number to be
//	 the next number greater than the new one received, and shall generate a
//	 link state PDU."
//
// The four steps are split across three producers. c-1 is the LSDB's refusal to
// store (lsdb.ownConflictResult). c-2 is lsdb.Originator.RaiseSequenceFloor. c-3
// and c-4 are here: originate() -- or, for a pseudo-node, the DIS re-election pass
// -- regenerates the LSP and arms SRM on every circuit forming the level.
//
// Three shapes are not answered, and RaiseSequenceFloor reports false for each:
// a claim BELOW a sequence this node has already issued (its own flood corrects
// the sender), a claim on an LSP ID this node does not originate (clause
// 7.3.16.4 c) has no un-expired own LSP to change the sequence of, and clause
// 7.3.16.4 a)'s acknowledgement is the whole answer), and a REPEAT of a claim
// already answered. The third is what stops a retransmission storm, and it needs
// its own record rather than the sequence test: raising the floor writes the
// claimed value into lastSeq, so for a fragment the current state no longer
// produces -- where the answer never writes that ID -- the sequence test can
// never damp it.
func (e *engine) reoriginateAboveClaim(level lsdb.Level, id types.LSPID, claimed types.SequenceNumber) {
	if e.originator == nil {
		return
	}
	if !e.originator.RaiseSequenceFloor(id, claimed) {
		return
	}
	e.log.Warn("isis: own LSP claimed by another system, re-originating above it",
		"level", level.String(), "lsp-id", id.String(), "claimed-sequence", uint32(claimed))
	if id.PseudonodeID() != 0 {
		// A pseudo-node LSP is regenerated by the DIS re-election pass, not by
		// originate(). Dropping its coalescing record makes the next reelectTick
		// (once per second) re-originate it from the raised floor.
		e.clearPseudonodeCoalescing(level, id.SourceID())
		return
	}
	e.forceOriginate(level)
}

// forceOriginate re-originates level's own LSP set, bypassing the coalescing skip
// in originationUnchanged. That skip collapses a burst of requests for an
// UNCHANGED input into one flood. A sequence-floor raise changes no input, so
// without dropping the recorded input the regeneration clause 7.3.16.4 c-3
// requires would be coalesced away and the claim would stand.
func (e *engine) forceOriginate(level lsdb.Level) {
	e.mu.Lock()
	delete(e.lastOrigInput, level)
	e.mu.Unlock()
	e.originate()
}

// clearPseudonodeCoalescing drops the pseudo-node origination coalescing record
// for every (circuit, level) whose elected pseudo-node is src, so the next
// re-election pass regenerates that pseudo-node LSP instead of skipping it as an
// unchanged input. A src this node does not originate matches nothing and the
// call is inert -- which is the right outcome for a stale pseudo-node LSP echoed
// back after this node yielded the DIS role.
func (e *engine) clearPseudonodeCoalescing(level lsdb.Level, src types.SourceID) {
	e.disMu.Lock()
	defer e.disMu.Unlock()
	for key, elected := range e.disPseudonode {
		if key.level == level && elected == src {
			delete(e.pnLastInput, key)
			delete(e.pnLastOrigAt, key)
		}
	}
}
