// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import (
	configyang "codeberg.org/thomas-mangin/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-bfd-api.yang", ZeBFDAPIYANG)
	configyang.RegisterModule("ze-bfd-cmd.yang", ZeBFDCmdYANG)
	configyang.RegisterModule("ze-bfd-conf.yang", ZeBFDConfYANG)
}
