// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-bfd-api.yang", ZeBFDAPIYANG)
	configyang.RegisterModule("ze-bfd-cmd.yang", ZeBFDCmdYANG)
	configyang.RegisterModule("ze-bfd-conf.yang", ZeBFDConfYANG)
}
