// Design: ai/rules/architecture.md -- module-tier placement, audited from imports
//
// Package tier provides the reverse-dependency audit and module-tier placement
// gate. For each top-level directory in a registry area, it reports external
// importers.
//
// A directory imported only by registration roots and tests is a plugin
// candidate. No core or sibling package calls it, so only the registry reaches
// it. It already passes the delete-the-folder test. External importers identify
// genuine core or shared code.
//
// The static scan reads import strings without build-tag filtering. Thus, it
// sees platform-specific imports that `go list` misses on another platform. It
// cannot distinguish used imports from dead imports, which is correct for a
// move audit.
//
// Plugin roots come from internal/le/pluginimports.PluginSearchRoots. This function
// uses the composition-root generator's actual list. The replaced script parsed
// the same list from scripts/codegen/plugin_imports.go. A direct call preserves
// the guarantee and survives script deletion.
//
// Detail: gates.go -- the five checks --check runs
// Detail: selftest.go -- the fixtures that prove those checks still detect
// Detail: actions.go -- the four actions and the tree each is pointed at
// Detail: report.go -- what each action answers
package tier

import (
	"errors"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/ze-software/ze/internal/core/textbuf"
	"github.com/ze-software/ze/internal/le/pluginimports"
)

// These two registry areas can contain an engine. The placement rule,
// classification, manifest, and fixtures all use these constants. A typo would
// create a gate that checks nothing.
const (
	AreaComponent = "internal/component"
	AreaPlugins   = "internal/plugins"
)

// DefaultAreas are the three registries the report covers.
var DefaultAreas = [...]string{
	AreaComponent,
	AreaPlugins,
	"internal/component/bgp/plugins",
}

// skipWalk are directory names the edge scan never descends into.
var skipWalk = map[string]bool{
	".git":         true,
	".claude":      true,
	"vendor":       true,
	"tmp":          true,
	"node_modules": true,
}

// modCacheDir holds extracted copies of external modules AND a self-copy of ze,
// regenerated by appliance builds. Auditing those duplicates the working tree's
// already-baselined edges, and none of it is first-party source.
const modCacheDir = "gokrazy/modcache"

// engineCall is the constructor that makes a package a config-driven engine.
const engineCall = "sdk.NewWithConn("

// setupFeaturePattern matches the per-feature setup registration files under
// cmd/ze, which are a composition root like the generated all.go.
const setupFeaturePattern = `/setup_features_[^/]+\.go$`

var setupFeatureRe = regexp.MustCompile(setupFeaturePattern)

// Edges maps an imported package's import path to the tree-relative files that
// import it.
type Edges map[string][]string

// ModulePath answers the module path go.mod declares.
func ModulePath(tree string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(tree, "go.mod")) //nolint:gosec // the go.mod of the tree the caller named
	if err != nil {
		return "", err
	}
	for line := range strings.SplitSeq(string(raw), "\n") {
		if !strings.HasPrefix(line, "module ") {
			continue
		}
		return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
	}
	return "", errors.New("go.mod: no module line found")
}

// IsRegistrationImporter reports files that only blank-import for side-effect
// registration.
//
// Generated per-feature compile-out files beside all.go are composition roots
// behind build tags. They MUST count. Otherwise, moving a gated ENGINE import
// from all.go to all_<tag>.go would appear to create a feature dependency.
func IsRegistrationImporter(rel string) bool {
	if strings.HasSuffix(rel, "/all/all.go") {
		return true
	}
	parent, base := path.Split(rel)
	parent = strings.TrimSuffix(parent, "/")
	if strings.HasSuffix(parent, "/plugin/all") && strings.HasPrefix(base, "all_") && strings.HasSuffix(base, ".go") {
		return true
	}
	if !strings.HasPrefix(rel, "cmd/ze/") {
		return false
	}
	return strings.Contains(rel, "dispatch") ||
		strings.HasSuffix(rel, "_imports.go") ||
		setupFeatureRe.MatchString(rel)
}

// CollectEdges reads every tree Go file and answers its import edges.
//
// An unreadable file stops the run. The script skipped it. A missing import edge
// can hide an upward import from the direction gate. The resulting lower
// violation count looks like a pass, with no skipped-file notice.
func CollectEdges(tree, module string) (Edges, error) {
	var tb textbuf.Buffer
	importRe, err := regexp.Compile(tb.Byte('"').Byte('(').Str(regexp.QuoteMeta(module)).Str(`/[^"]+)"`).String())
	if err != nil {
		return nil, err
	}

	edges := make(Edges)
	err = filepath.WalkDir(tree, func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, relErr := filepath.Rel(tree, name)
		if relErr != nil {
			return relErr
		}
		rel = filepath.ToSlash(rel)
		if entry.IsDir() {
			if rel == "." {
				return nil
			}
			if skipWalk[entry.Name()] || rel == modCacheDir {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(entry.Name(), ".go") {
			return nil
		}
		raw, readErr := os.ReadFile(name) //nolint:gosec // a Go file of the tree the caller named
		if readErr != nil {
			return readErr
		}
		for _, match := range importRe.FindAllStringSubmatch(string(raw), -1) {
			edges[match[1]] = append(edges[match[1]], rel)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	for imported := range edges {
		sort.Strings(edges[imported])
	}
	return edges, nil
}

// importersOf answers the tree-relative files importing a package or anything
// under it, split into the three classes the audit cares about.
func (e Edges) importersOf(pkgPrefix, ownPrefix string) (external, registration, tests []string) {
	seen := make(map[string]bool)
	for imported, importers := range e {
		if !underDir(imported, pkgPrefix) {
			continue
		}
		for _, importer := range importers {
			if seen[importer] || strings.HasPrefix(importer, ownPrefix) {
				continue
			}
			seen[importer] = true
			switch {
			case strings.HasSuffix(importer, "_test.go"):
				tests = append(tests, importer)
			case IsRegistrationImporter(importer):
				registration = append(registration, importer)
			default:
				external = append(external, importer)
			}
		}
	}
	sort.Strings(external)
	sort.Strings(registration)
	sort.Strings(tests)
	return external, registration, tests
}

// classifyRel answers one package directory's audit row, without the name.
func (e Edges) classifyRel(rel, module string, engineDirs map[string]bool) Row {
	var tb textbuf.Buffer
	pkgPrefix := tb.Str(module).Byte('/').Str(rel).String()
	tb.Reset()
	ownPrefix := tb.Str(rel).Byte('/').String()

	external, registration, tests := e.importersOf(pkgPrefix, ownPrefix)
	row := Row{
		External:     external,
		Registration: registration,
		Tests:        tests,
		IsCandidate:  len(external) == 0,
		IsRegistered: len(registration) > 0,
		IsEngine:     engineDirs[rel],
	}
	// A genuine internal/core candidate: a leaf nothing depends on, that no
	// composition root wires, and that is not a config-driven engine.
	row.CoreCandidate = row.IsCandidate && !row.IsRegistered && !row.IsEngine
	return row
}

// Classify answers one area's audit rows, one per top-level subsystem, in name
// order.
//
// "Wired" means blank-imported by a composition root, which is the
// authoritative signal that the build treats a subsystem as a plugin or a
// command. It reuses the generator's output plus the dispatch root rather than
// a per-mechanism registration grep, which mis-sent every *-cmd directory to
// core.
func Classify(area, tree, module string, edges Edges, engines map[string]bool) ([]Row, error) {
	entries, err := os.ReadDir(filepath.Join(tree, area))
	if err != nil {
		return nil, err
	}

	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			names = append(names, entry.Name())
		}
	}
	sort.Strings(names)

	rows := make([]Row, 0, len(names))
	for _, name := range names {
		var tb textbuf.Buffer
		subsystem := tb.Str(area).Byte('/').Str(name).String()
		row := edges.classifyRel(subsystem, module, nil)
		row.Name = name
		row.IsEngine = engines[subsystem]
		row.CoreCandidate = row.IsCandidate && !row.IsRegistered && !row.IsEngine
		rows = append(rows, row)
	}
	return rows, nil
}

// PluginDirs answers every directory a plugin can legitimately live under.
//
// It is a CALL into the composition-root generator's own list rather than a
// parse of the generator's source, which is what the script did. The two
// derivations are pinned against each other by
// internal/le/pluginimports.TestTheRootsAreTheGeneratorsOwnList's sibling here,
// TestThePluginDirsAreTheGeneratorsOwnList.
func PluginDirs() []string { return pluginimports.PluginSearchRoots() }

// NestedNamespaces answers the sub-plugin registries nested under a component,
// such as bgp/plugins.
//
// These are plugin roots under internal/component that are deeper than a
// top-level subsystem. An engine inside one is a sub-plugin of its host and is
// correctly placed, so the tier check skips it.
func NestedNamespaces(pluginDirs []string) []string {
	var nested []string
	for _, dir := range pluginDirs {
		if strings.HasPrefix(dir, "internal/component/") && strings.Count(dir, "/") >= 3 {
			nested = append(nested, dir)
		}
	}
	return nested
}

// FindEngineDirs answers every directory under the two areas whose non-test
// code calls the engine constructor, excluding anything inside a nested
// sub-plugin namespace.
func FindEngineDirs(tree string, nested []string) ([]string, error) {
	var engines []string
	for _, area := range [...]string{AreaComponent, AreaPlugins} {
		root := filepath.Join(tree, area)
		info, err := os.Stat(root)
		if err != nil || !info.IsDir() {
			continue
		}
		err = filepath.WalkDir(root, func(name string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			rel, relErr := filepath.Rel(tree, name)
			if relErr != nil {
				return relErr
			}
			rel = filepath.ToSlash(rel)
			if entry.IsDir() {
				if entry.Name() == ".git" || entry.Name() == "vendor" || entry.Name() == "tmp" {
					return fs.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
				return nil
			}
			dir := path.Dir(rel)
			if isUnder(dir, nested) || slices.Contains(engines, dir) {
				return nil
			}
			raw, readErr := os.ReadFile(name) //nolint:gosec // a Go file of the tree the caller named
			if readErr != nil {
				return readErr
			}
			if strings.Contains(string(raw), engineCall) {
				engines = append(engines, dir)
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	sort.Strings(engines)
	return engines, nil
}

// isUnder reports whether rel is one of the namespaces or sits inside one.
func isUnder(rel string, namespaces []string) bool {
	for _, namespace := range namespaces {
		if underDir(rel, namespace) {
			return true
		}
	}
	return false
}

// TopSubsystem maps any package path under the two areas to its top-level
// subsystem directory.
func TopSubsystem(rel string) string {
	parts := strings.Split(rel, "/")
	if len(parts) > 3 {
		parts = parts[:3]
	}
	return strings.Join(parts, "/")
}

// EngineSubsystems answers the top-level subsystems holding an engine, used
// only to LABEL the advisory tiers. The enforced gate reads FindEngineDirs.
func EngineSubsystems(tree string) (map[string]bool, error) {
	dirs, err := FindEngineDirs(tree, NestedNamespaces(PluginDirs()))
	if err != nil {
		return nil, err
	}
	subsystems := make(map[string]bool, len(dirs))
	for _, dir := range dirs {
		subsystems[TopSubsystem(dir)] = true
	}
	return subsystems, nil
}

// EngineDepended reports whether a FEATURE imports the engine package subtree.
//
// It excludes the engine subtree, tests, generated composition root, cmd/ze
// dispatch, and non-feature trees. None is a feature that depends on the engine.
func EngineDepended(engineRel, module string, edges Edges) bool {
	var tb textbuf.Buffer
	pkg := tb.Str(module).Byte('/').Str(engineRel).String()
	tb.Reset()
	own := tb.Str(engineRel).Byte('/').String()

	for imported, importers := range edges {
		if !underDir(imported, pkg) {
			continue
		}
		for _, importer := range importers {
			if strings.HasPrefix(importer, own) || strings.HasSuffix(importer, "_test.go") {
				continue
			}
			if IsRegistrationImporter(importer) || hasAnyPrefix(importer, NonFeaturePrefixes[:]) {
				continue
			}
			if strings.HasPrefix(importer, "internal/component/") || strings.HasPrefix(importer, "internal/plugins/") {
				return true
			}
		}
	}
	return false
}

// hasAnyPrefix reports whether rel starts with any of the prefixes.
func hasAnyPrefix(rel string, prefixes []string) bool {
	for _, prefix := range prefixes {
		if strings.HasPrefix(rel, prefix) {
			return true
		}
	}
	return false
}

// EngineMisplacements answers every misplaced engine and the area it belongs
// in.
//
// A search-root list that came back EMPTY stops the gate rather than flagging
// everything, which is what the script's parse failure did. The list is a Go
// call now, so an empty answer is a defect in the generator's own declaration.
func EngineMisplacements(tree, module string, edges Edges) (map[string]string, error) {
	pluginDirs := PluginDirs()
	if len(pluginDirs) == 0 {
		return nil, errors.New("internal/le/pluginimports: no plugin search root -- gate cannot run safely")
	}

	dirs, err := FindEngineDirs(tree, NestedNamespaces(pluginDirs))
	if err != nil {
		return nil, err
	}

	misplaced := make(map[string]string)
	for _, engine := range dirs {
		area := AreaPlugins
		if strings.HasPrefix(engine, "internal/component/") {
			area = AreaComponent
		}
		expected := AreaPlugins
		if EngineDepended(engine, module, edges) {
			expected = AreaComponent
		}
		if expected != area {
			misplaced[engine] = expected
		}
	}
	return misplaced, nil
}

// sortedKeys answers a map's keys in order, which every gate page needs.
func sortedKeys(items map[string]string) []string {
	keys := make([]string, 0, len(items))
	for key := range items {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
