// Design: (none -- new feature, shell completion generation)
// Overview: main.go -- completion dispatch
// Related: words.go -- dynamic completion data source

package completion

import "github.com/ze-software/ze/internal/core/textbuf"

// fishScript returns the fish completion script for ze.
// Top-level commands are derived from the command registry at generation time.
// Uses ze completion words for dynamic multi-level show/env completion
// with native fish description support (word\tdescription output format).
func fishScript() string {
	var tb textbuf.Buffer
	return tb.Str(`# ze fish completion -- generated by ze completion fish
# Install: ze completion fish | source
# Or:      ze completion fish > ~/.config/fish/completions/ze.fish

# Disable file completions by default.
complete -c ze -f

# __ze_needs_command returns true when no subcommand has been typed yet.
function __ze_needs_command
    set -l cmd (commandline -opc)
    set -l i 2
    while test $i -le (count $cmd)
        switch $cmd[$i]
            case '-d' '--debug' '-V' '--version'
                # no-arg flags
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set i (math $i + 1)
            case '-*'
                # unknown flag
            case '*'
                return 1
        end
        set i (math $i + 1)
    end
    return 0
end

# __ze_depth subcmd — echoes the completion depth (0-indexed) after subcmd.
# Returns 1 (no output) if subcmd not found. A partial current token does not
# count as a completed level, matching bash depth and zsh CURRENT guards.
function __ze_depth
    set -l expected $argv[1]
    set -l cmd (commandline -opc)
    set -l n 0
    set -l found 0
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '-d' '--debug' '-V' '--version'
                continue
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        if test $found -eq 1
            set n (math $n + 1)
        else if test "$word" = "$expected"
            set found 1
        else
            return 1
        end
    end
    test $found -eq 0; and return 1
    # Partial current token is part of current depth, not next.
    set -l ct (commandline -ct)
    test -n "$ct"; and set n (math $n - 1)
    echo $n
end

# __ze_under_command subcmd — true when first subcommand matches (any depth).
## Used for show where __ze_complete_dynamic handles multi-level depth.
function __ze_under_command
    set -l expected $argv[1]
    set -l cmd (commandline -opc)
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '-d' '--debug' '-V' '--version'
                continue
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        test "$word" = "$expected"; and return 0
        return 1
    end
    return 1
end

# __ze_complete_plugins outputs dynamic plugin names for completion.
# Uses ze cli -c "show plugins | json" at tab time, plus the static test/help entries.
function __ze_complete_plugins
    ze cli -c 'show plugins | json' 2>/dev/null | string match -r '"name": *"[^"]*"' | string replace -r '"name": *"([^"]*)"' '$1'
    echo test
    echo help
end

# __ze_complete_schema_modules outputs YANG module names for schema show/methods.
# Only produces output when the schema subcommand is "show" or "methods".
function __ze_complete_schema_modules
    # Find the first positional word after "schema" (skipping flags).
    set -l cmd (commandline -opc)
    set -l found 0
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '-d' '--debug' '-V' '--version'
                continue
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        if test $found -eq 1
            # This is the word after "schema" — check if show or methods.
            switch $word
                case show methods
                    ze schema list 2>/dev/null | tail -n +2 | string match -r '^\S+'
            end
            return
        else if test "$word" = schema
            set found 1
        else
            return
        end
    end
end

# __ze_complete_dynamic calls ze completion words for multi-level completion.
# Extracts the command path after the subcommand and passes it to words.
function __ze_complete_dynamic
    set -l subcmd $argv[1]
    set -l cmd (commandline -opc)
    set -l all_words
    set -l found 0
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '-d' '--debug' '-V' '--version'
                continue
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        if test $found -eq 1
            set all_words $all_words $word
        else if test "$word" = "$subcmd"
            set found 1
        else
            return
        end
    end
    test $found -eq 0; and return

    # If the current token is non-empty (partial word), exclude it from path.
    set -l ct (commandline -ct)
    set -l path $all_words
    if test -n "$ct"; and test (count $path) -gt 0
        set path $path[1..-2]
    end

    ze completion words $subcmd $path 2>/dev/null
    # Add dynamic peer selectors when completing after "peer"
    if test (count $path) -eq 1; and test "$path[1]" = "peer"
        ze completion peers 2>/dev/null
    end
end

# __ze_prev_is target — true when the last completed token equals target.
function __ze_prev_is
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 1; and test "$cmd[-1]" = "$argv[1]"
end

# __ze_complete_families outputs address families for --family <TAB>.
function __ze_complete_families
    ze completion families 2>/dev/null
end

# __ze_subcmd_path echoes the positional command path after ze (skipping flags).
function __ze_subcmd_path
    set -l cmd (commandline -opc)
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        echo $word
    end
end

# __ze_complete_flags offers flag names from the registry inventory for the
# current subcommand path (registration over hardcoding).
function __ze_complete_flags
    set -l path (__ze_subcmd_path)
    test (count $path) -ge 1; and ze completion flags $path 2>/dev/null
end

# __ze_config_subcmd echoes the config subcommand (word after "config").
function __ze_config_subcmd
    set -l cmd (commandline -opc)
    set -l found 0
    for word in $cmd[2..]
        switch $word
            case '-*'
                continue
        end
        if test $found -eq 1
            echo $word
            return
        else if test "$word" = config
            set found 1
        end
    end
end

# __ze_complete_config_section completes config-section paths for
# "ze config show <file> [path...]" via the "ze config completion" engine.
function __ze_complete_config_section
    set -l cmd (commandline -opc)
    set -l idx 0
    set -l i 1
    while test $i -le (count $cmd)
        if test "$cmd[$i]" = config
            set idx $i
            break
        end
        set i (math $i + 1)
    end
    test $idx -eq 0; and return
    set -l file $cmd[(math $idx + 2)]
    test -z "$file"; and return
    set -l sections
    set -l j (math $idx + 3)
    while test $j -le (count $cmd)
        set sections $sections $cmd[$j]
        set j (math $j + 1)
    end
    set -l ctx (string join / $sections)
    ze config completion --context "$ctx" --input 'set ' "$file" 2>/dev/null | awk '{print $2}'
end

# --- Global flags ---
complete -c ze -n __ze_needs_command -s d -l debug -d 'Enable debug logging'
complete -c ze -n __ze_needs_command -s h -l help -d 'Show help'
complete -c ze -n __ze_needs_command -s V -l version -d 'Show version'
complete -c ze -n __ze_needs_command -l plugin -x -d 'Load plugin before starting'
complete -c ze -n __ze_needs_command -l plugins -d 'List available internal plugins'
complete -c ze -n __ze_needs_command -l pprof -x -d 'Start pprof HTTP server'
complete -c ze -n __ze_needs_command -l chaos-seed -x -d 'Enable chaos mode with PRNG seed'
complete -c ze -n __ze_needs_command -l chaos-rate -x -d 'Fault probability (0.0-1.0)'

# --- Flag inventory + value completion (registration over hardcoding) ---
# --family value completion from the shared registry.
complete -c ze -n '__ze_prev_is --family' -f -a '(__ze_complete_families)'
# Flag names for the current subcommand path when typing a "-" token.
complete -c ze -n 'string match -q -- "-*" (commandline -ct)' -f -a '(__ze_complete_flags)'

# --- Top-level subcommands (derived from command registry) ---
`).Str(fishRootLines()).Str(`
# --- bgp (depth 1 only) ---
complete -c ze -n 'test (__ze_depth bgp) = 0' -a decode -d 'Decode BGP message from hex to JSON'
complete -c ze -n 'test (__ze_depth bgp) = 0' -a encode -d 'Encode API route command to BGP hex'
complete -c ze -n 'test (__ze_depth bgp) = 0' -a help -d 'Show help'

# --- config (depth 1 = subcommands, depth 2+ = .conf files / sections) ---
complete -c ze -n 'test (__ze_depth config) = 0' -a edit -d 'Interactive configuration editor'
complete -c ze -n 'test (__ze_depth config) = 0' -a validate -d 'Validate configuration file'
complete -c ze -n 'test (__ze_depth config) = 0' -a migrate -d 'Convert configuration to current format'
complete -c ze -n 'test (__ze_depth config) = 0' -a fmt -d 'Format and normalize configuration file'
complete -c ze -n 'test (__ze_depth config) = 0' -a dump -d 'Dump parsed configuration'
complete -c ze -n 'test (__ze_depth config) = 0' -a diff -d 'Compare two configuration files'
complete -c ze -n 'test (__ze_depth config) = 0' -a completion -d 'Query completion engine'
complete -c ze -n 'test (__ze_depth config) = 0' -a show -d 'Show the config tree at a path'
complete -c ze -n 'test (__ze_depth config) = 0' -a help -d 'Show help'
# Non-show subcommands take a .conf file at depth >= 1.
complete -c ze -n 'test (__ze_depth config) -ge 1; and test (__ze_config_subcmd) != show' -F
# config show <file>: the file at depth 1, then config-section paths at depth >= 2.
complete -c ze -n 'test (__ze_depth config) = 1; and test (__ze_config_subcmd) = show' -F
complete -c ze -n 'test (__ze_depth config) -ge 2; and test (__ze_config_subcmd) = show' -f -a '(__ze_complete_config_section)'

# --- cli (depth 1 only) ---
complete -c ze -n 'test (__ze_depth cli) = 0' -a bgp -d 'BGP daemon (default)'
complete -c ze -n 'test (__ze_depth cli) = 0' -a help -d 'Show help'

# --- schema (depth 1 = subcommands, depth 2 = dynamic module names) ---
complete -c ze -n 'test (__ze_depth schema) = 0' -a list -d 'List all registered schemas'
complete -c ze -n 'test (__ze_depth schema) = 0' -a show -d 'Show YANG content for a module'
complete -c ze -n 'test (__ze_depth schema) = 0' -a handlers -d 'List handler to module mapping'
complete -c ze -n 'test (__ze_depth schema) = 0' -a methods -d 'List RPCs from YANG'
complete -c ze -n 'test (__ze_depth schema) = 0' -a events -d 'List notifications from YANG'
complete -c ze -n 'test (__ze_depth schema) = 0' -a protocol -d 'Show protocol version and format info'
complete -c ze -n 'test (__ze_depth schema) = 0' -a help -d 'Show help'
# Dynamic: module names for "schema show" and "schema methods"
complete -c ze -n 'test (__ze_depth schema) = 1' -a '(__ze_complete_schema_modules)'

# --- show: dynamic multi-level from command tree ---
complete -c ze -n '__ze_under_command show' -a '(__ze_complete_dynamic show)'

# --- env: dynamic multi-level from env catalog ---
complete -c ze -n '__ze_under_command env' -a '(__ze_complete_dynamic env)'

# --- plugin (depth 1: dynamic plugin names + test/help) ---
complete -c ze -n 'test (__ze_depth plugin) = 0' -a '(__ze_complete_plugins)'

# --- exabgp (depth 1 = subcommands, depth 2+ = .conf files) ---
complete -c ze -n 'test (__ze_depth exabgp) = 0' -a plugin -d 'ExaBGP bridge plugin'
complete -c ze -n 'test (__ze_depth exabgp) = 0' -a migrate -d 'ExaBGP config migration'
complete -c ze -n 'test (__ze_depth exabgp) = 0' -a help -d 'Show help'
complete -c ze -n 'test (__ze_depth exabgp) -ge 1' -F

# --- signal (depth 1 only) ---
complete -c ze -n 'test (__ze_depth signal) = 0' -a reload -d 'Send SIGHUP - reload configuration'
complete -c ze -n 'test (__ze_depth signal) = 0' -a stop -d 'Send SIGTERM - graceful shutdown'
complete -c ze -n 'test (__ze_depth signal) = 0' -a restart -d 'Graceful restart (writes GR marker, then shuts down)'
complete -c ze -n 'test (__ze_depth signal) = 0' -a reboot -d 'Graceful shutdown then system reboot (requires root on Linux)'
complete -c ze -n 'test (__ze_depth signal) = 0' -a status -d 'Send SIGUSR1 - dump daemon status'
complete -c ze -n 'test (__ze_depth signal) = 0' -a quit -d 'Send SIGQUIT - goroutine dump + immediate exit'

# --- completion (depth 1 only) ---
complete -c ze -n 'test (__ze_depth completion) = 0' -a bash -d 'Generate bash completion script'
complete -c ze -n 'test (__ze_depth completion) = 0' -a zsh -d 'Generate zsh completion script'
complete -c ze -n 'test (__ze_depth completion) = 0' -a fish -d 'Generate fish completion script'
complete -c ze -n 'test (__ze_depth completion) = 0' -a nushell -d 'Generate nushell completion script'
`).String()
}
