// Design: (none -- new feature, shell completion generation)
// Overview: main.go -- completion dispatch
// Related: words.go -- dynamic completion data source
// Related: root_commands.go -- registry-derived top-level command list

package completion

// nushellScript returns the nushell completion script for ze.
// Top-level commands are derived from the command registry at generation time.
// A single extern with a context-aware subargs completer handles all depth
// levels, avoiding duplicate entries from sub-extern definitions.
func nushellScript() string {
	return `# ze nushell completion -- generated by ze completion nushell
# Install: ze completion nushell | save -f ($nu.default-config-dir | path join "completions" "ze.nu")
# Then add to config.nu: source completions/ze.nu

# --- Dynamic completers ---

` + nushellRootCompleter() + `
def "nu-complete ze plugins" [] {
    try {
        ^ze cli -c "show plugins | json"
        | from json
        | each {|p| { value: $p.name, description: $p.description? } }
        | append [{ value: "test", description: "Run plugin tests" } { value: "help", description: "Show help" }]
    } catch {
        ["test" "help"]
    }
}

def "nu-complete ze subargs" [context: string, offset: int] {
    let parts = ($context | str trim | split row " " | where {|w| ($w | str length) > 0 })
    if ($parts | length) < 2 { return [] }
    let subcmd = $parts.1
    mut rest = ($parts | skip 2)
    # If context does not end with a space, the last word is a partial
    # prefix being typed. Exclude it from the path so ze completion words
    # returns the full sibling list; nushell filters by prefix.
    if not ($context | str ends-with " ") and ($rest | length) > 0 {
        $rest = ($rest | drop 1)
    }

    mut result = []
    try {
        $result = (^ze completion words $subcmd ...$rest
        | lines
        | where {|line| ($line | str length) > 0 }
        | each {|line|
            let cols = ($line | split column "\t")
            if ($cols | length) > 0 {
                let row = ($cols | first)
                { value: $row.column0, description: ($row.column1? | default "") }
            }
        })
    } catch {}

    if $subcmd == "show" and ($rest | length) == 1 and ($rest | first) == "peer" {
        try {
            let peers = (^ze completion peers
            | lines
            | where {|line| ($line | str length) > 0 }
            | each {|line|
                let cols = ($line | split column "\t")
                if ($cols | length) > 0 {
                    let row = ($cols | first)
                    { value: $row.column0, description: ($row.column1? | default "") }
                }
            })
            $result = ($result | append $peers)
        } catch {}
    }
    $result
}

# --- Top-level command ---

extern "ze" [
    command?: string@"nu-complete ze commands"
    ...args: string@"nu-complete ze subargs"
    --debug(-d)                                                 # Enable debug logging
    --help(-h)                                                  # Show help
    --version(-V)                                               # Show version
    --plugin: string@"nu-complete ze plugins"                   # Load plugin before starting (repeatable)
    --pprof: string                                             # Start pprof HTTP server
    --chaos-seed: int                                           # Enable chaos self-test mode with PRNG seed
    --chaos-rate: number                                        # Fault probability per operation (0.0-1.0)
]
`
}
