// Design: (none -- new feature, shell completion generation)
// Overview: main.go -- completion dispatch
// Related: words.go -- dynamic completion data source

package completion

import "github.com/ze-software/ze/internal/core/textbuf"

// zshScript returns the zsh completion script for ze.
// Top-level commands are derived from the command registry at generation time.
// Dynamic completions (plugin names, schema modules, show/env subcommands)
// call back to ze at completion time.
func zshScript() string {
	var tb textbuf.Buffer
	return tb.Str("#compdef ze\n").Str(`# ze zsh completion -- generated by ze completion zsh
# Install: eval "$(ze completion zsh)"

_ze() {
    local -a commands
    commands=(
`).Str(zshRootArray()).Str(`    )

    _arguments -C \
        '-d[Enable debug logging]' \
        '--debug[Enable debug logging]' \
        '-h[Show help]' \
        '--help[Show help]' \
        '-V[Show version]' \
        '--version[Show version]' \
        '--plugin[Load plugin before starting]:plugin name:' \
        '--pprof[Start pprof HTTP server]:address:' \
        '--chaos-seed[Enable chaos self-test mode with PRNG seed]:seed:' \
        '--chaos-rate[Fault probability per operation (0.0-1.0)]:rate:' \
        '1:command:->cmd' \
        '*::arg:->args'

    case $state in
        cmd)
            _describe 'ze command' commands
            ;;
        args)
            # Value completion for --family (any subcommand), from the registry.
            if [[ "${words[CURRENT-1]}" == "--family" ]]; then
                local -a _ze_fam
                _ze_fam=(${(f)"$(ze completion families 2>/dev/null | sed $'s/\t/:/')"})
                [[ ${#_ze_fam} -gt 0 ]] && { _describe 'family' _ze_fam; return }
            fi
            # Flag-name completion from the registry inventory (registration
            # over hardcoding).
            if [[ "${words[CURRENT]}" == -* ]]; then
                local -a _ze_fp
                local _ze_w
                for _ze_w in ${words[2,CURRENT-1]}; do
                    [[ "$_ze_w" == -* ]] || _ze_fp+=("$_ze_w")
                done
                local -a _ze_fl
                _ze_fl=(${(f)"$(ze completion flags ${_ze_fp} 2>/dev/null | sed $'s/\t/:/')"})
                [[ ${#_ze_fl} -gt 0 ]] && { _describe 'flag' _ze_fl; return }
            fi
            case ${words[1]} in
                bgp)
                    if (( CURRENT == 2 )); then
                        local -a bgp_commands
                        bgp_commands=(
                            'decode:Decode BGP message from hex to JSON'
                            'encode:Encode API route command to BGP hex'
                            'help:Show help'
                        )
                        _describe 'bgp command' bgp_commands
                    fi
                    ;;
                config)
                    local -a config_commands
                    config_commands=(
                        'edit:Interactive configuration editor'
                        'validate:Validate configuration file'
                        'migrate:Convert configuration to current format'
                        'fmt:Format and normalize configuration file'
                        'dump:Dump parsed configuration'
                        'diff:Compare two configuration files'
                        'completion:Query completion engine'
                        'show:Show the config tree at a path'
                        'help:Show help'
                    )
                    if (( CURRENT == 2 )); then
                        _describe 'config command' config_commands
                    elif [[ ${words[2]} == show ]]; then
                        if (( CURRENT == 3 )); then
                            _files -g '*.conf'
                        else
                            # ze config show <file> [path...]: config-section
                            # paths via the "ze config completion" engine.
                            local _ze_cfg="${words[3]}"
                            local -a _ze_sec=("${words[4,CURRENT-1]}")
                            local _ze_ctx="${(j:/:)_ze_sec}"
                            local -a _ze_secs
                            _ze_secs=(${(f)"$(ze config completion --context "${_ze_ctx}" --input 'set ' "${_ze_cfg}" 2>/dev/null | awk '{print $2}')"})
                            [[ ${#_ze_secs} -gt 0 ]] && _describe 'section' _ze_secs
                        fi
                    else
                        _files -g '*.conf'
                    fi
                    ;;
                cli)
                    if (( CURRENT == 2 )); then
                        local -a cli_commands
                        cli_commands=(
                            'bgp:BGP daemon (default)'
                            'help:Show help'
                        )
                        _describe 'cli command' cli_commands
                    fi
                    ;;
                schema)
                    local -a schema_commands
                    schema_commands=(
                        'list:List all registered schemas'
                        'show:Show YANG content for a module'
                        'handlers:List handler to module mapping'
                        'methods:List RPCs from YANG'
                        'events:List notifications from YANG'
                        'protocol:Show protocol version and format info'
                        'help:Show help'
                    )
                    if (( CURRENT == 2 )); then
                        _describe 'schema command' schema_commands
                    elif (( CURRENT == 3 )) && [[ ${words[2]} == (show|methods) ]]; then
                        # Dynamic: module names from YANG registry
                        local -a modules
                        modules=(${(f)"$(ze schema list 2>/dev/null | tail -n +2 | awk '{print $1}')"})
                        _describe 'YANG module' modules
                    fi
                    ;;
                show)
                    # Dynamic: multi-level completion from YANG-driven command tree (read-only)
                    local -a path_words=()
                    if (( CURRENT > 2 )); then
                        path_words=("${words[2,CURRENT-1]}")
                    fi
                    local -a dynamic_commands
                    dynamic_commands=(${(f)"$(ze completion words show ${path_words} 2>/dev/null | sed $'s/\t/:/')"})
                    # Add dynamic peer selectors when completing after "peer"
                    if [[ ${#path_words} -eq 1 && "${path_words[1]}" == "peer" ]]; then
                        local -a peer_completions
                        peer_completions=(${(f)"$(ze completion peers 2>/dev/null | sed $'s/\t/:/')"})
                        dynamic_commands+=("${peer_completions[@]}")
                    fi
                    [[ ${#dynamic_commands} -gt 0 ]] && _describe 'command' dynamic_commands
                    ;;
                env)
                    # Dynamic: multi-level completion from env catalog
                    local -a path_words=()
                    if (( CURRENT > 2 )); then
                        path_words=("${words[2,CURRENT-1]}")
                    fi
                    local -a dynamic_commands
                    dynamic_commands=(${(f)"$(ze completion words env ${path_words} 2>/dev/null | sed $'s/\t/:/')"})
                    [[ ${#dynamic_commands} -gt 0 ]] && _describe 'command' dynamic_commands
                    ;;
                plugin)
                    if (( CURRENT == 2 )); then
                        # Dynamic: plugin names from YANG-driven registry
                        local -a plugin_names
                        plugin_names=(${(f)"$(ze cli -c 'show plugins | json' 2>/dev/null | grep -o '` + `"name": *"[^"]*"` + `' | sed 's/.*: *\"//;s/\"$//')"})
                        plugin_names+=(test help)
                        _describe 'plugin' plugin_names
                    fi
                    ;;
                exabgp)
                    local -a exabgp_commands
                    exabgp_commands=(
                        'plugin:ExaBGP bridge plugin'
                        'migrate:ExaBGP config migration'
                        'help:Show help'
                    )
                    if (( CURRENT == 2 )); then
                        _describe 'exabgp command' exabgp_commands
                    else
                        _files -g '*.conf'
                    fi
                    ;;
                signal)
                    local -a signal_commands
                    signal_commands=(
                        'reload:Send SIGHUP - reload configuration'
                        'stop:Send SIGTERM - graceful shutdown'
                        'restart:Graceful restart (writes GR marker, then shuts down)'
                        'reboot:Graceful shutdown then system reboot (requires root on Linux)'
                        'status:Send SIGUSR1 - dump daemon status'
                        'quit:Send SIGQUIT - goroutine dump + immediate exit'
                    )
                    if (( CURRENT == 2 )); then
                        _describe 'signal command' signal_commands
                    else
                        _files -g '*.conf'
                    fi
                    ;;
                completion)
                    if (( CURRENT == 2 )); then
                        local -a shells
                        shells=(bash zsh fish nushell)
                        _describe 'shell' shells
                    fi
                    ;;
            esac
            ;;
    esac
}

compdef _ze ze
`).String()
}
