// Code generated by scripts/gen-plugin-imports.go; DO NOT EDIT.

// Package all imports all internal plugins and schema packages,
// triggering their init() registration.
//
// To add a plugin, create internal/plugins/<name>/register.go with an init()
// that calls registry.Register(). Then run: make generate
package all

import (
	// Infrastructure schema packages — YANG module registration.
	_ "codeberg.org/thomas-mangin/ze/internal/component/bgp/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/hub/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/ipc/schema"
	_ "codeberg.org/thomas-mangin/ze/internal/plugin/schema"

	// Plugin packages — plugin + schema registration.
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-adj-rib-in"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-gr"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-hostname"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-llnh"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-evpn"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-flowspec"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-labeled"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-ls"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-mup"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-mvpn"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-rtc"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-vpls"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-nlri-vpn"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-rib"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-role"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-route-refresh"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-rs"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-softver"
	_ "codeberg.org/thomas-mangin/ze/internal/plugins/bgp-watchdog"
)

