// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-gnmi-cmd.yang
var ZeGNMICmdYANG string

//go:embed ze-gnmi-conf.yang
var ZeGNMIConfYANG string
