// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// Design: docs/architecture/web-interface.md -- web interface component

package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// toolCapture is the packet capture tool page.
func toolCapture(v toolPageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"wb-tool-page\"><h2 class=\"wb-form-title\">Capture</h2><form class=\"wb-tool-form\" method=\"post\" action=\"/show/tools/capture/\" hx-post=\"/show/tools/capture/\" hx-target=\"#tool-result\" hx-swap=\"innerHTML\"><div class=\"wb-form-field\"><label for=\"field-tunnel-id\" class=\"wb-form-label\">Tunnel ID</label> <input type=\"number\" id=\"field-tunnel-id\" name=\"tunnel-id\" class=\"wb-form-input\" placeholder=\"0\" min=\"0\" max=\"65535\"> <span class=\"wb-form-description\">L2TP tunnel ID filter (0-65535, 0 means no filter)</span></div><div class=\"wb-form-field\"><label for=\"field-peer\" class=\"wb-form-label\">Peer</label> <input type=\"text\" id=\"field-peer\" name=\"peer\" class=\"wb-form-input\" placeholder=\"192.0.2.1\"> <span class=\"wb-form-description\">Peer IP address filter</span></div><div class=\"wb-form-field\"><label for=\"field-count\" class=\"wb-form-label\">Count</label> <input type=\"number\" id=\"field-count\" name=\"count\" class=\"wb-form-input\" value=\"100\" min=\"1\" max=\"10000\"> <span class=\"wb-form-description\">Number of packets to capture (1-10000, default 100)</span></div><div class=\"wb-form-actions\"><button type=\"submit\" class=\"wb-form-save\">Run</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = toolResult(v).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
