// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
// Design: docs/architecture/web-interface.md -- web interface component

package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// toolMetrics is the Prometheus metric query tool page.
func toolMetrics(v toolPageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"wb-tool-page\"><h2 class=\"wb-form-title\">Metrics Query</h2><form class=\"wb-tool-form\" method=\"post\" action=\"/show/tools/metrics/\" hx-post=\"/show/tools/metrics/\" hx-target=\"#tool-result\" hx-swap=\"innerHTML\"><div class=\"wb-form-field\"><label for=\"field-name\" class=\"wb-form-label wb-form-label--required\">Metric Name</label> <input type=\"text\" id=\"field-name\" name=\"name\" class=\"wb-form-input\" placeholder=\"bgp_peer_up\" required> <span class=\"wb-form-description\">Prometheus metric name (alphanumeric, underscore, colon)</span></div><div class=\"wb-form-field\"><label for=\"field-label\" class=\"wb-form-label\">Label Filter</label> <input type=\"text\" id=\"field-label\" name=\"label\" class=\"wb-form-input\" placeholder=\"instance=peer1\"> <span class=\"wb-form-description\">Optional label=value filter</span></div><div class=\"wb-form-actions\"><button type=\"submit\" class=\"wb-form-save\">Query</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = toolResult(v).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
