// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// logLive is the live log page: the filter toolbar and the stream container
// that log-live.js fills over SSE.
func logLive() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"wb-log-live\"><h2 class=\"wb-form-title\">Live Log</h2><div class=\"wb-log-toolbar\"><select id=\"log-namespace\" class=\"wb-form-input\" aria-label=\"Namespace filter\"><option value=\"\">All Namespaces</option></select> <label class=\"wb-log-level\"><input type=\"checkbox\" name=\"level\" value=\"error\" checked> Error</label> <label class=\"wb-log-level\"><input type=\"checkbox\" name=\"level\" value=\"warning\" checked> Warning</label> <label class=\"wb-log-level\"><input type=\"checkbox\" name=\"level\" value=\"info\" checked> Info</label> <label class=\"wb-log-level\"><input type=\"checkbox\" name=\"level\" value=\"debug\"> Debug</label> <input type=\"search\" id=\"log-search\" class=\"wb-form-input\" placeholder=\"Search...\" aria-label=\"Search log entries\"> <button id=\"log-pause\" class=\"wb-form-save\">Pause</button></div><div class=\"wb-log-stream\" id=\"log-stream\" data-log-live=\"true\"><p class=\"wb-log-hint\" id=\"log-status\">Connecting to live log stream...</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
