// Design: docs/architecture/web-interface.md -- per-page web asset sets
//
// Code generated by ./le web-assets write; DO NOT EDIT.

// The vendored assets each page of this package loads, derived from the markup
// every page reaches. To change a set, change the markup. Then: ./le web-assets write

package web

// pageID names one page whose head block loads an asset set.
type pageID string

// The pages of this package, each named after the component that renders it.
const (
	// pgL2tpDetail is rendered by internal/component/web/l2tp_detail.templ.
	pgL2tpDetail pageID = "l2tpDetail"
	// pgL2tpList is rendered by internal/component/web/l2tp_list.templ.
	pgL2tpList pageID = "l2tpList"
	// pgLoginFullPage is rendered by internal/component/web/page_login.templ.
	pgLoginFullPage pageID = "loginFullPage"
	// pgPageLayout is rendered by internal/component/web/page_layout.templ.
	pgPageLayout pageID = "pageLayout"
	// pgPageWorkbench is rendered by internal/component/web/page_workbench.templ.
	pgPageWorkbench pageID = "pageWorkbench"
	// pgSnapshotPage is rendered by internal/component/web/page_snapshot.templ.
	pgSnapshotPage pageID = "snapshotPage"
)

// pageAssetSets maps each page onto the assets its head block loads.
var pageAssetSets = map[pageID][]string{
	pgL2tpDetail:    {},
	pgL2tpList:      {},
	pgLoginFullPage: {},
	pgPageLayout:    {"/assets/htmx.min.js"},
	pgPageWorkbench: {"/assets/htmx.min.js"},
	pgSnapshotPage:  {},
}

// everyAsset is every asset this package renders. It is what an unknown page
// gets: a page that loads one file too many costs bytes, and a page that loads
// nothing renders correctly and does nothing in the browser.
var everyAsset = []string{"/assets/htmx.min.js"}

// pageAssets returns the assets one page must load.
func pageAssets(page pageID) []string {
	assets, known := pageAssetSets[page]
	if !known {
		return everyAsset
	}

	return assets
}
