frr defaults traditional
hostname frr-ospf
service integrated-vtysh-config
log file /tmp/frr-ospf.log informational
!
interface eth0
 ip ospf network point-to-point
 ip ospf area 0.0.0.0
 ip ospf hello-interval 1
 ip ospf dead-interval 4
!
interface lo
 ip ospf area 0.0.0.0
!
router ospf
 ospf router-id 172.31.0.3
 passive-interface lo
 redistribute connected
!
