environment {
    ssh {
        enabled enable
        server main { ip 127.0.0.1; port 2222; }
    }
}

ospf {
    router-id 172.31.0.2
    areas { area 0.0.0.0 { area-type normal; } }
    interfaces {
        interface eth0 {
            area 0.0.0.0
            network-type point-to-point
            hello-interval 1
            dead-interval 4
            cost 10
        }
        interface lo {
            area 0.0.0.0
            passive true
        }
    }
}
