environment {
    ssh {
        enabled enable
        server main {
            ip 127.0.0.1
            port 2222
        }
    }
}

plugin {
    internal bgp-rib {
        use bgp-rib
    }
    internal rib {
        use rib
    }
    internal fib-kernel {
        use fib-kernel
    }
    internal sysctl {
        use sysctl
    }
}

bgp {
    router-id 192.0.2.1
    session {
        asn {
            local 65000
        }
    }
    peer synthetic {
        connection {
            remote {
                ip 192.0.2.10
            }
            local {
                ip 127.0.0.1
                accept false
            }
        }
        session {
            asn {
                local 65000
                remote 65001
            }
            family {
                ipv4/unicast {
                    prefix {
                        maximum 100
                    }
                }
            }
        }
    }
}
