// Design: (none -- new feature, shell completion generation)
// Overview: main.go -- completion dispatch

package completion

// bashScript returns the bash completion script for ze.
//
// Static completions cover the CLI dispatch tree (subcommands that are
// hardcoded switch cases in Go). Dynamic completions call back to ze
// at tab time for YANG-driven data: plugin names (ze --plugins --json),
// schema modules (ze schema list), and show subcommands (ze show help).
func bashScript() string {
	return `# ze bash completion -- generated by ze completion bash
# Install: eval "$(ze completion bash)"
# Or:      ze completion bash > /etc/bash_completion.d/ze

_ze_filedir() {
    if declare -F _filedir >/dev/null 2>&1; then
        _filedir "$@"
    else
        # Fallback: filter by extension if provided, otherwise all files
        if [[ -n "$1" ]]; then
            COMPREPLY=($(compgen -f -X "!*.$1" -- "${cur}"))
        else
            COMPREPLY=($(compgen -f -- "${cur}"))
        fi
    fi
}

# _ze_find_subcmd skips global flags to find the subcommand word index.
# ze --debug --plugin foo bgp decode -> subcmd_idx=4 (words[4]="bgp")
_ze_find_subcmd() {
    local i
    _ze_subcmd_idx=0
    for (( i=1; i < cword; i++ )); do
        case "${words[i]}" in
            -d|--debug|-V|--version)
                ;;
            --plugin|--pprof|--chaos-seed|--chaos-rate)
                (( i++ ))  # skip argument
                ;;
            --plugins)
                ;;
            -*)
                ;;  # skip unknown flags
            *)
                _ze_subcmd_idx=$i
                return
                ;;
        esac
    done
}

_ze() {
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion || return
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=${COMP_CWORD}
    fi

    local commands="bgp config cli validate schema show run plugin exabgp signal completion version help"

    # Complete argument for flags that take a value
    case "${prev}" in
        --plugin)
            local plugins
            plugins=$(ze --plugins --json 2>/dev/null | grep -o '"Name":"[^"]*"' | sed 's/"Name":"//;s/"//')
            COMPREPLY=($(compgen -W "${plugins}" -- "${cur}"))
            return
            ;;
        --pprof|--chaos-seed|--chaos-rate)
            return
            ;;
    esac

    # Find the subcommand position (skip global flags)
    local _ze_subcmd_idx
    _ze_find_subcmd

    # No subcommand found yet -- complete top-level commands and global flags
    if [[ ${_ze_subcmd_idx} -eq 0 ]]; then
        if [[ "${cur}" == -* ]]; then
            COMPREPLY=($(compgen -W "-d --debug -h --help --plugin --plugins --pprof --chaos-seed --chaos-rate" -- "${cur}"))
        else
            COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
        fi
        return
    fi

    local subcmd="${words[_ze_subcmd_idx]}"
    local depth=$(( cword - _ze_subcmd_idx ))

    case "${subcmd}" in
        bgp)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "decode encode help" -- "${cur}"))
            fi
            ;;
        config)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "edit check migrate fmt dump diff completion help" -- "${cur}"))
            else
                _ze_filedir conf
            fi
            ;;
        cli)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "bgp help" -- "${cur}"))
            fi
            ;;
        validate)
            _ze_filedir conf
            ;;
        schema)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "list show handlers methods events protocol help" -- "${cur}"))
            elif [[ ${depth} -eq 2 ]]; then
                local schema_sub="${words[_ze_subcmd_idx+1]}"
                if [[ "${schema_sub}" == "show" || "${schema_sub}" == "methods" ]]; then
                    # Dynamic: module names from YANG registry
                    local modules
                    modules=$(ze schema list 2>/dev/null | tail -n +2 | awk '{print $1}')
                    COMPREPLY=($(compgen -W "${modules}" -- "${cur}"))
                fi
            fi
            ;;
        plugin)
            if [[ ${depth} -eq 1 ]]; then
                # Dynamic: plugin names from YANG-driven registry
                local plugins
                plugins=$(ze --plugins --json 2>/dev/null | grep -o '"Name":"[^"]*"' | sed 's/"Name":"//;s/"//')
                plugins="${plugins} test help"
                COMPREPLY=($(compgen -W "${plugins}" -- "${cur}"))
            fi
            ;;
        exabgp)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "plugin migrate help" -- "${cur}"))
            else
                _ze_filedir conf
            fi
            ;;
        signal)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "reload stop quit status" -- "${cur}"))
            else
                _ze_filedir conf
            fi
            ;;
        show)
            if [[ ${depth} -eq 1 ]]; then
                # Dynamic: subcommands from YANG-driven RPC command tree (read-only)
                local show_cmds
                show_cmds=$(ze show help 2>&1 | awk '/^Available commands:/,/^$/{if (/^  [a-z]/) print $1}')
                COMPREPLY=($(compgen -W "${show_cmds}" -- "${cur}"))
            fi
            ;;
        run)
            if [[ ${depth} -eq 1 ]]; then
                # Dynamic: subcommands from YANG-driven RPC command tree (all)
                local run_cmds
                run_cmds=$(ze run help 2>&1 | awk '/^Available commands:/,/^$/{if (/^  [a-z]/) print $1}')
                COMPREPLY=($(compgen -W "${run_cmds}" -- "${cur}"))
            fi
            ;;
        completion)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "bash zsh" -- "${cur}"))
            fi
            ;;
    esac
}

complete -F _ze ze
`
}
