// Design: (none -- new feature, shell completion generation)
// Overview: main.go -- completion dispatch
// Related: words.go -- dynamic completion data source

package completion

// bashScript returns the bash completion script for ze.
//
// Static completions cover the CLI dispatch tree (subcommands that are
// hardcoded switch cases in Go). Dynamic completions call back to ze
// at tab time for YANG-driven data: plugin names (ze --plugins --json),
// schema modules (ze schema list), and show/run subcommands
// (ze completion words show|run).
func bashScript() string {
	return `# ze bash completion -- generated by ze completion bash
# Install: eval "$(ze completion bash)"
# Or:      ze completion bash > /etc/bash_completion.d/ze

_ze_filedir() {
    if declare -F _filedir >/dev/null 2>&1; then
        _filedir "$@"
    else
        # Fallback: filter by extension if provided, otherwise all files
        if [[ -n "$1" ]]; then
            COMPREPLY=($(compgen -f -X "!*.$1" -- "${cur}"))
        else
            COMPREPLY=($(compgen -f -- "${cur}"))
        fi
    fi
}

# _ze_find_subcmd skips global flags to find the subcommand word index.
# ze --debug --plugin foo bgp decode -> subcmd_idx=4 (words[4]="bgp")
_ze_find_subcmd() {
    local i
    _ze_subcmd_idx=0
    for (( i=1; i < cword; i++ )); do
        case "${words[i]}" in
            -d|--debug|-V|--version)
                ;;
            --plugin|--pprof|--chaos-seed|--chaos-rate)
                (( i++ ))  # skip argument
                ;;
            --plugins)
                ;;
            -*)
                ;;  # skip unknown flags
            *)
                _ze_subcmd_idx=$i
                return
                ;;
        esac
    done
}

_ze() {
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion || return
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=${COMP_CWORD}
    fi

    local commands="bgp config cli exabgp interface plugin schema show run status signal completion version help"

    # Complete argument for flags that take a value
    case "${prev}" in
        --plugin)
            local plugins
            plugins=$(ze --plugins --json 2>/dev/null | grep -o '"Name":"[^"]*"' | sed 's/"Name":"//;s/"//')
            COMPREPLY=($(compgen -W "${plugins}" -- "${cur}"))
            return
            ;;
        --pprof|--chaos-seed|--chaos-rate)
            return
            ;;
    esac

    # Find the subcommand position (skip global flags)
    local _ze_subcmd_idx
    _ze_find_subcmd

    # No subcommand found yet -- complete top-level commands and global flags
    if [[ ${_ze_subcmd_idx} -eq 0 ]]; then
        if [[ "${cur}" == -* ]]; then
            COMPREPLY=($(compgen -W "-d --debug -h --help --plugin --plugins --pprof --chaos-seed --chaos-rate" -- "${cur}"))
        else
            COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
        fi
        return
    fi

    local subcmd="${words[_ze_subcmd_idx]}"
    local depth=$(( cword - _ze_subcmd_idx ))

    case "${subcmd}" in
        bgp)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "decode encode help" -- "${cur}"))
            fi
            ;;
        config)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "edit validate migrate fmt dump diff completion help" -- "${cur}"))
            else
                _ze_filedir conf
            fi
            ;;
        cli)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "help" -- "${cur}"))
            fi
            ;;
        schema)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "list show handlers methods events protocol help" -- "${cur}"))
            elif [[ ${depth} -eq 2 ]]; then
                local schema_sub="${words[_ze_subcmd_idx+1]}"
                if [[ "${schema_sub}" == "show" || "${schema_sub}" == "methods" ]]; then
                    # Dynamic: module names from YANG registry
                    local modules
                    modules=$(ze schema list 2>/dev/null | tail -n +2 | awk '{print $1}')
                    COMPREPLY=($(compgen -W "${modules}" -- "${cur}"))
                fi
            fi
            ;;
        plugin)
            if [[ ${depth} -eq 1 ]]; then
                # Dynamic: plugin names from YANG-driven registry
                local plugins
                plugins=$(ze --plugins --json 2>/dev/null | grep -o '"Name":"[^"]*"' | sed 's/"Name":"//;s/"//')
                plugins="${plugins} test help"
                COMPREPLY=($(compgen -W "${plugins}" -- "${cur}"))
            fi
            ;;
        exabgp)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "plugin migrate help" -- "${cur}"))
            else
                _ze_filedir conf
            fi
            ;;
        signal)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "reload stop restart status quit" -- "${cur}"))
            else
                _ze_filedir conf
            fi
            ;;
        show)
            # Dynamic: multi-level completion from YANG-driven command tree (read-only)
            local -a path_words=()
            local i
            for (( i=_ze_subcmd_idx+1; i < cword; i++ )); do
                path_words+=("${words[i]}")
            done
            local completions
            completions=$(ze completion words show "${path_words[@]}" 2>/dev/null | cut -f1)
            # Add dynamic peer selectors when completing after "peer"
            if [[ ${#path_words[@]} -eq 1 && "${path_words[0]}" == "peer" ]]; then
                local peer_completions
                peer_completions=$(ze completion peers 2>/dev/null | cut -f1)
                completions="${completions} ${peer_completions}"
            fi
            COMPREPLY=($(compgen -W "${completions}" -- "${cur}"))
            ;;
        run)
            # Dynamic: multi-level completion from YANG-driven command tree (all)
            local -a path_words=()
            local i
            for (( i=_ze_subcmd_idx+1; i < cword; i++ )); do
                path_words+=("${words[i]}")
            done
            local completions
            completions=$(ze completion words run "${path_words[@]}" 2>/dev/null | cut -f1)
            # Add dynamic peer selectors when completing after "peer"
            if [[ ${#path_words[@]} -eq 1 && "${path_words[0]}" == "peer" ]]; then
                local peer_completions
                peer_completions=$(ze completion peers 2>/dev/null | cut -f1)
                completions="${completions} ${peer_completions}"
            fi
            COMPREPLY=($(compgen -W "${completions}" -- "${cur}"))
            ;;
        completion)
            if [[ ${depth} -eq 1 ]]; then
                COMPREPLY=($(compgen -W "bash zsh fish nushell" -- "${cur}"))
            fi
            ;;
    esac
}

complete -F _ze ze
`
}
