// Design: (none -- new feature, shell completion generation)
// Overview: main.go -- completion dispatch
// Related: words.go -- dynamic completion data source

package completion

// fishScript returns the fish completion script for ze.
// Uses ze completion words for dynamic multi-level show/run completion
// with native fish description support (word\tdescription output format).
func fishScript() string {
	return `# ze fish completion -- generated by ze completion fish
# Install: ze completion fish | source
# Or:      ze completion fish > ~/.config/fish/completions/ze.fish

# Disable file completions by default.
complete -c ze -f

# __ze_needs_command returns true when no subcommand has been typed yet.
function __ze_needs_command
    set -l cmd (commandline -opc)
    set -l i 2
    while test $i -le (count $cmd)
        switch $cmd[$i]
            case '-d' '--debug' '-V' '--version' '--plugins'
                # no-arg flags
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set i (math $i + 1)
            case '-*'
                # unknown flag
            case '*'
                return 1
        end
        set i (math $i + 1)
    end
    return 0
end

# __ze_depth subcmd — echoes the completion depth (0-indexed) after subcmd.
# Returns 1 (no output) if subcmd not found. A partial current token does not
# count as a completed level, matching bash depth and zsh CURRENT guards.
function __ze_depth
    set -l expected $argv[1]
    set -l cmd (commandline -opc)
    set -l n 0
    set -l found 0
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '-d' '--debug' '-V' '--version' '--plugins'
                continue
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        if test $found -eq 1
            set n (math $n + 1)
        else if test "$word" = "$expected"
            set found 1
        else
            return 1
        end
    end
    test $found -eq 0; and return 1
    # Partial current token is part of current depth, not next.
    set -l ct (commandline -ct)
    test -n "$ct"; and set n (math $n - 1)
    echo $n
end

# __ze_under_command subcmd — true when first subcommand matches (any depth).
# Used for show/run where __ze_complete_dynamic handles multi-level depth.
function __ze_under_command
    set -l expected $argv[1]
    set -l cmd (commandline -opc)
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '-d' '--debug' '-V' '--version' '--plugins'
                continue
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        test "$word" = "$expected"; and return 0
        return 1
    end
    return 1
end

# __ze_complete_plugins outputs dynamic plugin names for completion.
# Uses ze --plugins --json at tab time, plus the static test/help entries.
function __ze_complete_plugins
    ze --plugins --json 2>/dev/null | string match -r '"Name":"[^"]*"' | string replace -r '"Name":"([^"]*)"' '$1'
    echo test
    echo help
end

# __ze_complete_schema_modules outputs YANG module names for schema show/methods.
# Only produces output when the schema subcommand is "show" or "methods".
function __ze_complete_schema_modules
    # Find the first positional word after "schema" (skipping flags).
    set -l cmd (commandline -opc)
    set -l found 0
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '-d' '--debug' '-V' '--version' '--plugins'
                continue
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        if test $found -eq 1
            # This is the word after "schema" — check if show or methods.
            switch $word
                case show methods
                    ze schema list 2>/dev/null | tail -n +2 | string match -r '^\S+'
            end
            return
        else if test "$word" = schema
            set found 1
        else
            return
        end
    end
end

# __ze_complete_dynamic calls ze completion words for multi-level completion.
# Extracts the command path after the subcommand and passes it to words.
function __ze_complete_dynamic
    set -l subcmd $argv[1]
    set -l cmd (commandline -opc)
    set -l all_words
    set -l found 0
    set -l skip_next 0
    for word in $cmd[2..]
        if test $skip_next -eq 1
            set skip_next 0
            continue
        end
        switch $word
            case '-d' '--debug' '-V' '--version' '--plugins'
                continue
            case '--plugin' '--pprof' '--chaos-seed' '--chaos-rate'
                set skip_next 1
                continue
            case '-*'
                continue
        end
        if test $found -eq 1
            set all_words $all_words $word
        else if test "$word" = "$subcmd"
            set found 1
        else
            return
        end
    end
    test $found -eq 0; and return

    # If the current token is non-empty (partial word), exclude it from path.
    set -l ct (commandline -ct)
    set -l path $all_words
    if test -n "$ct"; and test (count $path) -gt 0
        set path $path[1..-2]
    end

    ze completion words $subcmd $path 2>/dev/null
    # Add dynamic peer selectors when completing after "peer"
    if test (count $path) -eq 1; and test "$path[1]" = "peer"
        ze completion peers 2>/dev/null
    end
end

# --- Global flags ---
complete -c ze -n __ze_needs_command -s d -l debug -d 'Enable debug logging'
complete -c ze -n __ze_needs_command -s h -l help -d 'Show help'
complete -c ze -n __ze_needs_command -s V -l version -d 'Show version'
complete -c ze -n __ze_needs_command -l plugin -x -d 'Load plugin before starting'
complete -c ze -n __ze_needs_command -l plugins -d 'List available internal plugins'
complete -c ze -n __ze_needs_command -l pprof -x -d 'Start pprof HTTP server'
complete -c ze -n __ze_needs_command -l chaos-seed -x -d 'Enable chaos mode with PRNG seed'
complete -c ze -n __ze_needs_command -l chaos-rate -x -d 'Fault probability (0.0-1.0)'

# --- Top-level subcommands ---
complete -c ze -n __ze_needs_command -a bgp -d 'BGP protocol tools (decode, encode)'
complete -c ze -n __ze_needs_command -a config -d 'Configuration management'
complete -c ze -n __ze_needs_command -a cli -d 'Interactive CLI for running daemons'
complete -c ze -n __ze_needs_command -a exabgp -d 'ExaBGP bridge tools'
complete -c ze -n __ze_needs_command -a interface -d 'Manage OS network interfaces'
complete -c ze -n __ze_needs_command -a plugin -d 'Plugin system'
complete -c ze -n __ze_needs_command -a schema -d 'Schema discovery'
complete -c ze -n __ze_needs_command -a show -d 'Show daemon state (read-only commands)'
complete -c ze -n __ze_needs_command -a run -d 'Execute daemon command (all commands)'
complete -c ze -n __ze_needs_command -a status -d 'Check if daemon is running'
complete -c ze -n __ze_needs_command -a signal -d 'Send signals to running daemon'
complete -c ze -n __ze_needs_command -a completion -d 'Generate shell completion scripts'
complete -c ze -n __ze_needs_command -a version -d 'Show version'
complete -c ze -n __ze_needs_command -a help -d 'Show help'

# --- bgp (depth 1 only) ---
complete -c ze -n 'test (__ze_depth bgp) = 0' -a decode -d 'Decode BGP message from hex to JSON'
complete -c ze -n 'test (__ze_depth bgp) = 0' -a encode -d 'Encode API route command to BGP hex'
complete -c ze -n 'test (__ze_depth bgp) = 0' -a help -d 'Show help'

# --- config (depth 1 = subcommands, depth 2+ = .conf files) ---
complete -c ze -n 'test (__ze_depth config) = 0' -a edit -d 'Interactive configuration editor'
complete -c ze -n 'test (__ze_depth config) = 0' -a validate -d 'Validate configuration file'
complete -c ze -n 'test (__ze_depth config) = 0' -a migrate -d 'Convert configuration to current format'
complete -c ze -n 'test (__ze_depth config) = 0' -a fmt -d 'Format and normalize configuration file'
complete -c ze -n 'test (__ze_depth config) = 0' -a dump -d 'Dump parsed configuration'
complete -c ze -n 'test (__ze_depth config) = 0' -a diff -d 'Compare two configuration files'
complete -c ze -n 'test (__ze_depth config) = 0' -a completion -d 'Query completion engine'
complete -c ze -n 'test (__ze_depth config) = 0' -a help -d 'Show help'
complete -c ze -n 'test (__ze_depth config) -ge 1' -F

# --- cli (depth 1 only) ---
complete -c ze -n 'test (__ze_depth cli) = 0' -a bgp -d 'BGP daemon (default)'
complete -c ze -n 'test (__ze_depth cli) = 0' -a help -d 'Show help'

# --- schema (depth 1 = subcommands, depth 2 = dynamic module names) ---
complete -c ze -n 'test (__ze_depth schema) = 0' -a list -d 'List all registered schemas'
complete -c ze -n 'test (__ze_depth schema) = 0' -a show -d 'Show YANG content for a module'
complete -c ze -n 'test (__ze_depth schema) = 0' -a handlers -d 'List handler to module mapping'
complete -c ze -n 'test (__ze_depth schema) = 0' -a methods -d 'List RPCs from YANG'
complete -c ze -n 'test (__ze_depth schema) = 0' -a events -d 'List notifications from YANG'
complete -c ze -n 'test (__ze_depth schema) = 0' -a protocol -d 'Show protocol version and format info'
complete -c ze -n 'test (__ze_depth schema) = 0' -a help -d 'Show help'
# Dynamic: module names for "schema show" and "schema methods"
complete -c ze -n 'test (__ze_depth schema) = 1' -a '(__ze_complete_schema_modules)'

# --- show: dynamic multi-level from command tree ---
complete -c ze -n '__ze_under_command show' -a '(__ze_complete_dynamic show)'

# --- run: dynamic multi-level from command tree ---
complete -c ze -n '__ze_under_command run' -a '(__ze_complete_dynamic run)'

# --- plugin (depth 1: dynamic plugin names + test/help) ---
complete -c ze -n 'test (__ze_depth plugin) = 0' -a '(__ze_complete_plugins)'

# --- exabgp (depth 1 = subcommands, depth 2+ = .conf files) ---
complete -c ze -n 'test (__ze_depth exabgp) = 0' -a plugin -d 'ExaBGP bridge plugin'
complete -c ze -n 'test (__ze_depth exabgp) = 0' -a migrate -d 'ExaBGP config migration'
complete -c ze -n 'test (__ze_depth exabgp) = 0' -a help -d 'Show help'
complete -c ze -n 'test (__ze_depth exabgp) -ge 1' -F

# --- signal (depth 1 only) ---
complete -c ze -n 'test (__ze_depth signal) = 0' -a reload -d 'Send SIGHUP - reload configuration'
complete -c ze -n 'test (__ze_depth signal) = 0' -a stop -d 'Send SIGTERM - graceful shutdown'
complete -c ze -n 'test (__ze_depth signal) = 0' -a quit -d 'Send SIGQUIT - goroutine dump + immediate exit'

# --- completion (depth 1 only) ---
complete -c ze -n 'test (__ze_depth completion) = 0' -a bash -d 'Generate bash completion script'
complete -c ze -n 'test (__ze_depth completion) = 0' -a zsh -d 'Generate zsh completion script'
complete -c ze -n 'test (__ze_depth completion) = 0' -a fish -d 'Generate fish completion script'
complete -c ze -n 'test (__ze_depth completion) = 0' -a nushell -d 'Generate nushell completion script'
`
}
