// Design: (none -- new feature, shell completion generation)
// Overview: main.go -- completion dispatch
// Related: words.go -- dynamic completion data source

package completion

// nushellScript returns the nushell completion script for ze.
// Uses `extern` definitions for static subcommands with descriptions
// and custom completers for dynamic data (plugin names, schema modules,
// show/run command trees).
func nushellScript() string {
	return `# ze nushell completion -- generated by ze completion nushell
# Install: ze completion nushell | save -f ($nu.default-config-dir | path join "completions" "ze.nu")
# Then add to config.nu: source completions/ze.nu

# --- Dynamic completers ---

def "nu-complete ze plugins" [] {
    try {
        ^ze --plugins --json
        | from json
        | each {|p| { value: $p.Name, description: $p.Description? } }
        | append [{ value: "test", description: "Run plugin tests" } { value: "help", description: "Show help" }]
    } catch {
        ["test" "help"]
    }
}

def "nu-complete ze schema-modules" [] {
    try {
        ^ze schema list
        | lines
        | skip 1
        | each {|line| $line | split words | first }
    } catch {
        []
    }
}

def "nu-complete ze peer-selectors" [] {
    try {
        ^ze completion peers
        | lines
        | where {|line| ($line | str length) > 0 }
        | each {|line|
            let cols = ($line | split column "\t")
            if ($cols | length) > 0 {
                let row = ($cols | first)
                { value: $row.column1, description: ($row.column2? | default "") }
            }
        }
    } catch {
        []
    }
}

def "nu-complete ze show-path" [context: string, offset: int] {
    let parts = ($context | str trim | split row " " | where {|w| ($w | str length) > 0 })
    # Find "show" in parts, take everything after it as the path
    let idx = ($parts | enumerate | where {|it| $it.item == "show"} | first | get index)
    let path = ($parts | skip ($idx + 1))
    mut result = []
    try {
        $result = (^ze completion words show ...$path
        | lines
        | where {|line| ($line | str length) > 0 }
        | each {|line|
            let cols = ($line | split column "\t")
            if ($cols | length) > 0 {
                let row = ($cols | first)
                { value: $row.column1, description: ($row.column2? | default "") }
            }
        })
    } catch {}
    # Add dynamic peer selectors when completing after "peer"
    if ($path | length) == 1 and ($path | first) == "peer" {
        $result = ($result | append (nu-complete ze peer-selectors))
    }
    $result
}

def "nu-complete ze run-path" [context: string, offset: int] {
    let parts = ($context | str trim | split row " " | where {|w| ($w | str length) > 0 })
    let idx = ($parts | enumerate | where {|it| $it.item == "run"} | first | get index)
    let path = ($parts | skip ($idx + 1))
    mut result = []
    try {
        $result = (^ze completion words run ...$path
        | lines
        | where {|line| ($line | str length) > 0 }
        | each {|line|
            let cols = ($line | split column "\t")
            if ($cols | length) > 0 {
                let row = ($cols | first)
                { value: $row.column1, description: ($row.column2? | default "") }
            }
        })
    } catch {}
    # Add dynamic peer selectors when completing after "peer"
    if ($path | length) == 1 and ($path | first) == "peer" {
        $result = ($result | append (nu-complete ze peer-selectors))
    }
    $result
}

def "nu-complete ze config-subcmds" [] {
    [
        { value: "edit", description: "Interactive configuration editor" }
        { value: "validate", description: "Validate configuration file" }
        { value: "migrate", description: "Convert configuration to current format" }
        { value: "fmt", description: "Format and normalize configuration file" }
        { value: "dump", description: "Dump parsed configuration" }
        { value: "diff", description: "Compare two configuration files" }
        { value: "completion", description: "Query completion engine" }
        { value: "help", description: "Show help" }
    ]
}

def "nu-complete ze bgp-subcmds" [] {
    [
        { value: "decode", description: "Decode BGP message from hex to JSON" }
        { value: "encode", description: "Encode API route command to BGP hex" }
        { value: "help", description: "Show help" }
    ]
}

def "nu-complete ze schema-subcmds" [] {
    [
        { value: "list", description: "List all registered schemas" }
        { value: "show", description: "Show YANG content for a module" }
        { value: "handlers", description: "List handler to module mapping" }
        { value: "methods", description: "List RPCs from YANG" }
        { value: "events", description: "List notifications from YANG" }
        { value: "protocol", description: "Show protocol version and format info" }
        { value: "help", description: "Show help" }
    ]
}

def "nu-complete ze exabgp-subcmds" [] {
    [
        { value: "plugin", description: "ExaBGP bridge plugin" }
        { value: "migrate", description: "ExaBGP config migration" }
        { value: "help", description: "Show help" }
    ]
}

def "nu-complete ze signal-subcmds" [] {
    [
        { value: "reload", description: "Send SIGHUP - reload configuration" }
        { value: "stop", description: "Send SIGTERM - graceful shutdown" }
        { value: "restart", description: "Graceful restart (writes GR marker, then shuts down)" }
        { value: "reboot", description: "Graceful shutdown then system reboot (requires root on Linux)" }
        { value: "status", description: "Send SIGUSR1 - dump daemon status" }
        { value: "quit", description: "Send SIGQUIT - goroutine dump + immediate exit" }
    ]
}

def "nu-complete ze completion-shells" [] {
    [
        { value: "bash", description: "Generate bash completion script" }
        { value: "zsh", description: "Generate zsh completion script" }
        { value: "fish", description: "Generate fish completion script" }
        { value: "nushell", description: "Generate nushell completion script" }
    ]
}

# --- Top-level command ---

extern "ze" [
    --debug(-d)                                                 # Enable debug logging
    --help(-h)                                                  # Show help
    --version(-V)                                               # Show version
    --plugin: string@"nu-complete ze plugins"                   # Load plugin before starting (repeatable)
    --plugins                                                   # List available internal plugins
    --pprof: string                                             # Start pprof HTTP server
    --chaos-seed: int                                           # Enable chaos self-test mode with PRNG seed
    --chaos-rate: number                                        # Fault probability per operation (0.0-1.0)
]

# --- interface ---

extern "ze interface" { }

# --- bgp ---

extern "ze bgp" [
    command?: string@"nu-complete ze bgp-subcmds"
    ...args: string
]

extern "ze bgp decode" [...args: string]
extern "ze bgp encode" [...args: string]
extern "ze bgp help" []

# --- config ---

extern "ze config" [
    command?: string@"nu-complete ze config-subcmds"
    ...args: string
]

extern "ze config edit" [file?: path]
extern "ze config validate" [
    file: path
    --verbose(-v)                                               # Verbose output
    --quiet(-q)                                                 # Quiet mode (exit code only)
    --json                                                      # JSON output
]
extern "ze config migrate" [file: path]
extern "ze config fmt" [file: path]
extern "ze config dump" [file: path]
extern "ze config diff" [file1: path, file2: path]
extern "ze config completion" [file: path]
extern "ze config help" []

# --- cli ---

extern "ze cli" [...args: string]

# --- schema ---

extern "ze schema" [
    command?: string@"nu-complete ze schema-subcmds"
    ...args: string
]

extern "ze schema list" []
extern "ze schema show" [module: string@"nu-complete ze schema-modules"]
extern "ze schema handlers" []
extern "ze schema methods" [module?: string@"nu-complete ze schema-modules"]
extern "ze schema events" []
extern "ze schema protocol" []
extern "ze schema help" []

# --- show (dynamic from YANG command tree, read-only) ---

extern "ze show" [
    ...path: string@"nu-complete ze show-path"
]

# --- run (dynamic from YANG command tree, all) ---

extern "ze run" [
    ...path: string@"nu-complete ze run-path"
]

# --- plugin ---

extern "ze plugin" [
    name: string@"nu-complete ze plugins"
    ...args: string
]

# --- exabgp ---

extern "ze exabgp" [
    command?: string@"nu-complete ze exabgp-subcmds"
    ...args: string
]

extern "ze exabgp plugin" [...args: string]
extern "ze exabgp migrate" [file: path]
extern "ze exabgp help" []

# --- status ---

extern "ze status" [...args: string]

# --- signal ---

extern "ze signal" [
    command?: string@"nu-complete ze signal-subcmds"
    ...args: string
]

extern "ze signal reload" [--host: string, --port: string]
extern "ze signal stop" [--host: string, --port: string]
extern "ze signal restart" [--host: string, --port: string]
extern "ze signal reboot" [--host: string, --port: string]
extern "ze signal status" [--host: string, --port: string]
extern "ze signal quit" [--host: string, --port: string]

# --- completion ---

extern "ze completion" [
    shell?: string@"nu-complete ze completion-shells"
]

# --- version / help ---

extern "ze version" []
extern "ze help" []
`
}
