// Design: (none -- new feature, shell completion generation)
// Overview: main.go -- completion dispatch

package completion

// zshScript returns the zsh completion script for ze.
// Dynamic completions (plugin names, schema modules, show/run subcommands)
// call back to ze at completion time. Static completions cover the CLI
// dispatch tree (subcommands that are hardcoded switch cases in Go).
func zshScript() string {
	return "#compdef ze\n" + `# ze zsh completion -- generated by ze completion zsh
# Install: eval "$(ze completion zsh)"

_ze() {
    local -a commands
    commands=(
        'bgp:BGP protocol tools (decode, encode)'
        'config:Configuration management'
        'cli:Interactive CLI for running daemons'
        'validate:Validate configuration file'
        'schema:Schema discovery'
        'show:Show daemon state (read-only commands)'
        'run:Execute daemon command (all commands)'
        'plugin:Plugin system'
        'exabgp:ExaBGP bridge tools'
        'signal:Send signals to running daemon'
        'completion:Generate shell completion scripts'
        'version:Show version'
        'help:Show help'
    )

    _arguments -C \
        '-d[Enable debug logging]' \
        '--debug[Enable debug logging]' \
        '-h[Show help]' \
        '--help[Show help]' \
        '-V[Show version]' \
        '--version[Show version]' \
        '--plugin[Load plugin before starting]:plugin name:' \
        '--plugins[List available internal plugins]' \
        '--pprof[Start pprof HTTP server]:address:' \
        '--chaos-seed[Enable chaos self-test mode with PRNG seed]:seed:' \
        '--chaos-rate[Fault probability per operation (0.0-1.0)]:rate:' \
        '1:command:->cmd' \
        '*::arg:->args'

    case $state in
        cmd)
            _describe 'ze command' commands
            ;;
        args)
            case ${words[1]} in
                bgp)
                    if (( CURRENT == 2 )); then
                        local -a bgp_commands
                        bgp_commands=(
                            'decode:Decode BGP message from hex to JSON'
                            'encode:Encode API route command to BGP hex'
                            'help:Show help'
                        )
                        _describe 'bgp command' bgp_commands
                    fi
                    ;;
                config)
                    local -a config_commands
                    config_commands=(
                        'edit:Interactive configuration editor'
                        'check:Check config status'
                        'migrate:Convert configuration to current format'
                        'fmt:Format and normalize configuration file'
                        'dump:Dump parsed configuration'
                        'diff:Compare two configuration files'
                        'completion:Query completion engine'
                        'help:Show help'
                    )
                    if (( CURRENT == 2 )); then
                        _describe 'config command' config_commands
                    else
                        _files -g '*.conf'
                    fi
                    ;;
                cli)
                    if (( CURRENT == 2 )); then
                        local -a cli_commands
                        cli_commands=(
                            'bgp:BGP daemon (default)'
                            'help:Show help'
                        )
                        _describe 'cli command' cli_commands
                    fi
                    ;;
                validate)
                    _files -g '*.conf'
                    ;;
                schema)
                    local -a schema_commands
                    schema_commands=(
                        'list:List all registered schemas'
                        'show:Show YANG content for a module'
                        'handlers:List handler to module mapping'
                        'methods:List RPCs from YANG'
                        'events:List notifications from YANG'
                        'protocol:Show protocol version and format info'
                        'help:Show help'
                    )
                    if (( CURRENT == 2 )); then
                        _describe 'schema command' schema_commands
                    elif (( CURRENT == 3 )) && [[ ${words[2]} == (show|methods) ]]; then
                        # Dynamic: module names from YANG registry
                        local -a modules
                        modules=(${(f)"$(ze schema list 2>/dev/null | tail -n +2 | awk '{print $1}')"})
                        _describe 'YANG module' modules
                    fi
                    ;;
                show)
                    if (( CURRENT == 2 )); then
                        # Dynamic: subcommands from YANG-driven RPC command tree (read-only)
                        local -a show_commands
                        show_commands=(${(f)"$(ze show help 2>&1 | awk '/^Available commands:/,/^$/{if (/^  [a-z]/) printf "%s:%s\n", $1, substr($0, index($0,$2))}')"})
                        _describe 'show command' show_commands
                    fi
                    ;;
                run)
                    if (( CURRENT == 2 )); then
                        # Dynamic: subcommands from YANG-driven RPC command tree (all)
                        local -a run_commands
                        run_commands=(${(f)"$(ze run help 2>&1 | awk '/^Available commands:/,/^$/{if (/^  [a-z]/) printf "%s:%s\n", $1, substr($0, index($0,$2))}')"})
                        _describe 'run command' run_commands
                    fi
                    ;;
                plugin)
                    if (( CURRENT == 2 )); then
                        # Dynamic: plugin names from YANG-driven registry
                        local -a plugin_names
                        plugin_names=(${(f)"$(ze --plugins --json 2>/dev/null | grep -o '` + `"Name":"[^"]*"` + `' | sed 's/\"Name\":\"//;s/\"//')"})
                        plugin_names+=(test help)
                        _describe 'plugin' plugin_names
                    fi
                    ;;
                exabgp)
                    local -a exabgp_commands
                    exabgp_commands=(
                        'plugin:ExaBGP bridge plugin'
                        'migrate:ExaBGP config migration'
                        'help:Show help'
                    )
                    if (( CURRENT == 2 )); then
                        _describe 'exabgp command' exabgp_commands
                    else
                        _files -g '*.conf'
                    fi
                    ;;
                signal)
                    local -a signal_commands
                    signal_commands=(
                        'reload:Send SIGHUP - reload configuration'
                        'stop:Send SIGTERM - graceful shutdown'
                        'quit:Send SIGQUIT - goroutine dump + immediate exit'
                        'status:Check if process is running'
                    )
                    if (( CURRENT == 2 )); then
                        _describe 'signal command' signal_commands
                    else
                        _files -g '*.conf'
                    fi
                    ;;
                completion)
                    if (( CURRENT == 2 )); then
                        local -a shells
                        shells=(bash zsh)
                        _describe 'shell' shells
                    fi
                    ;;
            esac
            ;;
    esac
}

compdef _ze ze
`
}
