// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-bgp-cmd-log-api.yang
var ZeBGPCmdLogAPIYANG string

//go:embed ze-cli-log-cmd.yang
var ZeCliLogCmdYANG string
