// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-filter-path-asn-cmd.yang
var ZeFilterPathAsnCmdYANG string

//go:embed ze-filter-path-asn.yang
var ZeFilterPathAsnYANG string
