// Design: docs/architecture/core-design.md -- native Go gates run through le
// Overview: fixtures.go -- typed behavioral fixture population

package hookcheck

// fixtureSites contains one typed row per Results.check callsite in category order.
// Loop-backed callsites carry a generator whose labels expand to concrete runtime names.
var fixtureSites = [...]fixtureSite{
	{category: categoryFormatAlloc, name: "format-alloc-live-join", expectedExit: 2},
	{category: categoryFormatAlloc, name: "format-alloc-live-builder", expectedExit: 2},
	{category: categoryFormatAlloc, name: "format-alloc-comment-exempt", expectedExit: 0},
	{category: categoryFormatAlloc, name: "format-alloc-json-guarded", expectedExit: 2},
	{category: categoryFormatAlloc, name: "format-alloc-unguarded-file", expectedExit: 0},
	{category: categoryFormatAlloc, name: "format-alloc-stale-attribute-path", expectedExit: 0},
	{category: categoryFormatAlloc, name: "format-alloc-reactor-filter", expectedExit: 2},
	{category: categoryFormatAlloc, name: "format-alloc-test-file-skip", expectedExit: 0},
	{category: categoryDesignRef, name: "design-ref-vendor-exempt", expectedExit: 0},
	{category: categoryDesignRef, name: "design-ref-vendor-relative-exempt", expectedExit: 0},
	{category: categoryDesignRef, name: "design-ref-vendor-substring-still-blocked", expectedExit: 2},
	{category: categoryDesignRef, name: "design-ref-ze-file-blocked", expectedExit: 2},
	{category: categoryDesignRef, name: "design-ref-ze-file-with-line", expectedExit: 0},
	{category: categoryTestFirst, name: "test-first-untested-package-blocks", expectedExit: 2},
	{category: categoryTestFirst, name: "test-first-package-level-test-passes", expectedExit: 0},
	{category: categoryTestFirst, name: "test-first-sibling-test-passes", expectedExit: 0},
	{category: categoryTestFirst, generator: fixtureNameGenerator{prefix: "test-first-exempt-c", suffix: goSuffix, labels: []string{"_test", "_gen", ".pb"}}, expectedExit: 0},
	{category: categoryTestFirst, name: "test-first-exempt-cmd", expectedExit: 0},
	{category: categoryTestFirst, name: "test-first-edit-out-of-scope", expectedExit: 0},
	{category: categoryRenderedRule, name: "rendered-rule-edit-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "ai/rules/points/performance/"}}},
	{category: categoryRenderedRule, name: "point-file-edit-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "point-manifest-edit-allowed", expectedExit: 0},
	{category: categoryRenderedRule, generator: fixtureNameGenerator{prefix: "rendered-rule-", suffix: "-refused", labels: []string{"index", "triggers", "core"}}, expectedExit: 2},
	{category: categoryRenderedRule, name: "rendered-rule-relative-path-refused", expectedExit: 2},
	{category: categoryRenderedRule, name: "rendered-rule-write-refused", expectedExit: 2},
	{category: categoryRenderedRule, name: "rendered-rule-other-checkout-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "rendered-rule-unrelated-doc-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "rendered-rule-claude-rules-allowed", expectedExit: 1, messages: []fixtureMessage{{match: matchContains, text: "shared home"}}},
	{category: categoryRenderedRule, generator: fixtureNameGenerator{prefix: "claude-tree-warns-for-", suffix: "s", labels: []string{"rule", "skill", "agent"}}, expectedExit: 1},
	{category: categoryRenderedRule, generator: fixtureNameGenerator{prefix: "claude-tree-silent-for-", suffix: "", labels: []string{"hooks", "plan", "output-styles"}}, expectedExit: -1, messages: []fixtureMessage{{match: matchNotContains, text: "shared home"}}},
	{category: categoryRenderedRule, name: "rendered-rule-non-md-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "point-overwrite-write-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "already exists"}}},
	{category: categoryRenderedRule, name: "point-overwrite-names-both-routes", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "Edit ai/rules/points/performance/manifest.md"}, {match: matchContains, text: "a-free-slug"}}},
	{category: categoryRenderedRule, name: "point-overwrite-section-point-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "one instruction of the rule"}}},
	{category: categoryRenderedRule, name: "point-overwrite-section-point-names-its-path", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "ai/rules/points/performance/hot-path-rule/apply-the-hot-path-ban-to-these-packages.md"}}},
	{category: categoryRenderedRule, name: "point-overwrite-section-point-edit-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "point-overwrite-new-slug-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "point-overwrite-edit-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "point-overwrite-other-checkout-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "point-overwrite-nested-path-allowed", expectedExit: 0},
	{category: categoryRenderedRule, name: "point-overwrite-loose-md-allowed", expectedExit: 0},
	{category: categoryRenderedRule, generator: fixtureNameGenerator{prefix: "point-overwrite-case-variant-", suffix: "", labels: []string{"ai", "rules", "points", "rule-dir", "section-dir"}}, expectedExit: -1},
	{category: categoryRenderedRule, name: "point-overwrite-case-variant-slug", expectedExit: -1},
	{category: categoryRenderedRule, generator: fixtureNameGenerator{prefix: "rendered-rule-case-variant-", suffix: "", labels: []string{"ai", "rules"}}, expectedExit: -1},
	{category: categoryRenderedRule, name: "rendered-rule-case-variant-names-the-real-generator", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "./le rules index-update"}}},
	{category: categoryRenderedRule, name: "point-overwrite-multiedit-empty-old-string-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "already exists"}}},
	{category: categoryRenderedRule, name: "point-overwrite-multiedit-targeted-allowed", expectedExit: 0},
	{category: categoryRenderedRule, generator: fixtureNameGenerator{prefix: "c_", suffix: "-wired-into-CHECKS", labels: []string{"rendered_rules", "point_overwrite"}}, expectedExit: -1},
	{category: categoryRFCLanguage, name: "rfc-language-probe-slug-is-free", expectedExit: -1},
	{category: categoryRFCLanguage, name: "rfc-language-write-without-keyword-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: statesNoRFCLevel}}},
	{category: categoryRFCLanguage, name: "rfc-language-write-with-keyword-allowed", expectedExit: 0},
	{category: categoryRFCLanguage, generator: fixtureNameGenerator{prefix: "rfc-language-write-", suffix: "e-allowed", labels: []string{"not", "tabl"}}, expectedExit: 0},
	{category: categoryRFCLanguage, name: "rfc-language-write-keyword-only-in-code-span-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: statesNoRFCLevel}}},
	{category: categoryRFCLanguage, name: "rfc-language-write-keyword-only-in-fence-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: statesNoRFCLevel}}},
	{category: categoryRFCLanguage, name: "rfc-language-write-keyword-only-in-tilde-fence-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: statesNoRFCLevel}}},
	{category: categoryRFCLanguage, name: "rfc-language-write-keyword-only-in-blockquote-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: statesNoRFCLevel}}},
	{category: categoryRFCLanguage, name: "rfc-language-corpus-has-both-kinds", expectedExit: -1},
	{category: categoryRFCLanguage, name: "rfc-language-edit-lowercase-modal-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "lowercase obligation word"}}},
	{category: categoryRFCLanguage, name: "rfc-language-edit-modal-in-code-span-allowed", expectedExit: 0},
	{category: categoryRFCLanguage, name: "rfc-language-edit-modal-in-tilde-fence-allowed", expectedExit: 0},
	{category: categoryRFCLanguage, name: "rfc-language-edit-modal-in-blockquote-allowed", expectedExit: 0},
	{category: categoryRFCLanguage, name: "rfc-language-multiedit-lowercase-modal-refused", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "lowercase obligation word"}}},
	{category: categoryRFCLanguage, name: "rfc-language-edit-without-keyword-allowed", expectedExit: 0},
	{category: categoryRFCLanguage, name: "rfc-language-edit-hyphenated-compound-allowed", expectedExit: 0},
	{category: categoryRFCLanguage, name: "rfc-language-edit-note-allowed", expectedExit: 0},
	{category: categoryRFCLanguage, name: "rfc-language-manifest-allowed", expectedExit: 0},
	{category: categoryRFCLanguage, name: "rfc-language-unrelated-doc-allowed", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-ascii-arrows", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-unicode-arrows", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-missing-section-blocks", expectedExit: 2},
	{category: categoryValidateSpec, name: "validate-spec-argv-no-stdin-refuses", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "NOTHING WAS CHECKED"}}},
	{category: categoryValidateSpec, name: "validate-spec-absent-tool-name-refuses", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "NOTHING WAS CHECKED"}}},
	{category: categoryValidateSpec, name: "validate-spec-other-tool-quiet-pass", expectedExit: 0, messages: []fixtureMessage{{match: matchEquals, text: ""}}},
	{category: categoryValidateSpec, name: "validate-spec-line-numbered-citation-accepted", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-shell-and-makefile-citable", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-whole-current-behavior-read", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-prose-citation-still-rejected", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "list source files read"}}},
	{category: categoryValidateSpec, name: "validate-spec-tooling-surface-accepted", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-daemon-still-needs-ci", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "must reference a functional test file"}}},
	{category: categoryValidateSpec, name: "validate-spec-daemon-py-surface-still-rejected", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "must reference a functional test file"}}},
	{category: categoryValidateSpec, name: "validate-spec-empty-basename-citation-rejected", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "list source files read"}}},
	{category: categoryValidateSpec, name: "validate-spec-verify-command-accepted", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-legacy-test-command-warns", expectedExit: 0},
	{category: categoryValidateSpec, name: "validate-spec-no-verification-command-rejected", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "verification checklist item"}}},
	{category: categoryValidateSpec, name: "validate-spec-skeleton-placeholder-warns", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "warning"}}},
	{category: categoryValidateSpec, name: "validate-spec-design-placeholder-blocks", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: entryPointPlaceholder}}},
	{category: categoryValidateSpec, name: "validate-spec-where-data-enters-alone-caught", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: entryPointPlaceholder}}},
	{category: categoryValidateSpec, name: "validate-spec-undeclared-design-doc-blocks", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "docs/architecture/fixture.md"}}},
	{category: categoryValidateSpec, name: "validate-spec-named-design-doc-accepted", expectedExit: 0, messages: []fixtureMessage{{match: matchNotContains, text: "docs/architecture/fixture.md"}}},
	{category: categoryValidateSpec, name: "validate-spec-verification-status-accepted", expectedExit: 0, messages: []fixtureMessage{{match: matchNotContains, text: "Invalid Status"}}},
	{category: categoryValidateSpec, name: "validate-spec-verification-placeholder-blocks", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: entryPointPlaceholder}}},
	{category: categoryValidateSpec, name: "validate-spec-design-missing-doc-checklist-warns", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "Documentation Update Checklist"}}},
	{category: categoryValidateSpec, name: "validate-spec-skeleton-missing-doc-checklist-warns", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "warning"}}},
	{category: categoryValidateSpec, name: "validate-spec-design-missing-integration-checklist-warns", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "Integration Checklist"}}},
	{category: categoryCommitGate, name: "commit-gate-deferral-unassigned", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-deferral-assigned-ok", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-deferral-assigned-missing-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-deferral-in-diff", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-deferral-in-diff-logged-ok", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-deferral-in-diff-code-literal-exempt", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-deferral-in-diff-prose-still-caught", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-wiring-warn", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-wiring-with-ci-ok", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-doc-drift-absent-skips", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-doc-drift-warns", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-spec-audit-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-spec-audit-filled-ok", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-spec-audit-no-claim-skips", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-spec-audit-non-closure-skips", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-spec-audit-journal-row-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-spec-audit-journal-filled-ok", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-spec-audit-journal-other-spec-skips", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-spec-audit-journal-row-at-head-skips", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-journal-malformed-row-blocks-via-create", expectedExit: 2},
	{category: categoryCommitGate, name: "commit-gate-journal-wellformed-row-passes", expectedExit: 0},
	{category: categoryCommitGate, name: "commit-gate-journal-prose-spec-cell-blocks-via-create", expectedExit: 2},
	{category: categoryCommitGate, name: "commit-gate-journal-none-spec-cell-passes", expectedExit: 0},
	{category: categoryCommitGate, name: "commit-gate-create-blocks-deferral", expectedExit: 2},
	{category: categoryCommitGate, name: "commit-gate-index-own-staleness-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-index-unrelated-commit-passes", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-index-foreign-staleness-passes", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-index-foreign-row-included-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-design-ref-missing-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-design-ref-present-passes", expectedExit: -1},
	{category: categoryCommitGate, generator: fixtureNameGenerator{prefix: "commit-gate-go-design-ref-exempt-", suffix: goSuffix, labels: []string{"a_test", "a_gen", "register", "embed", "doc", "x", "g"}}, expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-design-ref-ignores-non-go", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-design-ref-ignores-absent", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-test-coverage-no-test-reports", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-test-coverage-unit-test-passes", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-test-coverage-functional-test-passes", expectedExit: -1},
	{category: categoryCommitGate, generator: fixtureNameGenerator{prefix: "commit-gate-test-coverage-exempt-", suffix: goSuffix, labels: []string{"a_gen", "x", "main", "g"}}, expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-test-coverage-ignores-non-go", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-added-line-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-panic-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-bug-prefix-passes", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-test-file-ignored", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-non-go-ignored", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-scripts-exempt", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-non-scripts-still-fires", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-vendor-exempt", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-vendor-lookalike-still-fires", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-reached-from-commit-gate", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-go-style-missing-check-is-loud", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-index-unfed-index-still-verified", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-index-removal-stale-blocks", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-index-removal-regenerated-passes", expectedExit: -1},
	{category: categoryCommitGate, name: "commit-gate-index-removal-blocks-via-create", expectedExit: 2},
	{category: categorySessionID, name: "session-id-mint-stable", expectedExit: -1},
	{category: categorySessionID, name: "session-id-mint-unique", expectedExit: -1},
	{category: categorySessionID, name: "session-id-mint-not-constant", expectedExit: -1},
	{category: categorySessionID, name: "session-id-mint-heals-empty-cache", expectedExit: -1},
	{category: categorySessionID, name: "session-id-start-time-readable", expectedExit: -1},
	{category: categorySessionID, name: "session-id-start-time-ps-branch", expectedExit: -1},
	{category: categorySessionID, name: "session-id-cache-key-carries-start-time", expectedExit: -1},
	{category: categorySessionID, name: "session-id-live-cache-hit-stable", expectedExit: -1},
	{category: categorySessionID, name: "session-id-cache-file-named-by-key", expectedExit: -1},
	{category: categorySessionID, name: "session-id-reused-pid-mints-fresh-id", expectedExit: -1},
	{category: categorySessionID, name: "session-id-reused-pid-leaves-dead-entry", expectedExit: -1},
	{category: categorySessionID, generator: fixtureNameGenerator{prefix: "session-start-rejects-raw-", suffix: "-id", labels: []string{labelTrailingNewline, "encoded-nul", labelDot, labelDotDot}}, expectedExit: 0},
	{category: categorySessionID, generator: fixtureNameGenerator{prefix: "hook-session-id-status-", suffix: "", labels: []string{"safe", "absent", "malformed-dot", "malformed-trailing-newline"}}, expectedExit: -1},
	{category: categorySessionID, name: "session-start-empty-matcher-registered", expectedExit: -1},
	{category: categorySessionID, name: "subagent-context-emits-json-contract", expectedExit: 0},
	{category: categorySessionID, name: "subagent-context-names-safe-parent-id", expectedExit: -1},
	{category: categorySessionID, name: "subagent-context-names-exact-parent-scratch", expectedExit: -1},
	{category: categorySessionID, generator: fixtureNameGenerator{prefix: "subagent-context-rejects-present-", suffix: "-parent-id", labels: []string{labelDot, labelTrailingNewline}}, expectedExit: 0},
	{category: categorySessionID, name: "subagent-context-absent-id-keeps-legacy-fallback", expectedExit: 0},
	{category: categorySessionID, name: "pretool-bash-prefixes-safe-parent-export", expectedExit: 0},
	{category: categorySessionID, generator: fixtureNameGenerator{prefix: "pretool-bash-leaves-", suffix: "-id-unchanged", labels: []string{labelTrailingNewline, "encoded-nul", labelDot, labelDotDot}}, expectedExit: 0},
	{category: categorySessionID, name: "pretool-bash-parent-export-keeps-three-scratch-calls-stable", expectedExit: 0},
	{category: categorySessionID, name: "pretool-bash-parent-export-reaches-make", expectedExit: -1},
	{category: categorySessionID, name: "pretool-bash-parent-export-reaches-review", expectedExit: -1},
	{category: categorySessionID, name: "session-id-fork-parent-marker", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-parent-persisted-env", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-parent-bash-command", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-parent-make-path", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-parent-review-artifact", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-parent-scratch-stable", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-tool-canonical", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-tool-make-path", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-tool-review-session", expectedExit: 0},
	{category: categorySessionID, name: "session-id-fork-tool-scratch-stable", expectedExit: 0},
	{category: categorySessionID, name: "session-id-human-make-path", expectedExit: 0, messages: []fixtureMessage{{match: matchEquals, text: "bin/ze"}}},
	{category: categorySessionID, name: "session-id-human-review-fallback", expectedExit: 0, messages: []fixtureMessage{{match: matchEquals, text: "shared"}}},
	{category: categorySessionID, name: "session-id-env-parity", expectedExit: -1},
	{category: categorySessionID, name: "session-id-distinct-sessions-differ", expectedExit: -1},
	{category: categorySessionID, generator: fixtureNameGenerator{prefix: "session-id-rejects-", suffix: "", labels: []string{"traversal", "slash", "space", "empty"}}, expectedExit: -1},
	{category: categorySessionID, name: "session-id-no-source-parity", expectedExit: -1},
	{category: categorySessionID, name: "session-id-commit-helper-agrees", expectedExit: -1},
	{category: categorySessionID, name: "session-id-no-python-fallback-constant", expectedExit: -1},
	{category: categorySessionID, name: "session-id-commit-helper-walk-removed", expectedExit: -1},
	{category: categorySessionID, name: "session-id-one-argv-walk", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-blocks-expectation-swap", expectedExit: 2},
	{category: categoryRFCTestGuard, name: "rfc-guard-blocks-assertion-delete", expectedExit: 2},
	{category: categoryRFCTestGuard, name: "rfc-guard-allows-reformat", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-allows-comment-edit", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-marker-no-longer-approves", expectedExit: 2},
	{category: categoryRFCTestGuard, name: "rfc-guard-allows-import-only-add", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-allows-aliased-import", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-allows-import-block-growth", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-import-plus-assertion-blocks", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-import-exemption-spares-no-test-delete", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-import-exemption-is-go-only", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-import-edit-cannot-drop-a-tag", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-untagged-unaffected", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-covers-ci", expectedExit: 2},
	{category: categoryRFCTestGuard, name: "rfc-guard-blocks-body-edit-tag-outside-hunk", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-untagged-func-in-tagged-file-passes", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-body-edit-reformat-passes", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-body-edit-comment-only-passes", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-body-edit-marker-blocks", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-blocks-tag-deletion", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-replace-all-reaches-tagged-copy", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-hoisted-tag-widens-to-file", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-tag-between-funcs-widens", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-blank-line-tag-widens", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-unowned-tag-covers-file", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-ambiguous-hunk-no-replace-all-passes", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-multiedit-tagged-hunk-blocks", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-ci-on-disk-covers-whole-file", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "weakening-ci-shrink-reported-not-refused", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: removingExpectations}}},
	{category: categoryRFCTestGuard, name: "relax-ci-sleep-to-barrier-allowed", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "relax-ci-barrier-removal-reported", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: removingExpectations}}},
	{category: categoryRFCTestGuard, name: "relax-ci-tautology-swap-blocked", expectedExit: 2},
	{category: categoryRFCTestGuard, name: "relax-go-tautology-swap-blocked", expectedExit: 2},
	{category: categoryRFCTestGuard, name: "relax-et-expectation-removal-reported", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: removingExpectations}}},
	{category: categoryRFCTestGuard, generator: fixtureNameGenerator{prefix: "relax-ci-", suffix: "-does-not-offset-a-deleted-expectation", labels: []string{"comment", "string-literal"}}, expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "removing expectations (2 -> 1"}}},
	{category: categoryRFCTestGuard, name: "relax-ci-cmd-removal-reported", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: removingExpectations}}},
	{category: categoryRFCTestGuard, name: "relax-ci-reject-to-expect-reported", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "removing negative expectations"}}},
	{category: categoryRFCTestGuard, name: "relax-ci-emptied-needle-blocked", expectedExit: 2},
	{category: categoryRFCTestGuard, name: "weakening-removing-a-comment-whose-prose-names-an-assertion", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "relax-prose-does-not-offset-a-deleted-go-assertion", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "removing assertions (2 -> 1)"}}},
	{category: categoryRFCTestGuard, name: "relax-go-comment-inside-a-string-literal-is-not-stripped", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "removing assertions"}}},
	{category: categoryRFCTestGuard, name: "relax-go-assertion-like-url-is-not-a-comment", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "relax-ci-trailing-comment-does-not-pay-for-a-deleted-expectation", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: removingExpectations}}},
	{category: categoryRFCTestGuard, name: "relax-go-trailing-comment-does-not-pay-for-a-deleted-subtest", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "removing t.Run cases"}}},
	{category: categoryRFCTestGuard, name: "relax-ci-hash-leading-needle-allowed", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "relax-ci-emptying-a-hash-leading-needle-blocked", expectedExit: 2},
	{category: categoryRFCTestGuard, name: "rfc-guard-covers-tagged-check-py", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-untagged-py-unaffected", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-py-comment-edit-passes", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-one-line-func-does-not-absorb-tag", expectedExit: 0},
	{category: categoryRFCTestGuard, name: "rfc-guard-one-line-func-neighbor-still-blocks", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-unlocatable-hunk-fails-closed", expectedExit: -1},
	{category: categoryRFCTestGuard, name: "rfc-guard-untagged-file-unaffected", expectedExit: 0},
	{category: categoryWeakenedHatch, name: "weakened-missing-row-refuses-the-edit", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: ribHoldsRow}, {match: matchContains, text: "test/weakened.md"}, {match: matchContains, text: "WRITE THE ROW FIRST"}}},
	{category: categoryWeakenedHatch, name: "weakened-row-opens-the-hatch", expectedExit: 0},
	{category: categoryWeakenedHatch, name: "weakened-row-for-another-test-buys-nothing", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: ribHoldsRow}}},
	{category: categoryWeakenedHatch, name: "weakened-qualified-row-opens-the-hatch", expectedExit: 0},
	{category: categoryWeakenedHatch, name: "weakened-wrong-package-qualifier-buys-nothing", expectedExit: 2},
	{category: categoryWeakenedHatch, name: "weakened-write-overwrite-needs-a-row", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: ribHoldsRow}}},
	{category: categoryWeakenedHatch, name: "weakened-write-overwrite-row-opens-the-hatch", expectedExit: 0},
	{category: categoryWeakenedHatch, name: "weakened-row-does-not-authorize-an-rfc-tagged-test", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "RFC-tagged test"}}},
	{category: categoryWeakenedHatch, name: "weakened-count-drop-still-only-notices", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "removing assertions"}}},
	{category: categoryWeakenedHatch, name: "weakened-sees-a-gofmt-table-case-leave", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "removing table-driven cases (2 -> 1)"}}},
	{category: categoryWeakenedHatch, name: "weakened-embedlit-rewrite-is-not-a-case-leaving", expectedExit: 0},
	{category: categoryRFCChangedLedger, name: "rfc-changed-absent-ledger-refuses", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "test/rfc-changed.md"}}},
	{category: categoryRFCChangedLedger, name: "rfc-changed-missing-row-refuses-the-edit", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "| TestTagged |"}, {match: matchContains, text: "RFC7606-7.1-1"}}},
	{category: categoryRFCChangedLedger, name: "rfc-changed-row-opens-the-gate", expectedExit: 0},
	{category: categoryRFCChangedLedger, name: "rfc-changed-row-for-another-test-buys-nothing", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "| TestTagged |"}}},
	{category: categoryRFCChangedLedger, name: "rfc-changed-qualified-row-opens-the-gate", expectedExit: 0},
	{category: categoryRFCChangedLedger, name: "rfc-changed-wrong-package-qualifier-buys-nothing", expectedExit: -1},
	{category: categoryRFCChangedLedger, name: "rfc-changed-in-file-marker-no-longer-approves", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "test/rfc-changed.md"}}},
	{category: categoryRFCChangedLedger, name: "rfc-changed-message-does-not-teach-the-marker", expectedExit: -1, messages: []fixtureMessage{{match: matchNotContains, text: "// rfc-test-change-approved: <"}}},
	{category: categoryRFCChangedLedger, name: "rfc-changed-unreadable-ledger-refuses", expectedExit: -1},
	{category: categoryRFCChangedLedger, name: "rfc-changed-untagged-func-unaffected", expectedExit: 0},
	{category: categoryDraftIncubator, name: "draft-edit-rfc-tagged-passes", expectedExit: 0},
	{category: categoryDraftIncubator, name: "live-edit-rfc-tagged-still-blocks", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "RFC-tagged test"}}},
	{category: categoryDraftIncubator, name: "draft-rm-needs-no-approval", expectedExit: 0},
	{category: categoryDraftIncubator, name: "draft-rm-recursive-needs-no-approval", expectedExit: 0},
	{category: categoryDraftIncubator, name: "live-rm-still-needs-approval", expectedExit: 2},
	{category: categoryDraftIncubator, name: "mixed-rm-still-needs-approval", expectedExit: 2},
	{category: categoryDraftIncubator, name: "draft-root-rm-recursive-needs-no-approval", expectedExit: 0},
	{category: categoryDraftIncubator, name: "draft-pair-rm-needs-no-approval", expectedExit: 0},
	{category: categoryDraftIncubator, name: "live-go-test-rm-still-needs-approval", expectedExit: 2},
	{category: categoryDraftIncubator, name: "mixed-go-test-rm-still-needs-approval", expectedExit: 2},
	{category: categoryDraftIncubator, name: "draft-then-live-go-test-rm-still-needs-approval", expectedExit: 2},
	{category: categoryDraftIncubator, name: "draft-then-live-newline-rm-still-needs-approval", expectedExit: 2},
	{category: categoryDraftIncubator, name: "mixed-recursive-rm-still-needs-approval", expectedExit: 2},
	{category: categoryDraftIncubator, name: "mixed-git-rm-still-needs-approval", expectedExit: 2},
	{category: categoryDraftIncubator, name: "draft-traversal-rm-still-needs-approval", expectedExit: 2},
	{category: categoryGovernedDocEdit, generator: fixtureNameGenerator{prefix: governedPrefix, suffix: "-blocks", labels: []string{"redirect", "append", "sed-i", "tee", "cp-into"}}, expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-heredoc-literal-blocks", expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-heredoc-variable-blocks", expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-write-script-then-run-blocks", expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-write-script-without-interpreter-passes", expectedExit: -1},
	{category: categoryGovernedDocEdit, generator: fixtureNameGenerator{prefix: governedPrefix, suffix: "-passes", labels: []string{"grep", "sed-n", "cat", "wc"}}, expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-commit-helper-passes", expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-scratch-redirect-passes", expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-read-only-payload-blocks", expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-escape-admits", expectedExit: -1},
	{category: categoryGovernedDocEdit, generator: fixtureNameGenerator{prefix: "governed-escape-needs-a-reason-", suffix: "", labels: []string{"bare", "double-quoted", "single-quoted", "whitespace-only"}}, expectedExit: -1},
	{category: categoryGovernedDocEdit, generator: fixtureNameGenerator{prefix: governedPrefix, suffix: "-blocks", labels: []string{"subst-paren", "subst-backtick", "continuation-trailing", "continuation-leading", "continuation-sed-i"}}, expectedExit: -1},
	{category: categoryGovernedDocEdit, name: "governed-bare-newline-passes", expectedExit: -1},
	{category: categoryMarkSourceRead, generator: fixtureNameGenerator{prefix: "mark-source-read-writes-", suffix: "", labels: []string{"go-internal", "py-scripts", "py-hooks", "sh-hooks", "sh-scripts", kindMakefile, "mk-file", "yang-model", "py-under-test", "py-under-tools", "sh-under-packaging", "go-under-test"}}, expectedExit: -1},
	{category: categoryMarkSourceRead, generator: fixtureNameGenerator{prefix: "mark-source-read-skips-", suffix: "", labels: []string{"doc", "spec", "json", "functional-test", "no-extension"}}, expectedExit: -1},
	{category: categoryMarkSourceRead, generator: fixtureNameGenerator{prefix: "mark-source-read-depth-", suffix: "", labels: []string{"keyhole-window", "short-window", "adequate-window", "whole-small-file", "content-counted", "num-without-total-short", "num-without-total-long", "limit-only-keyhole", "limit-only-adequate", "file-unchanged", "empty-file", "read-error", "unrecognized-no-response", "unrecognized-shape"}}, expectedExit: -1},
	{category: categoryMarkSourceRead, generator: fixtureNameGenerator{prefix: "mark-source-read-depth-real-", suffix: "", labels: []string{"window", "boundary-19-lines", "boundary-20-lines", "whole"}}, expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-hooks-spec-reads-its-hook", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-yang-spec-reads-its-model", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-tooling-spec-reads-its-tool", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-daemon-spec-uninvestigated-blocked", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-daemon-spec-grounded-by-hook-blocked", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-daemon-spec-reads-its-go", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-subject-read-showed-nothing-blocked", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-subjectless-spec-any-source", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-subjectless-spec-nothing-blocked", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-kindless-marker-not-enough-for-subject", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-lsp-grounds-go-spec", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-lsp-alone-does-not-ground-py-spec", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-multi-kind-needs-every-kind", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-multi-kind-both-read-allowed", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-fresh-kind-does-not-carry-stale-kind", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "longer ago"}}},
	{category: categoryDesignGate, name: "design-gate-subjectless-write-warns", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-bare-path-is-a-subject", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-multiedit-subject-seen", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-checklist-row-is-not-a-subject", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-files-to-create-is-a-subject", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-checklist-adds-no-requirement", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-new-spec-subject-from-payload", expectedExit: -1},
	{category: categoryDesignGate, generator: fixtureNameGenerator{prefix: "design-gate-", suffix: "-subject-needs-its-own-kind", labels: []string{"go", "script", kindShell, kindYang, kindMakefile, "mk"}}, expectedExit: -1},
	{category: categoryDesignGate, generator: fixtureNameGenerator{prefix: "design-gate-", suffix: "-subject-cleared-by-its-own-file", labels: []string{"go", "script", kindShell, kindYang, kindMakefile, "mk"}}, expectedExit: -1},
	{category: categoryDesignGate, generator: fixtureNameGenerator{prefix: "design-gate-contract-both-ends-agree-", suffix: "", labels: []string{"internal_component_bgp_reactor_peer.go", "test_interop_harness_test.go", "scripts_dev_commit_helper_script", ".claude_hooks_pretool-writeedit_script", "test_interop-ipsec_lab_script", "tools_kernel-builder_build_script", ".claude_hooks_mark-source-read_shell", "packaging_deb_preinstall_shell", "test_interop-ipsec_scenarios_eap-tls13_pki_gen-pki_shell", "Makefile", "mk_build-appliance.mk", "internal_component_iface_yang_ze-iface.yang", "docs_guide_x.md", "test_bgp_session.ci"}}, expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-message-names-both-sections", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "Files to Modify / Files to Create"}}},
	{category: categoryDesignGate, name: "design-gate-description-column-is-not-a-subject", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-first-cell-is-still-a-subject", expectedExit: -1},
	{category: categoryDesignGate, name: "design-gate-keyhole-read-does-not-ground", expectedExit: -1},
	{category: categoryDelegation, name: "delegation-marker-written", expectedExit: -1},
	{category: categoryDelegation, name: "delegation-nudge-fires", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: delegationHeading}}},
	{category: categoryDelegation, name: "delegation-nudge-warns-not-blocks", expectedExit: 1},
	{category: categoryDelegation, name: "delegation-nudge-silent-when-spawned", expectedExit: -1, messages: []fixtureMessage{{match: matchNotContains, text: delegationHeading}}},
	{category: categoryDelegation, name: "delegation-spawned-allows-stop", expectedExit: 0},
	{category: categoryDelegation, name: "delegation-no-spec-no-nudge", expectedExit: -1, messages: []fixtureMessage{{match: matchNotContains, text: delegationHeading}}},
	{category: categoryDelegation, name: "delegation-context-names-spec", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "plan/spec-fixture.md"}}},
	{category: categoryDelegation, name: "delegation-context-carries-contract", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: planningRule}, {match: matchContains, text: "evidence.md"}}},
	{category: categoryDelegation, name: "delegation-context-no-spec-block", expectedExit: 0, messages: []fixtureMessage{{match: matchNotContains, text: "Spec claimed by"}}},
	{category: categoryDelegation, name: "delegation-stop-hook-registered", expectedExit: -1},
	{category: categoryDelegation, name: "delegation-stop-hook-runs-before-marker-release", expectedExit: -1},
	{category: categoryDelegation, name: "stop-phrase-blocks-real-use", expectedExit: 2},
	{category: categoryDelegation, name: "stop-phrase-remedy-does-not-order-the-offered-work", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "DROP IT"}, {match: matchContains, text: "not an instruction to do the work you just offered"}, {match: matchNotContains, text: "Continue without asking permission"}}},
	{category: categoryDelegation, name: "stop-phrase-ignores-backticks", expectedExit: 0},
	{category: categoryDelegation, name: "stop-phrase-ignores-fenced-block", expectedExit: 0},
	{category: categoryDelegation, name: "stop-phrase-fence-is-not-a-bypass", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: wouldYouLikeMe}, {match: matchNotContains, text: "let me know"}}},
	{category: categoryDelegation, name: "stop-phrase-unclosed-fence-still-blocks", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: wouldYouLikeMe}}},
	{category: categoryDelegation, name: "stop-phrase-all-markup-scans-raw-text", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: wouldYouLikeMe}}},
	{category: categoryDelegation, name: "stop-phrase-nested-fence-ignored", expectedExit: 0},
	{category: categoryDelegation, name: "stop-hook-malformed-input-allows-stop", expectedExit: 0},
	{category: categoryDelegation, name: "stop-hook-honors-stop-hook-active", expectedExit: 0},
	{category: categoryDelegation, name: "stop-phrase-what-next-allowed-when-no-open-work", expectedExit: 0},
	{category: categoryDelegation, name: "stop-phrase-permission-blocks-without-open-work", expectedExit: 2},
	{category: categoryDelegation, name: "stop-phrase-mandated-spec-ask-allowed", expectedExit: 0},
	{category: categoryDelegation, name: "stop-phrase-mandated-ask-does-not-cover-a-second-request", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: wouldYouLikeMe}}},
	{category: categoryDelegation, name: "stop-phrase-unpaired-backtick-still-blocks", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: wouldYouLikeMe}}},
	{category: categoryDelegation, name: "stop-hook-retry-still-runs-state-checks", expectedExit: 1, messages: []fixtureMessage{{match: matchContains, text: delegationHeading}}},
	{category: categoryDelegation, name: "stop-phrase-what-next-blocks-with-open-work", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: "what next"}}},
	{category: categoryDelegation, name: "delegation-summary-reaches-end", expectedExit: 0},
	{category: categoryDelegation, name: "delegation-claim-survives-stop", expectedExit: -1},
	{category: categoryDelegation, name: "delegation-nudge-fires-on-second-stop", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: delegationHeading}}},
	{category: categoryDelegation, name: "delegation-no-session-end-hook-registered", expectedExit: -1},
	{category: categoryDelegation, name: "delegation-claim-heartbeat-on-stop", expectedExit: -1},
	{category: categoryDelegation, name: "delegation-session-start-deletes-no-marker", expectedExit: 0},
	{category: categoryDelegation, name: "delegation-session-start-reaps-no-session-dir", expectedExit: -1},
	{category: categoryDelegation, name: "delegation-spawn-marker-heartbeat", expectedExit: -1, messages: []fixtureMessage{{match: matchNotContains, text: delegationHeading}}},
	{category: categoryDelegation, name: "delegation-heartbeat-never-creates-spawn-marker", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: delegationHeading}}},
	{category: categorySessionState, name: "session-state-handoff-after-the-kept-snapshots-survives", expectedExit: 0},
	{category: categorySessionState, name: "session-state-handoff-between-snapshots-survives", expectedExit: 0},
	{category: categorySessionState, name: "session-state-four-snapshots-rotate-to-three", expectedExit: 0},
	{category: categorySessionState, name: "session-state-precompact-keeps-handoff", expectedExit: 0},
	{category: categorySessionStateLocation, name: "session-state-digest-lands-in-the-session-directory", expectedExit: 0},
	{category: categorySessionStateLocation, name: "session-state-digest-directory-is-created", expectedExit: -1},
	{category: categorySessionStateLocation, name: "session-state-nothing-is-written-flat", expectedExit: -1},
	{category: categorySessionStateLocation, name: "session-state-digest-reuses-an-existing-dated-directory", expectedExit: 0},
	{category: categorySessionStateLocation, name: "session-state-resolver-walks-every-session-directory", expectedExit: 0, messages: []fixtureMessage{{match: matchSuffix, text: "session-state-fixture-old2.md"}}},
	{category: categorySessionStateLocation, name: "session-state-resolver-still-finds-a-flat-digest", expectedExit: 0, messages: []fixtureMessage{{match: matchSuffix, text: "session-state-fixture-oldsession.md"}}},
	{category: categorySessionStateLocation, name: "session-state-resolver-finds-a-nested-digest-alone", expectedExit: 0, messages: []fixtureMessage{{match: matchSuffix, text: "session-state-fixture-old2.md"}}},
	{category: categorySessionStateLocation, generator: fixtureNameGenerator{prefix: "session-state-resolver-legacy-session-state-fixture", suffix: ".md", labels: []string{"-ancientsid", ""}}, expectedExit: 0},
	{category: categorySessionStateLocation, name: "session-state-flat-markers-do-not-move", expectedExit: -1},
	{category: categorySubagentContext, name: "subagent-context-carries-economy", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "ONE message"}, {match: matchContains, text: "Read the range"}, {match: matchContains, text: "Grep"}, {match: matchContains, text: "ai/rules/context-economy.md"}}},
	{category: categorySubagentContext, name: "subagent-context-carries-lsp-fallback-order", expectedExit: 0, messages: []fixtureMessage{{match: matchContains, text: "select:LSP"}, {match: matchContains, text: "gopls symbols"}, {match: matchContains, text: "gopls definition|references"}, {match: matchContains, text: "line range"}, {match: matchNotContains, text: "NO LSP"}}},
	{category: categorySubagentContext, name: "subagent-context-carries-spec-digest", expectedExit: 0},
	{category: categorySubagentContext, name: "subagent-context-no-digest-when-absent", expectedExit: 0, messages: []fixtureMessage{{match: matchNotContains, text: "Digest of that spec"}}},
	{category: categoryDelegationReminder, name: "delegation-reminder-exists", expectedExit: -1},
	{category: categoryDelegationReminder, name: "delegation-reminder-exits-zero", expectedExit: 0},
	{category: categoryDelegationReminder, name: "delegation-reminder-grants-permission", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "needs no permission"}}},
	{category: categoryDelegationReminder, name: "delegation-reminder-cites-rule", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: planningRule}}},
	{category: categoryDelegationReminder, name: "delegation-reminder-stderr-empty", expectedExit: -1, messages: []fixtureMessage{{match: matchEquals, text: ""}}},
	{category: categoryDelegationReminder, name: "delegation-reminder-single-line", expectedExit: -1},
	{category: categoryDelegationReminder, name: "delegation-reminder-registered", expectedExit: -1},
	{category: categoryPhaseGates, name: "review-model-fork-transcript-uses-canonical-id-not-mtime", expectedExit: 0},
	{category: categoryPhaseGates, name: "review-model-human-transcript-keeps-mtime-fallback", expectedExit: -1},
	{category: categoryPhaseGates, name: "review-model-ack-uses-canonical-fork-id", expectedExit: 0},
	{category: categoryPhaseGates, name: "agent-skill-hook-exists", expectedExit: -1},
	{category: categoryPhaseGates, name: "agent-skill-blocks-research", expectedExit: 2},
	{category: categoryPhaseGates, name: "agent-skill-names-explore", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: exploreSkill}}},
	{category: categoryPhaseGates, name: "agent-skill-blocks-review", expectedExit: 2},
	{category: categoryPhaseGates, name: "agent-skill-names-review", expectedExit: -1},
	{category: categoryPhaseGates, name: "agent-skill-named-skill-passes", expectedExit: 0},
	{category: categoryPhaseGates, name: "agent-skill-uncovered-task-passes", expectedExit: 0},
	{category: categoryPhaseGates, name: "agent-skill-repo-path-is-not-a-skill", expectedExit: 2},
	{category: categoryPhaseGates, name: "agent-skill-make-target-is-not-a-skill", expectedExit: 2},
	{category: categoryPhaseGates, name: "agent-skill-unknown-skill-name-blocks", expectedExit: 2},
	{category: categoryPhaseGates, name: "agent-style-guide-warns", expectedExit: 1},
	{category: categoryPhaseGates, name: "agent-style-guide-names-the-guide", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "docs/contributing/ze-go-style.md"}}},
	{category: categoryPhaseGates, name: "agent-style-guide-says-precondition", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "PRECONDITION"}, {match: matchContains, text: "before you finish"}}},
	{category: categoryPhaseGates, name: "agent-style-guide-named-passes", expectedExit: 0},
	{category: categoryPhaseGates, generator: fixtureNameGenerator{prefix: "agent-style-guide-quiet-", suffix: "", labels: []string{"docs-only", "python-only", "read-only-go"}}, expectedExit: 0},
	{category: categoryPhaseGates, name: "agent-skill-malformed-input-passes", expectedExit: 0},
	{category: categoryPhaseGates, name: "agent-skill-registered", expectedExit: -1},
	{category: categoryPhaseGates, name: "delegation-reminder-names-skills", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: exploreSkill}, {match: matchContains, text: "/ze-review"}}},
	{category: categoryPhaseGates, name: "review-model-blocks-spawn-off-opus-5", expectedExit: 2},
	{category: categoryPhaseGates, name: "review-model-spawn-names-the-rule", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: planningRule}}},
	{category: categoryPhaseGates, name: "review-model-allows-spawn-on-opus-5", expectedExit: 0},
	{category: categoryPhaseGates, name: "review-model-record-blocked-off-opus-5", expectedExit: 2, messages: []fixtureMessage{{match: matchContains, text: planningRule}}},
	{category: categoryPhaseGates, name: "review-model-record-override-works", expectedExit: 0},
	{category: categoryPhaseGates, name: "review-model-missing-sid-file-is-unknown", expectedExit: -1, messages: []fixtureMessage{{match: matchEquals, text: "unknown"}}},
	{category: categoryPhaseGates, name: "review-model-empty-path-is-unknown", expectedExit: -1, messages: []fixtureMessage{{match: matchEquals, text: "unknown"}}},
	{category: categoryPhaseGates, generator: fixtureNameGenerator{prefix: "review-model-", suffix: "", labels: []string{"allows-fixing-findings", "allows-editing-a-skill-file", "blocks-routed-review"}}, expectedExit: -1},
	{category: categoryPhaseGates, generator: fixtureNameGenerator{prefix: "review-model-verb-", suffix: "", labels: []string{"polite-lead-in", "skill-first", "role-form", "fixes-is-a-noun-here", "implementation", "implementation", "editing-a-file"}}, expectedExit: -1},
	{category: categoryPhaseGates, generator: fixtureNameGenerator{prefix: "review-model-ack-", suffix: "", labels: []string{"empty", "with-reason"}}, expectedExit: -1},
	{category: categoryPhaseGates, name: "review-model-ack-uses-safe-payload-id", expectedExit: 0},
	{category: categoryPhaseGates, generator: fixtureNameGenerator{prefix: "review-model-ack-rejects-", suffix: "-id", labels: []string{"trailing-space", labelTrailingNewline, labelDot, labelDotDot}}, expectedExit: 2},
	{category: categoryPhaseGates, name: "review-model-spawn-uses-payload-transcript", expectedExit: 2},
	{category: categoryPhaseGates, name: "review-model-unknown-stands-down", expectedExit: 0},
	{category: categoryPhaseGates, name: "review-model-unknown-says-so", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "UNCHECKED"}}},
	{category: categoryRawJobAdmission, generator: fixtureNameGenerator{prefix: "", suffix: "", labels: []string{"native-action-itself-is-not-refused", "native-changed-lint-action-not-refused", "native-functional-suite-not-refused", "native-full-verify-not-refused", "native-action-carrying-the-runner-in-an-argument-not-refused", "search-pattern-naming-a-raw-command-not-refused", "git-log-pickaxe-naming-the-linter-not-refused", "golangci-lint-config-verify-not-refused", "go-build-not-this-check-s-business", "the-daemon-binary-is-not-the-runner", "a-non-test-python-tool-is-not-refused"}}, expectedExit: 0},
	{category: categoryRawJobAdmission, generator: fixtureNameGenerator{prefix: "", suffix: "", labels: []string{"raw-go-test-is-refused-and-names-the-native-action", "raw-go-test-replacement-carries-run-filter", "raw-golangci-lint-is-refused", "raw-ze-test-runner-is-refused", "raw-ze-test-runner-with-dot-slash-is-refused", "session-directory-runner-is-refused", "raw-python-test-is-refused", "a-launcher-does-not-hide-the-raw-job", "a-raw-job-after-a-native-action-is-still-refused"}}, expectedExit: 2},
	{category: categoryRawJobAdmission, name: "a-declared-reason-admits-the-raw-form", expectedExit: 0},
	{category: categoryRawJobAdmission, name: "an-empty-reason-does-not-admit", expectedExit: 2},
	{category: categoryRawJobAdmission, name: "an-unrelated-assignment-does-not-admit", expectedExit: 2},
	{category: categoryRawJobAdmission, name: "the-wrapper-admits-the-command-it-queues", expectedExit: 0},
	{category: categoryRawJobAdmission, name: "every-refusal-names-a-way-through", expectedExit: -1},
	{category: categoryJournalRowShape, name: "journal-row-well-formed-passes", expectedExit: 0},
	{category: categoryJournalRowShape, name: "journal-row-prose-pipe-caught", expectedExit: 1, messages: []fixtureMessage{{match: matchContains, text: "1 line(s)"}, {match: matchContains, text: "line 5:"}}},
	{category: categoryJournalRowShape, name: "journal-row-second-table-caught", expectedExit: 1, messages: []fixtureMessage{{match: matchContains, text: "2 line(s)"}, {match: matchContains, text: "line 5:"}, {match: matchContains, text: "line 6:"}}},
	{category: categoryJournalRowShape, name: "journal-row-message-names-the-fix", expectedExit: -1, messages: []fixtureMessage{{match: matchContains, text: "second markdown table"}, {match: matchContains, text: "Reword the pipe out of the prose"}}},
	{category: categoryJournalRowShape, name: "journal-row-readme-exempt", expectedExit: 0},
	{category: categoryJournalRowShape, name: "journal-row-outside-journal-ignored", expectedExit: 0},
	{category: categoryJournalRowShape, name: "journal-row-spec-file-ignored", expectedExit: 0},
	{category: categoryJournalRowShape, name: "journal-row-non-markdown-ignored", expectedExit: 0},
	{category: categoryJournalRowShape, name: "journal-row-reads-the-file-not-new-string", expectedExit: 1},
	{category: categoryJournalRowShape, name: "journal-row-other-tool-ignored", expectedExit: 0},
	{category: categoryJournalRowShape, name: "journal-row-unreadable-spec-cell-caught", expectedExit: 1, messages: []fixtureMessage{{match: matchContains, text: "name no spec stem"}, {match: matchContains, text: "walked into during closure"}}},
	{category: categoryJournalRowShape, name: "journal-row-readable-spec-cells-pass", expectedExit: 0},
	{category: categoryJournalRowShape, name: "journal-row-nested-class-file-caught", expectedExit: 1},
	{category: categoryJournalRowShape, name: "journal-row-nested-readme-exempt", expectedExit: 0},
	{category: categoryJournalRowShape, name: "journal-row-parser-not-loaded-at-import", expectedExit: -1},
	{category: categoryJournalRowShape, name: "journal-row-unloadable-parser-warns", expectedExit: 1, messages: []fixtureMessage{{match: matchContains, text: "could not be loaded"}}},
	{category: categoryJournalRowShape, name: "c_journal_row_shape-wired-into-CHECKS", expectedExit: -1},
	{category: categoryScriptWeakeningArms, generator: fixtureNameGenerator{prefix: "script-arm-", suffix: "-refused", labels: []string{"expectedFailure", "xfail", "bare-expectedFailure", "xfail-with-reason", "unittest-skip"}}, expectedExit: -1},
	{category: categoryScriptWeakeningArms, name: "script-arm-framework-named-file-judged", expectedExit: -1},
	{category: categoryScriptWeakeningArms, name: "script-arm-tagged-check-not-refused", expectedExit: -1},
	{category: categoryScriptWeakeningArms, name: "script-arm-tagged-check-no-assert-notice", expectedExit: -1},
	{category: categoryScriptWeakeningArms, name: "script-arm-non-test-ignored", expectedExit: -1},
	{category: categoryScriptWeakeningArms, name: "script-arm-assertion-count-is-advisory", expectedExit: -1},
	{category: categoryScriptWeakeningArms, name: "script-arm-population-is-the-two-declared-shapes", expectedExit: -1},
	{category: categoryCISleepMarker, generator: fixtureNameGenerator{prefix: "ci-sleep-", suffix: "", labels: []string{"bare-sleep-block", "vague-comment-block", "invented-kind-block", "empty-reason-block", "marker-above-pass", "marker-trailing-pass", "poll-interval-pass", "commented-out-sleep-pass", "no-sleep-pass"}}, expectedExit: -1},
	{category: categoryCISleepMarker, name: "ci-sleep-non-ci-path-untouched", expectedExit: 0},
}

var fixtureCatalog = expandFixtureSites(fixtureSites[:])
