// Design: docs/architecture/core-design.md -- native Go gates run through le
// Overview: parity.go -- typed dispatcher fixtures and native evaluation

package hookcheck

// parityCatalog is the complete dispatcher fixture population. The order matches
// the former producer and is part of the structured answer contract.
var parityCatalog = [...]parityTable{
	{
		key: "BASH_GOLDEN", name: "bash-dispatcher-golden", expected: 82, judge: bashCode,
		fixtures: []parityFixture{
			{name: "cat /tmp/x", expectedCode: 2},
			{name: "cat tmp/x", expectedCode: 0},
			{name: "cp .claude/worktrees/a internal/x", expectedCode: 2},
			{name: "git commit -m x", expectedCode: 2},
			{name: "git merge main", expectedCode: 2},
			{name: "git reset --hard", expectedCode: 2},
			{name: "git restore --staged f", expectedCode: 0},
			{name: "go build -o bin/ze ./cmd/ze", expectedCode: 0},
			{name: "go build ./...", expectedCode: 0},
			{name: "go build ./cmd/ze", expectedCode: 2},
			{name: "go build -o tmp/session/2026-08-10-abc123/bin/ze ./cmd/ze", expectedCode: 0},
			{name: "grep -n x f.log", expectedCode: 0},
			{name: "grep x | tail -5", expectedCode: 0},
			{name: "git log --oneline | tail -3", expectedCode: 0},
			{name: "go test ./... | head -50", expectedCode: 2},
			{name: "go test ./... 2>&1 | tee tmp/t.log", expectedCode: 2},
			{name: "bin/ze-test bgp plugin | grep FAIL", expectedCode: 2},
			{name: "git status | grep foo; ./le rules index-update", expectedCode: 0},
			{name: "ls | head; go test ./... | grep FAIL", expectedCode: 2},
			{name: "go test ./... 2>&1 |\n  grep -c FAIL", expectedCode: 2},
			{name: "./le verify current mode full \\\n  | tail -40", expectedCode: 2},
			{name: "./bin/ze-test bgp plugin | grep FAIL", expectedCode: 2},
			{name: "tmp/session/2026-08-10-abc123/bin/ze-test bgp plugin | grep FAIL", expectedCode: 2},
			{name: "/home/u/ze/tmp/session/2026-08-10-abc123/bin/ze-test bgp plugin | grep FAIL", expectedCode: 2},
			{name: "tmp/session/abc123/bin/ze-test bgp plugin | grep FAIL", expectedCode: 0},
			{name: "ze le hook-check unit | tail -25", expectedCode: 2},
			{name: "./le spec session wip | head -5", expectedCode: 0},
			{name: "git diff internal/le/hookcheck/fixtures.go | head -60", expectedCode: 0},
			{name: "./le verify current mode full |& tail -5", expectedCode: 2},
			{name: "./le verify status check | tail -1", expectedCode: 0},
			{name: "ls -la", expectedCode: 0},
			{name: "./le verify current mode full 2>&1 | tee tmp/v.log", expectedCode: 2},
			{name: "./le verify current mode full | grep X", expectedCode: 2},
			{name: "timeout 240s ./le verify current mode full | tail -5", expectedCode: 2},
			{name: "timeout -k 5 30 ./le verify current mode full | tail -5", expectedCode: 2},
			{name: "nice -n 5 ./le verify current mode full | head -20", expectedCode: 2},
			{name: "timeout 240s ls | head -5", expectedCode: 0},
			{name: "rm internal/foo_test.go", expectedCode: 2},
			{name: "rm tmp/x", expectedCode: 0},
			{name: "until ! pgrep -f qemu; do sleep 5; done", expectedCode: 2},
			{name: "while pgrep -q qemu; do :; done", expectedCode: 2},
			{name: "timeout 600 bash -c 'until [ -f tmp/session/2026-08-10-x/ready ]; do sleep 30; done'", expectedCode: 0},
			{name: "while read -r f; do echo $f; done < tmp/list", expectedCode: 0},
			{name: "pgrep -f qemu", expectedCode: 0},
			{name: "grep -rn 'time.sleep(' test/plugin", expectedCode: 0},
			{name: "timeout 10 curl -s localhost:8080; until ! pgrep -f qemu; do sleep 5; done", expectedCode: 2},
			{name: "timeout 60 bash -c 'until [ -f a ]; do sleep 1; done'; while true; do sleep 5; done", expectedCode: 2},
			{name: "while true; do sleep 5; timeout 10 curl -s localhost; done", expectedCode: 2},
			{name: "go test -timeout 300s ./... | while read l; do sleep 5; done", expectedCode: 2},
			{name: "timeout bash -c 'until [ -f tmp/session/2026-08-10-x/r ]; do sleep 30; done'", expectedCode: 2},
			{name: "grep -rn 'until ! pgrep' ai/rules", expectedCode: 0},
			{name: "while read -r line; do echo no-sleep-here; done < tmp/list", expectedCode: 0},
			{name: "bash -c 'while true; do sleep 5; done'", expectedCode: 2},
			{name: "grep -rn foo ai/rules > tmp/notes.txt", expectedCode: 2},
			{name: "echo probe > ./tmp/notes.txt", expectedCode: 2},
			{name: "echo probe > @PROJECT@/tmp/notes.txt", expectedCode: 2},
			{name: "tee @PROJECT@/tmp/notes.txt", expectedCode: 2},
			{name: "echo probe > sub/tmp/notes.txt", expectedCode: 0},
			{name: "./le verify deps unit-race-changed > \"$dir/unit.log\" 2>&1", expectedCode: 0},
			{name: "go test ./... 2>&1 | tee tmp/session/2026-08-10-abc123/t.log", expectedCode: 2},
			{name: "./le doc check verify > tmp/verify/out.log 2>&1", expectedCode: 0},
			{name: "./le doc check verify > tmp/ze-verify.log 2>&1", expectedCode: 0},
			{name: "./le doc check verify > tmp/.ze-verify-duration.txt 2>&1", expectedCode: 0},
			{name: "./le doc check verify > tmp/commit-abc123.log 2>&1", expectedCode: 0},
			{name: "./le doc check verify > tmp/delete-abc123.sh 2>&1", expectedCode: 0},
			{name: "./le doc check verify > tmp/mutation-survivors.md 2>&1", expectedCode: 0},
			{name: "./le doc check verify > tmp/test-timings.json 2>&1", expectedCode: 0},
			{name: "grep -rn '> tmp/out.log' ai/rules", expectedCode: 0},
			{name: "bash -c \"./le doc check verify > tmp/out.log\"", expectedCode: 2},
			{name: "cat >> tmp/session/x/state.md <<'EOF'\n  -- never write > tmp/out.log\nEOF", expectedCode: 0},
			{name: "bash <<'EOF'\n./le doc check verify > tmp/out.log\nEOF", expectedCode: 2},
			{name: "cat > tmp/out.log <<'EOF'\nhello\nEOF", expectedCode: 2},
			{name: "./le test-unit core", expectedCode: 0},
			{name: "./le changed scope", expectedCode: 0},
			{name: "./le qemu run command 'bin/ze-test-linux-arm64 bgp parse 91 -v'", expectedCode: 0},
			{name: "golangci-lint config verify", expectedCode: 0},
			{name: "go test ./internal/core/env", expectedCode: 2},
			{name: "golangci-lint run ./...", expectedCode: 2},
			{name: "bin/ze-test bgp plugin", expectedCode: 2},
			{name: "./le commit no-such-action", expectedCode: 2},
			{name: "ZE_ADMIT_RAW=\"bisecting one 2s case\" go test -run TestX ./internal/core/env", expectedCode: 0},
			{name: "./le job run label gotest command go test ./internal/core/env", expectedCode: 0},
		},
	},
	{
		key: "WE_GOLDEN", name: "write-edit-dispatcher-golden", expected: 92, judge: writeEditCode,
		fixtures: []parityFixture{
			{name: "Edit|and function", expectedCode: 2},
			{name: "Edit|append encode", expectedCode: 2},
			{name: "Edit|banned fmt format (dead hook)", expectedCode: 2},
			{name: "Edit|bufhandle", expectedCode: 2},
			{name: "Edit|camel json", expectedCode: 2},
			{name: "Edit|claude plans", expectedCode: 0},
			{name: "Edit|clean go", expectedCode: 2},
			{name: "Edit|clean test", expectedCode: 2},
			{name: "Edit|design absent", expectedCode: 2},
			{name: "Edit|design present ok", expectedCode: 2},
			{name: "Edit|empty default", expectedCode: 2},
			{name: "Edit|errorf ok", expectedCode: 2},
			{name: "Edit|exabgp", expectedCode: 2},
			{name: "Edit|generated claude", expectedCode: 2},
			{name: "Edit|nested claude not generated", expectedCode: 0},
			{name: "Edit|go func cold ok", expectedCode: 2},
			{name: "Edit|go func hot", expectedCode: 2},
			{name: "Edit|hardcoded cmds", expectedCode: 2},
			{name: "Edit|ignored err", expectedCode: 2},
			{name: "Edit|init register", expectedCode: 2},
			{name: "Edit|kebab json ok", expectedCode: 2},
			{name: "Edit|layering", expectedCode: 2},
			{name: "Edit|lint exclusion", expectedCode: 2},
			{name: "Edit|md naming bad", expectedCode: 0},
			{name: "Edit|nolint bad", expectedCode: 2},
			{name: "Edit|nolint good", expectedCode: 2},
			{name: "Edit|observer ok ci", expectedCode: 0},
			{name: "Edit|observer sysexit ci", expectedCode: 1},
			{name: "Edit|os.Exit", expectedCode: 2},
			{name: "Edit|os.Exit in main ok", expectedCode: 2},
			{name: "Edit|panic", expectedCode: 2},
			{name: "Edit|panic unreachable ok", expectedCode: 2},
			{name: "Edit|println", expectedCode: 2},
			{name: "Edit|raw ansi", expectedCode: 2},
			{name: "Edit|scratch dated session dir", expectedCode: 0},
			{name: "Edit|scratch producer folder", expectedCode: 0},
			{name: "Edit|scratch shared root name", expectedCode: 0},
			{name: "Edit|scratch tmp root", expectedCode: 2},
			{name: "Edit|scripts os.exit ok", expectedCode: 2},
			{name: "Edit|sprintf", expectedCode: 2},
			{name: "Edit|strconv format", expectedCode: 2},
			{name: "Edit|string concat", expectedCode: 2},
			{name: "Edit|system tmp write", expectedCode: 2},
			{name: "Edit|utils pkg", expectedCode: 2},
			{name: "Edit|version config", expectedCode: 2},
			{name: "Edit|yagni", expectedCode: 2},
			{name: "Write|and function", expectedCode: 2},
			{name: "Write|append encode", expectedCode: 2},
			{name: "Write|banned fmt format (dead hook)", expectedCode: 2},
			{name: "Write|bufhandle", expectedCode: 2},
			{name: "Write|camel json", expectedCode: 2},
			{name: "Write|claude plans", expectedCode: 2},
			{name: "Write|clean go", expectedCode: 2},
			{name: "Write|clean test", expectedCode: 2},
			{name: "Write|design absent", expectedCode: 2},
			{name: "Write|design present ok", expectedCode: 2},
			{name: "Write|empty default", expectedCode: 2},
			{name: "Write|errorf ok", expectedCode: 2},
			{name: "Write|exabgp", expectedCode: 2},
			{name: "Write|generated claude", expectedCode: 2},
			{name: "Write|nested claude not generated", expectedCode: 0},
			{name: "Write|go func cold ok", expectedCode: 2},
			{name: "Write|go func hot", expectedCode: 2},
			{name: "Write|hardcoded cmds", expectedCode: 2},
			{name: "Write|ignored err", expectedCode: 2},
			{name: "Write|init register", expectedCode: 2},
			{name: "Write|kebab json ok", expectedCode: 2},
			{name: "Write|layering", expectedCode: 2},
			{name: "Write|lint exclusion", expectedCode: 2},
			{name: "Write|md naming bad", expectedCode: 1},
			{name: "Write|nolint bad", expectedCode: 2},
			{name: "Write|nolint good", expectedCode: 2},
			{name: "Write|observer ok ci", expectedCode: 0},
			{name: "Write|observer sysexit ci", expectedCode: 1},
			{name: "Write|os.Exit", expectedCode: 2},
			{name: "Write|os.Exit in main ok", expectedCode: 2},
			{name: "Write|panic", expectedCode: 2},
			{name: "Write|panic unreachable ok", expectedCode: 2},
			{name: "Write|println", expectedCode: 2},
			{name: "Write|raw ansi", expectedCode: 2},
			{name: "Write|scratch dated session dir", expectedCode: 0},
			{name: "Write|scratch producer folder", expectedCode: 0},
			{name: "Write|scratch shared root name", expectedCode: 0},
			{name: "Write|scratch tmp root", expectedCode: 2},
			{name: "Write|scripts os.exit ok", expectedCode: 2},
			{name: "Write|sprintf", expectedCode: 2},
			{name: "Write|strconv format", expectedCode: 2},
			{name: "Write|string concat", expectedCode: 2},
			{name: "Write|system tmp write", expectedCode: 2},
			{name: "Write|utils pkg", expectedCode: 2},
			{name: "Write|version config", expectedCode: 2},
			{name: "Write|yagni", expectedCode: 2},
		},
	},
	{
		key: "WEAKEN_GOLDEN", name: "weakening-dispatcher-golden", expected: 10, judge: weakeningCode,
		fixtures: []parityFixture{
			{name: "skip added", expectedCode: 2},
			{name: "skip added with a retired relax token", expectedCode: 2},
			{name: "partial assertion removal", expectedCode: 0},
			{name: "fatal to nonfatal downgrade", expectedCode: 0},
			{name: "commented out assertion", expectedCode: 2},
			{name: "build tag ignore added", expectedCode: 2},
			{name: "delete test func", expectedCode: 2},
			{name: "benign edit adds assertions", expectedCode: 0},
			{name: "write overwrite weakens", expectedCode: 2},
			{name: "write overwrite benign", expectedCode: 0},
		},
	},
	{
		key: "POST_GOLDEN", name: "post-write-edit-dispatcher-golden", expected: 24, judge: postWriteEditCode,
		fixtures: []parityFixture{
			{name: "Edit|big >1000", expectedCode: 1},
			{name: "Edit|big under 1000", expectedCode: 0},
			{name: "Edit|journal malformed row", expectedCode: 1},
			{name: "Edit|md clean", expectedCode: 0},
			{name: "Edit|md deferral", expectedCode: 1},
			{name: "Edit|numeric no test", expectedCode: 0},
			{name: "Edit|parse no fuzz", expectedCode: 0},
			{name: "Edit|py file", expectedCode: 0},
			{name: "Edit|rfc no header", expectedCode: 0},
			{name: "Edit|small go", expectedCode: 0},
			{name: "Edit|test no docs", expectedCode: 0},
			{name: "Edit|vague names", expectedCode: 0},
			{name: "Write|big >1000", expectedCode: 1},
			{name: "Write|big under 1000", expectedCode: 0},
			{name: "Write|journal malformed row", expectedCode: 1},
			{name: "Write|md clean", expectedCode: 0},
			{name: "Write|md deferral", expectedCode: 1},
			{name: "Write|numeric no test", expectedCode: 0},
			{name: "Write|parse no fuzz", expectedCode: 0},
			{name: "Write|py file", expectedCode: 0},
			{name: "Write|rfc no header", expectedCode: 0},
			{name: "Write|small go", expectedCode: 0},
			{name: "Write|test no docs", expectedCode: 0},
			{name: "Write|vague names", expectedCode: 0},
		},
	},
}
