// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-command-meta-api.yang
var ZeCommandMetaAPIYANG string

//go:embed ze-command-meta-cmd.yang
var ZeCommandMetaCmdYANG string

//go:embed ze-command-monitor-cmd.yang
var ZeCommandMonitorCmdYANG string
