// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-command-meta-api.yang", ZeCommandMetaAPIYANG)
	configyang.RegisterModule("ze-command-meta-cmd.yang", ZeCommandMetaCmdYANG)
	configyang.RegisterModule("ze-command-monitor-cmd.yang", ZeCommandMonitorCmdYANG)
}
