// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-l2tp-api.yang
var ZeL2TPAPIYANG string

//go:embed ze-l2tp-cmd.yang
var ZeL2TPCmdYANG string

//go:embed ze-l2tp-conf.yang
var ZeL2TPConfYANG string
