// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-l2tp-api.yang", ZeL2TPAPIYANG)
	configyang.RegisterModule("ze-l2tp-conf.yang", ZeL2TPConfYANG)
}
