// Code generated by ./le yang-glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-bgp-cmd-metrics-api.yang
var ZeBGPCmdMetricsAPIYANG string

//go:embed ze-cli-metrics-cmd.yang
var ZeCliMetricsCmdYANG string
