plugin {
	external silence-ack {
		run ./run/api-silence-ack.run
		encoder text
	}
}
bgp {
	peer 127.0.0.1 {
		router-id 1.2.3.4
		local-address 127.0.0.1
		local-as 1
		peer-as 1
		group-updates disable

		family {
			ipv4/unicast
		}
		capability {
			graceful-restart
		}
		process silence-ack {
		}
	}
}
