plugin {
	external announce-routes {
		run ./run/api-nexthop-self.run;
		encoder json;
	}
}
bgp {
	peer 127.0.0.1 {
		router-id 1.2.3.4;
		local-address 127.0.0.1;
		local-as 1;
		peer-as 1;
		group-updates disable;

		family {
			ipv4/unicast;
		}
		announce {
			ipv4 {
				unicast 10.0.0.1 next-hop self;
				unicast 10.0.0.2 next-hop self;
			}
		}
		process announce-routes {
		}
	}
}
