plugin {
	external blocklist-10.0.0.2 {
		run ./run/api-blocklist.run
		encoder text
	}
	external blocklist-10.0.0.3 {
		run ./run/api-blocklist.run
		encoder text
	}
}
bgp {
	group blocklist {
		router-id 10.0.0.17
		local-address 10.0.0.17
		local-as 64512
		peer-as 64512
		hold-time 180
		group-updates enable

		family {
			ipv4/unicast
			ipv6/unicast
		}
		capability {
			route-refresh enable
			graceful-restart 1200
			operational enable
		}

		peer 10.0.0.2 {
			process blocklist-10.0.0.2 {
			}
		}
		peer 10.0.0.3 {
			process blocklist-10.0.0.3 {
			}
		}
	}
}
