plugin {
	external check-and-announce {
		run ./run/api-check.run
		encoder text
	}
}
template {
	bgp {
		peer * {
			inherit-name controler

			family {
				ipv4/unicast
				ipv6/unicast
			}
			announce {
				ipv4 {
					unicast 127.0.0.1/32 next-hop 127.0.0.2
				}
				ipv6 {
					unicast ::1/128 next-hop ::1
				}
			}
			process check-and-announce {
				content {
					format parsed
				}
				receive {
					update
				}
				send {
					update
				}
			}
		}
	}
}
bgp {
	peer 127.0.0.1 {
		inherit controler
		router-id 10.0.0.139
		local-address 127.0.0.1
		local-as 65512
		peer-as 65512
		hold-time 30
	}
}
