plugin {
	external expecting-a-keepalive {
		run ./run/api-api.receive.run;
		encoder json;
	}
	external expecting-no-data {
		run ./run/api-api.nothing.run;
		encoder json;
	}
}
template {
	bgp {
		peer * {
			inherit-name controller;

			family {
				ipv4/nlri-mpls;
				ipv4/unicast;
			}
			process expecting-a-keepalive {
				content {
					format parsed;
				}
				receive {
					keepalive;
					update;
				}
				send {
					keepalive;
					update;
				}
			}
			process expecting-no-data {
			}
		}
	}
}
bgp {
	peer 127.0.0.1 {
		inherit controller;
		router-id 127.0.0.123;
		local-address 127.0.0.1;
		local-as 65535;
		peer-as 65535;
		group-updates disable;
	}
}
