bgp {
	peer 127.0.0.1 {
		description "m7i-4 router";
		router-id 10.0.0.1;
		local-address 127.0.0.1;
		local-as 65500;
		peer-as 65500;
		group-updates disable;

		family {
			ipv4/flow;
			ipv4/flow-vpn;
			ipv6/flow;
		}
		capability {
			graceful-restart 5;
		}
		flow {
			route alternative-syntax {
				match {
					destination 192.168.0.1/32;
					source 10.0.0.1/32;
				}
				then {
					community [ 30740:0 30740:30740 ];
					extended-community [ redirect:65500:12345 origin:2345:6.7.8.9 origin:2.3.4.5:6789 ];
				}
			}
			route issue-542 {
				match {
					destination 118.184.176.6/32;
				}
				then {
					rate-limit 1250000000;
					redirect 65001:119;
				}
			}
			route optional-name-of-the-route {
				match {
					destination 192.168.0.1/32;
					destination-port [ >8080&<8088 =3128 ];
					dscp [ 10 20 ];
					fragment [ first-fragment last-fragment ];
					icmp-code [ host-unreachable network-unreachable ];
					icmp-type [ unreachable echo-request echo-reply ];
					packet-length [ >200&<300 >400&<500 ];
					port [ =80 =8080 ];
					protocol [ tcp udp ];
					source 10.0.0.1/32;
					source-port >1024;
					tcp-flags [ urgent rst ];
				}
				then {
					community [ 30740:0 30740:30740 ];
					extended-community [ origin:2345:6.7.8.9 origin:2.3.4.5:6789 ];
					redirect 65500:12345;
				}
			}
			route redirect-nexthop-ietf-ipv4 {
				match {
					destination 192.168.0.1/32;
					source 10.0.0.1/32;
				}
				then {
					redirect-to-nexthop 1.2.3.4;
				}
			}
			route redirect-nexthop-ietf-ipv6 {
				match {
					destination 192.168.0.2/32;
					source 10.0.0.1/32;
				}
				then {
					redirect-to-nexthop 2A02:B80:0:1::1;
				}
			}
		}
	}
}
