template {
	bgp {
		peer * {
			inherit-name test;
			local-as 65533;
			peer-as 65533;
			hold-time 180;
			group-updates disable;

			family {
				ipv4/unicast;
			}
			capability {
				graceful-restart 1200;
			}
			announce {
				ipv4 {
					unicast 1.0.0.0/8 next-hop 1.1.1.1;
					unicast 2.0.0.0/8 next-hop 1.1.1.1;
					unicast 3.0.0.0/8 next-hop 1.1.1.1;
					unicast 4.0.0.0/8 next-hop 1.1.1.1;
				}
			}
		}
	}
}
bgp {
	peer 127.0.0.1 {
		inherit test;
		description "router 2 with four routes";
		router-id 127.0.0.0;
		local-address 127.0.0.1;
	}
}
