plugin {
	external my-process {
		run ./run/syslog-1.py;
		encoder json;
	}
}
template {
	bgp {
		peer * {
			inherit-name test;
			process my-process {
				receive {
					state;
				}
			}
		}
	}
}
bgp {
	peer 10.0.0.3 {
		description "will pass received routes to the program";
		router-id 10.0.0.2;
		local-address 10.0.0.2;
		local-as 65533;
		peer-as 65533;
		hold-time 180;
	}
}
