plugin {
	external parsed-route-backend {
		run ./run/syslog-1.py
		encoder json
	}
}
bgp {
	group default {
		peer 10.0.0.3 {
			description "will pass received routes to the program"
			router-id 10.0.0.2
			local-address 10.0.0.2
			local-as 123456
			peer-as 123456
			receive-hold-time 180
			capability {
				multi-session
			}
			announce {
				ipv4 {
					unicast 10.0.0.0/24 next-hop 192.0.2.1
					unicast 10.0.1.0/24 next-hop 192.0.2.1
					unicast 10.0.2.0/24 next-hop 192.0.2.1
					unicast 10.0.3.0/24 next-hop 192.0.2.1
				}
				ipv6 {
					unicast 2A02:B80:0:1::/64 next-hop 2A02:B80:0:2::1 local-preference 200 community "30740:0 30740:30740"
				}
			}
			process parsed-route-backend {
			}
		}
	}
}
