plugin {
	external my-process {
		run ./syslog-1.py
		encoder json
	}
	external my-second-process {
		run ./stderr-1.py
		encoder json
	}
}
bgp {
	group test {
		process my-process {
			receive [ state ]
		}
		process my-second-process {
			receive [ state ]
		}

		peer peer3 {
			connection {
				remote {
					ip 10.0.0.3
				}
				local {
					ip 10.0.0.2
				}
			}
			session {
				asn {
					local 65533
					remote 65533
				}
				router-id 10.0.0.2
			}
			description "will pass received routes to the program"
			timer {
				receive-hold-time 180
			}
		}
	}
}
