bgp {
	peer peer3 {
		connection {
			remote {
				ip 10.0.0.3
			}
			local {
				ip 10.0.0.2
			}
			ttl {
				set 1
			}
		}
		session {
			asn {
				local 65533
				remote 65533
			}
			router-id 198.111.227.39
		}
		description "will announce 256 /24"
		timer {
			receive-hold-time 180
		}
		update {
			attribute {
				origin igp
				next-hop 192.0.2.1
				med 200
				community 174:666
			}
			nlri {
				ipv4/unicast add 172.10.0.0/16
			}
		}
	}
}
