// Design: docs/architecture/command-ownership.md -- YANG as data, generated glue wires it in
//
// Package yangglue generates the embed.go and register.go beside every .yang
// file in the tree. The generated Go is what wires a YANG module into the
// config/yang registry: an //go:embed directive per module, and an init() that
// calls RegisterModule with the module's FILE NAME as its key.
//
// The pair is a generator and its read-only twin. `le yang-glue write` writes
// the glue; `le yang-glue check` regenerates it in memory and reports every
// file that disagrees, which is what makes a generated file gateable
// (ze-yang-glue-check).
//
// Two directories are excluded and both exclusions are load-bearing.
// internal/component/config/yang is the registry the glue registers INTO, so
// glue written there would register the registry with itself. internal/test
// holds fixture schemas the suites feed to a parser, never modules ze serves.
package yangglue

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"

	"github.com/ze-software/ze/internal/core/textbuf"
	"github.com/ze-software/ze/letools/lepath"
)

// generatedHeader opens every file this tool writes. It names the SCRIPT
// because the committed glue names the script: changing the line would make
// every generated file in the tree stale at once, and the two halves of the
// port would stop agreeing about bytes. It moves when the script does.
const generatedHeader = "// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.\n"

// registryPackage is the config/yang package, relative to internal/. It is the
// registry the generated init() calls, so it is never itself a schema package.
var registryPackage = filepath.Join("component", "config", "yang")

// discover answers every yang/ directory under root holding at least one .yang
// file, sorted.
//
// A directory the walk LISTS and cannot read stops the run. For a generator
// that is the only safe answer: a package passed over silently is a set of YANG
// modules that vanish from the composition root, and the write half would then
// commit the tree with them gone.
func discover(root string) ([]string, error) {
	internalDir := filepath.Join(root, "internal")

	var dirs []string

	err := filepath.WalkDir(internalDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		if strings.Contains(filepath.ToSlash(path), "/internal/test/") {
			return filepath.SkipDir
		}
		if d.Name() != "yang" {
			return nil
		}
		if rel, relErr := filepath.Rel(internalDir, path); relErr == nil && rel == registryPackage {
			return filepath.SkipDir
		}

		entries, readErr := os.ReadDir(path)
		if readErr != nil {
			return readErr
		}
		for _, entry := range entries {
			if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".yang") {
				dirs = append(dirs, path)
				break
			}
		}
		// A yang/ directory holds modules, never another yang/ directory.
		return filepath.SkipDir
	})
	if err != nil {
		return nil, err
	}

	slices.Sort(dirs)

	return dirs, nil
}

// modulesIn answers the .yang file names of one directory, sorted.
func modulesIn(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var modules []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".yang") {
			modules = append(modules, entry.Name())
		}
	}

	slices.Sort(modules)

	return modules, nil
}

// embedSource renders the embed.go of one schema package: one //go:embed
// directive and one string variable per module.
func embedSource(modules []string) []byte {
	var tb textbuf.Buffer

	tb.Str(generatedHeader)
	tb.Str("\npackage yang\n")
	tb.Str("\nimport _ \"embed\"\n")

	for _, module := range modules {
		tb.Str("\n//go:embed ").Str(module).Byte('\n')
		tb.Str("var ").Str(varName(module)).Str(" string\n")
	}

	return slices.Clone(tb.Bytes())
}

// registerSource renders the register.go of one schema package: an init() that
// registers each module under its FILE NAME, which is the key the loader reads.
func registerSource(modules []string, module string) []byte {
	var tb textbuf.Buffer

	tb.Str(generatedHeader)
	tb.Str("\npackage yang\n")
	tb.Str("\nimport (\n\tconfigyang \"").Str(module).Str("/internal/component/config/yang\"\n)\n")
	tb.Str("\nfunc init() {\n")

	for _, name := range modules {
		tb.Str("\tconfigyang.RegisterModule(\"").Str(name).Str("\", ").Str(varName(name)).Str(")\n")
	}

	tb.Str("}\n")

	return slices.Clone(tb.Bytes())
}

// acronyms are the words whose Go spelling is not their title case. A word this
// table does not hold is title-cased, so adding one is the whole cost of a new
// module whose name carries an initialism.
var acronyms = map[string]string{
	"aaa":        "AAA",
	"api":        "API",
	"as":         "AS",
	"aspath":     "AsPath",
	"bgp":        "BGP",
	"bfd":        "BFD",
	"bmp":        "BMP",
	"dhcp":       "DHCP",
	"dns":        "DNS",
	"fd":         "FD",
	"flowexport": "FlowExport",
	"gnmi":       "GNMI",
	"http":       "HTTP",
	"ike":        "IKE",
	"ip":         "IP",
	"ipc":        "IPC",
	"ipsec":      "IPsec",
	"l2tp":       "L2TP",
	"ldp":        "LDP",
	"mcp":        "MCP",
	"mpls":       "MPLS",
	"mrt":        "MRT",
	"ntp":        "NTP",
	"ospf":       "OSPF",
	"ospfv3":     "OSPFv3",
	"pki":        "PKI",
	"poolstats":  "PoolStats",
	"pppoe":      "PPPoE",
	"rpc":        "RPC",
	"rpki":       "RPKI",
	"rr":         "RR",
	"rsvp":       "RSVP",
	"ssh":        "SSH",
	"tcp":        "TCP",
	"te":         "TE",
	"tftp":       "TFTP",
	"vpp":        "VPP",
}

// varName answers the Go variable name of one module file: ze-host-cmd.yang
// becomes ZeHostCmdYANG.
func varName(filename string) string {
	var tb textbuf.Buffer

	for part := range strings.SplitSeq(strings.TrimSuffix(filename, ".yang"), "-") {
		if upper, listed := acronyms[strings.ToLower(part)]; listed {
			tb.Str(upper)
			continue
		}
		tb.Str(titleCase(part))
	}
	tb.Str("YANG")

	return tb.String()
}

// titleCase upper-cases the first rune and leaves the rest, which is what a
// hyphen-separated name part owes.
func titleCase(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

// glue is one generated file: where it goes, and what it must hold.
type glue struct {
	path string
	want []byte
}

// derive answers every generated file the tree owes, and how many schema
// packages produced them.
func derive(root string) (files []glue, dirs int, err error) {
	found, err := discover(root)
	if err != nil {
		return nil, 0, err
	}
	if len(found) == 0 {
		return nil, 0, nil
	}

	module, err := lepath.Module(root)
	if err != nil {
		return nil, 0, err
	}

	for _, dir := range found {
		modules, listErr := modulesIn(dir)
		if listErr != nil {
			return nil, 0, listErr
		}
		if len(modules) == 0 {
			continue
		}
		files = append(files,
			glue{path: filepath.Join(dir, "embed.go"), want: embedSource(modules)},
			glue{path: filepath.Join(dir, "register.go"), want: registerSource(modules, module)},
		)
	}

	return files, len(found), nil
}

// Check reports every generated file that disagrees with the .yang files beside
// it. It writes nothing.
func Check(root string) (CheckReport, error) {
	files, dirs, err := derive(root)
	if err != nil {
		return CheckReport{}, err
	}

	report := CheckReport{Dirs: dirs}

	for _, file := range files {
		got, readErr := os.ReadFile(file.path) //nolint:gosec // a build tool reads the checkout it was pointed at
		if readErr != nil || !bytes.Equal(got, file.want) {
			report.Stale = append(report.Stale, relativeTo(root, file.path))
		}
	}

	return report, nil
}

// Write generates the glue, and answers the files whose bytes changed. A file
// that already agrees is left alone, so `make generate` moves no mtime it does
// not have to.
func Write(root string) (WriteReport, error) {
	files, dirs, err := derive(root)
	if err != nil {
		return WriteReport{}, err
	}

	report := WriteReport{Dirs: dirs}

	for _, file := range files {
		got, readErr := os.ReadFile(file.path) //nolint:gosec // a build tool reads the checkout it was pointed at
		if readErr == nil && bytes.Equal(got, file.want) {
			continue
		}
		if err := os.WriteFile(file.path, file.want, 0o644); err != nil { //nolint:gosec // generated source, read by everyone who reads the tree
			return WriteReport{}, err
		}
		report.Written = append(report.Written, relativeTo(root, file.path))
	}

	return report, nil
}

// relativeTo answers a path as the tree sees it. A generated file's identity is
// its place in the checkout, and an absolute path names this machine's tmp
// directory as much as it names the file.
func relativeTo(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return filepath.ToSlash(path)
	}
	return filepath.ToSlash(rel)
}
