// Design: docs/architecture/core-design.md -- what the source-anchor index answers
// Overview: codetodocs.go -- the walk that fills this in
//
// codetodocs_report.go holds the RENDERING of ai/CODE-TO-DOCS.md and what
// `le docs-to-code ze-doc-index-check` answers.
//
// The payload carries the findings rather than a count of them, because a
// finding is what a reader acts on. One key holds rows, so the row operators
// act on the stale references.
//
// Both modes deliberately put IDENTICAL content in the index. The stale table
// appears only in the report. If check and update rendered different index
// content for one tree, the gate would stay stale after the generator ran.

package docstocode

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ze-software/ze/internal/core/textbuf"
)

// StaleRef is one document line naming a code path that no longer exists.
type StaleRef struct {
	Path string `json:"path"`
	Doc  string `json:"doc"`
	Line int    `json:"line"`
}

// CodeReport is what the reverse index answers.
type CodeReport struct {
	File string `json:"file"`
	// Paths is how many code paths the anchors name, and Packages how many
	// directories they group into. Both are what the script prints.
	Paths    int `json:"paths"`
	Packages int `json:"packages"`
	// Stale names every anchor pointing at a path that no longer exists.
	Stale []StaleRef `json:"stale"`
	// Claims names every symbol an anchor names that its file neither declares
	// nor mentions.
	Claims []string `json:"claims"`
	// Written says the index file was rewritten by this run.
	Written bool `json:"written"`
}

// Text renders the verdict for a person, in the words the script prints and in
// its order. It ends in a newline.
func (r CodeReport) Text() string {
	var tb textbuf.Buffer

	if r.Written {
		tb.Str("wrote ").Str(r.File).Str(" (").Int(int64(r.Paths)).Str(" code paths, ").
			Int(int64(r.Packages)).Str(" packages)\n")
		return tb.String()
	}

	tb.Str("checked ").Int(int64(r.Paths)).Str(" code paths, ").
		Int(int64(r.Packages)).Str(" packages\n")

	switch {
	case len(r.Stale) > 0:
		tb.Int(int64(len(r.Stale))).Str(" stale references (code path no longer exists)\n")
		tb.Str(r.staleLines())
	case len(r.Claims) > 0:
		tb.Int(int64(len(r.Claims))).Str(" anchor symbol(s) not declared where named\n")
		for _, claim := range r.Claims {
			tb.Str("  CLAIM: ").Str(claim).Byte('\n')
		}
	default:
		tb.Str("all references valid\n")
	}
	return tb.String()
}

// staleLines renders the stale references grouped by code path, naming three
// documents apiece and counting the rest.
func (r CodeReport) staleLines() string {
	byPath := map[string][]string{}
	for _, ref := range r.Stale {
		var tb textbuf.Buffer
		byPath[ref.Path] = append(byPath[ref.Path], tb.Str(ref.Doc).Byte(':').Int(int64(ref.Line)).String())
	}

	paths := make([]string, 0, len(byPath))
	for path := range byPath {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	var tb textbuf.Buffer
	for _, path := range paths {
		refs := byPath[path]
		tb.Str("  MISSING: ").Str(path).Byte('\n')
		named := refs
		if len(named) > namedRefs {
			named = named[:namedRefs]
		}
		for _, ref := range named {
			tb.Str("           <- ").Str(ref).Byte('\n')
		}
		if len(refs) > namedRefs {
			tb.Str("           ... and ").Int(int64(len(refs) - namedRefs)).Str(" more\n")
		}
	}
	return tb.String()
}

// RenderCodeIndex answers the bytes of ai/CODE-TO-DOCS.md for one index.
//
// The renderer groups entries by package directory, which is how a code editor
// searches. A package with at most three files uses bullets. A larger package
// uses a table because a two-row table costs more to read than it saves.
func RenderCodeIndex(index CodeIndex) string {
	var tb textbuf.Buffer
	tb.Str("# Code to Documentation Index\n\n")
	tb.Str("<!-- GENERATED by scripts/dev/code_to_docs.py -- do not edit -->\n")
	tb.Str("<!-- Regenerate: make ze-doc-index-update -->\n\n")

	byPackage := groupByPackage(index)
	packages := make([]string, 0, len(byPackage))
	for pkg := range byPackage {
		packages = append(packages, pkg)
	}
	sort.Strings(packages)

	for _, pkg := range packages {
		files := byPackage[pkg]
		paths := make([]string, 0, len(files))
		allDocs := map[string]bool{}
		for path, docs := range files {
			paths = append(paths, path)
			for doc := range docs {
				allDocs[doc] = true
			}
		}
		sort.Strings(paths)

		tb.Str("## `").Str(pkg).Str("/`\n\n")

		if len(files) <= namedInline {
			for _, path := range paths {
				tb.Str("- `").Str(path).Str("` -> ").Str(quotedList(sortedKeys(files[path]))).Byte('\n')
			}
			tb.Byte('\n')
			continue
		}

		tb.Str("Files: ").Int(int64(len(files))).Str(" | Docs: ").Str(quotedList(sortedKeys(allDocs))).Byte('\n')
		tb.Str("\n| File | Docs |\n|------|------|\n")
		for _, path := range paths {
			name := path[strings.LastIndex(path, "/")+1:]
			tb.Str("| `").Str(name).Str("` | ").Str(quotedList(sortedKeys(files[path]))).Str(" |\n")
		}
		tb.Byte('\n')
	}

	// The script joins lines with "\n" and writes no trailing newline. Thus, the
	// file ends with the blank line after the final package. This port preserves
	// that output byte for byte for the comparison.
	return strings.TrimSuffix(tb.String(), "\n")
}

// groupByPackage inverts the index into package -> code path -> documents.
func groupByPackage(index CodeIndex) map[string]map[string]map[string]bool {
	byPackage := map[string]map[string]map[string]bool{}
	for path, refs := range index.Refs {
		pkg := PackageDir(path)
		if byPackage[pkg] == nil {
			byPackage[pkg] = map[string]map[string]bool{}
		}
		if byPackage[pkg][path] == nil {
			byPackage[pkg][path] = map[string]bool{}
		}
		for _, ref := range refs {
			byPackage[pkg][path][ref.Doc] = true
		}
	}
	return byPackage
}

// sortedKeys answers a set's members in order.
func sortedKeys(set map[string]bool) []string {
	keys := make([]string, 0, len(set))
	for key := range set {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// quotedList renders a comma-separated list of backquoted names.
func quotedList(names []string) string {
	var tb textbuf.Buffer
	for i, name := range names {
		if i > 0 {
			tb.Str(", ")
		}
		tb.Byte('`').Str(name).Byte('`')
	}
	return tb.String()
}

// CheckCodeIndex judges the anchors of one tree. It writes nothing.
func CheckCodeIndex(root string) (CodeReport, error) {
	index, err := BuildCodeIndex(root)
	if err != nil {
		return CodeReport{}, err
	}

	report := codeCounts(index)
	for _, path := range sortedRefPaths(index) {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(path))); err == nil {
			continue
		}
		for _, ref := range index.Refs[path] {
			report.Stale = append(report.Stale, StaleRef{Path: path, Doc: ref.Doc, Line: ref.Line})
		}
	}
	report.Claims = CheckAnchors(root, index.Anchors)
	return report, nil
}

// UpdateCodeIndex rewrites ai/CODE-TO-DOCS.md from the tree.
func UpdateCodeIndex(root string) (CodeReport, error) {
	index, err := BuildCodeIndex(root)
	if err != nil {
		return CodeReport{}, err
	}

	out := filepath.Join(root, filepath.FromSlash(CodeOutputRel))
	if err := os.WriteFile(out, []byte(RenderCodeIndex(index)), 0o600); err != nil {
		return CodeReport{}, err
	}

	report := codeCounts(index)
	report.Written = true
	return report, nil
}

// codeCounts answers the two numbers both modes print.
func codeCounts(index CodeIndex) CodeReport {
	packages := map[string]bool{}
	for path := range index.Refs {
		packages[PackageDir(path)] = true
	}
	return CodeReport{File: CodeOutputRel, Paths: len(index.Refs), Packages: len(packages)}
}

// sortedRefPaths answers every code path the anchors name, in order.
func sortedRefPaths(index CodeIndex) []string {
	paths := make([]string, 0, len(index.Refs))
	for path := range index.Refs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}
