// Design: docs/architecture/core-design.md -- the generated docs-to-code index
// Detail: report.go -- what the command answers, and the rendering of the file
// Detail: codetodocs.go -- the MIRROR index, from the anchors inside docs/
//
// Package docstocode generates ai/DOCS-TO-CODE.md, the reverse index from the
// `// Design:` headers that live in Go files.
//
// Every non-test, non-generated Go file has a
// `// Design: <doc> -- topic` header (ai/rules/go-standards.md, hook-enforced).
// The code-to-docs index inverts `<!-- source: -->` anchors from docs/. This
// index maps each `// Design:` edge in the opposite direction. A reader can
// therefore find all files that implement a design document with no tree search.
package docstocode

import (
	"bufio"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"unicode"
)

const (
	// OutputRel is the index this tool writes, relative to the checkout.
	OutputRel = "ai/DOCS-TO-CODE.md"

	// StaleExit means that the committed output no longer matches its sources.
	// It differs from 1, which means that the generator failed. The commit gate
	// BLOCKS on drift but stays warn-only when the generator fails. The exit
	// code is the contract, and the warning text CAN change.
	StaleExit = 3

	// HeaderLines limits the search for a `// Design:` line in a file. The
	// header block contains that line. This exported CONTRACT value matches the
	// Python half. Output cannot show a difference because neither half finds a
	// later citation.
	HeaderLines = 25

	// maxLineBytes bounds one line of a source file. It is the same bound the
	// verify log reader uses, and three orders of magnitude above the longest
	// generated line in this tree.
	maxLineBytes = 4 << 20

	// InlineRefs is the largest reference list rendered as bullets. Above it
	// the entry becomes a table, because a longer list is read by scanning a
	// column rather than by reading sentences. It is exported for the same
	// reason as HeaderLines: it is a number both halves must share.
	InlineRefs = 3

	// ModCache holds extracted external modules AND a self-copy of ze,
	// regenerated by appliance builds. Indexing those duplicates the working
	// tree and is not first-party source.
	ModCache = "gokrazy/modcache"
)

// skipDirs are directory names the walk does not enter.
var skipDirs = map[string]bool{
	"vendor":       true,
	"tmp":          true,
	"testdata":     true,
	"node_modules": true,
	".git":         true,
}

// separators are the leading topic separators a `// Design:` line can use
// between the document path and the topic. The longest match wins, so `--` is
// tried before `-`.
var separators = [...]string{"—", "--", "-", ":"}

// Reference is one edge of the index: a design document, the file that cites
// it, and the topic that citation names.
type Reference struct {
	Doc   string `json:"doc"`
	File  string `json:"file"`
	Topic string `json:"topic"`
}

// Build reads the tree and answers every `// Design:` edge in it, sorted by
// document, then file, then topic.
//
// Every read error reaches the caller. If an unreadable file looks like a file
// with no citation, the generator writes that omission into the index. The
// check then agrees with that index and cannot detect the omission. Only a path
// that VANISHED during the walk is not a failure. This checkout is shared, so
// another session can remove a file that was never in the described tree.
func Build(root string) ([]Reference, error) {
	seen := make(map[Reference]bool)
	if err := walkGo(root, root, func(path, rel string) error {
		refs, err := designRefs(path, rel)
		if err != nil {
			return err
		}
		for _, ref := range refs {
			seen[ref] = true
		}
		return nil
	}); err != nil {
		return nil, err
	}

	out := make([]Reference, 0, len(seen))
	for ref := range seen {
		out = append(out, ref)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Doc != out[j].Doc {
			return out[i].Doc < out[j].Doc
		}
		if out[i].File != out[j].File {
			return out[i].File < out[j].File
		}
		return out[i].Topic < out[j].Topic
	})
	return out, nil
}

// walkGo visits every `.go` file under dir, in name order, and hands each one
// its absolute path and its path relative to root.
func walkGo(root, dir string, visit func(path, rel string) error) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if vanished(dir, err) {
			return nil
		}
		return fmt.Errorf("reading %s: %w", dir, err)
	}

	var files, subdirs []string
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() {
			if skipDirs[name] || strings.HasPrefix(name, ".") {
				continue
			}
			subdirs = append(subdirs, name)
			continue
		}
		if strings.HasSuffix(name, ".go") {
			files = append(files, name)
		}
	}

	sort.Strings(files)
	for _, name := range files {
		path := filepath.Join(dir, name)
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return fmt.Errorf("locating %s under %s: %w", path, root, err)
		}
		if err := visit(path, filepath.ToSlash(rel)); err != nil {
			return err
		}
	}

	sort.Strings(subdirs)
	for _, name := range subdirs {
		sub := filepath.Join(dir, name)
		rel, err := filepath.Rel(root, sub)
		if err != nil {
			return fmt.Errorf("locating %s under %s: %w", sub, root, err)
		}
		if filepath.ToSlash(rel) == ModCache {
			continue
		}
		if err := walkGo(root, sub, visit); err != nil {
			return err
		}
	}
	return nil
}

// designRefs answers every design edge one file's header block declares.
func designRefs(path, rel string) ([]Reference, error) {
	file, err := os.Open(path) //nolint:gosec // path comes from a walk of the tree the caller named
	if err != nil {
		if vanished(path, err) {
			return nil, nil
		}
		return nil, fmt.Errorf("opening %s: %w", path, err)
	}
	defer file.Close() //nolint:errcheck // read-only

	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, 64*1024), maxLineBytes)

	var refs []Reference
	for read := 0; read < HeaderLines && scanner.Scan(); read++ {
		doc, topic, ok := designLine(strings.TrimSpace(scanner.Text()))
		if !ok || !isDocPath(doc) {
			continue
		}
		refs = append(refs, Reference{Doc: doc, File: rel, Topic: topic})
	}
	if err := scanner.Err(); err != nil {
		// A scan that STOPS on a long line leaves the header block half read,
		// so the edges after it go unrecorded. That is the same omission an
		// unreadable file would contribute, and it is reported the same way.
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	return refs, nil
}

// designLine reads a `// Design: <doc> <topic>` header line.
func designLine(line string) (doc, topic string, ok bool) {
	rest, ok := strings.CutPrefix(line, "//")
	if !ok {
		return "", "", false
	}
	rest = strings.TrimLeftFunc(rest, unicode.IsSpace)
	rest, ok = strings.CutPrefix(rest, "Design:")
	if !ok {
		return "", "", false
	}
	rest = strings.TrimLeftFunc(rest, unicode.IsSpace)
	if rest == "" {
		return "", "", false
	}
	// The document path is one run of non-space characters. The topic follows
	// it after the parser removes its leading separator.
	idx := strings.IndexFunc(rest, unicode.IsSpace)
	if idx < 0 {
		return rest, "", true
	}
	return rest[:idx], stripSeparator(strings.TrimSpace(rest[idx:])), true
}

// stripSeparator removes the leading topic separator a citation writes between
// the document path and the topic.
func stripSeparator(topic string) string {
	for _, sep := range separators {
		if rest, ok := strings.CutPrefix(topic, sep); ok {
			return strings.TrimSpace(rest)
		}
	}
	return strings.TrimSpace(topic)
}

// isDocPath reports a real design-document reference, as against a `(none ...)`
// placeholder: a markdown path with a directory in it.
func isDocPath(token string) bool {
	return strings.HasSuffix(token, ".md") && strings.Contains(token, "/")
}

// vanished reports a path that disappeared during the walk. This checkout is
// shared, so another session can remove a file between the listing and read.
// That file was not part of the described tree. The generator does not report
// another session's timing as a defect.
func vanished(path string, err error) bool {
	if !errors.Is(err, fs.ErrNotExist) {
		return false
	}
	_, statErr := os.Lstat(path)
	return errors.Is(statErr, fs.ErrNotExist)
}

// SkipDirs answers the directory names the walk does not enter, sorted. The
// caller receives a copy, so a reader cannot widen the walk by editing what it
// was handed.
func SkipDirs() []string {
	out := make([]string, 0, len(skipDirs))
	for name := range skipDirs {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// Separators answers the leading topic separators a citation can use between
// the document path and the topic, longest first.
func Separators() []string { return slices.Clone(separators[:]) }
