// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-isis-cmd.yang
var ZeIsisCmdYANG string

//go:embed ze-isis-conf.yang
var ZeIsisConfYANG string
