#!/usr/bin/env python3

import time

from zebgp_api import ready, send, wait_for_ack, wait_for_shutdown


def main() -> None:
    ready()

    # neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 1 peer-as 1 router-id 1.2.3.4 family-allowed ipv4-unicast
    messages = [
        'update text med set 200 community set [2:1] nhop set 101.1.101.1 nlri ipv4/unicast add 1.0.0.0/24',
        'neighbor 127.0.0.1 update text nhop set 101.1.101.1 nlri ipv4/unicast add 1.1.0.0/24',
        'neighbor 127.0.0.1 local-as 1 family-allowed ipv4-unicast update text nhop set 101.1.101.1 nlri ipv4/unicast add 1.2.0.0/24',
        'neighbor 127.0.0.1 local-as 1 family-allowed in-open update text nhop set 101.1.101.1 nlri ipv4/unicast add 9.9.9.9/24',
        'neighbor 127.0.0.1 local-as 1 peer-as 1 local-ip 127.0.0.1 router-id 1.2.3.4 update text nhop set 101.1.101.1 nlri ipv4/unicast add 1.3.0.0/24',
    ]

    for message in messages:
        send(message)
        time.sleep(0.2)

    wait_for_ack(expected_count=5)
    wait_for_shutdown()


if __name__ == '__main__':
    main()
