#!/usr/bin/env python3

import time

from zebgp_api import ready, send, wait_for_shutdown


def main() -> None:
    ready()

    try:
        # this will never be received by the peer
        send('update text nhop set 5.6.7.8 nlri ipv4/unicast add 1.2.3.4')
        wait_for_shutdown()
        # This route will never be sent
    except IOError:
        pass


if __name__ == '__main__':
    main()
