// Design: (none -- new TACACS+ component)
// Detail: client.go -- randomSessionID, the producer this file pins
//
// VALIDATES: RFC 8907 Section 4, session_id. The four octets come from the
// operating system's cryptographic generator and from nothing else.
// PREVENTS: a session_id drawn from a counter or from math/rand. Both are
// distinct across draws, so a uniqueness test alone accepts them, and either
// lets an attacker predict the id and forge or correlate TACACS+ sessions.
//
// The test lives beside client_test.go rather than inside it: that file carries
// `RFC requirement:` tags and the pretool-writeedit hook refuses every edit to a
// tagged test file, an addition included (ai/rules/testing.md).

package tacacs

import (
	"bytes"
	"crypto/rand"
	"encoding/binary"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestRFC8907SessionIDComesFromCryptoRand substitutes the crypto/rand reader and
// requires the session id to be exactly the number those octets spell.
//
// No unit test can prove four octets are random: a counter satisfies every
// statistical check a sample allows, and TestRandomSessionIDDistinct accepts one.
// What a test CAN prove is the structural property the requirement rests on, that
// the octets come from the cryptographic generator rather than from any other
// source. Any other source fails this, a counter included.
//
// RFC 8907 Section 4: "This number MUST be generated by a cryptographically
// strong random number generation method. Failure to do so will compromise
// security of the session."
//
// RFC requirement: RFC8907-4-3 positive -- randomSessionID reads its four octets
// from crypto/rand.Reader: with that reader substituted the returned id is the
// big-endian number those exact octets spell (client.go randomSessionID).
func TestRFC8907SessionIDComesFromCryptoRand(t *testing.T) {
	saved := rand.Reader
	t.Cleanup(func() { rand.Reader = saved })

	marker := []byte{0xA1, 0xB2, 0xC3, 0xD4}
	rand.Reader = bytes.NewReader(marker)

	id, err := randomSessionID()
	require.NoError(t, err)

	want := binary.BigEndian.Uint32(marker)
	if id != want {
		t.Fatalf("session_id = %#08x, want %#08x (the octets crypto/rand.Reader supplied); the id is coming from another source", id, want)
	}
}
