// Design: (none -- code generator for RIR ASN delegation table)

//go:build ignore

// gen-iana-asn fetches the 5 RIR delegation files and generates rir_table.go
// in the irr package, containing the ASN-to-RIR mapping with whois servers.
// This is the seed data committed to the repo for zefs prepopulation.
//
// Usage: go generate ./internal/component/bgp/irr/...
//    or: go run scripts/gen-iana-asn.go
package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const outputFile = "internal/component/bgp/irr/rir_table.go"

var delegationURLs = []string{
	"https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest",
	"https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest",
	"https://ftp.apnic.net/pub/stats/apnic/delegated-apnic-extended-latest",
	"https://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest",
	"https://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest",
}

var rirNames = map[string]string{
	"ripencc": "RIPE",
	"arin":    "ARIN",
	"apnic":   "APNIC",
	"afrinic": "AFRINIC",
	"lacnic":  "LACNIC",
}

var rirWhois = map[string]string{
	"ripencc": "whois.ripe.net",
	"arin":    "whois.arin.net",
	"apnic":   "whois.apnic.net",
	"afrinic": "whois.afrinic.net",
	"lacnic":  "whois.lacnic.net",
}

type entry struct {
	start uint32
	end   uint32
	rir   string
	whois string
}

var rirConstNames = map[string]string{
	"RIPE":    "RIRRIPE",
	"ARIN":    "RIRARIN",
	"APNIC":   "RIRAPNIC",
	"AFRINIC": "RIRAFRINIC",
	"LACNIC":  "RIRLACNIC",
}

var whoisConstNames = map[string]string{
	"whois.ripe.net":    "WhoisRIPE",
	"whois.arin.net":    "WhoisARIN",
	"whois.apnic.net":   "WhoisAPNIC",
	"whois.afrinic.net": "WhoisAFRINIC",
	"whois.lacnic.net":  "WhoisLACNIC",
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("gen-iana-asn: ")

	var allEntries []entry
	client := &http.Client{Timeout: 60 * time.Second}

	for _, url := range delegationURLs {
		log.Printf("fetching %s", url)
		entries, err := fetchAndParse(client, url)
		if err != nil {
			log.Fatalf("error: %v", err)
		}
		log.Printf("  %d ASN records", len(entries))
		allEntries = append(allEntries, entries...)
	}

	sort.Slice(allEntries, func(i, j int) bool {
		return allEntries[i].start < allEntries[j].start
	})

	collapsed := collapse(allEntries)
	generate(collapsed)
	log.Printf("wrote %s (%d collapsed ranges from %d records)", outputFile, len(collapsed), len(allEntries))
}

func fetchAndParse(client *http.Client, url string) ([]entry, error) {
	resp, err := client.Get(url) //nolint:gosec,noctx // standalone generator
	if err != nil {
		return nil, fmt.Errorf("fetch %s: %w", url, err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: HTTP %d", url, resp.StatusCode)
	}

	return parseDelegation(resp.Body)
}

func parseDelegation(r io.Reader) ([]entry, error) {
	var entries []entry
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || line[0] == '#' {
			continue
		}

		fields := strings.Split(line, "|")
		if len(fields) < 7 {
			continue
		}

		registry := fields[0]
		recType := fields[2]
		startStr := fields[3]
		countStr := fields[4]
		status := fields[6]

		if recType != "asn" {
			continue
		}
		if status != "allocated" && status != "assigned" {
			continue
		}

		rir, ok := rirNames[registry]
		if !ok {
			continue
		}
		whois := rirWhois[registry]

		start, err := strconv.ParseUint(startStr, 10, 32)
		if err != nil {
			continue
		}
		count, err := strconv.ParseUint(countStr, 10, 32)
		if err != nil || count == 0 {
			continue
		}

		entries = append(entries, entry{
			start: uint32(start),
			end:   uint32(start + count - 1),
			rir:   rir,
			whois: whois,
		})
	}

	return entries, scanner.Err()
}

func collapse(entries []entry) []entry {
	if len(entries) == 0 {
		return nil
	}

	result := []entry{entries[0]}
	for _, e := range entries[1:] {
		last := &result[len(result)-1]
		if e.rir == last.rir && e.start <= last.end+1 {
			if e.end > last.end {
				last.end = e.end
			}
			continue
		}
		result = append(result, e)
	}
	return result
}

func generate(entries []entry) {
	f, err := os.Create(outputFile)
	if err != nil {
		log.Fatalf("create %s: %v", outputFile, err)
	}

	w := func(s string) {
		if _, wErr := io.WriteString(f, s); wErr != nil {
			log.Fatalf("write: %v", wErr)
		}
	}

	w("// Design: (none -- generated RIR delegation table)\n//\n// Code generated by scripts/gen-iana-asn.go; DO NOT EDIT.\n")
	w("// Source: RIR delegation files (RIPE, ARIN, APNIC, AFRINIC, LACNIC)\n")
	w("// Generated: " + time.Now().UTC().Format("2006-01-02") + "\n")
	w("// This is seed data for zefs prepopulation. Runtime updates via `ze bgp irr update`.\n\n")
	w("package irr\n\n")
	w("// seedRIRTable is the compiled-in RIR delegation data.\n")
	w("// Used as fallback when zefs has no data or as initial seed.\n")
	w("var seedRIRTable = []RIREntry{\n")

	for _, e := range entries {
		// Use constant names for interned strings (RIR* and Whois* in rir.go).
		rirConst := rirConstNames[e.rir]
		whoisConst := whoisConstNames[e.whois]
		line := fmt.Sprintf("\t{%d, %d, %s, %s},\n", e.start, e.end, rirConst, whoisConst)
		w(line)
	}

	w("}\n")

	if err := f.Close(); err != nil {
		log.Fatalf("close: %v", err)
	}
}
