// gen-plugin-imports generates internal/plugin/all/all.go from register.go discovery.
//
// It scans internal/plugins/*/register.go to find plugin packages and generates
// the blank-import file that triggers init() registration.
//
// Usage: go run scripts/gen-plugin-imports.go
// Called by: go generate ./internal/plugin/all/...
//
//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root, err := findModuleRoot()
	if err != nil {
		fatal(err)
	}

	module, err := readModulePath(filepath.Join(root, "go.mod"))
	if err != nil {
		fatal(err)
	}

	plugins, err := discoverPlugins(filepath.Join(root, "internal", "plugins"))
	if err != nil {
		fatal(err)
	}

	output := filepath.Join(root, "internal", "plugin", "all", "all.go")
	if err := generateAllGo(output, module, plugins); err != nil {
		fatal(err)
	}

	fmt.Printf("Generated %s with %d plugins: %s\n", output, len(plugins), strings.Join(plugins, " "))
}

func fatal(err error) {
	fmt.Println("gen-plugin-imports:", err)
	os.Exit(1)
}

// findModuleRoot walks up from the current directory to find go.mod.
func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

// readModulePath reads the module path from go.mod.
func readModulePath(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module")), nil
		}
	}
	return "", fmt.Errorf("module directive not found in %s", path)
}

// discoverPlugins finds plugin packages by looking for register.go files.
func discoverPlugins(pluginsDir string) ([]string, error) {
	entries, err := os.ReadDir(pluginsDir)
	if err != nil {
		return nil, err
	}

	var plugins []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		regPath := filepath.Join(pluginsDir, entry.Name(), "register.go")
		if _, err := os.Stat(regPath); err == nil {
			plugins = append(plugins, entry.Name())
		}
	}

	sort.Strings(plugins)
	return plugins, nil
}

// generateAllGo writes the all.go file with blank imports for each plugin.
func generateAllGo(path, module string, plugins []string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := bufio.NewWriter(f)

	fmt.Fprintln(w, "// Code generated by scripts/gen-plugin-imports.go; DO NOT EDIT.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Package all imports all internal plugins, triggering their init() registration.")
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "// To add a plugin, create internal/plugins/<name>/register.go with an init()")
	fmt.Fprintln(w, "// that calls registry.Register(). Then run: make generate")
	fmt.Fprintln(w, "package all")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "import (")
	for _, name := range plugins {
		fmt.Fprintf(w, "\t_ \"%s/internal/plugins/%s\"\n", module, name)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w)

	return w.Flush()
}
