#!/usr/bin/env python3
"""Check that path references resolve, in the instruction corpus and beyond it.

Five checks:
  1. Markdown corpus: backtick path references and markdown links in the
     normative agent-instruction files (ai/, .claude/rules/, plan/ meta docs)
     must point at files/dirs that exist. Historical records (plan/handover/)
     are NOT checked: they describe the tree as it was at the time.
  2. Go sources, `_test.go` included: the target of every `// Design:` comment
     must exist (`(none ...)` placeholders are allowed). Inside a test file a
     `plan/spec-` target is refused even when it exists -- spec closure deletes
     the spec, so a test cites a durable document instead.
  3. Dead names: a backticked `*.sh` filename or `c_*`/`check_*` function name
     in the hook-describing documents must name something in the tree. Check 1
     cannot see these: a bare `foo.sh` carries no `/`, so `candidate_paths`
     drops it, and a function name is not a path at all.
  4. Suppression reasons: every `doc-links: ignore` marker in a TRACKED file
     must carry a reason. Checks 1, 3 and 5 read the marker. Check 5 gives it
     effect over nearly the whole tree, so a reason is what makes a
     suppression auditable rather than a hole. Before check 5 existed, only
     `MD_GLOBS` and `NAME_LINT_FILES` were read, and a marker outside both
     was decoration no gate ever saw.
  5. Tracked citations: a path reference in any other TRACKED file must
     resolve too, under check 1's grammar. The population that predates this
     check is grandfathered in `scripts/dev/doc_citation_baseline.txt`, which
     is shrink-only: the gate compares the SETS and refuses each pair HEAD
     does not hold. Checks 4 and 5 share ONE read of each tracked file.

A line is skipped by checks 1, 3 and 5 when it carries the marker inside an HTML
comment AND that marker states a reason:

    <!-- doc-links: ignore (why this path cannot resolve) -->

Use it for a deliberate reference to a path that is not in the tree, such as a
negative example or a sibling repository. Two properties are load-bearing. The
marker counts only inside an HTML comment, so a document that MENTIONS the
words in prose no longer silences its own line. The reason is mandatory and
check 4 reports a marker without one, so a suppression is auditable: an
unreasoned marker is a silent allowlist, and 98 dead citations sat behind one.

A path that git IGNORES is never reported missing: `.gitignore` is where this
repo declares "generated or local-state artifact" (CLAUDE.md, AGENTS.md,
`.claude/skills/`, ... are generated by `make ze-ai-sync`). They exist in a
working tree that has run the generator and are absent from a fresh checkout,
so their absence is a property of the checkout, not a broken reference.

Usage: scripts/dev/check_doc_links.py [--md-only|--design-only] [-v]
       scripts/dev/check_doc_links.py --write-baseline
Called by: make ze-doc-links, make ze-regen-check
Exit codes: 0 = all resolve, 1 = broken references found.
"""

import argparse
import ast
import glob as globmod
import os
import re
import subprocess
import sys

KNOWN_ROOTS = {
    "ai",
    ".claude",
    ".codex",
    ".agents",
    ".github",
    "scripts",
    "internal",
    "cmd",
    "pkg",
    "test",
    "plan",
    "docs",
    "mk",
    "rfc",
    "tools",
    "etc",
    "examples",
    "api",
    "contrib",
    "gokrazy",
    "third_party",
    "parked",
    "vendor",
    # Non-canonical shorthands, deliberately checked so they FAIL:
    # write ai/rules/, .claude/rules/, ai/patterns/ explicitly.
    "rules",
    "patterns",
}
ROOT_FILES = {
    "Makefile",
    "CLAUDE.md",
    "AGENTS.md",
    "README.md",
    "go.mod",
    "go.sum",
    ".gitignore",
    ".golangci.yml",
    "tools.go",
    "LICENSE",
    "SECURITY.md",
    "CONTRIBUTING.md",
}
# Runtime/build artifacts: existence depends on local state, never checked.
SKIP_PREFIXES = ("tmp/", "bin/", "~", "/", "test/tmp/")
# Tokens containing these are templates, not concrete paths.
PLACEHOLDER_MARKERS = ("<", ">", "$", "*", "NNN", "...", "..")

MD_GLOBS = [
    "ai/INSTRUCTIONS.md",
    "ai/INDEX.md",
    "ai/NAVIGATION.md",
    "ai/rules/*.md",
    "ai/rationale/*.md",
    "ai/patterns/*.md",
    "ai/skills/*.md",
    "ai/agents/*.md",
    ".claude/rules/*.md",
    ".claude/README.md",
    ".claude/hooks/README.md",
    "plan/README.md",
    "plan/TEMPLATE.md",
    "plan/TEMPLATE-CLOSURE.md",
    "plan/learned/RECURRING-PATTERNS.md",
    "plan/learned/HOOK-FRICTION.md",
    # DESIGN-HISTORY.md was exempt until 2026-08-01, on the reasoning that a
    # historical narrative may name paths as they were. That exemption is why
    # its rot went unseen for three months: it is a document agents READ to
    # find code, so a path it names must resolve today. A genuinely retired
    # path is marked `doc-links: ignore` on its own line, which states the
    # intent the blanket exemption only implied.
    "plan/learned/DESIGN-HISTORY.md",
]
# Generated indexes are validated by their own --check generators.
MD_EXCLUDE = {"ai/CODE-TO-DOCS.md"}

BACKTICK = re.compile(r"`([^`]+)`")
MD_LINK = re.compile(r"\]\(([^)#][^)]*)\)")
LINE_SUFFIX = re.compile(r":\d+(?:-\d+)?$")
# `ai/digests/*.md` writes several line numbers as a comma run:
# `forward_body.go,47,64,82`. A member of the run can be a RANGE, as
# `selfupdate.go,875-886` is: the first form covered 1332 baseline pairs and the
# second covered 94 more, all of them live files reported dead. The FILE still
# has to resolve, so this strips the run and leaves the path, exactly as
# LINE_SUFFIX strips `:12` and `:12-14`.
LINE_RUN_SUFFIX = re.compile(r"(?:,\d+(?:-\d+)?)+$")
# `file.go:Symbol` / `pkg.Symbol` references: strip the symbol, check the path.
# The doubled colon is pytest's node id, `lab_test.py::test_name`, and a
# single-colon rule left the second colon ON the path. `lab_test.py:` resolves
# nowhere, so a live file was reported as a dead citation and the cheapest way
# out was a suppression over a reference that is not broken.
SYMBOL_COLON = re.compile(r"::?[A-Za-z_][\w.]*$")
SYMBOL_DOT = re.compile(r"\.[A-Z]\w*$")
DESIGN = re.compile(r"^// Design:\s*(.+)$")
# A `// Design:` target under this prefix is refused inside a `_test.go`.
SPEC_PREFIX = "plan/spec-"

# --- The suppression marker -------------------------------------------------
# `<!-- doc-links: ignore (reason) -->`. The HTML comment is part of the
# grammar, not decoration: the old test was `"doc-links: ignore" in line`, so a
# sentence naming the marker suppressed its own line, and the document that
# DESCRIBES the marker was the one document that could never be checked.
# `(?:(?!-->).)*` keeps the match inside one comment, so a comment that opens
# after an unrelated one on the same line cannot borrow its `-->`.
IGNORE_MARKER = re.compile(r"<!--(?:(?!-->).)*?doc-links:\s*ignore((?:(?!-->).)*)-->")
IGNORE_REASON = re.compile(r"\(([^)]*)\)")
# Cheap pre-filter for the tracked-file sweep: the bytes every marker contains.
MARKER_BYTES = b"doc-links: ignore"
# This checker and its tests OWN the marker and the path grammar: their
# occurrences are the implementation and its fixtures, never a suppression of
# a reference and never a citation.
SWEEP_EXCLUDE = frozenset(
    {
        "scripts/dev/check_doc_links.py",
        "scripts/dev/check_doc_links_test.py",
    }
)


def ignore_markers(line: str) -> list[str]:
    """The text between `ignore` and `-->` for every marker on `line`.

    Code spans are blanked first, so a backticked marker is read as the syntax
    EXAMPLE it is. `ai/INDEX.md` documents the marker on the same line as the
    paths it names, and without this that one line would suppress its own
    checks -- the failure the HTML-comment grammar exists to remove, rebuilt
    by writing the documentation for it.

    A backticked marker therefore excuses nothing and is audited by nothing,
    which is the fail-closed pairing: no suppression, so no exemption to read.
    """
    return [m.group(1) for m in IGNORE_MARKER.finditer(BACKTICK.sub(" ", line))]


def marker_reason(tail: str) -> str:
    """One marker's parenthesised reason, or `""` when it states none."""
    m = IGNORE_REASON.search(tail)
    return m.group(1).strip() if m else ""


def suppressed(line: str) -> bool:
    """True when `line` carries a marker that states a reason.

    An unreasoned marker excuses nothing. The reason is what makes the
    suppression auditable, so a marker without one is a finding (check 4)
    rather than a licence, and the references on its line stay checked.
    """
    return any(marker_reason(tail) for tail in ignore_markers(line))


# --- Check 3: dead hook and check names -------------------------------------
NAME_LINT_FILES = (
    "plan/learned/HOOK-FRICTION.md",
    "plan/learned/RECURRING-PATTERNS.md",
    "ai/rules/repo-maintenance.md",
)
# Every check these documents describe is a top-level def in one of these.
# Resolution reads `def` names, NEVER the `CHECKS` registry tuples: the guard
# behind `rfc-tagged-test` is `_rfc_tagged_change_err`, called from
# `c_test_weakening`, and appears in no tuple.
NAME_LINT_SOURCES = (
    ".claude/hooks/pretool-writeedit.py",
    ".claude/hooks/pretool-bash.py",
    ".claude/hooks/pretool-agent-skill.py",
    ".claude/hooks/posttool-writeedit.py",
    "scripts/dev/verify_wiring_docs.py",
)
SH_TOKEN = re.compile(r"([A-Za-z0-9][\w.-]*\.sh)\b")
CHECK_TOKEN = re.compile(r"\b((?:c_|check_)[a-z0-9_]+)\b")
HEADING = re.compile(r"^(#+)\s")
RETIRED_HEADING = re.compile(r"^#+\s*Retired\b", re.IGNORECASE)
# A cell that STARTS with the marker. A substring match anywhere in the row
# would let the word "retired" inside a prose cell excuse a live dead name.
RETIRED_CELL = re.compile(r"^(?:retired\b|fixed\b.*\bat the source\b)", re.IGNORECASE)
# ... and only in a cell entitled to say it: the row's own first cell, or the
# column its table's header calls Status. Anchoring alone was not enough. A
# prose cell reading "Retired elsewhere, but this is live" starts with the
# marker too, and excused every dead name in its row.
STATUS_HEADING = re.compile(r"^status\b", re.IGNORECASE)
TABLE_SEPARATOR = re.compile(r"^:?-{2,}:?$")


def expand_braces(token: str) -> list[str]:
    m = re.search(r"\{([^{}]+)\}", token)
    if not m or "," not in m.group(1):
        return [token]
    out = []
    for alt in m.group(1).split(","):
        out.extend(expand_braces(token[: m.start()] + alt + token[m.end() :]))
    return out


def candidate_paths(raw: str) -> list[str]:
    """Reduce a backtick span to concrete repo paths to verify ([] = skip)."""
    token = raw.strip().split()[0] if raw.strip() else ""
    token = token.rstrip(".,;:)('\"")
    token = token.split("#")[0]
    token = LINE_RUN_SUFFIX.sub("", token)
    token = LINE_SUFFIX.sub("", token)
    token = SYMBOL_COLON.sub("", token)
    if not os.path.exists(token):
        token = SYMBOL_DOT.sub("", token)
    if not token or "/" not in token and token not in ROOT_FILES:
        return []
    if any(m in token for m in PLACEHOLDER_MARKERS):
        return []
    if token.startswith(SKIP_PREFIXES):
        return []
    root = token.split("/")[0]
    if token not in ROOT_FILES and root not in KNOWN_ROOTS:
        return []
    return [
        t for t in expand_braces(token) if not any(m in t for m in PLACEHOLDER_MARKERS)
    ]


def path_resolves(path: str) -> bool:
    if "*" in path or "?" in path or "[" in path:
        return bool(globmod.glob(path))
    return os.path.exists(path.rstrip("/"))


def gitignored(paths: list[str]) -> set[str]:
    """Of `paths`, the ones git ignores (generated / local-state artifacts).

    One batched `git check-ignore --stdin` call, never one fork per path
    (ai/rules/commands.md). Exit status 1 means "none ignored", which is
    not an error here, so the call is unchecked.
    """
    if not paths:
        return set()
    proc = subprocess.run(
        ["git", "check-ignore", "--stdin"],
        input="\n".join(paths),
        capture_output=True,
        text=True,
        check=False,
    )
    return {line.strip() for line in proc.stdout.splitlines() if line.strip()}


def drop_generated(broken: list[tuple[str, str]]) -> list[str]:
    """Format the surviving failures, minus references to ignored paths."""
    ignored = gitignored([path for _, path in broken])
    return [
        f"{where}: {path}"
        for where, path in broken
        if path.rstrip("/") not in ignored and path not in ignored
    ]


def md_corpus_files() -> list[str]:
    """The files check 1 walks: `MD_GLOBS` expanded, minus `MD_EXCLUDE`.

    Check 5 skips this set. Check 1 already reports every dead reference in
    it, and it does so with no baseline to grandfather one.
    """
    files: list[str] = []
    for pattern in MD_GLOBS:
        files.extend(sorted(globmod.glob(pattern)))
    return [f for f in files if f not in MD_EXCLUDE]


def line_citations(line: str) -> list[str]:
    """Every repo path one line cites: backtick spans and markdown links.

    Checks 1 and 5 share this grammar, so a token one of them reads is a
    token the other reads.
    """
    out: list[str] = []
    for raw in BACKTICK.findall(line) + MD_LINK.findall(line):
        if raw.startswith(("http://", "https://", "mailto:")):
            continue
        out.extend(candidate_paths(raw))
    return out


def check_markdown(verbose: bool) -> list[tuple[str, str]]:
    errors = []
    for md in md_corpus_files():
        with open(md, encoding="utf-8") as fh:
            for lineno, line in enumerate(fh, 1):
                if suppressed(line):
                    continue
                for path in line_citations(line):
                    if not path_resolves(path):
                        errors.append((f"{md}:{lineno}: broken path reference", path))
                    elif verbose:
                        print(f"ok {md}:{lineno}: {path}")
    return errors


def go_files() -> list[str]:
    """Every tracked Go source, `_test.go` included.

    Test files were excluded until 2026-08-09, and `check_design_refs()` is the
    only caller, so the exclusion meant one thing: no `// Design:` pointer in a
    test was ever checked. 133 of them had died by then.
    """
    out = subprocess.run(
        ["git", "ls-files", "internal/", "cmd/", "pkg/", "scripts/", "*.go"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    return [f for f in out if f.endswith(".go")]


def check_design_refs(verbose: bool) -> list[tuple[str, str]]:
    errors = []
    for go in go_files():
        try:
            with open(go, encoding="utf-8") as fh:
                head = fh.read(4096)
        except OSError:
            continue
        if "Code generated" in head.split("\n", 3)[0]:
            continue
        for lineno, line in enumerate(head.splitlines(), 1):
            m = DESIGN.match(line)
            if not m:
                continue
            target = m.group(1).strip()
            if target.startswith("("):
                break
            target = target.split()[0].rstrip(".,;:")
            # Same-package anchors ("// Design: pipe.go") resolve relative
            # to the referencing file's own directory.
            if "/" not in target and not os.path.exists(target):
                target = os.path.join(os.path.dirname(go), target)
            if go.endswith("_test.go") and target.startswith(SPEC_PREFIX):
                # Existence is not enough in a test. Spec closure removes the
                # spec (ai/rules/planning.md, "Spec Closure"), so this pointer
                # dies on an unrelated author's commit. Non-test files keep the
                # plain existence check: 21 live spec pointers sit in them.
                errors.append(
                    (
                        (
                            f"{go}:{lineno}: a test must cite a durable "
                            "document, never a spec deleted at closure "
                            "(ai/rules/planning.md)"
                        ),
                        target,
                    )
                )
            elif not path_resolves(target):
                errors.append((f"{go}:{lineno}: broken Design reference", target))
            elif verbose:
                print(f"ok {go}:{lineno}: {target}")
            break
    return errors


def python_check_sources() -> list[str]:
    """Tracked Python under scripts/ and .claude/hooks/ -- where checks live."""
    out = subprocess.run(
        ["git", "ls-files", "scripts", ".claude/hooks"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    return [f for f in out if f.endswith(".py")]


def known_names() -> tuple[set[str], set[str], list[str]]:
    """(script basenames, check names, errors) the lint resolves against.

    A `c_*`/`check_*` reference resolves against every top-level `def`, and
    also against the module stem of a tracked check SOURCE: `check_doc_links.py`
    is matched by `CHECK_TOKEN`, never by `SH_TOKEN`, so a document naming a
    check's own file had no set to resolve against and read as dead. The stems
    come from `python_check_sources` alone, so naming an unrelated tracked
    script still fails.

    Names never resolve against the `CHECKS` registry tuples: a check can be
    reached through a helper that no tuple names. Sources are PARSED, never
    imported -- a doc check must not execute hook code.
    """
    errors: list[str] = []
    tracked = subprocess.run(
        ["git", "ls-files"], capture_output=True, text=True, check=True
    ).stdout.splitlines()
    scripts = {os.path.basename(f) for f in tracked if f.endswith((".sh", ".py"))}

    defs: set[str] = set()
    sources = python_check_sources()
    defs.update(os.path.basename(src)[: -len(".py")] for src in sources)
    for required in NAME_LINT_SOURCES:
        if required not in sources:
            # Fail closed: losing a source silently turns its live checks dead.
            errors.append(
                f"{required}: dead-name lint source is missing from the tree "
                f"-- restore it or update NAME_LINT_SOURCES in {__file__}"
            )
    for src in sources:
        try:
            with open(src, encoding="utf-8") as fh:
                tree = ast.parse(fh.read(), filename=src)
        except (OSError, SyntaxError) as err:
            errors.append(
                f"{src}: cannot parse for check names: {err} -- every name it "
                f"defines would read as dead until this parses"
            )
            continue
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                defs.add(node.name)
    return scripts, defs, errors


def _row_cells(line: str) -> list[str]:
    """A table row's cells, indexed so a header and its rows line up.

    Split on `|` and keep the empty edges, because index alignment between the
    header row and the body rows is the whole point: drop the leading empty on
    one and the Status column moves.
    """
    return [c.strip().strip("*_ ") for c in line.lstrip().split("|")]


def retired_lines(text: str) -> set[int]:
    """Line numbers excused from the dead-name lint.

    Two escapes, both narrow: a line under a `## Retired` heading (until the
    next heading at the same or a higher level), and a table row that says
    `Retired` or `Fixed ... at the source` IN A CELL ENTITLED TO SAY IT -- the
    row's first cell, or the column its header calls Status.

    Which cell it is matters. The two shapes in the corpus put the marker in
    different places: `| Hook | Appearances | Status | Entry |` carries it in the
    Status column, and `| Retired name | Live check | Dispatcher |` carries it in
    the first. Accepting it anywhere in the row covered both, and also let a
    description cell excuse the dead names beside it.
    """
    excused: set[int] = set()
    retired_depth = None
    lines = text.splitlines()
    status_col: int | None = None
    for lineno, line in enumerate(lines, 1):
        head = HEADING.match(line)
        if head:
            depth = len(head.group(1))
            if RETIRED_HEADING.match(line):
                retired_depth = depth
            elif retired_depth is not None and depth <= retired_depth:
                retired_depth = None
        if retired_depth is not None:
            excused.add(lineno)
            continue
        if not line.lstrip().startswith("|"):
            status_col = None  # the table ended; its header no longer applies
            continue
        cells = _row_cells(line)
        following = lines[lineno] if lineno < len(lines) else ""
        if following.lstrip().startswith("|") and all(
            TABLE_SEPARATOR.match(c) for c in _row_cells(following) if c
        ):
            # This row is a header: the next line is its `|---|---|` separator.
            status_col = next(
                (i for i, c in enumerate(cells) if STATUS_HEADING.match(c)), None
            )
        entitled = {1} | ({status_col} if status_col is not None else set())
        if any(
            RETIRED_CELL.match(cells[i])
            for i in entitled
            if i < len(cells) and cells[i]
        ):
            excused.add(lineno)
    return excused


def check_hook_names(
    files: tuple[str, ...] = NAME_LINT_FILES, verbose: bool = False
) -> list[str]:
    """Report `*.sh` and `c_*`/`check_*` names that name nothing in the tree."""
    present = [f for f in files if os.path.exists(f)]
    if not present:
        # Not the Ze corpus: nothing to lint, so no sources are needed either.
        # Presence in the real tree is asserted by
        # test_real_corpus_is_present_and_clean.
        return []
    scripts, defs, findings = known_names()
    for md in present:
        try:
            with open(md, encoding="utf-8") as fh:
                text = fh.read()
        except OSError as err:
            # Fail closed: an unreadable document is reported, never skipped.
            findings.append(f"{md}: cannot read for the dead-name lint: {err}")
            continue
        excused = retired_lines(text)
        for lineno, line in enumerate(text.splitlines(), 1):
            if suppressed(line):
                continue
            for span in BACKTICK.findall(line):
                dead = [t for t in SH_TOKEN.findall(span) if t not in scripts]
                dead += [t for t in CHECK_TOKEN.findall(span) if t not in defs]
                for token in dead:
                    if lineno in excused:
                        if verbose:
                            print(f"retired {md}:{lineno}: {token}")
                        continue
                    findings.append(
                        f"{md}:{lineno}: dead name reference: {token} -- names "
                        f"no tracked script, no check source file, and no "
                        f"check function under scripts/ or .claude/hooks/; "
                        f"correct it to the live name, or move the entry "
                        f"under '## Retired'"
                    )
    return findings


# --- Check 5: dead citations in every tracked file --------------------------
BASELINE_REL = "scripts/dev/doc_citation_baseline.txt"
# Two roots the citation check never reads, for one reason each.
# `vendor/` and `third_party/` hold another repository's files: their
# references point into their own upstream tree, so nobody here can repair one
# and the baseline could never shrink. `go_files` excludes vendor the same
# way, by naming the roots it walks.
# `plan/handover/` is a historical record: it describes the tree as it was,
# which is why check 1 skips it too (see the module docstring).
CITATION_EXCLUDE_PREFIXES = ("vendor/", "third_party/", "plan/handover/")
# How many new baseline pairs a growth failure names before it counts the rest.
BASELINE_GROWTH_SHOWN = 10


def parse_baseline(text: str) -> set[tuple[str, str]]:
    """The `citing file<TAB>target path` pairs `text` lists.

    Blank lines and `#` comments are skipped. A line with no TAB yields an
    empty target, which matches no citation and so grandfathers nothing.
    `baseline_format_problems` is what REPORTS such a line: a parser that
    silently drops it would leave a typo looking like a grandfathered pair.
    """
    pairs: set[tuple[str, str]] = set()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        citer, _, target = line.partition("\t")
        pairs.add((citer.strip(), target.strip()))
    return pairs


def load_baseline(path: str = BASELINE_REL) -> set[tuple[str, str]]:
    """The grandfathered pairs on disk. A missing file grandfathers nothing."""
    try:
        with open(path, encoding="utf-8") as fh:
            return parse_baseline(fh.read())
    except OSError:
        return set()


def head_baseline(path: str = BASELINE_REL) -> set[tuple[str, str]] | None:
    """The baseline as HEAD holds it, or `None` when HEAD holds no such file.

    `None` is the state of a first commit and of a fresh checkout with no
    history, and it passes: there is nothing to compare against yet.

    ONLY that state returns `None`, and `git cat-file -e` is what separates it
    from the rest. Reading `git show`'s exit status alone mapped EVERY failure
    to "nothing to compare against", which disarms the shrink-only ratchet and
    says nothing: a blob missing from a `--filter=blob:none` clone, a corrupt
    object, and a rename of `BASELINE_REL` all took that branch. A guard whose
    failure mode is silent approval is the one shape `ai/rules/evidence.md`
    refuses, so anything else raises and reds the gate.
    """
    absent = subprocess.run(
        ["git", "cat-file", "-e", f"HEAD:{path}"],
        capture_output=True,
        text=True,
        check=False,
    )
    if absent.returncode != 0:
        return None
    proc = subprocess.run(
        ["git", "show", f"HEAD:{path}"],
        capture_output=True,
        text=True,
        check=True,
    )
    return parse_baseline(proc.stdout)


def baseline_format_problems(path: str = BASELINE_REL) -> list[str]:
    """Report every baseline line that is not `citer<TAB>target`.

    A line with no TAB grandfathers nothing, so the citation it was written
    for is reported anyway. The author sees the citation they thought they had
    covered and no reason for it, which reads as a gate that ignores its own
    baseline. Naming the malformed line turns that into one obvious fix.
    """
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        return []
    problems = []
    for lineno, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "\t" not in stripped:
            problems.append(
                f"{path}:{lineno}: baseline line has no TAB: {stripped} -- "
                f"write it as `<citing file><TAB><target path>`, or delete it"
            )
    return problems


def check_baseline_growth(path: str = BASELINE_REL) -> list[str]:
    """Refuse a baseline pair that HEAD does not already hold.

    The baseline is shrink-only. Without this check `--write-baseline` is one
    command that absorbs every new dead citation, which is an escape from
    every other property this gate has.

    The comparison is over the PAIRS, not over their number. A count lets a
    swap through: repair one citation, add one dead citation, regenerate, and
    the total is unchanged while a pair the sweep failed on is grandfathered.
    """
    head = head_baseline(path)
    if head is None:
        return []
    added = sorted(load_baseline(path) - head)
    if not added:
        return []
    shown = added[:BASELINE_GROWTH_SHOWN]
    lines = [f"  {citer} -> {target}" for citer, target in shown]
    if len(added) > len(shown):
        lines.append(f"  ... and {len(added) - len(shown)} more")
    listing = "\n".join(lines)
    return [
        f"{path}: {len(added)} baseline pair(s) are new against HEAD -- the "
        f"baseline is shrink-only:\n{listing}\n"
        f"Repair each citation, or mark its line `<!-- doc-links: ignore (why "
        f"this path cannot resolve) -->`. Never regenerate the baseline to "
        f"absorb it"
    ]


def drop_ignored(dead: list[tuple[str, int, str]]) -> list[tuple[str, int, str]]:
    """`dead` minus the references to gitignored (generated) targets."""
    ignored = gitignored(sorted({target for _, _, target in dead}))
    return [
        (citer, lineno, target)
        for citer, lineno, target in dead
        if target.rstrip("/") not in ignored and target not in ignored
    ]


def baseline_findings(
    dead: list[tuple[str, int, str]],
    baseline: set[tuple[str, str]],
    verbose: bool = False,
    drift: bool = False,
) -> tuple[list[str], list[str]]:
    """(findings, drift warnings) for the sweep's dead citations.

    A pair the baseline lists is grandfathered. The baseline holds PAIRS, so a
    NEW file that cites an already-dead target is still reported.

    Drift is the reverse direction: a pair the baseline lists that the tree no
    longer holds. It is a WARN and it is asked for only after a whole-tree
    sweep, because a sweep over some of the files misses most pairs.
    """
    live = drop_ignored(dead)
    findings: list[str] = []
    for citer, lineno, target in live:
        if (citer, target) in baseline:
            if verbose:
                print(f"baselined {citer}:{lineno}: {target}")
            continue
        findings.append(
            f"{citer}:{lineno}: dead path reference: {target} -- repair the "
            f"reference, or mark the line `<!-- doc-links: ignore (why this "
            f"path cannot resolve) -->`"
        )
    if not drift:
        return findings, []
    seen = {(citer, target) for citer, _, target in live}
    stale = [
        f"WARN {BASELINE_REL}: {citer} no longer cites {target} -- delete the "
        f"entry, so the baseline shrinks"
        for citer, target in sorted(baseline - seen)
    ]
    return findings, stale


def write_baseline(path: str = BASELINE_REL) -> int:
    """Write today's dead citations as the grandfathered population."""
    _unreadable, _markers, dead = sweep_tracked(markers=False)
    pairs = sorted({(citer, target) for citer, _, target in drop_ignored(dead)})
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(BASELINE_HEADER + "".join(f"{c}\t{t}\n" for c, t in pairs))
    print(f"wrote {path} with {len(pairs)} grandfathered citation pair(s)")
    return 0


# The header `write_baseline` emits, and the ONE place its text lives. It sat
# inline in that function until 2026-08-10, when the shrink-only rule changed
# from a count to a set comparison: the file on disk was corrected by hand and
# the generator was not, so the next `--write-baseline` would have reverted the
# correction and restored a description that is now false.
# `test_baseline_header_is_what_the_generator_writes` compares the two.
BASELINE_HEADER = (
    "# Doc citation baseline: the dead path references this tree already\n"
    "# carried when check 5 of scripts/dev/check_doc_links.py was armed.\n"
    "#\n"
    "# One pair per line: the citing file, a TAB, and the target that does\n"
    "# not resolve. The gate skips a pair this file lists and reports every\n"
    "# other one. Pairs, never bare targets: a new file that cites an\n"
    "# already-dead target is reported, so the rot cannot spread.\n"
    "#\n"
    "# The list is SHRINK-ONLY. The gate compares it against its own\n"
    "# version at HEAD and fails on each pair HEAD does not hold. It\n"
    "# compares the SETS, so a repair and a new dead pair in one commit\n"
    "# is refused although the total did not move. Remove a pair by\n"
    "# repairing the citation, or by marking its line\n"
    "# `<!-- doc-links: ignore (why this path cannot resolve) -->`.\n"
    "#\n"
    "# Regenerate with: python3 scripts/dev/check_doc_links.py"
    " --write-baseline\n"
)


def tracked_files() -> list[str]:
    """Every tracked path the tracked-file sweep reads.

    A path git tracks but the working tree no longer holds is skipped, not
    reported: the sweep judges the working tree, and a file somebody is part
    way through deleting carries no marker to audit. Several sessions share
    this checkout, so a staged deletion is an ordinary state. The fail-closed
    branch below still owns a file that EXISTS and cannot be read.
    """
    out = subprocess.run(
        ["git", "ls-files"], capture_output=True, text=True, check=True
    ).stdout.splitlines()
    return [f for f in out if f and f not in SWEEP_EXCLUDE and os.path.exists(f)]


def sweep_tracked(
    files: tuple[str, ...] | None = None,
    verbose: bool = False,
    markers: bool = True,
    citations: bool = True,
) -> tuple[list[str], list[str], list[tuple[str, int, str]]]:
    """Read every tracked file ONCE and run checks 4 and 5 over each line.

    Returns three lists: the files that exist and cannot be read, the markers
    that state no reason, and the `(citing file, line, dead target)` triples.
    An unreadable file belongs to both checks, so it is reported once and
    every caller adds it.

    The sweep covers every TRACKED file, not the `MD_GLOBS` corpus. A marker
    outside that corpus suppresses nothing today, which is exactly why it is
    worth reading: nobody audits it, and the reference under it rots unseen.
    Scoping either check to the walked corpus leaves that hole open.

    Reading is a two-step: the raw bytes are searched for `MARKER_BYTES`
    first, so a binary or vendored file costs one read and no decode.
    """
    unreadable: list[str] = []
    marker_findings: list[str] = []
    dead: list[tuple[str, int, str]] = []
    corpus = set(md_corpus_files()) if citations else set()
    for path in tracked_files() if files is None else files:
        try:
            with open(path, "rb") as fh:
                raw = fh.read()
        except FileNotFoundError:
            # The file was listed and then deleted before this read. Several
            # sessions share this checkout and a spec closure deletes its spec
            # mid-run, so the window is real and hit twice on 2026-08-10. A
            # file that is GONE carries no marker to audit, which is the same
            # reason tracked_files skips a staged deletion.
            continue
        except OSError as err:
            # Fail closed: a file that EXISTS and cannot be read is a finding,
            # never a skip. A marker or a citation it carries would otherwise
            # pass by being unreadable.
            unreadable.append(
                f"{path}: cannot read for the tracked-file sweep: {err} -- "
                f"every marker and every path reference it carries would go "
                f"unchecked"
            )
            continue
        read_markers = markers and MARKER_BYTES in raw
        read_citations = (
            citations
            and path not in corpus
            and not path.startswith(CITATION_EXCLUDE_PREFIXES)
        )
        if not read_markers and not read_citations:
            continue
        for lineno, line in enumerate(
            raw.decode("utf-8", errors="replace").splitlines(), 1
        ):
            if read_markers:
                for tail in ignore_markers(line):
                    reason = marker_reason(tail)
                    if reason:
                        if verbose:
                            print(f"reasoned {path}:{lineno}: {reason}")
                        continue
                    marker_findings.append(
                        f"{path}:{lineno}: doc-links: ignore marker states no "
                        f"reason -- write it as `<!-- doc-links: ignore (why "
                        f"this path cannot resolve) -->`, or delete the marker "
                        f"and fix the reference it hides"
                    )
            if not read_citations or suppressed(line):
                continue
            for target in line_citations(line):
                if not path_resolves(target):
                    dead.append((path, lineno, target))
    return unreadable, marker_findings, dead


def check_ignore_reasons(
    files: tuple[str, ...] | None = None, verbose: bool = False
) -> list[str]:
    """Report every `doc-links: ignore` marker that states no reason."""
    unreadable, marker_findings, _ = sweep_tracked(
        files=files, verbose=verbose, citations=False
    )
    return unreadable + marker_findings


def check_tracked_citations(
    files: tuple[str, ...] | None = None,
    verbose: bool = False,
    baseline: set[tuple[str, str]] | None = None,
) -> list[str]:
    """Report every dead path reference the baseline does not grandfather."""
    unreadable, _, dead = sweep_tracked(files=files, verbose=verbose, markers=False)
    if baseline is None:
        baseline = load_baseline()
    return unreadable + baseline_findings(dead, baseline, verbose)[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--md-only", action="store_true")
    parser.add_argument("--design-only", action="store_true")
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="record today's dead citations as the grandfathered population",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    os.chdir(
        subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    )

    if args.write_baseline:
        return write_baseline()

    broken: list[tuple[str, str]] = []
    if not args.design_only:
        broken += check_markdown(args.verbose)
    if not args.md_only:
        broken += check_design_refs(args.verbose)
    errors = drop_generated(broken)

    baseline: set[tuple[str, str]] = set()
    stale: list[str] = []
    if not args.design_only:
        errors += check_hook_names(verbose=args.verbose)
        # Checks 4 and 5 read each tracked file once, together.
        unreadable, marker_findings, dead = sweep_tracked(verbose=args.verbose)
        baseline = load_baseline()
        found, stale = baseline_findings(dead, baseline, args.verbose, drift=True)
        errors += unreadable + marker_findings + found
        errors += baseline_format_problems()
        errors += check_baseline_growth()

    for warn in stale:
        print(warn)
    for err in errors:
        print(err)
    if errors:
        print(
            f"{len(errors)} broken reference(s) -- fix the reference, or mark "
            f"the line `<!-- doc-links: ignore (reason) -->`",
            file=sys.stderr,
        )
        return 1
    summary = "every path reference resolves"
    if baseline:
        summary += f" ({len(baseline)} citation pair(s) baselined"
        if stale:
            summary += f", {len(stale)} stale baseline entry(s)"
        summary += ")"
    print(summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
