#!/usr/bin/env python3
"""Reverse-dependency audit: find which components/plugins are import-independent.

Complements scripts/dev/arch_map.py (which lists the directories) by answering a
different question: for each top-level dir under an area, WHO imports it from
OUTSIDE its own subtree?

A directory is a "plugin candidate" when its only importers are registration
blank-imports (the generated composition root internal/component/plugin/all/all.go
and the cmd/ze dispatch files) plus tests. Nothing in the core or any sibling
calls into it directly -- it is reachable only through the registry, so it already
passes the "delete the folder" test (ai/rules/plugins.md) and could
live under internal/plugins/ unchanged. Directories WITH external importers are
genuine core/shared code (the daemon wires them, siblings call them).

This is a static text scan of import strings, so it is build-tag agnostic on
purpose: it sees linux-only importers that `go list` on darwin would miss. The
trade-off is it cannot tell a used import from a dead one -- it answers "who could
reference this", which is the right question for a "can this move" audit.

Usage:
    scripts/dev/dep_audit.py [AREA ...] [--json] [--candidates-only]   # report
    scripts/dev/dep_audit.py --check            # module-tier placement GATE
    scripts/dev/dep_audit.py --write-baseline   # (re)generate the engine baseline

    AREA defaults to the three registries:
        internal/component  internal/plugins  internal/component/bgp/plugins

Report exit code: 0 always.
Gate (--check) exit codes: 0 = compliant (or only baselined), 2 = a new misplaced
engine, stale baseline entry, illegal/unclassified non-engine placement, manifest
error, pluginDirs parse failure, or a new/stale internal/core upward import
(core import-direction gate, baseline: scripts/dev/core_import_baseline.txt).

Module-tier rule (see ai/rules/architecture.md): a config-driven engine
(`sdk.NewWithConn`) at a top-level subsystem MUST live in internal/component/ if a
feature depends on it, else in internal/plugins/. Nested sub-plugin namespaces
(from the generator's pluginDirs) are excluded. Non-engine packages that are not
decided by the existing plugin/component/core mechanics MUST be classified in
scripts/dev/tier_non_engine_categories.txt as framework, host-service,
domain-library, or planned-violation. The engine baseline remains transitional and
is NOT a permanent allowlist.
"""

import json
import os
import re
import subprocess
import sys
from collections import defaultdict

DEFAULT_AREAS = (
    "internal/component",
    "internal/plugins",
    "internal/component/bgp/plugins",
)


def repo_root() -> str:
    return subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


def module_path(root: str) -> str:
    with open(os.path.join(root, "go.mod"), encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("module "):
                return line.split(None, 1)[1].strip()
    raise SystemExit("go.mod: no module line found")


def is_registration_importer(rel: str) -> bool:
    """True for files that only blank-import for side-effect registration."""
    if rel.endswith("/all/all.go"):
        return True
    # Per-feature compile-out files generated next to all.go (all_<tag>.go,
    # //go:build <tag>) are the same registration composition root, just gated
    # behind a build tag. They MUST count as registration importers, or a gated
    # ENGINE's blank import moving from all.go into all_<tag>.go reads as a
    # feature dependency (spec-feature-gate-8: the routing protocols are the
    # first gated packages that are also sdk.NewWithConn engines).
    parent, _, base = rel.rpartition("/")
    if (
        parent.endswith("/plugin/all")
        and base.startswith("all_")
        and base.endswith(".go")
    ):
        return True
    if rel.startswith("cmd/ze/") and (
        "dispatch" in rel
        or rel.endswith("_imports.go")
        or re.search(r"/setup_features_[^/]+\.go$", rel)
    ):
        return True
    return False


def collect_edges(root: str, module: str) -> dict:
    """imported package import-path -> set of importer file paths (repo-relative)."""
    edges = defaultdict(set)
    imp_re = re.compile(r'"(' + re.escape(module) + r'/[^"]+)"')
    modcache_rel = os.path.join("gokrazy", "modcache")
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [
            d
            for d in dirs
            if d not in (".git", ".claude", "vendor", "tmp", "node_modules")
            # Skip the gokrazy module cache: it holds extracted copies of external
            # modules AND a self-copy of ze (github.com/ze-software/ze@vX/...),
            # regenerated by appliance builds. Auditing those duplicates the
            # working tree's already-baselined edges and is not first-party source.
            and os.path.relpath(os.path.join(dirpath, d), root) != modcache_rel
        ]
        for f in files:
            if not f.endswith(".go"):
                continue
            full = os.path.join(dirpath, f)
            rel = os.path.relpath(full, root)
            try:
                txt = open(full, encoding="utf-8", errors="ignore").read()
            except OSError:
                continue
            for m in imp_re.finditer(txt):
                edges[m.group(1)].add(rel)
    return edges


def classify(area: str, root: str, module: str, edges: dict, engines: set) -> list:
    base = module + "/" + area
    area_dir = os.path.join(root, area)
    out = []
    for top in sorted(os.listdir(area_dir)):
        if not os.path.isdir(os.path.join(area_dir, top)):
            continue
        subsystem = area + "/" + top
        pkg_prefix = base + "/" + top
        own_rel_prefix = os.path.join(area, top) + os.sep
        external, registration, tests = set(), set(), set()
        for imported, importers in edges.items():
            if imported != pkg_prefix and not imported.startswith(pkg_prefix + "/"):
                continue
            for imp in importers:
                if imp.startswith(own_rel_prefix):
                    continue  # inside its own subtree
                if imp.endswith("_test.go"):
                    tests.add(imp)
                elif is_registration_importer(imp):
                    registration.add(imp)
                else:
                    external.add(imp)
        # "wired" = blank-imported by a composition root (the generated all.go OR
        # cmd/ze dispatch), per is_registration_importer. This is the authoritative
        # "the build treats this subsystem as a plugin/command" signal -- it reuses
        # the generator's output (all.go) plus the dispatch root, instead of a
        # per-mechanism registration grep that mis-sends *-cmd dirs to core
        # (umbrella blocker B-1). It catches every shape: registry.Register,
        # RegisterRPCs, RegisterBackend, doctor checks, and *-cmd verb providers.
        is_registered = len(registration) > 0
        is_engine = subsystem in engines
        out.append(
            {
                "name": top,
                "external": sorted(external),
                "registration": sorted(registration),
                "tests": sorted(tests),
                "is_candidate": len(external) == 0,
                "is_registered": is_registered,
                "is_engine": is_engine,
                # a genuine internal/core candidate: a leaf nothing depends on that
                # no composition root wires and that is not a config-driven engine.
                "core_candidate": len(external) == 0
                and not is_registered
                and not is_engine,
            }
        )
    return out


# ---------------------------------------------------------------------------
# Disableable-feature direct-import audit (feature-gate compile-out)
# ---------------------------------------------------------------------------
#
# A compile-out-able feature (guarded by //go:build ze_<feature>) must be reached
# ONLY through build-tag-gated registration. A direct functional import from
# always-on (untagged) code pins the package into every binary, defeating the
# compile-out. This audit flags any non-test, out-of-tree file that imports a
# disableable package without the gating build tag.
#
# The disableable set is NOT hand-maintained here: it is loaded from the
# feature-gate manifest (feature-gates.txt), the single source of truth shared
# with the generator, the Makefile, and the test runner. Add a gate by adding
# one line to that file. See plan/spec-feature-gate-0-umbrella.md,
# ai/rules/plugins.md, and ai/rules/architecture.md.
FEATURE_GATES_MANIFEST = "feature-gates.txt"
GOLANGCI = ".golangci.yml"
# Non-feature build tags that legitimately appear in .golangci.yml build-tags
# alongside the per-feature gate tags (the lint build is ze_core + every gate).
GOLANGCI_BASE_TAGS = {"ze_core"}

# Trees that are NOT part of the production `ze` daemon and therefore cannot pin
# a disableable feature into it. The chaos orchestrator (internal/chaos/*) is the
# ze-chaos binary's code, reached from cmd/ze only under //go:build ze_chaos
# (cmd/ze/ze_chaos_run.go); ze-chaos is built `-tags ze_chaos` and always wants
# the feature it imports. Test-support packages (internal/test/*) are likewise
# not in the daemon. A direct, untagged import of a disableable feature from
# these trees is NOT a compile-out violation. cmd/ze is deliberately NOT listed:
# the gated service/seam files live there and MUST carry the build tag, so they
# stay in scope. Mirrors the engine gate's NON_FEATURE_PREFIXES rationale.
DISABLEABLE_NONPROD_PREFIXES = (
    "internal/chaos/",
    "internal/test/",
    # internal/perf is the ze-perf binary's benchmark harness, reached from
    # cmd/ze only under //go:build ze_perf; ze-perf is built with the feature it
    # measures forced on. scripts/ holds build-time tooling (codegen, doc and
    # grammar checkers) run with `go run`, never linked into ze -- several are
    # //go:build ignore. Neither tree can pin a disableable feature into the
    # daemon, so an untagged import from them is not a compile-out violation.
    "internal/perf/",
    "scripts/",
)


def load_feature_gates(root: str) -> dict:
    """Parse feature-gates.txt -> {gated-package: build-tag}.

    Lines are "<tag> <pkg>"; '#' comments and blanks are ignored. This is the
    DISABLEABLE map: the package each //go:build ze_<tag> guards.
    """
    path = os.path.join(root, FEATURE_GATES_MANIFEST)
    gates = {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 2:
                raise SystemExit(
                    f"{FEATURE_GATES_MANIFEST}: malformed line {line!r} "
                    "(want '<tag> <pkg>')"
                )
            tag, pkg = parts[0], parts[1]
            gates[pkg] = tag
    return gates


def _tag_required(constraint: str, tag: str) -> bool:
    """True if a //go:build constraint string positively requires tag."""
    if re.search(r"!\s*" + re.escape(tag) + r"\b", constraint):
        return False
    return re.search(r"\b" + re.escape(tag) + r"\b", constraint) is not None


def file_requires_tag(root: str, rel: str, tag: str) -> bool:
    """True if file rel carries a //go:build constraint requiring tag."""
    try:
        txt = open(os.path.join(root, rel), encoding="utf-8", errors="ignore").read()
    except OSError:
        return False
    for line in txt.splitlines():
        s = line.strip()
        if s.startswith("//go:build"):
            return _tag_required(s[len("//go:build") :], tag)
        if s and not s.startswith("//"):
            return False  # reached code before any build constraint
    return False


def _same_feature_importer(imp: str, tag: str, disableable: dict) -> bool:
    """True if file imp lives inside ANY package gated by the same tag.

    Such an importer belongs to the same feature: it is dropped together with the
    imported package when the tag is off, so it cannot pin that package into a
    no-tag build (it is not an always-on pin). This generalises the old
    own-subtree skip to multi-package features -- a routing protocol's engine,
    transport, and cli sub-packages all share one tag and freely import each
    other (spec-feature-gate-8). The gate still independently verifies each gated
    package has no truly always-on (untagged, cross-feature) importer.
    """
    for other_pkg, other_tag in disableable.items():
        if other_tag == tag and (imp == other_pkg or imp.startswith(other_pkg + "/")):
            return True
    return False


def disableable_violations(
    root: str, module: str, edges: dict, disableable=None
) -> list:
    """Always-on files that directly import a disableable feature package."""
    if disableable is None:
        disableable = load_feature_gates(root)
    out = []
    for pkg, tag in sorted(disableable.items()):
        import_path = module + "/" + pkg
        for imp in sorted(edges.get(import_path, ())):
            if _same_feature_importer(imp, tag, disableable):
                continue  # same feature (same tag) -- dropped together, not a pin
            if imp.endswith("_test.go"):
                continue  # tests may import the package directly
            if any(imp.startswith(p) for p in DISABLEABLE_NONPROD_PREFIXES):
                continue  # not in the production ze daemon (ze-chaos / test support)
            if not file_requires_tag(root, imp, tag):
                out.append((imp, pkg, tag))
    return out


def disableable_gate(root: str, module: str, edges: dict) -> int:
    viol = disableable_violations(root, module, edges)
    if not viol:
        return 0
    print(
        "FAIL: disableable feature(s) imported by always-on code -- breaks compile-out:",
        file=sys.stderr,
    )
    for imp, pkg, tag in viol:
        print(f"  {imp} imports {pkg} without //go:build {tag}", file=sys.stderr)
    print(
        "  Rule: a compile-out-able feature is reached ONLY via build-tag-gated "
        "registration (ai/rules/architecture.md). Gate the importer with "
        "//go:build <tag> or route it through the service construction registry.",
        file=sys.stderr,
    )
    return 2


def parse_golangci_build_tags(root: str) -> set:
    """Read the `build-tags:` list from .golangci.yml (no YAML dependency).

    Captures the `- <tag>` items under the `build-tags:` key and stops at the
    next non-list line, mirroring the file's simple two-space-indented layout.
    """
    path = os.path.join(root, GOLANGCI)
    tags = set()
    capturing = False
    item_re = re.compile(r"^\s*-\s*(\S+)\s*$")
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            # Strip any inline "# ..." comment (YAML allows them); build tags are
            # Go identifiers and never contain '#', so this is lossless.
            line = raw.split("#", 1)[0]
            if re.match(r"^\s*build-tags:\s*$", line):
                capturing = True
                continue
            if not capturing:
                continue
            m = item_re.match(line)
            if m:
                tags.add(m.group(1))
                continue
            if line.strip() == "":
                continue  # blank or comment-only line inside the list
            break  # reached the next key; the build-tags list is done
    return tags


def golangci_drift_gate(root: str) -> int:
    """.golangci.yml build-tags is static YAML (it cannot read the manifest), so
    this catches drift: its feature tags MUST equal the manifest's gate tags.

    This is the one consumer that does not derive automatically; every other
    consumer reads feature-gates.txt directly. Keeping the lint build's tag set
    in lock-step ensures the //go:build ze_<feature> files get lint coverage.
    """
    manifest_tags = set(load_feature_gates(root).values())
    golangci_tags = parse_golangci_build_tags(root)
    golangci_features = golangci_tags - GOLANGCI_BASE_TAGS
    if golangci_features == manifest_tags:
        return 0
    missing = manifest_tags - golangci_features
    extra = golangci_features - manifest_tags
    print(
        f"FAIL: {GOLANGCI} build-tags drifted from {FEATURE_GATES_MANIFEST}:",
        file=sys.stderr,
    )
    if missing:
        print(f"  add to {GOLANGCI} build-tags: {sorted(missing)}", file=sys.stderr)
    if extra:
        print(
            f"  remove from {GOLANGCI} build-tags (no such gate): {sorted(extra)}",
            file=sys.stderr,
        )
    print(
        f"  build-tags must be {sorted(GOLANGCI_BASE_TAGS)} + every gate tag in "
        f"{FEATURE_GATES_MANIFEST}.",
        file=sys.stderr,
    )
    return 2


# ---------------------------------------------------------------------------
# Path C engine-placement gate
# ---------------------------------------------------------------------------

GENERATOR = "scripts/codegen/plugin_imports.go"
BASELINE = "scripts/dev/tier_migration_baseline.txt"
NON_ENGINE_CATEGORIES = "scripts/dev/tier_non_engine_categories.txt"
LEGAL_NON_ENGINE_CATEGORIES = {
    "framework",
    "host-service",
    "domain-library",
    "planned-violation",
}
DOMAIN_LIBRARY_PREFIXES = (
    "internal/component/l2tp",
    "internal/component/ike",
)
NON_FEATURE_PREFIXES = (
    "cmd/ze/",
    "internal/core/",
    "internal/chaos/",
    "internal/test/",
)


def _parse_string_list(root: str, name: str) -> list:
    path = os.path.join(root, GENERATOR)
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(rf"var {name} = \[\]string\{{(.*?)\}}", text, re.DOTALL)
    if not m:
        return []
    return re.findall(r'"([^"]+)"', m.group(1))


def parse_plugin_dirs(root: str) -> list:
    """Read plugin search roots from the generator.

    The generator is the authority on where plugins (incl. nested sub-plugin
    namespaces) legitimately live. Parsing it keeps the gate consistent with the
    composition root instead of duplicating a guess (umbrella blocker B-1).
    """
    roots = list(_parse_string_list(root, "pluginDirs"))
    seen = set(roots)
    for domain in _parse_string_list(root, "nestedPluginDomains"):
        rel = f"internal/component/{domain}/plugins"
        if rel not in seen:
            roots.append(rel)
            seen.add(rel)
    return roots


def nested_namespaces(plugin_dirs: list) -> list:
    """Sub-plugin registries nested under a component (e.g. bgp/plugins).

    These are pluginDirs entries under internal/component/ that are deeper than a
    top-level subsystem (>= 4 path segments). Engine packages inside them are
    sub-plugins of their host and are correctly placed, so the tier check skips
    them.
    """
    return [
        pd
        for pd in plugin_dirs
        if pd.startswith("internal/component/") and pd.count("/") >= 3
    ]


def find_engine_dirs(root: str, nested_ns: list) -> list:
    """Repo-relative dirs (under the two areas) whose non-test code calls
    sdk.NewWithConn, excluding anything inside a nested sub-plugin namespace."""
    engines = []
    for area in ("internal/component", "internal/plugins"):
        area_abs = os.path.join(root, area)
        for dirpath, dirs, files in os.walk(area_abs):
            dirs[:] = [d for d in dirs if d not in (".git", "vendor", "tmp")]
            rel = os.path.relpath(dirpath, root)
            if any(rel == ns or rel.startswith(ns + os.sep) for ns in nested_ns):
                continue
            for f in files:
                if not f.endswith(".go") or f.endswith("_test.go"):
                    continue
                try:
                    txt = open(os.path.join(dirpath, f), errors="ignore").read()
                except OSError:
                    continue
                if "sdk.NewWithConn(" in txt:
                    engines.append(rel)
                    break
    return sorted(engines)


def top_subsystem(rel: str) -> str:
    """Map any package path under the two areas to its top-level subsystem dir,
    e.g. internal/component/ike/engine -> internal/component/ike, and
    internal/plugins/log/cmd -> internal/plugins/log."""
    return "/".join(rel.split("/")[:3])


def engine_subsystems(root: str) -> set:
    """Top-level subsystems containing an sdk.NewWithConn engine (nested sub-plugin
    namespaces from the generator's pluginDirs excluded), used only to LABEL the
    advisory tiers -- the enforced gate uses find_engine_dirs directly."""
    plugin_dirs = parse_plugin_dirs(root)
    nested_ns = nested_namespaces(plugin_dirs)
    return {top_subsystem(e) for e in find_engine_dirs(root, nested_ns)}


def engine_depended(engine_rel: str, module: str, edges: dict) -> bool:
    """True if a feature (another component/plugins package) imports the engine
    package's own subtree. Excludes the engine's own subtree, tests, the generated
    composition root, cmd/ze dispatch, and non-feature trees (core/chaos/test)."""
    pkg = module + "/" + engine_rel
    own = engine_rel + os.sep
    for imported, importers in edges.items():
        if imported != pkg and not imported.startswith(pkg + "/"):
            continue
        for imp in importers:
            if imp.startswith(own) or imp.endswith("_test.go"):
                continue
            if is_registration_importer(imp):
                continue
            if any(imp.startswith(p) for p in NON_FEATURE_PREFIXES):
                continue
            if imp.startswith("internal/component/") or imp.startswith(
                "internal/plugins/"
            ):
                return True
    return False


def engine_misplacements(root: str, module: str, edges: dict) -> dict:
    """dir -> expected_area for every misplaced engine (Path C). Raises on a failed
    pluginDirs parse so the gate fails loud rather than flagging everything."""
    plugin_dirs = parse_plugin_dirs(root)
    if not plugin_dirs:
        raise SystemExit(
            f"{GENERATOR}: could not parse pluginDirs -- gate cannot run safely"
        )
    nested_ns = nested_namespaces(plugin_dirs)
    out = {}
    for eng in find_engine_dirs(root, nested_ns):
        area = (
            "internal/component"
            if eng.startswith("internal/component/")
            else "internal/plugins"
        )
        expected = (
            "internal/component"
            if engine_depended(eng, module, edges)
            else "internal/plugins"
        )
        if expected != area:
            out[eng] = expected
    return out


def read_baseline(root: str) -> set:
    path = os.path.join(root, BASELINE)
    if not os.path.exists(path):
        return set()
    keys = set()
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        keys.add(line.split()[0])
    return keys


def write_baseline(root: str, mis: dict) -> None:
    lines = [
        "# Tier migration baseline -- TRANSITIONAL, not a permanent allowlist.",
        "# Each row is a misplaced engine scheduled to move; the gate FAILS on a NEW",
        "# misplacement and on a STALE entry (one no longer misplaced). An empty file",
        "# means full engine-placement enforcement with zero exceptions.",
        "# See ai/rules/architecture.md and plan/spec-tiers-0-umbrella.md.",
        "# columns: <current-dir>\\t<expected-area>\\t<resolving-child-spec>",
    ]
    for eng in sorted(mis):
        spec = "spec-tiers-2" if mis[eng].endswith("plugins") else "spec-tiers-3"
        lines.append(f"{eng}\t{mis[eng]}\t{spec}")
    out = os.path.join(root, BASELINE)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def load_non_engine_categories(root: str) -> tuple[dict, list]:
    """Parse tier_non_engine_categories.txt.

    Rows are repo-relative package dirs plus a category and free-form rationale:
        internal/component/host  host-service  host APIs + doctor registration

    The manifest is the human-readable source of truth for intentional non-engine
    placements outside the purely mechanical plugin/component/core rules.
    """
    path = os.path.join(root, NON_ENGINE_CATEGORIES)
    rows = {}
    errors = []
    if not os.path.exists(path):
        return rows, [f"{NON_ENGINE_CATEGORIES}: missing non-engine category manifest"]
    for lineno, line in enumerate(open(path, encoding="utf-8"), 1):
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split(None, 2)
        if len(parts) != 3 or not parts[2].strip():
            errors.append(
                f"{NON_ENGINE_CATEGORIES}:{lineno}: expected '<path> <category> <rationale>'"
            )
            continue
        rel, category, rationale = parts[0], parts[1], parts[2].strip()
        if rel in rows:
            errors.append(f"{NON_ENGINE_CATEGORIES}:{lineno}: duplicate row for {rel}")
            continue
        if category not in LEGAL_NON_ENGINE_CATEGORIES:
            cats = ", ".join(sorted(LEGAL_NON_ENGINE_CATEGORIES))
            errors.append(
                f"{NON_ENGINE_CATEGORIES}:{lineno}: unknown category {category!r}; expected one of {cats}"
            )
            continue
        if category == "planned-violation" and not re.search(
            r"\bspec-[A-Za-z0-9][A-Za-z0-9_.-]*\b", rationale
        ):
            errors.append(
                f"{NON_ENGINE_CATEGORIES}:{lineno}: planned-violation rationale must cite a spec-* reference"
            )
            continue
        rows[rel] = {
            "category": category,
            "rationale": rationale,
            "line": lineno,
        }
    return rows, errors


def non_engine_manifest_required(row: dict) -> bool:
    """True when mechanics cannot classify this non-engine placement alone."""
    if row["is_engine"] or row["is_registered"]:
        return False
    return True


def non_engine_area(rel: str) -> str | None:
    if rel.startswith("internal/component/"):
        return "internal/component"
    if rel.startswith("internal/plugins/"):
        return "internal/plugins"
    return None


def _under(rel: str, prefix: str) -> bool:
    return rel == prefix or rel.startswith(prefix + "/")


def _setup_feature_registration(importer: str) -> bool:
    return importer.startswith("cmd/ze/") and bool(
        re.search(r"/setup_features_[^/]+\.go$", importer)
    )


def valid_non_engine_category(rel: str, category: str, row: dict) -> tuple[bool, str]:
    if category == "framework":
        if rel.startswith("internal/component/"):
            return True, ""
        if rel.startswith("internal/plugins/") and any(
            _setup_feature_registration(imp) for imp in row["registration"]
        ):
            return True, ""
        return (
            False,
            "framework rows under internal/plugins must be setup-feature registrations",
        )
    if category == "host-service":
        if rel.startswith("internal/component/"):
            return True, ""
        return False, "host-service rows are allowed only under internal/component"
    if category == "domain-library":
        if any(_under(rel, prefix) for prefix in DOMAIN_LIBRARY_PREFIXES):
            return True, ""
        allowed = ", ".join(DOMAIN_LIBRARY_PREFIXES)
        return False, f"domain-library rows are allowed only under {allowed}"
    if category == "planned-violation":
        if rel.startswith("internal/component/") or rel.startswith("internal/plugins/"):
            return True, ""
        return (
            False,
            "planned-violation rows are allowed only under internal/component or internal/plugins",
        )
    return False, f"unknown category {category!r}"


def classify_rel(rel: str, module: str, edges: dict, engine_dirs: set) -> dict:
    pkg_prefix = module + "/" + rel
    own_rel_prefix = rel + os.sep
    external, registration, tests = set(), set(), set()
    for imported, importers in edges.items():
        if imported != pkg_prefix and not imported.startswith(pkg_prefix + "/"):
            continue
        for imp in importers:
            if imp.startswith(own_rel_prefix):
                continue
            if imp.endswith("_test.go"):
                tests.add(imp)
            elif is_registration_importer(imp):
                registration.add(imp)
            else:
                external.add(imp)
    is_registered = len(registration) > 0
    is_engine = rel in engine_dirs
    return {
        "external": sorted(external),
        "registration": sorted(registration),
        "tests": sorted(tests),
        "is_registered": is_registered,
        "is_engine": is_engine,
        "core_candidate": len(external) == 0 and not is_registered and not is_engine,
    }


def non_engine_category_errors(root: str, module: str, edges: dict) -> list:
    manifest, errors = load_non_engine_categories(root)
    plugin_dirs = parse_plugin_dirs(root)
    nested_ns = nested_namespaces(plugin_dirs)
    engine_dirs = set(find_engine_dirs(root, nested_ns))
    engines = {top_subsystem(e) for e in engine_dirs}
    audited = {}
    for area in ("internal/component", "internal/plugins"):
        for row in classify(area, root, module, edges, engines):
            audited[f"{area}/{row['name']}"] = (area, row)

    for rel, meta in sorted(manifest.items()):
        area = non_engine_area(rel)
        if area is None:
            errors.append(
                f"{NON_ENGINE_CATEGORIES}:{meta['line']}: {rel} is outside internal/component or internal/plugins"
            )
            continue
        if not os.path.isdir(os.path.join(root, rel)):
            errors.append(
                f"{NON_ENGINE_CATEGORIES}:{meta['line']}: {rel} does not exist"
            )
            continue
        row = (
            audited[rel][1]
            if rel in audited
            else classify_rel(rel, module, edges, engine_dirs)
        )
        category = meta["category"]
        if row["is_engine"]:
            errors.append(
                f"{NON_ENGINE_CATEGORIES}:{meta['line']}: {rel} is an engine; engine placement is mechanical, not a non-engine category"
            )
        ok, reason = valid_non_engine_category(rel, category, row)
        if not ok:
            errors.append(
                f"{NON_ENGINE_CATEGORIES}:{meta['line']}: {rel} uses category {category!r}: {reason}"
            )

    for rel, (_, row) in sorted(audited.items()):
        if non_engine_manifest_required(row) and rel not in manifest:
            errors.append(
                f"{rel}: unclassified non-engine placement; add a {NON_ENGINE_CATEGORIES} row or move it to the mechanical tier"
            )
    return errors


def non_engine_category_gate(root: str, module: str, edges: dict) -> int:
    errors = non_engine_category_errors(root, module, edges)
    if errors:
        print("FAIL: non-engine tier category manifest mismatch:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        print(
            "  Rule: ai/rules/architecture.md (non-engine categories are manifest-backed).",
            file=sys.stderr,
        )
        return 2
    manifest, _ = load_non_engine_categories(root)
    print(
        f"OK: non-engine placement categories clean; {len(manifest)} manifest row(s)."
    )
    return 0


# ---------------------------------------------------------------------------
# Core import-direction gate (internal/core must not import upward)
# ---------------------------------------------------------------------------
#
# internal/core is the leaf library tier (ai/rules/architecture.md): it may not
# import internal/component or internal/plugins. The grandfathered violations
# live in a shrink-only baseline at PAIR granularity (importer file + imported
# package), each row annotated with its fix route, so a fixed pair left behind
# is a stale-entry failure and a NEW upward import in an already-baselined file
# is still caught. See plan/spec-layout-0-umbrella.md (child 2).

CORE_IMPORT_BASELINE = "scripts/dev/core_import_baseline.txt"
CORE_AREA_PREFIX = "internal/core/"
CORE_FORBIDDEN = ("internal/component", "internal/plugins")
CORE_FIX_ROUTES = ("hand-fixable", "generator-fixable", "needs-design")


def core_direction_violations(root: str, module: str, edges: dict) -> set:
    """(importer-file, imported-package) pairs where internal/core imports a
    package under internal/component or internal/plugins. Test files count:
    the grandfathered set includes internal/core/ipc/yang_test.go."""
    out = set()
    bases = tuple(module + "/" + p for p in CORE_FORBIDDEN)
    for imported, importers in edges.items():
        if not any(imported == b or imported.startswith(b + "/") for b in bases):
            continue
        rel = imported[len(module) + 1 :]
        for imp in importers:
            if imp.startswith(CORE_AREA_PREFIX):
                out.add((imp, rel))
    return out


def read_core_import_baseline(root: str) -> tuple[set, list]:
    """Parse the shrink-only baseline: '<core-file> <imported-package>
    <fix-route>: <rationale>' rows. Returns (pairs, errors); an illegal fix
    route is an error so nothing can be baselined without a named route."""
    path = os.path.join(root, CORE_IMPORT_BASELINE)
    pairs, errors = set(), []
    if not os.path.exists(path):
        return pairs, errors
    for lineno, line in enumerate(open(path, encoding="utf-8"), 1):
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split(None, 2)
        if len(parts) != 3:
            errors.append(
                f"{CORE_IMPORT_BASELINE}:{lineno}: expected "
                "'<core-file> <imported-package> <fix-route>: <rationale>'"
            )
            continue
        route = parts[2].split(":", 1)[0].strip()
        if route not in CORE_FIX_ROUTES:
            errors.append(
                f"{CORE_IMPORT_BASELINE}:{lineno}: fix route {route!r} "
                f"not one of {sorted(CORE_FIX_ROUTES)}"
            )
            continue
        pairs.add((parts[0], parts[1]))
    return pairs, errors


def core_direction_gate(root: str, module: str, edges: dict) -> int:
    current = core_direction_violations(root, module, edges)
    baseline, errors = read_core_import_baseline(root)
    if errors:
        print(f"FAIL: {CORE_IMPORT_BASELINE} malformed:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return 2
    new = current - baseline
    stale = baseline - current
    if new:
        print(
            "FAIL: new upward import(s) from internal/core -- wrong direction:",
            file=sys.stderr,
        )
        for imp, pkg in sorted(new):
            print(f"  {imp} imports {pkg}", file=sys.stderr)
        print(
            "  Rule: internal/core is the leaf tier and imports neither "
            "internal/component nor internal/plugins (ai/rules/architecture.md).",
            file=sys.stderr,
        )
        print(
            f"  A deliberate, spec-referenced exception goes in {CORE_IMPORT_BASELINE} "
            "with a fix route (hand-fixable / generator-fixable / needs-design).",
            file=sys.stderr,
        )
    if stale:
        print(
            "FAIL: stale core-import baseline row(s) -- the upward import is "
            f"gone, remove from {CORE_IMPORT_BASELINE}:",
            file=sys.stderr,
        )
        for imp, pkg in sorted(stale):
            print(f"  {imp} imports {pkg}", file=sys.stderr)
    if new or stale:
        return 2
    if current:
        files = sorted({imp for imp, _ in current})
        print(
            f"OK: core import direction clean; {len(current)} pair(s) in "
            f"{len(files)} file(s) baselined (pending fix)."
        )
    else:
        print("OK: core import direction clean; no exceptions (baseline empty).")
    return 0


def run_gate(root: str, module: str, edges: dict) -> int:
    """Combined --check gate: engine placement, non-engine category manifest,
    core import direction, disableable imports, and .golangci.yml manifest
    drift."""
    engine_rc = engine_placement_gate(root, module, edges)
    non_engine_rc = non_engine_category_gate(root, module, edges)
    core_rc = core_direction_gate(root, module, edges)
    dis_rc = disableable_gate(root, module, edges)
    golangci_rc = golangci_drift_gate(root)
    return engine_rc or non_engine_rc or core_rc or dis_rc or golangci_rc


def engine_placement_gate(root: str, module: str, edges: dict) -> int:
    mis = engine_misplacements(root, module, edges)
    baseline = read_baseline(root)
    current = set(mis)
    new = current - baseline
    stale = baseline - current

    if new:
        print("FAIL: new misplaced engine(s) -- wrong module tier:", file=sys.stderr)
        for eng in sorted(new):
            print(f"  {eng}  must move to {mis[eng]}/", file=sys.stderr)
        print(
            "  Rule: ai/rules/architecture.md (engine -> component if a feature "
            "depends on it, else plugins).",
            file=sys.stderr,
        )
        print(
            f"  If this is an intentional, scheduled move, add it to {BASELINE}.",
            file=sys.stderr,
        )
    if stale:
        print(
            "FAIL: stale baseline entry(ies) -- no longer misplaced, remove from "
            f"{BASELINE}:",
            file=sys.stderr,
        )
        for eng in sorted(stale):
            print(f"  {eng}", file=sys.stderr)
    if new or stale:
        return 2

    if current:
        print(
            f"OK: engine placement clean; {len(current)} engine(s) baselined "
            "(pending migration):"
        )
        for eng in sorted(current):
            print(f"  {eng} -> {mis[eng]}/")
    else:
        print("OK: engine placement clean; no exceptions (baseline empty).")
    print(
        "advisory: engine placement is mechanical; intentional non-engine "
        f"framework/host/domain placements are declared in {NON_ENGINE_CATEGORIES}."
    )
    return 0


def _quiet_gate(root: str, module: str, edges: dict) -> int:
    import contextlib
    import io

    with (
        contextlib.redirect_stdout(io.StringIO()),
        contextlib.redirect_stderr(io.StringIO()),
    ):
        return run_gate(root, module, edges)


def selftest() -> int:
    """Isolated fixture tests for the Path C gate -- no repo mutation.

    Mirrors the `--selftest` convention of scripts/dev/audit-test-relaxation.py.
    """
    import tempfile

    def w(root: str, rel: str, content: str) -> None:
        p = os.path.join(root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(content)

    with tempfile.TemporaryDirectory() as root:
        mod = "example.com/m"
        w(root, "go.mod", f"module {mod}\n")
        w(
            root,
            "scripts/codegen/plugin_imports.go",
            "var pluginDirs = []string{\n"
            '\t"internal/component/host/plugins",\n'
            '\t"internal/plugins",\n}\n',
        )
        # edge engine in component, nothing depends on it -> belongs in plugins
        w(
            root,
            "internal/component/edgeproto/r.go",
            "package edgeproto\nfunc R(){ sdk.NewWithConn() }\n",
        )
        # platform engine in component, a feature depends on it -> correct
        w(
            root,
            "internal/component/platform/r.go",
            f'package platform\nimport _ "{mod}/internal/plugins/platformx"\nfunc R(){{ sdk.NewWithConn() }}\n',
        )
        w(
            root,
            "internal/plugins/consumer/r.go",
            f'package consumer\nimport _ "{mod}/internal/component/platform"\n',
        )
        # nested sub-plugin engine -> excluded by pluginDirs
        w(
            root,
            "internal/component/host/plugins/sub/r.go",
            "package sub\nfunc R(){ sdk.NewWithConn() }\n",
        )
        # edge engine already in plugins -> correct
        w(
            root,
            "internal/plugins/edge1/r.go",
            "package edge1\nfunc R(){ sdk.NewWithConn() }\n",
        )
        # platform engine stuck in plugins (a feature depends on it) -> belongs in component
        w(
            root,
            "internal/plugins/platformx/r.go",
            "package platformx\nfunc R(){ sdk.NewWithConn() }\n",
        )
        # --- classify / B-1 fixtures: "wired" via a composition root, not an engine ---
        # command plugin wired ONLY via cmd/ze dispatch (the *-cmd shape the all.go-only
        # signal used to mis-send to core) -> must classify as a registered plugin.
        w(root, "internal/plugins/cmdverb/r.go", "package cmdverb\n")
        w(
            root,
            "cmd/ze/ze_core_dispatch.go",
            f'package main\nimport _ "{mod}/internal/plugins/cmdverb"\n',
        )
        # plugin wired via the generated composition root (all.go) -> registered plugin.
        w(root, "internal/plugins/genverb/r.go", "package genverb\n")
        w(
            root,
            "internal/component/plugin/all/all.go",
            f'package all\nimport _ "{mod}/internal/plugins/genverb"\n',
        )
        # genuine leaf: no composition root wires it, nothing imports it, not an engine.
        w(root, "internal/plugins/leaflib/lib.go", "package leaflib\n")
        # shared library: a feature imports it -> has an external importer (not a candidate).
        w(root, "internal/plugins/sharedlib/lib.go", "package sharedlib\n")
        w(
            root,
            "internal/plugins/edge1/use.go",
            f'package edge1\nimport _ "{mod}/internal/plugins/sharedlib"\n',
        )
        # setup feature packages are wired by cmd/ze/setup_features_*.go. They
        # must classify as registered, not shared libraries.
        w(root, "internal/plugins/setupcmd/r.go", "package setupcmd\n")
        w(
            root,
            "cmd/ze/setup_features_distro.go",
            f'package main\nimport _ "{mod}/internal/plugins/setupcmd"\n',
        )
        # non-engine category-manifest fixtures.
        w(root, "internal/component/frameworklib/lib.go", "package frameworklib\n")
        w(root, "internal/component/hostsvc/lib.go", "package hostsvc\n")
        w(root, "internal/component/l2tp/lib.go", "package l2tp\n")
        w(root, "internal/plugins/oldleaf/lib.go", "package oldleaf\n")
        w(root, "internal/component/unclassified/lib.go", "package unclassified\n")

        edges = collect_edges(root, mod)
        mis = engine_misplacements(root, mod, edges)
        expect = {
            "internal/component/edgeproto": "internal/plugins",
            "internal/plugins/platformx": "internal/component",
        }
        assert mis == expect, f"misplacements {mis} != {expect}"
        assert "internal/component/host/plugins/sub" not in mis, (
            "nested sub-plugin not excluded"
        )
        assert "internal/component/platform" not in mis, (
            "depended component engine wrongly flagged"
        )
        assert "internal/plugins/edge1" not in mis, "edge plugin wrongly flagged"

        # --- classify / B-1: wired-vs-core determination from composition roots ---
        engines = engine_subsystems(root)
        rows = {
            r["name"]: r
            for r in classify("internal/plugins", root, mod, edges, engines)
        }
        assert rows["cmdverb"]["is_registered"], (
            "dispatch-wired *-cmd not seen as wired"
        )
        assert not rows["cmdverb"]["core_candidate"], (
            "wired *-cmd mis-sent to core (B-1)"
        )
        assert rows["genverb"]["is_registered"], "all.go-wired plugin not seen as wired"
        assert rows["setupcmd"]["is_registered"], (
            "setup_features_*.go-wired plugin not seen as wired"
        )
        assert not rows["setupcmd"]["core_candidate"], (
            "setup_features_*.go-wired plugin mis-sent to core"
        )
        assert not rows["genverb"]["core_candidate"], (
            "all.go-wired plugin mis-sent to core"
        )
        assert rows["leaflib"]["core_candidate"], "genuine leaf not a core candidate"
        assert not rows["leaflib"]["is_registered"], (
            "unwired leaf wrongly seen as wired"
        )
        assert not rows["sharedlib"]["core_candidate"], (
            "depended lib wrongly a core candidate"
        )
        assert rows["sharedlib"]["external"], (
            "shared lib should have an external importer"
        )

        # --- disableable-feature direct-import audit (feature-gate compile-out) ---
        w(root, "internal/component/widget/w.go", "package widget\n")
        # gated importer (correct): reaches widget only behind its build tag
        w(
            root,
            "cmd/app/svc_widget.go",
            f'//go:build ze_widget\n\npackage app\nimport _ "{mod}/internal/component/widget"\n',
        )
        # always-on importer (violation): imports widget with no build tag
        w(
            root,
            "internal/app/use.go",
            f'package app\nimport _ "{mod}/internal/component/widget"\n',
        )
        # test importer (allowed: tests don't affect the production binary)
        w(
            root,
            "internal/app/use_test.go",
            f'package app\nimport _ "{mod}/internal/component/widget"\n',
        )
        # non-production tree importer (allowed): ze-chaos orchestrator code is
        # not in the production ze daemon, so its untagged import of a disableable
        # feature cannot pin it -- DISABLEABLE_NONPROD_PREFIXES excludes it.
        w(
            root,
            "internal/chaos/orchestrator/use.go",
            f'package orchestrator\nimport _ "{mod}/internal/component/widget"\n',
        )
        # a sibling Claude agent worktree nested under .claude/worktrees/ (a real
        # concurrent-session layout, not hypothetical -- collect_edges previously
        # walked from repo root with no exclusion for it, so this same violation
        # committed by ANOTHER session's own in-progress worktree got reported
        # against THIS repo's tier-check gate the first time ze-plugin-boundary-check
        # was wired into the live `make ze-verify` path).
        w(
            root,
            ".claude/worktrees/agent-fake/internal/app/use2.go",
            f'package app\nimport _ "{mod}/internal/component/widget"\n',
        )
        dis_edges = collect_edges(root, mod)
        dmap = {"internal/component/widget": "ze_widget"}
        dfiles = {v[0] for v in disableable_violations(root, mod, dis_edges, dmap)}
        assert "internal/app/use.go" in dfiles, (
            "always-on direct import of a disableable feature not flagged"
        )
        assert "cmd/app/svc_widget.go" not in dfiles, (
            "build-tag-gated importer wrongly flagged"
        )
        assert "internal/app/use_test.go" not in dfiles, "test importer wrongly flagged"
        assert "internal/chaos/orchestrator/use.go" not in dfiles, (
            "non-production (ze-chaos) importer of a disableable feature wrongly flagged"
        )
        assert not any(".claude" in f for f in dfiles), (
            f"a sibling agent worktree under .claude/worktrees/ was scanned and flagged: {dfiles}"
        )

        # feature-gate manifest + lint build-tags fixtures keep the disableable
        # and golangci drift gates clean while the run_gate checks below exercise
        # engine placement and non-engine category enforcement.
        w(root, FEATURE_GATES_MANIFEST, "# no gates in this fixture\n")
        w(root, GOLANGCI, "run:\n  build-tags:\n    - ze_core\nlinters: {}\n")
        w(
            root,
            NON_ENGINE_CATEGORIES,
            "# path category rationale\n"
            "internal/component/frameworklib\tframework\tselftest framework package\n"
            "internal/component/plugin\tframework\tselftest composition root\n"
            "internal/component/hostsvc\thost-service\tselftest host service package\n"
            "internal/component/host\thost-service\tselftest host nested plugin root\n"
            "internal/component/l2tp\tdomain-library\tselftest domain library package\n"
            "internal/plugins/leaflib\tplanned-violation\tspec-tiers-5 selftest misplaced leaf\n"
            "internal/component/widget\tframework\tselftest disableable feature package\n"
            "internal/plugins/consumer\tplanned-violation\tspec-tiers-5 selftest feature importer fixture\n"
            "internal/plugins/oldleaf\tplanned-violation\tspec-tiers-5 selftest planned violation\n"
            "internal/plugins/sharedlib\tplanned-violation\tspec-tiers-5 selftest shared plugin lib\n"
            "internal/plugins/setupcmd\tframework\tselftest setup feature registration\n",
        )

        assert _quiet_gate(root, mod, edges) == 2, "empty baseline should fail (new)"
        write_baseline(root, mis)
        assert _quiet_gate(root, mod, edges) == 2, (
            "unclassified non-engine placement should fail"
        )
        with open(
            os.path.join(root, NON_ENGINE_CATEGORIES), "a", encoding="utf-8"
        ) as fh:
            fh.write(
                "internal/component/unclassified\tplanned-violation\t"
                "spec-tiers-5 selftest illegal package made explicit\n"
            )
        assert _quiet_gate(root, mod, edges) == 0, (
            "matching baseline and classified non-engines should pass"
        )
        with open(os.path.join(root, BASELINE), "a", encoding="utf-8") as fh:
            fh.write("internal/component/gone\tinternal/plugins\tspec-tiers-2\n")
        assert _quiet_gate(root, mod, edges) == 2, "stale baseline entry should fail"

    # --- feature-gate manifest loader + .golangci.yml drift gate (isolated) ---
    import contextlib
    import io

    with tempfile.TemporaryDirectory() as mroot:
        w(
            mroot,
            FEATURE_GATES_MANIFEST,
            "# header comment\n"
            "ze_alpha   internal/component/alpha\n"
            "ze_beta    internal/component/beta\n",
        )
        gates = load_feature_gates(mroot)
        assert gates == {
            "internal/component/alpha": "ze_alpha",
            "internal/component/beta": "ze_beta",
        }, f"manifest parse {gates}"

        # build-tags matching the manifest (+ base tag) -> no drift. An inline
        # comment and a comment-only line inside the list must be tolerated.
        w(
            mroot,
            GOLANGCI,
            "run:\n  build-tags:\n    - ze_core  # base tag\n    # the gates:\n"
            "    - ze_alpha\n    - ze_beta\n"
            "linters:\n  default: none\n",
        )
        assert parse_golangci_build_tags(mroot) == {"ze_core", "ze_alpha", "ze_beta"}, (
            "golangci build-tags parse (with inline/standalone comments)"
        )
        assert golangci_drift_gate(mroot) == 0, "matching golangci should pass"

        # a manifest gate missing from build-tags -> drift fail (exit 2)
        w(
            mroot,
            GOLANGCI,
            "run:\n  build-tags:\n    - ze_core\n    - ze_alpha\n"
            "linters:\n  default: none\n",
        )
        with contextlib.redirect_stderr(io.StringIO()):
            assert golangci_drift_gate(mroot) == 2, (
                "gate missing from golangci build-tags should fail"
            )

    # --- core import-direction gate (spec-layout-2): internal/core must not ---
    # --- import internal/component or internal/plugins (isolated fixtures) ---
    with tempfile.TemporaryDirectory() as croot:
        cmod = "example.com/m"
        w(croot, "go.mod", f"module {cmod}\n")
        # core -> core import: allowed, never a violation.
        w(croot, "internal/core/clean/lib.go", "package clean\n")
        w(
            croot,
            "internal/core/ok/self.go",
            f'package ok\nimport _ "{cmod}/internal/core/clean"\n',
        )
        # core -> component import (non-test): violation.
        w(
            croot,
            "internal/core/bad/uses.go",
            f'package bad\nimport _ "{cmod}/internal/component/thing"\n',
        )
        # core -> plugins import (test file): also a violation (tests count --
        # the real grandfathered set includes internal/core/ipc/yang_test.go).
        w(
            croot,
            "internal/core/bad/uses_test.go",
            f'package bad\nimport _ "{cmod}/internal/plugins/thingp"\n',
        )
        # component -> component import: out of scope for this gate.
        w(
            croot,
            "internal/component/other/lib.go",
            f'package other\nimport _ "{cmod}/internal/component/thing"\n',
        )
        cedges = collect_edges(croot, cmod)
        cviol = core_direction_violations(croot, cmod, cedges)
        cexpect = {
            ("internal/core/bad/uses.go", "internal/component/thing"),
            ("internal/core/bad/uses_test.go", "internal/plugins/thingp"),
        }
        assert cviol == cexpect, f"core-direction violations {cviol} != {cexpect}"

        with contextlib.redirect_stderr(io.StringIO()):
            assert core_direction_gate(croot, cmod, cedges) == 2, (
                "missing baseline: new upward imports should fail"
            )
        w(
            croot,
            CORE_IMPORT_BASELINE,
            "# core import-direction baseline -- selftest fixture\n"
            "internal/core/bad/uses.go\tinternal/component/thing\t"
            "hand-fixable: selftest fixture\n"
            "internal/core/bad/uses_test.go\tinternal/plugins/thingp\t"
            "needs-design: selftest fixture\n",
        )
        with contextlib.redirect_stdout(io.StringIO()):
            assert core_direction_gate(croot, cmod, cedges) == 0, (
                "fully baselined pairs should pass"
            )
        # a NEW pair in an already-baselined FILE must still fail (pair
        # granularity, not file granularity).
        w(
            croot,
            "internal/core/bad/more.go",
            f'package bad\nimport _ "{cmod}/internal/component/second"\n',
        )
        cedges = collect_edges(croot, cmod)
        with contextlib.redirect_stderr(io.StringIO()):
            assert core_direction_gate(croot, cmod, cedges) == 2, (
                "new pair in a baselined package should fail"
            )
        os.remove(os.path.join(croot, "internal/core/bad/more.go"))
        # stale baseline row (import gone) must fail until the row is removed.
        with open(
            os.path.join(croot, CORE_IMPORT_BASELINE), "a", encoding="utf-8"
        ) as fh:
            fh.write(
                "internal/core/gone/x.go\tinternal/component/thing\t"
                "hand-fixable: stale fixture\n"
            )
        cedges = collect_edges(croot, cmod)
        with contextlib.redirect_stderr(io.StringIO()):
            assert core_direction_gate(croot, cmod, cedges) == 2, (
                "stale baseline row should fail (shrink-only)"
            )
        # malformed fix route must fail loud, not silently baseline.
        w(
            croot,
            CORE_IMPORT_BASELINE,
            "internal/core/bad/uses.go\tinternal/component/thing\t"
            "wontfix: not a legal route\n",
        )
        with contextlib.redirect_stderr(io.StringIO()):
            assert core_direction_gate(croot, cmod, cedges) == 2, (
                "illegal fix route should fail"
            )

    print("dep_audit selftest OK")
    return 0


def main() -> int:
    argv = sys.argv[1:]
    as_json = "--json" in argv
    cands_only = "--candidates-only" in argv

    if "--selftest" in argv:
        return selftest()

    if "--check" in argv or "--write-baseline" in argv:
        root = repo_root()
        module = module_path(root)
        edges = collect_edges(root, module)
        if "--write-baseline" in argv:
            mis = engine_misplacements(root, module, edges)
            write_baseline(root, mis)
            print(f"wrote {BASELINE} with {len(mis)} engine(s)")
            return 0
        return run_gate(root, module, edges)
    areas = [a for a in argv if not a.startswith("--")] or list(DEFAULT_AREAS)

    root = repo_root()
    module = module_path(root)
    edges = collect_edges(root, module)

    engines = engine_subsystems(root)
    report = {area: classify(area, root, module, edges, engines) for area in areas}

    if as_json:
        if cands_only:
            report = {
                a: [r for r in rs if r["core_candidate"]] for a, rs in report.items()
            }
        print(json.dumps({"module": module, "areas": report}, indent=2))
        return 0

    for area, rows in report.items():
        plugins = [r for r in rows if r["is_registered"]]
        core_cands = [r for r in rows if r["core_candidate"]]
        shared = sorted(
            (r for r in rows if not r["is_registered"] and not r["core_candidate"]),
            key=lambda r: -len(r["external"]),
        )
        print("\n" + "=" * 78)
        print("AREA:", area)
        print("=" * 78)
        print(
            f"\n-- REGISTERED PLUGINS (wired by the generator / all.go): "
            f"{len(plugins)} --"
        )
        for r in plugins:
            eng = "engine" if r["is_engine"] else "  -   "
            print(f"  {r['name']:24s} {eng}  external={len(r['external'])}")
        print(
            f"\n-- CORE CANDIDATES (0 external, not registered, not an engine): "
            f"{len(core_cands)} --"
        )
        for r in core_cands:
            print(
                f"  {r['name']:24s} registration={len(r['registration'])} "
                f"tests={len(r['tests'])}"
            )
        if cands_only:
            continue
        print(
            f"\n-- SHARED LIBRARIES (external importers, not a registered plugin): "
            f"{len(shared)} --"
        )
        for r in shared:
            print(f"  {r['name']:24s} external={len(r['external'])}")
            for s in r["external"][:6]:
                print(f"        <- {s}")
            if len(r["external"]) > 6:
                print(f"        ... and {len(r['external']) - 6} more")
    return 0


if __name__ == "__main__":
    sys.exit(main())
