#!/usr/bin/env python3
"""Generate ai/DOCS-TO-CODE.md: reverse index from `// Design:` headers in .go files.

Every non-test, non-generated Go file carries a `// Design: <doc> -- topic` header
(ai/rules/go-standards.md, hook-enforced). code_to_docs.py inverts the
`<!-- source: -->` anchors that live inside docs/; this script inverts the other
direction, the `// Design:` edges that live inside the code, so that given a design
document you can list every file that implements it without grepping the tree.

Usage:
    python3 scripts/dev/docs_to_code.py          # regenerate ai/DOCS-TO-CODE.md
    python3 scripts/dev/docs_to_code.py --check   # exit 3 if the index is stale
    python3 scripts/dev/docs_to_code.py --root DIR   # run against another tree

`--root` exists so commit_helper.py can point this generator at a materialized
commit view (HEAD plus a commit's own files) instead of the working tree. In
write mode it writes into that tree, not the repo.
"""

import os
import re
import sys
from collections import defaultdict
from pathlib import Path

from discovery_sources import STALE_EXIT, root_from_argv


DESIGN_RE = re.compile(r"^//\s*Design:\s*(\S+)\s*(.*)$")
# Leading topic separator after the doc path: em dash, "--", "-", or ":".
SEP_RE = re.compile(r"^(?:—|--|-|:)\s*")
SKIP_DIRS = {"vendor", "tmp", "testdata", "node_modules", ".git"}
HEADER_LINES = 25  # `// Design:` lines live in the file header block


def is_doc_path(token: str) -> bool:
    """A real design-doc reference: a markdown path, not `(none ...)`."""
    return token.endswith(".md") and "/" in token


def iter_go_files(root: Path):
    for base, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(
            d
            for d in dirnames
            if d not in SKIP_DIRS
            and not d.startswith(".")
            # Skip the gokrazy module cache: it holds extracted external modules
            # AND a self-copy of ze (github.com/ze-software/ze@vX/...),
            # regenerated by appliance builds. Indexing those duplicates the
            # working tree and is not first-party source (matches package_map.py).
            and os.path.relpath(os.path.join(base, d), root) != "gokrazy/modcache"
        )
        for name in sorted(filenames):
            if name.endswith(".go"):
                yield Path(base) / name


def build(root: Path) -> dict[str, set[tuple[str, str]]]:
    """Return doc_path -> set of (source_file, topic annotation)."""
    index: dict[str, set[tuple[str, str]]] = defaultdict(set)
    for go in iter_go_files(root):
        rel = str(go.relative_to(root))
        try:
            with open(go, encoding="utf-8", errors="replace") as fh:
                for i, line in enumerate(fh):
                    if i >= HEADER_LINES:
                        break
                    m = DESIGN_RE.match(line.strip())
                    if not m:
                        continue
                    token = m.group(1)
                    if not is_doc_path(token):
                        continue
                    topic = SEP_RE.sub("", m.group(2).strip()).strip()
                    index[token].add((rel, topic))
        except OSError:
            continue
    return index


def render(index: dict[str, set[tuple[str, str]]]) -> str:
    files = {f for refs in index.values() for f, _ in refs}
    lines = [
        "# Documentation to Code Index",
        "",
        "<!-- GENERATED by scripts/dev/docs_to_code.py -- do not edit -->",
        "<!-- Regenerate: make ze-discovery-index-update -->",
        "",
        "Given a design doc, the `.go` files that cite it in their `// Design:`",
        "header. The inverse of `ai/CODE-TO-DOCS.md` (which is built from doc-side",
        "`<!-- source: -->` anchors). See `ai/rules/go-standards.md`.",
        "",
        f"Total: {len(index)} design docs, {len(files)} files",
        "",
    ]
    for doc in sorted(index):
        refs = sorted(index[doc])
        lines.append(f"## `{doc}`")
        lines.append("")
        if len(refs) <= 3:
            for fname, topic in refs:
                suffix = f" -- {topic}" if topic else ""
                lines.append(f"- `{fname}`{suffix}")
        else:
            lines.append("| File | Topic |")
            lines.append("|------|-------|")
            for fname, topic in refs:
                lines.append(f"| `{fname}` | {topic.replace('|', chr(92) + '|')} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    root = root_from_argv(__file__)
    output_file = root / "ai" / "DOCS-TO-CODE.md"
    check_mode = "--check" in sys.argv

    if not (root / "ai").is_dir():
        print(f"error: {root / 'ai'} not found", file=sys.stderr)
        return 1

    index = build(root)
    content = render(index)

    if check_mode:
        current = (
            output_file.read_text(encoding="utf-8") if output_file.exists() else ""
        )
        if current != content:
            print(
                f"WARNING: {output_file.relative_to(root)} is stale -- "
                "run: make ze-discovery-index-update",
                file=sys.stderr,
            )
            # STALE_EXIT, not 1: callers must distinguish drift from a crash. The
            # text above is what a human reads; the code is what a gate reads.
            return STALE_EXIT
        print(f"checked {len(index)} design docs, ai/DOCS-TO-CODE.md up to date")
        return 0

    output_file.write_text(content, encoding="utf-8")
    print(f"wrote {output_file} ({len(index)} design docs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
