#!/usr/bin/env python3
"""Generate ai/LEARNED-FULL-INDEX.md: every plan/learned summary, by number.

ai/LEARNED-INDEX.md is a curated, topic-grouped slice (roughly a fifth of the
corpus). The remaining summaries are reachable today only by `ls` and guessing
from the slug. This index lists every plan/learned/NNN-*.md with its number,
title, and path, grouped by hundred, so no summary is unreachable. It complements
the curated index; it does not replace it.

Usage:
    python3 scripts/dev/learned_index.py          # regenerate ai/LEARNED-FULL-INDEX.md
    python3 scripts/dev/learned_index.py --check   # exit 1 if the index is stale
    python3 scripts/dev/learned_index.py --root DIR   # run against another tree

`--root` exists so commit_helper.py can point this generator at a materialized
commit view (HEAD plus a commit's own files) instead of the working tree. In
write mode it writes into that tree, not the repo.
"""

import re
import sys
from pathlib import Path

from discovery_sources import root_from_argv


NUM_RE = re.compile(r"^(\d+)-")
TITLE_RE = re.compile(r"^#\s+(.+)$")
# A title of the form "NNN -- Name" or "NNN — Name": keep just the name.
NUM_PREFIX_RE = re.compile(r"^\d+\s*(?:—|--|-)\s*")


def title_of(md: Path, fallback: str) -> str:
    try:
        for line in md.read_text(encoding="utf-8", errors="replace").splitlines():
            m = TITLE_RE.match(line.strip())
            if m:
                return NUM_PREFIX_RE.sub("", m.group(1).strip()).strip() or fallback
    except OSError:
        pass
    return fallback


def entries(learned_dir: Path) -> list[tuple[int, str, str]]:
    """Return sorted (number, title, filename) for every numbered summary."""
    out: list[tuple[int, str, str]] = []
    for md in learned_dir.glob("[0-9]*.md"):
        m = NUM_RE.match(md.name)
        if not m:
            continue
        num = int(m.group(1))
        out.append((num, title_of(md, md.stem), md.name))
    out.sort()
    return out


def render(items: list[tuple[int, str, str]]) -> str:
    lines = [
        "# Learned Summaries -- Full Index",
        "",
        "<!-- GENERATED by scripts/dev/learned_index.py -- do not edit -->",
        "<!-- Regenerate: make ze-discovery-index -->",
        "",
        "Every summary under `plan/learned/`, by number. Curated, topic-grouped",
        "reading: `ai/LEARNED-INDEX.md`. Meta-summaries: `DESIGN-HISTORY.md`",
        "(why the code is as it is), `RECURRING-PATTERNS.md` (known traps),",
        "`HOOK-FRICTION.md` (hook false positives).",
        "",
        f"Total: {len(items)} summaries",
    ]
    current = None
    for num, title, fname in items:
        rng = (num // 100) * 100
        if rng != current:
            current = rng
            lines += [
                "",
                f"## {rng:03d}-{rng + 99:03d}",
                "",
                "| # | Summary | File |",
                "|---|---------|------|",
            ]
        safe = title.replace("|", "\\|")
        lines.append(f"| {num:03d} | {safe} | `plan/learned/{fname}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    root = root_from_argv(__file__)
    learned_dir = root / "plan" / "learned"
    output_file = root / "ai" / "LEARNED-FULL-INDEX.md"
    check_mode = "--check" in sys.argv

    if not learned_dir.is_dir():
        print(f"error: {learned_dir} not found", file=sys.stderr)
        return 1

    items = entries(learned_dir)
    content = render(items)

    if check_mode:
        current = output_file.read_text(encoding="utf-8") if output_file.exists() else ""
        if current != content:
            print(
                f"WARNING: {output_file.relative_to(root)} is stale -- "
                "run: make ze-discovery-index",
                file=sys.stderr,
            )
            return 1
        print(f"checked {len(items)} summaries, ai/LEARNED-FULL-INDEX.md up to date")
        return 0

    output_file.write_text(content, encoding="utf-8")
    print(f"wrote {output_file} ({len(items)} summaries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
