#!/usr/bin/env python3
"""Retire a band of numbered summaries from `plan/learned/`.

Band 1-400 is 46% of the tree-wide dead-path rot in 24% of the files
(`plan/spec-knowledge-1-corpus.md`). Its surviving knowledge is consolidated
into `plan/learned/DESIGN-HISTORY.md` first; this tool removes the files after
that assembly has landed.

**The 400 ceiling is a permission boundary, not a default.** `ai/rules/never-destroy-work.md`
requires explicit operator permission to delete user-visible files. That
permission was granted on 2026-08-01 for band 1-400 and for nothing else, so
`RETIREMENT_CEILING` is a module constant no argument can raise. A band whose
upper bound exceeds it is REFUSED, which is AC-9 of the spec.

`enforce_ceiling` is that check, and three guards call it rather than one:
`parse_band` on the CLI string, `select` on the integers it is given, and
`remove` on the number of each path it is about to unlink. The repetition is
deliberate. A ceiling enforced only where the string is parsed is a property of
`parse_band`, not of this module, and `remove` would unlink whatever list it was
handed (`ai/rules/fail-closed-guards.md`).

What it can reach, and what it cannot:

  * Only `plan/learned/<number>-<slug>.md` is ever a candidate. The glob is
    numeric-only and `PROTECTED` re-checks the result, so `DESIGN-HISTORY.md`,
    `METHODOLOGY.md`, `RECURRING-PATTERNS.md` and `HOOK-FRICTION.md` are
    unreachable twice over.
  * `plan/known-failures/` and `plan/deferrals/` are structurally out of reach:
    they are different directories and no argument selects a directory. Those
    hold DEFECT records, which `ai/rules/no-parking.md` forbids pruning. This
    tool retires records of COMPLETED work, which is a different thing.

Fail closed (`ai/rules/fail-closed-guards.md`): a filename in the learned
directory that does not parse as `<number>-<slug>.md` is a REFUSAL, never a
silent skip. A silent skip would let a file the tool cannot judge sit inside a
band it was told to clear, and the operator would never learn it was missed.
A candidate whose real path escapes the learned directory is refused the same
way, and nothing is deleted in either case.

It does NOT shell out to `git rm`. Removal is a working-tree unlink, and the
removed paths are printed so `scripts/dev/commit_helper.py --remove` can name
them, which is the sanctioned commit path (`ai/rules/git-safety.md`).

Usage:
    python3 scripts/dev/learned_retire.py --band 1-400            # dry run
    python3 scripts/dev/learned_retire.py --band 1-400 --json
    python3 scripts/dev/learned_retire.py --band 1-400 --expect list.tsv
    python3 scripts/dev/learned_retire.py --band 1-400 --apply    # deletes
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

# The operator's permission boundary (`ai/rules/never-destroy-work.md`, granted
# 2026-08-01 for band 1-400 only). Deliberately NOT a CLI argument: a ceiling an
# argument can raise is not a ceiling. Widening it needs a new grant and an edit
# here, so the change is reviewable in the diff.
RETIREMENT_CEILING = 400
# The lowest summary number that has ever existed.
RETIREMENT_FLOOR = 1

LEARNED_DIR = ("plan", "learned")

# Named files in the learned directory that are not summaries. The numeric glob
# already excludes them; this set is the second, explicit guard, so a future
# change to the glob cannot silently put them in range.
PROTECTED = frozenset(
    {
        "DESIGN-HISTORY.md",
        "METHODOLOGY.md",
        "RECURRING-PATTERNS.md",
        "HOOK-FRICTION.md",
        "README.md",
    }
)

# `plan/learned/059-pool-handle.md` -> 59. Anchored at both ends: a name that is
# only partly numeric must not parse, so `12abc.md` is refused rather than read
# as summary 12. The slug is `+` rather than `*` on purpose: `0-.md` carries no
# slug, so it is not a summary name, and admitting it would let a file the tool
# cannot identify be judged against the band.
SUMMARY_NAME = re.compile(r"^(\d+)-[^/]+\.md$")
BAND_SPEC = re.compile(r"^\s*(\d+)\s*-\s*(\d+)\s*$")
# The citation form both the doc-links checker and the staleness gate resolve:
# `plan/learned/734` and `plan/learned/734-slug.md` alike.
CITATION = re.compile(r"plan/learned/(\d+)")

# A generated file's citations are rebuilt from the tree by its own generator,
# so it is never a repoint target. Detected by the marker rather than by name
# (`ai/rules/derive-not-hardcode.md`): a new generated index needs no edit here.
GENERATED_MARKER = "GENERATED by"

# Tooling under here cites summary numbers as TEST FIXTURES it writes into a
# throwaway repo, or as illustrative examples in a docstring. Neither is a
# reader-facing pointer, so neither dangles when the band goes. Classified, not
# hidden: the rows are still printed, under their own heading, because a skip
# list would be the silent-pass this tool is written to avoid.
TOOL_SOURCE_ROOTS = ("scripts/",)
# Read far enough to reach the marker in every generated file in the tree; the
# furthest sits on line 3.
GENERATED_PROBE_BYTES = 4096

# Build artifacts, other checkouts, and the git object store. Presence is a
# property of this machine, not of the corpus, and walking them is slow enough
# to matter (`tmp/` alone carries several full worktrees).
SKIP_DIRS = frozenset(
    {".git", "tmp", "bin", "node_modules", "vendor", "testdata", ".claude"}
)
# Beyond this a file is a blob, not prose citing a summary.
MAX_SCAN_BYTES = 4_000_000


class RetireRefused(Exception):
    """The tool declined to act. Nothing was deleted."""


def enforce_ceiling(low: int, high: int) -> None:
    """Refuse any range outside the operator's grant, or return.

    The ceiling is a property of this MODULE, not of `parse_band`. Every guard
    below re-checks it: `parse_band` for the CLI string, `select` for the
    integers it is handed, and `remove` for each path it is about to unlink. A
    caller reaching any of them without passing through the others still cannot
    get past 400 (`ai/rules/fail-closed-guards.md`).

    Every refusal names the offending value AND the accepted range, so the
    reader can act without opening this file (`ai/rules/error-messages.md`)."""
    if low < RETIREMENT_FLOOR:
        raise RetireRefused(
            f"band lower bound {low} is below {RETIREMENT_FLOOR}; the lowest "
            f"summary number that exists is {RETIREMENT_FLOOR}"
        )
    if high > RETIREMENT_CEILING:
        raise RetireRefused(
            f"band upper bound {high} exceeds the retirement ceiling "
            f"{RETIREMENT_CEILING}; the operator authorised band "
            f"{RETIREMENT_FLOOR}-{RETIREMENT_CEILING} only "
            f"(ai/rules/never-destroy-work.md). Retiring anything above "
            f"{RETIREMENT_CEILING} needs a fresh grant and an edit to "
            f"RETIREMENT_CEILING in scripts/dev/learned_retire.py"
        )


def parse_band(spec: str) -> tuple[int, int]:
    """`"1-400"` -> `(1, 400)`, or refuse."""
    m = BAND_SPEC.match(spec or "")
    if not m:
        raise RetireRefused(
            f"band {spec!r} is not <low>-<high>; write two integers separated by "
            f"a hyphen, for example 1-{RETIREMENT_CEILING}"
        )
    low, high = int(m.group(1)), int(m.group(2))
    if low > high:
        raise RetireRefused(
            f"band {spec!r} is inverted ({low} > {high}); write it low-high, for "
            f"example 1-{RETIREMENT_CEILING}"
        )
    enforce_ceiling(low, high)
    return low, high


def summary_number(name: str) -> int:
    """The summary number in `name`, or refuse.

    Fail closed: an unparseable filename is never skipped. A skip would leave a
    file the tool cannot judge sitting inside a band it was told to clear."""
    m = SUMMARY_NAME.match(name)
    if not m:
        raise RetireRefused(
            f"{name!r} in plan/learned/ does not parse as <number>-<slug>.md, so "
            f"its summary number is unknown and it cannot be judged against the "
            f"band; rename it or move it out of plan/learned/. Nothing was deleted"
        )
    return int(m.group(1))


def select(root: Path, low: int, high: int) -> list[Path]:
    """Every summary in `[low, high]`, in number order, or refuse.

    Refuses before returning anything, so a tree the tool cannot fully judge
    never yields a partial deletion set. The band is re-checked here rather than
    trusted from `parse_band`: a caller that builds the integers itself must not
    be able to select past the ceiling."""
    enforce_ceiling(low, high)
    learned = root.joinpath(*LEARNED_DIR)
    if not learned.is_dir():
        raise RetireRefused(
            f"{'/'.join(LEARNED_DIR)} is not a directory under {root}; nothing "
            f"was deleted"
        )

    real_learned = os.path.realpath(learned)
    real_root = os.path.realpath(root)
    if real_learned != real_root and not real_learned.startswith(real_root + os.sep):
        raise RetireRefused(
            f"{'/'.join(LEARNED_DIR)} resolves outside the repository root "
            f"(symlink escape); nothing was deleted"
        )

    chosen: list[tuple[int, Path]] = []
    for path in sorted(learned.glob("[0-9]*.md")):
        if path.name in PROTECTED:
            # Unreachable through the numeric glob today. Kept as the second
            # guard so a widened glob cannot silently put these in range.
            raise RetireRefused(
                f"{path.name} is a protected meta-summary and must never be "
                f"retired; nothing was deleted"
            )
        number = summary_number(path.name)
        if not (low <= number <= high):
            continue
        real = os.path.realpath(path)
        if not real.startswith(real_learned + os.sep):
            raise RetireRefused(
                f"plan/learned/{path.name} resolves outside plan/learned/ "
                f"(symlink escape to {real}); nothing was deleted"
            )
        chosen.append((number, path))
    return [p for _, p in sorted(chosen)]


def _is_generated(path: Path) -> bool:
    try:
        with open(path, "rb") as fh:
            head = fh.read(GENERATED_PROBE_BYTES)
    except OSError:
        return False
    return GENERATED_MARKER.encode() in head


def classify(rel: str, generated: bool) -> str:
    """Which of the three citation kinds `rel` is.

    `document` is the only kind a human repoints. The other two are reported
    under their own headings rather than dropped, so the reader can disagree
    with the classification."""
    if generated:
        return "generated"
    if rel.startswith(TOOL_SOURCE_ROOTS):
        return "tool-source"
    return "document"


def scan_citations(root: Path, retired: set[int], removed: set[str]) -> list[dict]:
    """Files outside the removal set that cite a retired summary.

    One row per file, carrying the numbers it cites and its `kind`. Only a
    `document` row is a repoint target: a generated index is rebuilt by its own
    generator, and a `tool-source` row cites a fixture it creates itself."""
    rows: list[dict] = []
    real_root = os.path.realpath(root)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in sorted(dirnames) if d not in SKIP_DIRS]
        for name in sorted(filenames):
            full = Path(dirpath) / name
            rel = os.path.relpath(full, root)
            if rel in removed:
                continue
            try:
                if full.is_symlink() or not full.is_file():
                    continue
                if full.stat().st_size > MAX_SCAN_BYTES:
                    continue
                real = os.path.realpath(full)
                if not real.startswith(real_root + os.sep):
                    continue
                text = full.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                # Binary or unreadable: cannot carry a markdown citation.
                continue
            cited = sorted({int(n) for n in CITATION.findall(text)} & retired)
            if cited:
                posix = Path(rel).as_posix()
                generated = _is_generated(full)
                rows.append(
                    {
                        "path": posix,
                        "numbers": cited,
                        "generated": generated,
                        "kind": classify(posix, generated),
                    }
                )
    return rows


def load_expected(path: Path) -> dict[str, list[int]]:
    """A tab-separated `path\\t[n, n]` cross-check list.

    An unparseable line is a refusal: a silently dropped row would make the
    cross-check report a false agreement."""
    out: dict[str, list[int]] = {}
    for lineno, line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) != 2:
            raise RetireRefused(
                f"{path}:{lineno}: expected `<path>\\t[<numbers>]`, got {line!r}"
            )
        rel, nums = parts[0].strip(), parts[1].strip().strip("[]")
        try:
            out[rel] = sorted(int(n) for n in nums.split(",") if n.strip())
        except ValueError as err:
            raise RetireRefused(
                f"{path}:{lineno}: number list {nums!r} does not parse: {err}"
            ) from err
    return out


def cross_check(rows: list[dict], expected: dict[str, list[int]]) -> dict:
    """Compare the scanned citations against a recorded list of repoint targets.

    Only `document` rows are compared. A generated index regenerates and a
    tool-source row cites its own fixture, so neither belongs on a repoint list
    and counting either as a discrepancy would train the reader to ignore it."""
    found = {r["path"]: r["numbers"] for r in rows if r["kind"] == "document"}
    return {
        "missing-from-list": sorted(set(found) - set(expected)),
        "stale-list-entries": sorted(set(expected) - set(found)),
        "numbers-differ": sorted(
            p for p in set(found) & set(expected) if found[p] != expected[p]
        ),
    }


def _removable(root: Path, path: Path) -> str:
    """The repo-relative name of `path`, or refuse to unlink it.

    `remove` is the only function here that destroys anything, so it re-derives
    every property the caller is supposed to have established: the file lives in
    `plan/learned/`, its name parses as a summary, and its number is inside the
    operator's grant. None of that is trusted from `select`."""
    try:
        rel = path.relative_to(root).as_posix()
    except ValueError as err:
        raise RetireRefused(
            f"{path} is outside the repository root {root}; nothing was deleted"
        ) from err
    prefix = "/".join(LEARNED_DIR) + "/"
    if not rel.startswith(prefix) or "/" in rel[len(prefix) :]:
        raise RetireRefused(
            f"{rel} is not directly inside {prefix}; only a numbered summary "
            f"there can be retired. Nothing was deleted"
        )
    number = summary_number(path.name)
    enforce_ceiling(number, number)
    return rel


def remove(
    root: Path, paths: list[Path], removed: list[str] | None = None
) -> list[str]:
    """Unlink each path, recording the repo-relative names removed.

    The caller owns the `removed` list, so a run that fails PART-WAY can still
    name what went. Returning it instead loses the whole list to the unwinding
    exception, and the operator is told "Removed 0 file(s)" over a tree that is
    already short some files.

    Every path is checked before any is unlinked, so a set the tool cannot fully
    judge produces no partial deletion.

    Working tree only. `git rm` is deliberately not called: the commit runs
    through `commit_helper.py --remove` (`ai/rules/git-safety.md`)."""
    if removed is None:
        removed = []
    checked = [(_removable(root, path), path) for path in paths]
    for rel, path in checked:
        path.unlink()
        removed.append(rel)
    return removed


def _print_report(
    low: int,
    high: int,
    selected: list[Path],
    rows: list[dict],
    checks: dict | None,
    applied: bool,
) -> None:
    verb = "removed" if applied else "would remove"
    print(f"learned retire: band {low}-{high}, {verb} {len(selected)} summary(ies)")
    if selected:
        print(f"  first: {selected[0].name}")
        print(f"  last:  {selected[-1].name}")

    docs = [r for r in rows if r["kind"] == "document"]
    generated = [r for r in rows if r["kind"] == "generated"]
    tooling = [r for r in rows if r["kind"] == "tool-source"]

    dangling = sum(len(r["numbers"]) for r in docs)
    print(
        f"  citations that would dangle: {dangling} in {len(docs)} document(s), "
        f"each needing a repoint"
    )
    for r in docs:
        print(f"    {r['path']}: {r['numbers']}")
    if generated:
        print(f"  generated, regenerate rather than edit: {len(generated)} file(s)")
        for r in generated:
            print(f"    {r['path']}: {len(r['numbers'])} citation(s)")
    if tooling:
        print(
            f"  tool source, cites its own fixtures or examples: {len(tooling)} file(s)"
        )
        for r in tooling:
            print(f"    {r['path']}: {r['numbers']}")

    if checks is not None:
        bad = any(checks[k] for k in checks)
        if not bad:
            print("  cross-check against the recorded list: agrees")
        else:
            print("  cross-check against the recorded list: DISAGREES", file=sys.stderr)
            for key, values in checks.items():
                if values:
                    print(f"    {key}: {values}", file=sys.stderr)

    if not applied:
        print("  dry run: nothing was deleted. Re-run with --apply to remove.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo",
        default=str(Path(__file__).resolve().parents[2]),
        help="repository root (default: the checkout this script lives in)",
    )
    parser.add_argument(
        "--band",
        required=True,
        help=f"inclusive summary band to retire, <low>-<high>. Refused above "
        f"{RETIREMENT_CEILING}",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="delete the selected summaries; without it nothing is removed",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="report only (the default; accepted so the intent can be explicit)",
    )
    parser.add_argument("--json", action="store_true", help="machine-readable report")
    parser.add_argument(
        "--expect",
        help="tab-separated `<path>\\t[<numbers>]` list to cross-check the "
        "dangling-citation scan against",
    )
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)

    if args.apply and args.dry_run:
        print(
            "learned retire refused: --apply and --dry-run are contradictory; pass one",
            file=sys.stderr,
        )
        return 2

    root = Path(args.repo).resolve()
    try:
        low, high = parse_band(args.band)
        selected = select(root, low, high)
        expected = load_expected(Path(args.expect)) if args.expect else None
    except RetireRefused as err:
        print(f"learned retire refused: {err}", file=sys.stderr)
        return 2
    except OSError as err:
        print(f"learned retire refused: {err}", file=sys.stderr)
        return 2

    retired = set(range(low, high + 1))
    removed_rel = {p.relative_to(root).as_posix() for p in selected}
    rows = scan_citations(root, retired, removed_rel)
    checks = cross_check(rows, expected) if expected is not None else None

    removed: list[str] = []
    if args.apply:
        try:
            remove(root, selected, removed)
        except RetireRefused as err:
            print(f"learned retire refused: {err}", file=sys.stderr)
            return 2
        except OSError as err:
            print(
                f"learned retire failed part-way: {err}. Removed {len(removed)} "
                f"file(s) before the error; the tree is half-retired and the "
                f"remainder is still present",
                file=sys.stderr,
            )
            # The list the docstring promises `commit_helper.py --remove`. The
            # failure path is the one that most needs it: these files are gone
            # from the working tree and nothing else records which.
            for rel in removed:
                print(f"  removed: {rel}", file=sys.stderr)
            return 1

    if args.json:
        print(
            json.dumps(
                {
                    "band": [low, high],
                    "ceiling": RETIREMENT_CEILING,
                    "applied": bool(args.apply),
                    "selected": sorted(removed_rel),
                    "removed": removed,
                    "citations": rows,
                    "cross-check": checks,
                },
                indent=2,
            )
        )
    else:
        _print_report(low, high, selected, rows, checks, bool(args.apply))

    if checks is not None and any(checks[k] for k in checks):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
