#!/usr/bin/env python3
"""Remove line-number references from committed prose.

A `path.go:412` citation names a line that moves on the next edit, so the
citation is wrong the moment anybody touches the file. The path and the symbol
survive an edit. The number does not. `ai/rules/writing.md` already says
to cite the file and the symbol, and to give a line number only when the line
IS the fact. This tool makes the corpus agree with that rule, and
`c_line_number_ref` in `.claude/hooks/pretool-writeedit.py` keeps new ones out.

Three forms are removed:

    path-form   internal/x/y.go:412   ->  internal/x/y.go
    bare-form   (`:232-239`)          ->  removed, with its punctuation
    anchor-form https://.../f.c#L755  ->  https://.../f.c

NAME THE SYMBOL BEFORE RUNNING THIS OVER FORGE PERMALINKS. Two citations into
one external file collapse into the same link once their anchors go, and the
reader loses the distinction the anchor was carrying. Put the function in the
link text first, then sweep. `docs/research/` and
`docs/architecture/congestion-industry.md` cite FRR, BIRD, GoBGP and OpenBSD
this way.

A fenced code block is skipped. A line number inside quoted tool output is the
fact being quoted, not a citation.

Usage:
    scripts/dev/line_refs.py            report what would change
    scripts/dev/line_refs.py --apply    rewrite the files
"""

from __future__ import annotations

import pathlib
import re
import sys

# A path with one or more `:N` / `:N-N` suffixes. Only the suffix is dropped.
# The extension list covers other projects' languages too: this corpus cites
# FRR, BIRD, GoBGP and OpenBSD source, and a half-covered list left one document
# with `fsm.go` stripped beside `bgp_packet.c:755` untouched.
PATH_REF = re.compile(
    r"([A-Za-z0-9_./-]*\.(?:go|py|sh|md|mk|yang|ci|et|json|txt"
    r"|c|h|cc|cpp|rs|java|ts|js))"
    r"((?::\d+(?:-\d+)?)+)"
)

# A forge permalink's line anchor: `#L1903`, `#L1712-1716`, `#L12L20`. The URL
# still resolves to the file without it, and the symbol is what a reader needs.
LINE_ANCHOR = re.compile(r"#L\d+(?:[-L]\d+)?")

# A published RFC text never changes, so a line number into one is a stable
# fact rather than a citation that rots. `rfc/full/rfc7296.txt:5110` keeps its
# number.
STABLE_PATH = re.compile(r"rfc/full/[A-Za-z0-9_.-]+\.txt$")

# A bare backticked line reference: `:412` or `:232-239`. Only ever matched
# inside backticks: `buf[:0]` is Go slice syntax and has the same shape.
BARE = r"`:\d+(?:-\d+)?`"

# Deletable surroundings. A bare ref is removed only where the sentence still
# reads without it, which means two shapes and no others.
#
# The rejected third shape is why this list is short. " at `:193` and assembled
# at `:225-228`" leaves "set and assembled", which is grammatical and says
# nothing, and a line-start "(`:717`)." leaves a sentence opening on a period.
# Prose that carries a line number as its only object needs a human sentence,
# so those are counted as residue and left alone.
BARE_FORMS = (
    # A mid-sentence parenthetical of only bare refs: (`:1`) or (`:1`, `:2-3`).
    # The leading `(?<=[\w`)\].,])` keeps it mid-sentence: a parenthetical that
    # opens a line is carrying the previous sentence's terminator.
    re.compile(r"(?<=[\w`)\].,]) *\((?:" + BARE + r")(?:, *(?:" + BARE + r"))*\)"),
    # A comma-led appositive whose only content is the ref, inside a citation:
    # (`streamable.go`, defined `:341`) -> (`streamable.go`)
    re.compile(r", *(?:defined|declared|introduced|added) +" + BARE),
)

ROOTS = ("ai", "docs", "plan", ".claude")

# Generated files are rewritten by `make ze-generated-files-update`, never edited by hand
# (ai/rules/repo-maintenance.md).
GENERATED = frozenset(
    {
        "ai/CODE-TO-DOCS.md",
        "ai/DOCS-TO-CODE.md",
        "ai/PACKAGE-MAP.md",
        "ai/LEARNED-FULL-INDEX.md",
        # The index of an evidence ledger, regenerated by `make ze-rfc-index-update`.
        # Its per-RFC files live under `rfc/requirements/`, outside ROOTS, and
        # carry the `file.go:line` entries. The index quotes a producing
        # function's line in a backlog note, so there the line IS the fact and
        # stripping it would delete the evidence.
        "ai/RFC-REQUIREMENTS.md",
    }
)

# EVERY `*.md` sitting directly in ai/rules/ is generated: the 27 rules are
# rendered from ai/rules/points/<rule>/<section>/ by rules_points.py, and INDEX.md,
# TRIGGERS.md and CORE.md come from rules_index.py and rules_condensed.py. A
# sweep applied to a rendered rule is undone by the next `make ze-rules-render-update`,
# so the sweep reaches the POINT instead, which rglob already yields. Named as a
# directory rather than as eight filenames, so a new rule needs no wiring here.
RENDERED_RULES_DIR = "ai/rules"


def strip(text: str) -> tuple[str, int, int]:
    """Return the text with line-number refs removed, and the two counts."""
    out: list[str] = []
    fence = False
    n_path = n_bare = 0
    for line in text.splitlines(keepends=True):
        if line.lstrip().startswith("```"):
            fence = not fence
            out.append(line)
            continue
        if fence:
            out.append(line)
            continue

        def keep_stable(m: re.Match[str]) -> str:
            nonlocal n_path
            if STABLE_PATH.search(m.group(1)):
                return m.group(0)
            n_path += 1
            return m.group(1)

        line = PATH_REF.sub(keep_stable, line)
        line, hits = LINE_ANCHOR.subn("", line)
        n_path += hits
        for pattern in BARE_FORMS:
            line, hits = pattern.subn("", line)
            n_bare += hits
        out.append(line)
    return "".join(out), n_path, n_bare


def targets() -> list[pathlib.Path]:
    found: list[pathlib.Path] = []
    for root in ROOTS:
        base = pathlib.Path(root)
        if not base.is_dir():
            continue
        found.extend(
            p
            for p in sorted(base.rglob("*.md"))
            if str(p) not in GENERATED and p.parent.as_posix() != RENDERED_RULES_DIR
        )
    return found


def main(argv: list[str]) -> int:
    apply = "--apply" in argv
    files = tot_path = tot_bare = 0
    residue = 0
    bare_token = re.compile(BARE)
    for path in targets():
        original = path.read_text(errors="ignore")
        new, n_path, n_bare = strip(original)
        residue += len(bare_token.findall(new))
        if new == original:
            continue
        files += 1
        tot_path += n_path
        tot_bare += n_bare
        if apply:
            path.write_text(new)
    verb = "stripped" if apply else "would strip"
    print(f"{verb} {tot_path} path refs and {tot_bare} bare refs in {files} files")
    if residue:
        print(f"{residue} bare refs remain in prose that needs a human sentence")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
