#!/usr/bin/env python3
"""Report a .templ outside internal/, and a *_templ.go with no .templ source.

Run by `make ze-templ-orphan-check`, a prerequisite of
`make ze-templ-generate-check`.

THIS IS THE ONLY THING THAT SEES AN ORPHAN. `ze-templ-generate-check` passes
-keep-orphaned-files, so `FSEventHandler.HandleEvent`
(vendor/github.com/a-h/templ/cmd/templ/generatecmd/eventhandler.go) returns an
empty result on an orphan before any writer is consulted. That flag is what
makes the check read-only, and it costs the check writer its one sight of the
file. A .templ dropped by a rebase, or by a half-applied patch, leaves a
generated file no source produces, and nothing else reports it.

The write path is not checked here. `make generate` runs templ without the
flag, so templ deletes the orphan itself, which is what regeneration means.

The stray check keeps the walk scoped. Every renderer in ze lives under
internal/, so `templ generate -path internal` is what the recipes run, and a
.templ outside that walk is generated by nobody. A walk from the repo root
would descend into gokrazy/ and tmp/, which hold module and build caches.
`-path` is also load-bearing for file CONTENT: `FSEventHandler.generate`
computes the file name with filepath.Rel against the walk root, so the same
.templ under a different root writes a different path into the generated file.

This script reports. It writes nothing and it deletes nothing.

Usage: templ_orphan_check.py [--root DIR]
Exit: 0 clean, 1 a finding, 2 git failed.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# The directory templ walks. One name, used by the two checks and by both
# make recipes.
SCOPE = "internal/"

# go mod vendor copies two .templ files that templ's own CLI carries. They
# belong to the dependency, and templ skips a vendor directory on its walk.
VENDOR = "vendor/"


def repo_paths(root: Path) -> list[str]:
    """The files git knows about that are also ON DISK, ignores applied.

    An ignored file is excluded, because nothing commits it, so nothing
    depends on it being regenerated.

    THE DISK IS TEMPL'S POPULATION, and this filter is what matches it. templ
    walks the filesystem and knows nothing of the index, while `git ls-files
    --cached` still lists a tracked file the worktree no longer holds. Without
    the filter, deleting a .templ and its _templ.go together without staging
    reports an orphan for a file that is already gone.

    -z IS LOAD-BEARING TOO. Without it git quotes any path holding a byte
    outside ASCII (`core.quotePath`), so `internal/a/café_templ.go` arrives as <!-- doc-links: ignore (illustrative path in a docstring, deliberately absent) -->
    `"internal/a/caf\\303\\251_templ.go"`. The leading quote defeats every
    prefix and suffix test below, and the orphan reads as clean.
    """
    out = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    )
    return [path for path in out.stdout.split("\0") if path and (root / path).exists()]


def stray_sources(paths: list[str]) -> list[str]:
    """The .templ files the walk cannot reach. Takes `repo_paths` output."""
    return sorted(
        p
        for p in paths
        if p.endswith(".templ") and not p.startswith(SCOPE) and not p.startswith(VENDOR)
    )


def orphan_outputs(root: Path, paths: list[str]) -> list[str]:
    """The generated files whose .templ source is gone.

    Takes `repo_paths` output, so every candidate is already known to be on
    disk. The source is read from disk for the same reason (see `repo_paths`).
    """
    return sorted(
        p
        for p in paths
        if p.startswith(SCOPE)
        and p.endswith("_templ.go")
        and not (root / (p[: -len("_templ.go")] + ".templ")).exists()
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        default=str(Path(__file__).resolve().parents[2]),
        help="repository root to check (default: this script's repository)",
    )
    args = parser.parse_args(argv)
    root = Path(args.root)

    try:
        paths = repo_paths(root)
    except subprocess.CalledProcessError as err:
        print(f"error: git ls-files failed in {root}: {err.stderr}", file=sys.stderr)
        return 2

    stray = stray_sources(paths)
    if stray:
        print(
            f"error: templ generate reads {SCOPE} only, and these .templ files sit outside it:"
        )
        for p in stray:
            print(f"  {p}")
        return 1

    orphans = orphan_outputs(root, paths)
    if orphans:
        print("error: generated file with no .templ source:")
        for p in orphans:
            print(f"  {p}")
        print("delete it, or restore the .templ it came from")
        print("`make generate` deletes it for you, because no source produces it")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
