environment {
    ssh {
        enabled enable
        server main { ip 127.0.0.1; port 2222; }
    }
}

interface {
    backend netlink
}

traffic {
    usage {
        enabled true
        interfaces {
            interface traffic0 {
                track-ip true
                max-entries 256
            }
        }
        interval 250
        stale-timeout 60000
        track-ip true
        max-entries 256
    }
}
