// Design: docs/architecture/core-design.md -- native edit hook policy
package hookruntime

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/ze-software/ze/internal/core/textbuf"
	"github.com/ze-software/ze/internal/le/ste"
	"github.com/ze-software/ze/internal/le/testweakened"
)

var (
	lineCitation = regexp.MustCompile(`(^|[^A-Za-z0-9_])([A-Za-z0-9_./-]+\.(?:go|sh|md|mk|yang|ci|et|json|txt|c|h|cc|cpp|rs|java|ts|js)):[0-9]+(?:-[0-9]+)?`)
	lineAnchor   = regexp.MustCompile(`https?://\S*?(#L\d+(?:[-L]\d+)?)`)
	upperRFC     = regexp.MustCompile(`\b(?:MUST NOT|SHALL NOT|SHOULD NOT|NOT RECOMMENDED|MUST|SHALL|REQUIRED|SHOULD|RECOMMENDED|MAY|OPTIONAL)\b`)
	lowerModal   = regexp.MustCompile(`(^|[^A-Za-z0-9_-])(must|shall|should|may)([^A-Za-z0-9_-]|$)`)
)

type editPattern struct {
	pattern *regexp.Regexp
	code    int
	message string
	exempt  func(context) bool
}

func absolutePath(ctx context) string {
	if filepath.IsAbs(ctx.path) {
		return filepath.Clean(ctx.path)
	}
	return filepath.Join(ctx.root, filepath.Clean(ctx.path))
}

func relativePath(ctx context) string {
	relative, err := filepath.Rel(ctx.root, absolutePath(ctx))
	if err != nil {
		return filepath.ToSlash(ctx.path)
	}
	return filepath.ToSlash(relative)
}

// ze point: writing/detail-budget/write-only-what-changes-the-next-action
// ze point: evidence/no-fabrication/cite-a-line-number-only-when-a-generator-maintains-it
// writeLineCitation refuses a line-number citation in repository prose.
func writeLineCitation(ctx context) *verdict {
	if !strings.HasSuffix(ctx.path, ".md") {
		return nil
	}
	relative := relativePath(ctx)
	if !anyPrefix(relative, "ai/", "docs/", "plan/", ".claude/") {
		return nil
	}
	head := strings.Join(strings.Split(ctx.content, "\n")[:min(10, len(strings.Split(ctx.content, "\n")))], "\n")
	if regexp.MustCompile(`(?i)(GENERATED|generated by)`).MatchString(head) && strings.Contains(strings.ToLower(head), "do not edit") {
		return nil
	}
	bad := make([]string, 0, 4)
	fence := false
	for index, line := range strings.Split(ctx.content, "\n") {
		if strings.HasPrefix(strings.TrimLeft(line, " \t"), "```") {
			fence = !fence
			continue
		}
		if fence {
			continue
		}
		for _, match := range lineCitation.FindAllStringSubmatch(line, -1) {
			if !strings.HasPrefix(match[2], "rfc/full/") {
				bad = append(bad, fmt.Sprintf("  +%d: %s", index+1, strings.TrimSpace(match[0])))
			}
		}
		for _, match := range lineAnchor.FindAllStringSubmatch(line, -1) {
			bad = append(bad, fmt.Sprintf("  +%d: %s", index+1, match[1]))
		}
	}
	if len(bad) == 0 {
		return nil
	}
	return &verdict{2, red + bold + "❌ BLOCKED: line-number citation in prose" + reset + "\n" + strings.Join(bad[:min(4, len(bad))], "\n") +
		"\n  Cite the file and the SYMBOL, not the line: `session.go`, `handleOpen()`.\n  A line number is right only when the line itself IS the fact, and then it belongs in a fenced block as quoted output. See ai/rules/writing.md."}
}

// ze point: repo-maintenance/canonical-sources-and-sync-direction/edit-the-canonical-source-not-the-generated-file
// ze point: repo-maintenance/canonical-sources-and-sync-direction/sync-generated-files-from-their-canonical-source
// ze point: repo-maintenance/canonical-sources-and-sync-direction/keep-shared-rules-in-ai-rules-and-render-them
// writeGenerated refuses an edit to a generated file, and names its source.
func writeGenerated(ctx context) *verdict {
	if !oneOf(ctx.tool, toolWrite, "Edit") {
		return nil
	}
	relative := relativePath(ctx)
	if relative == "CLAUDE.md" || relative == "AGENTS.md" {
		base := filepath.Base(relative)
		return &verdict{2, "BLOCKED: " + base + " is generated\n  " + base + " is auto-generated. Edit the canonical source instead:\n    ai/INSTRUCTIONS.md  (then run the native sync action)\n  See ai/rules/repo-maintenance.md"}
	}
	parts := strings.Split(relative, "/")
	if len(parts) >= 3 && parts[0] == ".claude" {
		if info, err := os.Stat(filepath.Join(ctx.root, "ai", parts[1])); err == nil && info.IsDir() {
			return &verdict{1, yellow + bold + "WARN: " + relative + " is read by this tool alone; ai/" + parts[1] + "/ is the shared home" + reset + "\n  ai/INSTRUCTIONS.md generates BOTH CLAUDE.md and AGENTS.md, so an instruction that binds every agent belongs in the shared tree."}
		}
	}
	return nil
}

// ze point: repo-maintenance/canonical-sources-and-sync-direction/keep-shared-rules-in-ai-rules-and-render-them
// ze point: repo-maintenance/canonical-sources-and-sync-direction/sync-generated-files-from-their-canonical-source
// writeRenderedRule refuses an edit to a rendered rule, which points/ owns.
func writeRenderedRule(ctx context) *verdict {
	if !oneOf(ctx.tool, toolWrite, "Edit", "MultiEdit") {
		return nil
	}
	relative := relativePath(ctx)
	if !strings.HasPrefix(relative, "ai/rules/") {
		return nil
	}
	tail := strings.TrimPrefix(relative, "ai/rules/")
	if strings.Contains(tail, "/") || !strings.HasSuffix(tail, ".md") {
		return nil
	}
	return &verdict{2, red + bold + "❌ BLOCKED: ai/rules/" + tail + " is generated" + reset +
		"\n  Edit the rule's point under ai/rules/points/<rule>/, then run the native rules render action.\n  See ai/rules/repo-maintenance.md, Canonical Sources and Sync Direction"}
}

// ze point: never-destroy-work/forbidden-without-explicit-permission/ask-before-deleting-or-overwriting-user-work
// writePointOverwrite refuses a Write that replaces an existing rule point.
func writePointOverwrite(ctx context) *verdict {
	replaces := ctx.tool == toolWrite
	if ctx.tool == "MultiEdit" {
		edits, _ := ctx.input["edits"].([]any)
		for _, raw := range edits {
			edit, _ := raw.(map[string]any)
			if stringInput(edit, "old_string") == "" {
				replaces = true
			}
		}
	}
	if !replaces {
		return nil
	}
	relative := relativePath(ctx)
	parts := strings.Split(strings.TrimPrefix(relative, "ai/rules/points/"), "/")
	canonical := strings.HasPrefix(relative, "ai/rules/points/") && ((len(parts) == 2 && parts[1] == "manifest.md") || len(parts) == 3)
	if !canonical {
		return nil
	}
	if info, err := os.Stat(absolutePath(ctx)); err != nil || !info.Mode().IsRegular() {
		return nil
	}
	return &verdict{2, red + bold + "❌ BLOCKED: Write over an existing rule point" + reset + "\n  " + relative + " already exists and carries one instruction of the rule.\n  A Write replaces the whole file. Edit the existing point or write a free slug.\n  See ai/rules/never-destroy-work.md and docs/contributing/rule-authoring.md"}
}

func visibleMarkdown(text string) string {
	var visible textbuf.Buffer
	visible.Reset()
	fence := false
	for line := range strings.SplitSeq(text, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			fence = !fence
			continue
		}
		if fence || strings.HasPrefix(trimmed, ">") {
			continue
		}
		line = regexp.MustCompile("`[^`]*`").ReplaceAllString(line, "")
		visible.Str(line).Byte('\n')
	}
	return visible.String()
}

// ze point: rule-format/every-directive-states-a-level/every-directive-states-its-rfc-2119-level
// writePointLanguage refuses a rule directive that states no RFC 2119 level.
func writePointLanguage(ctx context) *verdict {
	relative := relativePath(ctx)
	parts := strings.Split(strings.TrimPrefix(relative, "ai/rules/points/"), "/")
	if !strings.HasPrefix(relative, "ai/rules/points/") || len(parts) != 3 || ctx.content == "" {
		return nil
	}
	directive := regexp.MustCompile(`(?m)^kind:[ \t]*directive[ \t]*$`).MatchString(ctx.content)
	if ctx.tool != toolWrite {
		body, err := os.ReadFile(absolutePath(ctx))
		directive = err == nil && regexp.MustCompile(`(?m)^kind:[ \t]*directive[ \t]*$`).Match(body[:min(400, len(body))])
	}
	if !directive {
		return nil
	}
	visible := visibleMarkdown(ctx.content)
	matches := lowerModal.FindAllStringSubmatch(visible, -1)
	if len(matches) != 0 {
		words := make([]string, 0, len(matches))
		for _, match := range matches {
			words = append(words, match[2])
		}
		sort.Strings(words)
		return &verdict{2, red + bold + "❌ BLOCKED: lowercase obligation word in a rule directive" + reset + "\n  " + relative + " states " + strings.Join(words, ", ") + " in lowercase.\n  Use MUST, MUST NOT, SHOULD, SHOULD NOT, or MAY."}
	}
	if ctx.tool == toolWrite && !upperRFC.MatchString(visible) {
		return &verdict{2, red + bold + "❌ BLOCKED: rule directive states no RFC 2119 level" + reset + "\n  " + relative + " declares `kind: directive` and states no capitalised keyword."}
	}
	return nil
}

// ze point: evidence/no-fabrication/investigate-source-in-session-before-writing-a-spec
// ze point: evidence/no-fabrication/read-the-producing-code-before-claiming-behavior
// writeDesignEvidence refuses a spec or design written before its source was read.
func writeDesignEvidence(ctx context) *verdict {
	relative := relativePath(ctx)
	if !anyPrefix(relative, "plan/spec-", "plan/design-", ".claude/plan/") {
		return nil
	}
	id := resolvedSessionID(ctx)
	if id == "" {
		return &verdict{2, "❌ BLOCKED: cannot resolve this session id; design evidence is fail-closed"}
	}
	if _, err := os.Stat(filepath.Join(ctx.root, "tmp", "session", ".lsp-invoked-"+id)); err == nil {
		return nil
	}
	entries, _ := filepath.Glob(filepath.Join(ctx.root, "tmp", "session", ".source-read-*-"+id))
	if len(entries) != 0 {
		return nil
	}
	return &verdict{2, "❌ BLOCKED: read the producing source before writing a design/spec\n  Use Read or LSP on the implementation this session, then retry.\n  ai/rules/evidence.md"}
}

// ze point: planning/spec-metadata-blocking/update-spec-status-at-each-transition
// writeSpecStatus refuses a source edit while the claimed spec is not in-progress.
func writeSpecStatus(ctx context) *verdict {
	if !strings.HasSuffix(ctx.path, ".go") || !oneOf(ctx.tool, toolWrite, "Edit", "MultiEdit") {
		return nil
	}
	id := resolvedSessionID(ctx)
	if id == "" {
		return nil
	}
	marker := filepath.Join(ctx.root, "tmp", "session", ".session-"+id)
	body, err := os.ReadFile(marker) //nolint:gosec // a session marker under the checkout tmp directory
	if err != nil {
		return nil
	}
	spec := strings.TrimSpace(string(body))
	if spec == "" || spec == specUnassigned {
		return nil
	}
	specBody, err := os.ReadFile(filepath.Join(ctx.root, "plan", spec)) //nolint:gosec // the claimed spec lives under the checkout plan directory
	if err != nil {
		return nil
	}
	text := string(specBody)
	if !strings.Contains(text, "| Status | in-progress |") && !strings.Contains(text, "| Status | verification |") {
		return &verdict{2, "❌ BLOCKED: source edit while selected spec is not in-progress\n  Update the spec status before implementation."}
	}
	return nil
}

func goEdit(ctx context) bool {
	return oneOf(ctx.tool, toolWrite, "Edit") && strings.HasSuffix(ctx.path, ".go")
}

// ze point: architecture/design-principles/apply-these-design-principles-to-every-decision
// ze point: cli/cli-patterns/return-exit-codes-and-write-errors-to-stderr
// ze point: go-standards/directives/never-write-these-forbidden-go-patterns
// ze point: go-standards/directives/log-through-slog-never-printf
// ze point: performance/three-rules/never-use-fmt-or-string-on-a-hot-path
// ze point: performance/directives/write-wire-encoding-into-pooled-bounded-buffers
// ze point: quality/linting/fix-lint-issues-never-disable-a-linter
// ze point: plugins/registration-based-dispatch/dispatch-subcommands-by-registration-not-switch
// ze point: goroutine-lifecycle/directives/keep-every-goroutine-a-long-lived-worker
// ze point: performance/common-mistakes/fix-these-common-allocation-mistakes
// writeGoPatterns refuses the Go patterns the rules ban, file by file.
func writeGoPatterns(ctx context) *verdict {
	if !goEdit(ctx) {
		return nil
	}
	path := filepath.ToSlash(ctx.path)
	if strings.HasSuffix(path, "_test.go") {
		return nil
	}
	// This file DECLARES the banned patterns, so it holds every one of them as a
	// literal. Judging it by its own list refuses the edit that repairs the list,
	// which is how a wrong pattern here becomes permanent. The links checker
	// excludes its own source for the same reason (sweepExcluded,
	// internal/le/doc/check/links.go). The exclusion is by suffix, so a checkout at
	// any path is covered.
	if strings.HasSuffix(path, "/internal/le/hookruntime/writeedit.go") {
		return nil
	}
	patterns := []editPattern{
		{regexp.MustCompile(`(?m)^func[ \t]+(?:\([^)]+\)[ \t]+)?[A-Z][A-Za-z]*And[A-Z]`), 1, red + bold + "❌ BLOCKED: Single responsibility violation" + reset + " (function with 'And' in name)", nil},
		{regexp.MustCompile(`os\.Exit\(`), 2, red + bold + "❌ BLOCKED: os.Exit() in handler" + reset + "\n  Return an error instead.", func(c context) bool {
			return strings.HasSuffix(c.path, "/main.go") || strings.HasSuffix(c.path, "/register.go")
		}},
		{regexp.MustCompile(`(^|[^A-Za-z0-9_])panic[ \t]*\(`), 2, red + "❌ Return error, don't panic()" + reset, nil},
		{regexp.MustCompile(`(?m)(^|[^A-Za-z0-9_])log\.(Print|Printf|Println|Fatal|Fatalf|Fatalln|Panic|Panicf|Panicln)`), 2, red + "❌ Use slog, not log package" + reset, nil},
		{regexp.MustCompile(`fmt\.(Sprintf|Fprintf|Printf)\(|strconv\.Format(Uint|Int)\(`), 2, red + bold + "✘ BLOCKED: allocation-heavy string formatting" + reset + "\n  Build the text with textbuf.Buffer, then print it with .StdOut() or .StdErr().\n  Neither .String() nor .Slice() is needed: the write consumes the buffer.", nil},
		// Two bad shapes, matched positively because RE2 has no negative lookahead.
		// First: a BARE nolint, with or without prose after it, which suppresses
		// every linter. Second: a nolint that names its linters and then states no
		// reason, either at end of line or with an empty trailing comment.
		// `//nolint:gosec // <reason>` matches neither and is the form the style
		// guide requires; the previous pattern refused it along with the rest, so
		// the only spelling this rule exists to ALLOW was the one it blocked.
		{regexp.MustCompile(`(?m)//nolint(?:[^:\n]|$)|//nolint:[A-Za-z0-9_,-]*[ \t]*(?://[ \t]*)?$`), 2, red + bold + "❌ BLOCKED: nolint without a specific linter and reason" + reset + "\n  Write //nolint:<linter> // <why the discard is correct>", nil},
		{regexp.MustCompile(`(?m)^func init\(\)[\s\S]{0,500}(Register|Subscribe|Add[A-Za-z]*Handler|Hook)`), 2, red + bold + "❌ BLOCKED: Implicit behavior in init()" + reset, func(c context) bool { return strings.HasPrefix(filepath.Base(c.path), "register") }},
		{regexp.MustCompile(`switch\s+args\[0\]`), 2, red + bold + "❌ BLOCKED: switch-based command dispatch in " + path + reset, nil},
		{regexp.MustCompile(`(?m)^\s*go\s+func\s*\(`), 2, red + bold + "❌ BLOCKED: anonymous goroutine" + reset, nil},
		{regexp.MustCompile(`BufHandle\{[^}]*Buf:[ \t]*make`), 2, red + bold + "BLOCKED: fake BufHandle construction in " + path + reset, nil},
	}
	for _, candidate := range patterns {
		if candidate.exempt != nil && candidate.exempt(ctx) {
			continue
		}
		if candidate.pattern.MatchString(ctx.content) {
			if strings.Contains(candidate.message, "panic") && regexp.MustCompile(`panic\([ \t]*"(unreachable|not implemented|unimplemented|TODO|BUG|impossible)`).MatchString(ctx.content) {
				continue
			}
			return &verdict{candidate.code, candidate.message}
		}
	}
	return nil
}

// ze point: architecture/directives/load-ze-context-before-any-design-decision
// ze point: testing/temporary-files/use-project-tmp-for-scratch-files
// ze point: commands/write-ad-hoc-scratch-under-your-per-session-dir/write-ad-hoc-scratch-under-this-session-s-private-directory
// ze point: quality/linting/fix-lint-issues-never-disable-a-linter
// ze point: config/directives/manipulate-config-only-by-the-two-approved-methods
// writeFilePatterns refuses the file-level patterns the rules ban, by path.
func writeFilePatterns(ctx context) *verdict {
	path := filepath.ToSlash(ctx.path)
	base := filepath.Base(path)
	if ctx.tool == toolWrite {
		if strings.Contains(path, ".claude/plans/") {
			return &verdict{2, "❌ BLOCKED: Do not use .claude/plans/\n  Write plans to .claude/plan/ze-plan-<name> instead."}
		}
		if strings.Contains(path, ".claude/plan/") && !strings.HasPrefix(base, "ze-plan-") {
			return &verdict{2, "❌ BLOCKED: Plan file must be named 'ze-plan-<name>'\n  Got: " + base}
		}
		if strings.HasSuffix(path, ".go") && (strings.Contains(path, "/utils/") || strings.Contains(path, "/helpers/") || strings.Contains(path, "/common/") || strings.Contains(path, "/misc/") || regexp.MustCompile(`(?m)^package[ \t]+(utils|helpers|common|misc)[ \t]*$`).MatchString(ctx.content)) {
			return &verdict{2, red + bold + "❌ BLOCKED: Forbidden package pattern" + reset}
		}
		if _, err := os.Stat(absolutePath(ctx)); os.IsNotExist(err) {
			if strings.HasSuffix(base, ".md") && (strings.Contains(base, "_") || regexp.MustCompile(`[A-Z]`).MatchString(base)) && !regexp.MustCompile(`^(README|INDEX|CLAUDE|LICENSE|CONTRIBUTING|CHANGELOG)\.md$`).MatchString(base) {
				return &verdict{1, red + bold + "❌ BLOCKED: Naming convention violation" + reset + "\n  File: " + base}
			}
			if strings.HasSuffix(base, ".go") && (strings.Contains(base, "-") || regexp.MustCompile(`^[A-Z]`).MatchString(base)) {
				return &verdict{1, red + bold + "❌ BLOCKED: Naming convention violation" + reset + "\n  File: " + base}
			}
		}
	}
	if strings.HasPrefix(path, "/tmp/") || path == "/tmp" {
		return &verdict{2, "❌ Blocked: /tmp access is forbidden\nUse this session's own scratch dir instead."}
	}
	if isAdHocScratch(path, ctx.root) {
		return &verdict{2, scratchMessage(path) + "\n  Use this session's private scratch directory: ./le session scratch ensure"}
	}
	if strings.HasSuffix(path, ".ci") && strings.Contains(ctx.content, "sys.exit(1)") && !strings.Contains(ctx.content, "runtime_fail") && !regexp.MustCompile(`(?m)^(expect|reject)=stderr`).MatchString(ctx.content) {
		return &verdict{1, yellow + bold + "WARN: observer-exit antipattern in " + path + reset}
	}
	if oneOf(ctx.tool, toolWrite, "Edit") && (strings.Contains(path, ".golangci") || strings.Contains(path, "golangci.yml") || strings.Contains(path, "golangci.yaml")) && regexp.MustCompile(`exclude-rules:|issues-exclude:|skip-files:|skip-dirs:`).MatchString(ctx.content) {
		return &verdict{2, red + bold + "❌ BLOCKED: Adding linter exclusions" + reset}
	}
	if oneOf(ctx.tool, toolWrite, "Edit") && (strings.Contains(path, "/config/") || strings.HasSuffix(path, ".conf") || strings.Contains(base, "config")) && regexp.MustCompile(`(?i)(config.?version|schema.?version|"version"[ \t]*:|version[ \t]*[=:][ \t]*[0-9])`).MatchString(ctx.content) {
		return &verdict{2, red + bold + "❌ BLOCKED: Version in config" + reset}
	}
	return nil
}

// ze point: testing/rfc-tagged-tests-blocking/never-edit-an-rfc-tagged-test-to-match-the-code
// ze point: testing/directives/write-the-test-first-and-never-weaken-it
// ze point: testing/fix-code-not-tests/fix-the-code-when-a-test-fails-not-the-test
// writeWeakening refuses a proposed edit that lowers what a test proves.
func writeWeakening(ctx context) *verdict {
	if !oneOf(ctx.tool, toolWrite, "Edit", "MultiEdit") || strings.Contains(filepath.ToSlash(ctx.path), "test/draft/") {
		return nil
	}
	request := testweakened.ProposedRequest{Path: ctx.path, Tool: ctx.tool, ToolInput: testweakened.ProposedToolInput{
		FilePath: ctx.path, Content: stringInput(ctx.input, "content"), OldString: stringInput(ctx.input, "old_string"), NewString: stringInput(ctx.input, "new_string"),
	}}
	if value, ok := ctx.input["replace_all"].(bool); ok {
		request.ToolInput.ReplaceAll = value
	}
	edits, _ := ctx.input["edits"].([]any)
	for _, raw := range edits {
		edit, _ := raw.(map[string]any)
		request.ToolInput.Edits = append(request.ToolInput.Edits, testweakened.ProposedEdit{OldString: stringInput(edit, "old_string"), NewString: stringInput(edit, "new_string")})
	}
	encoded, err := json.Marshal(request)
	if err != nil {
		return &verdict{2, red + bold + "BLOCKED: native weakening check could not run" + reset}
	}
	report, err := testweakened.Proposed(ctx.root, bytes.NewReader(encoded))
	if err != nil {
		return &verdict{2, red + bold + "BLOCKED: native weakening check could not judge " + ctx.path + reset + "\n  " + err.Error()}
	}
	if report.Blocking {
		return &verdict{2, red + bold + "BLOCKED: proposed test evidence change is not authorized" + reset + "\n" + report.Text()}
	}
	if report.Notice {
		return &verdict{1, yellow + bold + "NOTICE: proposed edit lowers a test count" + reset + "\n" + report.Text()}
	}
	return nil
}

// ze point: testing/ci-sleep-justification/justify-every-sleep-in-a-ci-test
// writeCISleep refuses a sleep in a .ci test that names no sleep kind.
func writeCISleep(ctx context) *verdict {
	path := filepath.ToSlash(ctx.path)
	if !strings.HasSuffix(path, ".ci") || !strings.Contains(path, "/test/") {
		return nil
	}
	marker := regexp.MustCompile(`#\s*sleep\(\s*(poll-interval|timer|timeout-under-test|needs-linux|no-signal)\s*\)\s*:\s*\S`)
	lines := strings.Split(ctx.content, "\n")
	bad := make([]string, 0, 4)
	for index, line := range lines {
		if !strings.Contains(line, "time.sleep(") || strings.HasPrefix(strings.TrimSpace(line), "#") || marker.MatchString(line) {
			continue
		}
		if index > 0 && marker.MatchString(lines[index-1]) {
			continue
		}
		bad = append(bad, fmt.Sprintf("  +%d: %s", index+1, strings.TrimSpace(line)))
	}
	if len(bad) == 0 {
		return nil
	}
	return &verdict{2, red + bold + "BLOCKED: time.sleep( with no sleep(<kind>) marker in " + path + reset + "\n" + strings.Join(bad, "\n")}
}

// yangSummaryChars bounds a YANG description statement, in characters.
// overlayInnerWidth clamps every Ze overlay box to [48, 96] characters
// (internal/component/cli/model_render.go), so a summary longer than this
// cannot render whole in any of them.
//
// The bound therefore governs the statements that REACH a one-line row.
// It governs no others (plan/spec-command-help-and-description.md, "What the
// Bounds Govern"). A module, a revision and an import declare schema
// documentation that no operator surface renders. 116 of the 640 over-long
// descriptions measured on 2026-09-03 were of that kind.
//
// Holding one to this bound invites the repair three agents each made under a
// brief that did not say so. Each moved the prose into a `//` comment. Standard
// YANG tooling cannot read a comment, and the schema output does not publish
// one.
const yangSummaryChars = 96

// yangRendering names the statements whose description reaches a one-line
// operator surface. The table is the spec's. It is the whole population that
// the character bound and the word bound govern.
var yangRendering = [...]string{
	"container", "list", "leaf", "leaf-list", "choice", "case",
	"action", "rpc", "notification",
}

// The rules a proposed YANG description is held to. Each is named on its own
// line of a refusal. The author is told which bound was passed, and not that
// something about the text is wrong.
const (
	yangRuleCharCap  = "char-cap"
	yangRuleWordCap  = "word-cap"
	yangRuleShape    = "shape"
	yangRuleRestates = "long-restates-summary"
)

// yangKeywordHelp is the extension that carries the long explanation, and
// yangKeywordSummary the statement that carries the one-line summary.
const (
	yangKeywordHelp    = "ze:help"
	yangKeywordSummary = "description"
)

// yangBlock is one open brace. It carries the keyword that opened it and the
// whole statement as the author wrote it. The identity stays unique when two
// blocks carry the same name.
type yangBlock struct {
	id      int
	keyword string
	name    string
}

// yangText is one `description` or `ze:help` argument read out of proposed
// text. It carries the keyword, the block that held it, the statement that
// named that block, and the argument itself. The argument arrives with its
// concatenation joined and its whitespace collapsed.
//
// Owned says whether the scan found the enclosing statement at all. An Edit
// region can carry a description and no statement around it. A text whose owner
// is unknown is REPORTED rather than judged, because nothing says which surface
// renders it (ai/rules/principles.md).
type yangText struct {
	keyword string
	block   int
	node    string
	owner   string
	owned   bool
	text    string
}

// yangArgument names the two statements a command module turns into a typed
// argument, where the text beside them is dropped.
var yangArgument = [...]string{"leaf", "leaf-list"}

// yangArgumentModule answers whether the module declares command arguments
// rather than config nodes. The file name is what separates the two producers
// at the level this hook reads.
func yangArgumentModule(path string) bool {
	return strings.HasSuffix(path, "-cmd.yang") || strings.HasSuffix(path, "-api.yang")
}

// yangRenders answers whether a description on this statement reaches a
// one-line operator surface. The statement decides it. For a leaf and a
// leaf-list, the module the statement sits in decides it too.
//
// extractArgDefs (internal/component/config/yang/command.go) walks every child
// of a command container and calls argDefFor, which admits any entry with a
// type. A leaf and a leaf-list each have one, so both become a command.ArgDef
// built from Type and Mandatory. ArgDef declares nine fields and none of them
// holds text, so the description is dropped at the tree boundary. The same
// statement in a config module renders on the completion row, through
// entryDescription (internal/component/cli/completer.go).
func yangRenders(path, keyword string) bool {
	if !slices.Contains(yangRendering[:], keyword) {
		return false
	}
	if !slices.Contains(yangArgument[:], keyword) {
		return true
	}
	return !yangArgumentModule(path)
}

// yangEscape answers the byte a backslash escape stands for. YANG names \n and
// \t. Every other escape stands for the character itself.
func yangEscape(char byte) byte {
	switch char {
	case 'n':
		return '\n'
	case 't':
		return '\t'
	}
	return char
}

// readYangString reads the quoted string that starts at index and answers its
// text, the index after the closing quote, and whether the quote closed. A
// single-quoted YANG string carries no escape, which is why the quote decides
// whether a backslash is read as one.
func readYangString(content string, index int) (string, int, bool) {
	quote := content[index]
	var text textbuf.Buffer
	text.Reset()
	for cursor := index + 1; cursor < len(content); cursor++ {
		if content[cursor] == '\\' && quote == '"' && cursor+1 < len(content) {
			cursor++
			text.Byte(yangEscape(content[cursor]))
			continue
		}
		if content[cursor] == quote {
			return text.String(), cursor + 1, true
		}
		text.Byte(content[cursor])
	}
	return "", len(content), false
}

// readYangToken reads one unquoted token and answers the index after it.
func readYangToken(content string, index int) (string, int) {
	for cursor := index; cursor < len(content); cursor++ {
		if strings.IndexByte(" \t\r\n;{}\"'", content[cursor]) >= 0 {
			return content[index:cursor], cursor
		}
	}
	return content[index:], len(content)
}

// yangSpaced collapses every run of whitespace to one space and trims the
// ends. That is how a description reads on a one-line surface, whatever wrapping
// the author gave it in the module.
func yangSpaced(text string) string {
	return strings.Join(strings.Fields(text), " ")
}

// scanYangText reads every `description` and `ze:help` argument out of proposed
// YANG text, lexically.
//
// It loads no YANG model. The hook judges one file that is not on disk yet.
// A module whose imports the loader cannot resolve still has to be judged.
// `./le docvalid help-shape` is the gate that reads the built tree.
//
// A string or a comment that never closes is an ERROR rather than an empty
// answer. The content can be one Edit fragment. A scan that stopped early must
// not read as a file that broke no rule (ai/rules/principles.md).
func scanYangText(content string) ([]yangText, error) {
	found := make([]yangText, 0, 8)
	stack := make([]yangBlock, 0, 8)
	blocks := 0
	keyword := ""
	var argument textbuf.Buffer
	argument.Reset()

	for cursor := 0; cursor < len(content); {
		char := content[cursor]

		if char == ' ' || char == '\t' || char == '\r' || char == '\n' {
			cursor++
			continue
		}
		if char == '/' && cursor+1 < len(content) && content[cursor+1] == '/' {
			end := strings.IndexByte(content[cursor:], '\n')
			if end < 0 {
				break
			}
			cursor += end + 1
			continue
		}
		if char == '/' && cursor+1 < len(content) && content[cursor+1] == '*' {
			end := strings.Index(content[cursor+2:], "*/")
			if end < 0 {
				return nil, errors.New("a block comment is never closed")
			}
			cursor += end + 4
			continue
		}
		if char == '"' || char == '\'' {
			text, next, closed := readYangString(content, cursor)
			if !closed {
				return nil, errors.New("a quoted string is never closed")
			}
			argument.Str(text)
			cursor = next
			continue
		}
		if char == '{' {
			blocks++
			stack = append(stack, yangBlock{id: blocks, keyword: keyword, name: yangSpaced(keyword + " " + argument.String())})
			keyword = ""
			argument.Reset()
			cursor++
			continue
		}
		if char == '}' {
			if len(stack) != 0 {
				stack = stack[:len(stack)-1]
			}
			keyword = ""
			argument.Reset()
			cursor++
			continue
		}
		if char == ';' {
			found = appendYangText(found, stack, keyword, argument.String())
			keyword = ""
			argument.Reset()
			cursor++
			continue
		}
		// A `+` joins two quoted parts of one argument, so it carries no text.
		if char == '+' {
			cursor++
			continue
		}
		token, next := readYangToken(content, cursor)
		if keyword == "" {
			keyword = token
		} else {
			argument.Str(token)
		}
		cursor = next
	}
	// An Edit fragment can end before the semicolon that closes its statement.
	// The text read so far is what the author proposed, so it is judged.
	return appendYangText(found, stack, keyword, argument.String()), nil
}

// appendYangText records one finished statement when it is a summary or a long
// help carrying text. An empty argument is left out. `./le docvalid help-shape`
// owns the `missing-summary` rule, and a fragment can end before its author
// typed the text.
func appendYangText(found []yangText, stack []yangBlock, keyword, argument string) []yangText {
	if keyword != yangKeywordSummary && keyword != yangKeywordHelp {
		return found
	}
	text := yangSpaced(argument)
	if text == "" {
		return found
	}
	entry := yangText{keyword: keyword, text: text}
	if len(stack) != 0 {
		entry.block = stack[len(stack)-1].id
		entry.node = stack[len(stack)-1].name
		entry.owner = stack[len(stack)-1].keyword
		entry.owned = true
	}
	return append(found, entry)
}

// yangFinding writes one refusal line: the node the text belongs to, the rule
// it broke, and what was measured beside the bound.
func yangFinding(text yangText, rule, detail string) string {
	return "  " + text.node + ": " + rule + ", " + detail
}

// judgeYangSummary answers every rule one description breaks.
func judgeYangSummary(text yangText) []string {
	bad := make([]string, 0, 4)
	if count := utf8.RuneCountInString(text.text); count > yangSummaryChars {
		bad = append(bad, yangFinding(text, yangRuleCharCap, fmt.Sprintf("%d characters, and the bound is %d", count, yangSummaryChars)))
	}
	if count := ste.WordCount(text.text); count > ste.MaxDescriptiveWords {
		bad = append(bad, yangFinding(text, yangRuleWordCap, fmt.Sprintf("%d words, and the bound is %d", count, ste.MaxDescriptiveWords)))
	}
	if strings.Contains(text.text, ";") {
		bad = append(bad, yangFinding(text, yangRuleShape, "the summary joins two statements with a semicolon"))
	}
	if !strings.HasSuffix(text.text, ".") {
		bad = append(bad, yangFinding(text, yangRuleShape, "the summary does not end in a full stop"))
	}
	return bad
}

// ze point: writing/directives/project-text-is-us-english-and-simplified-technical-english
// ze point: writing/detail-budget/write-only-what-changes-the-next-action
// writeYangDescription warns when a proposed YANG description is too long for
// the one-line surface that renders it. It warns again when the ze:help beside
// that description only repeats it.
func writeYangDescription(ctx context) *verdict {
	path := filepath.ToSlash(ctx.path)
	if !strings.HasSuffix(path, ".yang") || strings.TrimSpace(ctx.content) == "" {
		return nil
	}
	texts, err := scanYangText(ctx.content)
	if err != nil {
		return &verdict{1, yellow + bold + "WARN: the proposed text of " + path + " does not read as YANG" + reset +
			"\n  " + err.Error() + ", so no description in it was judged.\n" +
			"  Run ./le docvalid help-shape after the edit: it reads the built tree, and this hook reads one file."}
	}

	summaries := make(map[int]string, len(texts))
	bad := make([]string, 0, 4)
	unowned := 0
	for _, text := range texts {
		if text.keyword != yangKeywordSummary {
			continue
		}
		summaries[text.block] = text.text
		if !text.owned {
			unowned++
			continue
		}
		if !yangRenders(path, text.owner) {
			continue
		}
		bad = append(bad, judgeYangSummary(text)...)
	}
	for _, text := range texts {
		if text.keyword != yangKeywordHelp || !text.owned {
			continue
		}
		// Byte equality after the whitespace collapse, so a copy that was
		// rewrapped over more lines is still read as the copy it is.
		if beside, ok := summaries[text.block]; ok && beside == text.text {
			bad = append(bad, yangFinding(text, yangRuleRestates, "the ze:help repeats the description word for word"))
		}
	}
	if unowned == 1 {
		bad = append(bad, "  one description was NOT judged: the proposed text names no statement around it, so nothing says which surface renders it.")
	}
	if unowned > 1 {
		bad = append(bad, fmt.Sprintf("  %d descriptions were NOT judged: the proposed text names no statement around them, so nothing says which surface renders them.", unowned))
	}
	if len(bad) == 0 {
		return nil
	}
	shown := bad[:min(4, len(bad))]
	more := ""
	if len(shown) != len(bad) {
		more = fmt.Sprintf("\n  %d more findings are not shown.", len(bad)-len(shown))
	}
	return &verdict{1, yellow + bold + "WARN: a description in " + path + " breaks the summary rules" + reset + "\n" +
		strings.Join(shown, "\n") + more +
		"\n  Write the one-line summary in `description`, and the paragraph in the `ze:help` beside it.\n" +
		"  The bounds hold the statements that render on a one-line row.\n" +
		"  Those are container, list, leaf, leaf-list, choice, case, action, rpc and notification.\n" +
		"  A leaf and a leaf-list count in a config module alone, because a command module drops the text beside them.\n" +
		"  ./le docvalid help-shape is the gate over the whole tree; this hook reads one proposed file."}
}
