// Design: docs/architecture/core-design.md -- native edit hook policy
package hookruntime

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/ze-software/ze/internal/le/testweakened"
)

var (
	lineCitation = regexp.MustCompile(`(^|[^A-Za-z0-9_])([A-Za-z0-9_./-]+\.(?:go|sh|md|mk|yang|ci|et|json|txt|c|h|cc|cpp|rs|java|ts|js)):[0-9]+(?:-[0-9]+)?`)
	lineAnchor   = regexp.MustCompile(`https?://\S*?(#L\d+(?:[-L]\d+)?)`)
	upperRFC     = regexp.MustCompile(`\b(?:MUST NOT|SHALL NOT|SHOULD NOT|NOT RECOMMENDED|MUST|SHALL|REQUIRED|SHOULD|RECOMMENDED|MAY|OPTIONAL)\b`)
	lowerModal   = regexp.MustCompile(`(^|[^A-Za-z0-9_-])(must|shall|should|may)([^A-Za-z0-9_-]|$)`)
)

type editPattern struct {
	pattern *regexp.Regexp
	code    int
	message string
	exempt  func(context) bool
}

func absolutePath(ctx context) string {
	if filepath.IsAbs(ctx.path) {
		return filepath.Clean(ctx.path)
	}
	return filepath.Join(ctx.root, filepath.Clean(ctx.path))
}

func relativePath(ctx context) string {
	relative, err := filepath.Rel(ctx.root, absolutePath(ctx))
	if err != nil {
		return filepath.ToSlash(ctx.path)
	}
	return filepath.ToSlash(relative)
}

// ze point: writing/detail-budget/write-only-what-changes-the-next-action
// ze point: evidence/no-fabrication/cite-a-line-number-only-when-a-generator-maintains-it
// writeLineCitation refuses a line-number citation in repository prose.
func writeLineCitation(ctx context) *verdict {
	if !strings.HasSuffix(ctx.path, ".md") {
		return nil
	}
	relative := relativePath(ctx)
	if !anyPrefix(relative, "ai/", "docs/", "plan/", ".claude/") {
		return nil
	}
	head := strings.Join(strings.Split(ctx.content, "\n")[:min(10, len(strings.Split(ctx.content, "\n")))], "\n")
	if regexp.MustCompile(`(?i)(GENERATED|generated by)`).MatchString(head) && strings.Contains(strings.ToLower(head), "do not edit") {
		return nil
	}
	bad := make([]string, 0, 4)
	fence := false
	for index, line := range strings.Split(ctx.content, "\n") {
		if strings.HasPrefix(strings.TrimLeft(line, " \t"), "```") {
			fence = !fence
			continue
		}
		if fence {
			continue
		}
		for _, match := range lineCitation.FindAllStringSubmatch(line, -1) {
			if !strings.HasPrefix(match[2], "rfc/full/") {
				bad = append(bad, fmt.Sprintf("  +%d: %s", index+1, strings.TrimSpace(match[0])))
			}
		}
		for _, match := range lineAnchor.FindAllStringSubmatch(line, -1) {
			bad = append(bad, fmt.Sprintf("  +%d: %s", index+1, match[1]))
		}
	}
	if len(bad) == 0 {
		return nil
	}
	return &verdict{2, red + bold + "❌ BLOCKED: line-number citation in prose" + reset + "\n" + strings.Join(bad[:min(4, len(bad))], "\n") +
		"\n  Cite the file and the SYMBOL, not the line: `session.go`, `handleOpen()`.\n  A line number is right only when the line itself IS the fact, and then it belongs in a fenced block as quoted output. See ai/rules/writing.md."}
}

// ze point: repo-maintenance/canonical-sources-and-sync-direction/edit-the-canonical-source-not-the-generated-file
// ze point: repo-maintenance/canonical-sources-and-sync-direction/sync-generated-files-from-their-canonical-source
// ze point: repo-maintenance/canonical-sources-and-sync-direction/keep-shared-rules-in-ai-rules-and-render-them
// writeGenerated refuses an edit to a generated file, and names its source.
func writeGenerated(ctx context) *verdict {
	if !oneOf(ctx.tool, toolWrite, "Edit") {
		return nil
	}
	relative := relativePath(ctx)
	if relative == "CLAUDE.md" || relative == "AGENTS.md" {
		base := filepath.Base(relative)
		return &verdict{2, "BLOCKED: " + base + " is generated\n  " + base + " is auto-generated. Edit the canonical source instead:\n    ai/INSTRUCTIONS.md  (then run the native sync action)\n  See ai/rules/repo-maintenance.md"}
	}
	parts := strings.Split(relative, "/")
	if len(parts) >= 3 && parts[0] == ".claude" {
		if info, err := os.Stat(filepath.Join(ctx.root, "ai", parts[1])); err == nil && info.IsDir() {
			return &verdict{1, yellow + bold + "WARN: " + relative + " is read by this tool alone; ai/" + parts[1] + "/ is the shared home" + reset + "\n  ai/INSTRUCTIONS.md generates BOTH CLAUDE.md and AGENTS.md, so an instruction that binds every agent belongs in the shared tree."}
		}
	}
	return nil
}

// ze point: repo-maintenance/canonical-sources-and-sync-direction/keep-shared-rules-in-ai-rules-and-render-them
// ze point: repo-maintenance/canonical-sources-and-sync-direction/sync-generated-files-from-their-canonical-source
// writeRenderedRule refuses an edit to a rendered rule, which points/ owns.
func writeRenderedRule(ctx context) *verdict {
	if !oneOf(ctx.tool, toolWrite, "Edit", "MultiEdit") {
		return nil
	}
	relative := relativePath(ctx)
	if !strings.HasPrefix(relative, "ai/rules/") {
		return nil
	}
	tail := strings.TrimPrefix(relative, "ai/rules/")
	if strings.Contains(tail, "/") || !strings.HasSuffix(tail, ".md") {
		return nil
	}
	return &verdict{2, red + bold + "❌ BLOCKED: ai/rules/" + tail + " is generated" + reset +
		"\n  Edit the rule's point under ai/rules/points/<rule>/, then run the native rules render action.\n  See ai/rules/repo-maintenance.md, Canonical Sources and Sync Direction"}
}

// ze point: never-destroy-work/forbidden-without-explicit-permission/ask-before-deleting-or-overwriting-user-work
// writePointOverwrite refuses a Write that replaces an existing rule point.
func writePointOverwrite(ctx context) *verdict {
	replaces := ctx.tool == toolWrite
	if ctx.tool == "MultiEdit" {
		edits, _ := ctx.input["edits"].([]any)
		for _, raw := range edits {
			edit, _ := raw.(map[string]any)
			if stringInput(edit, "old_string") == "" {
				replaces = true
			}
		}
	}
	if !replaces {
		return nil
	}
	relative := relativePath(ctx)
	parts := strings.Split(strings.TrimPrefix(relative, "ai/rules/points/"), "/")
	canonical := strings.HasPrefix(relative, "ai/rules/points/") && ((len(parts) == 2 && parts[1] == "manifest.md") || len(parts) == 3)
	if !canonical {
		return nil
	}
	if info, err := os.Stat(absolutePath(ctx)); err != nil || !info.Mode().IsRegular() {
		return nil
	}
	return &verdict{2, red + bold + "❌ BLOCKED: Write over an existing rule point" + reset + "\n  " + relative + " already exists and carries one instruction of the rule.\n  A Write replaces the whole file. Edit the existing point or write a free slug.\n  See ai/rules/never-destroy-work.md and docs/contributing/rule-authoring.md"}
}

func visibleMarkdown(text string) string {
	var visible strings.Builder
	fence := false
	for line := range strings.SplitSeq(text, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			fence = !fence
			continue
		}
		if fence || strings.HasPrefix(trimmed, ">") {
			continue
		}
		line = regexp.MustCompile("`[^`]*`").ReplaceAllString(line, "")
		visible.WriteString(line)
		visible.WriteByte('\n')
	}
	return visible.String()
}

// ze point: rule-format/every-directive-states-a-level/every-directive-states-its-rfc-2119-level
// writePointLanguage refuses a rule directive that states no RFC 2119 level.
func writePointLanguage(ctx context) *verdict {
	relative := relativePath(ctx)
	parts := strings.Split(strings.TrimPrefix(relative, "ai/rules/points/"), "/")
	if !strings.HasPrefix(relative, "ai/rules/points/") || len(parts) != 3 || ctx.content == "" {
		return nil
	}
	directive := regexp.MustCompile(`(?m)^kind:[ \t]*directive[ \t]*$`).MatchString(ctx.content)
	if ctx.tool != toolWrite {
		body, err := os.ReadFile(absolutePath(ctx))
		directive = err == nil && regexp.MustCompile(`(?m)^kind:[ \t]*directive[ \t]*$`).Match(body[:min(400, len(body))])
	}
	if !directive {
		return nil
	}
	visible := visibleMarkdown(ctx.content)
	matches := lowerModal.FindAllStringSubmatch(visible, -1)
	if len(matches) != 0 {
		words := make([]string, 0, len(matches))
		for _, match := range matches {
			words = append(words, match[2])
		}
		sort.Strings(words)
		return &verdict{2, red + bold + "❌ BLOCKED: lowercase obligation word in a rule directive" + reset + "\n  " + relative + " states " + strings.Join(words, ", ") + " in lowercase.\n  Use MUST, MUST NOT, SHOULD, SHOULD NOT, or MAY."}
	}
	if ctx.tool == toolWrite && !upperRFC.MatchString(visible) {
		return &verdict{2, red + bold + "❌ BLOCKED: rule directive states no RFC 2119 level" + reset + "\n  " + relative + " declares `kind: directive` and states no capitalised keyword."}
	}
	return nil
}

// ze point: evidence/no-fabrication/investigate-source-in-session-before-writing-a-spec
// ze point: evidence/no-fabrication/read-the-producing-code-before-claiming-behavior
// writeDesignEvidence refuses a spec or design written before its source was read.
func writeDesignEvidence(ctx context) *verdict {
	relative := relativePath(ctx)
	if !anyPrefix(relative, "plan/spec-", "plan/design-", ".claude/plan/") {
		return nil
	}
	id := resolvedSessionID(ctx)
	if id == "" {
		return &verdict{2, "❌ BLOCKED: cannot resolve this session id; design evidence is fail-closed"}
	}
	if _, err := os.Stat(filepath.Join(ctx.root, "tmp", "session", ".lsp-invoked-"+id)); err == nil {
		return nil
	}
	entries, _ := filepath.Glob(filepath.Join(ctx.root, "tmp", "session", ".source-read-*-"+id))
	if len(entries) != 0 {
		return nil
	}
	return &verdict{2, "❌ BLOCKED: read the producing source before writing a design/spec\n  Use Read or LSP on the implementation this session, then retry.\n  ai/rules/evidence.md"}
}

// ze point: planning/spec-metadata-blocking/update-spec-status-at-each-transition
// writeSpecStatus refuses a source edit while the claimed spec is not in-progress.
func writeSpecStatus(ctx context) *verdict {
	if !strings.HasSuffix(ctx.path, ".go") || !oneOf(ctx.tool, toolWrite, "Edit", "MultiEdit") {
		return nil
	}
	id := resolvedSessionID(ctx)
	if id == "" {
		return nil
	}
	marker := filepath.Join(ctx.root, "tmp", "session", ".session-"+id)
	body, err := os.ReadFile(marker) //nolint:gosec // a session marker under the checkout tmp directory
	if err != nil {
		return nil
	}
	spec := strings.TrimSpace(string(body))
	if spec == "" || spec == specUnassigned {
		return nil
	}
	specBody, err := os.ReadFile(filepath.Join(ctx.root, "plan", spec)) //nolint:gosec // the claimed spec lives under the checkout plan directory
	if err != nil {
		return nil
	}
	text := string(specBody)
	if !strings.Contains(text, "| Status | in-progress |") && !strings.Contains(text, "| Status | verification |") {
		return &verdict{2, "❌ BLOCKED: source edit while selected spec is not in-progress\n  Update the spec status before implementation."}
	}
	return nil
}

func goEdit(ctx context) bool {
	return oneOf(ctx.tool, toolWrite, "Edit") && strings.HasSuffix(ctx.path, ".go")
}

// ze point: architecture/design-principles/apply-these-design-principles-to-every-decision
// ze point: cli/cli-patterns/return-exit-codes-and-write-errors-to-stderr
// ze point: go-standards/directives/never-write-these-forbidden-go-patterns
// ze point: go-standards/directives/log-through-slog-never-printf
// ze point: performance/three-rules/never-use-fmt-or-string-on-a-hot-path
// ze point: performance/directives/write-wire-encoding-into-pooled-bounded-buffers
// ze point: quality/linting/fix-lint-issues-never-disable-a-linter
// ze point: plugins/registration-based-dispatch/dispatch-subcommands-by-registration-not-switch
// ze point: goroutine-lifecycle/directives/keep-every-goroutine-a-long-lived-worker
// ze point: performance/common-mistakes/fix-these-common-allocation-mistakes
// writeGoPatterns refuses the Go patterns the rules ban, file by file.
func writeGoPatterns(ctx context) *verdict {
	if !goEdit(ctx) {
		return nil
	}
	path := filepath.ToSlash(ctx.path)
	if strings.HasSuffix(path, "_test.go") {
		return nil
	}
	// This file DECLARES the banned patterns, so it holds every one of them as a
	// literal. Judging it by its own list refuses the edit that repairs the list,
	// which is how a wrong pattern here becomes permanent. The links checker
	// excludes its own source for the same reason (sweepExcluded,
	// internal/le/doccheck/links.go). The exclusion is by suffix, so a checkout at
	// any path is covered.
	if strings.HasSuffix(path, "/internal/le/hookruntime/writeedit.go") {
		return nil
	}
	patterns := []editPattern{
		{regexp.MustCompile(`(?m)^func[ \t]+(?:\([^)]+\)[ \t]+)?[A-Z][A-Za-z]*And[A-Z]`), 1, red + bold + "❌ BLOCKED: Single responsibility violation" + reset + " (function with 'And' in name)", nil},
		{regexp.MustCompile(`os\.Exit\(`), 2, red + bold + "❌ BLOCKED: os.Exit() in handler" + reset + "\n  Return an error instead.", func(c context) bool {
			return strings.HasSuffix(c.path, "/main.go") || strings.HasSuffix(c.path, "/register.go")
		}},
		{regexp.MustCompile(`(^|[^A-Za-z0-9_])panic[ \t]*\(`), 2, red + "❌ Return error, don't panic()" + reset, nil},
		{regexp.MustCompile(`(?m)(^|[^A-Za-z0-9_])log\.(Print|Printf|Println|Fatal|Fatalf|Fatalln|Panic|Panicf|Panicln)`), 2, red + "❌ Use slog, not log package" + reset, nil},
		{regexp.MustCompile(`fmt\.(Sprintf|Fprintf|Printf)\(|strconv\.Format(Uint|Int)\(`), 2, red + bold + "✘ BLOCKED: allocation-heavy string formatting" + reset, nil},
		// Two bad shapes, matched positively because RE2 has no negative lookahead.
		// First: a BARE nolint, with or without prose after it, which suppresses
		// every linter. Second: a nolint that names its linters and then states no
		// reason, either at end of line or with an empty trailing comment.
		// `//nolint:gosec // <reason>` matches neither and is the form the style
		// guide requires; the previous pattern refused it along with the rest, so
		// the only spelling this rule exists to ALLOW was the one it blocked.
		{regexp.MustCompile(`(?m)//nolint(?:[^:\n]|$)|//nolint:[A-Za-z0-9_,-]*[ \t]*(?://[ \t]*)?$`), 2, red + bold + "❌ BLOCKED: nolint without a specific linter and reason" + reset + "\n  Write //nolint:<linter> // <why the discard is correct>", nil},
		{regexp.MustCompile(`(?m)^func init\(\)[\s\S]{0,500}(Register|Subscribe|Add[A-Za-z]*Handler|Hook)`), 2, red + bold + "❌ BLOCKED: Implicit behavior in init()" + reset, func(c context) bool { return strings.HasPrefix(filepath.Base(c.path), "register") }},
		{regexp.MustCompile(`switch\s+args\[0\]`), 2, red + bold + "❌ BLOCKED: switch-based command dispatch in " + path + reset, nil},
		{regexp.MustCompile(`(?m)^\s*go\s+func\s*\(`), 2, red + bold + "❌ BLOCKED: anonymous goroutine" + reset, nil},
		{regexp.MustCompile(`BufHandle\{[^}]*Buf:[ \t]*make`), 2, red + bold + "BLOCKED: fake BufHandle construction in " + path + reset, nil},
	}
	for _, candidate := range patterns {
		if candidate.exempt != nil && candidate.exempt(ctx) {
			continue
		}
		if candidate.pattern.MatchString(ctx.content) {
			if strings.Contains(candidate.message, "panic") && regexp.MustCompile(`panic\([ \t]*"(unreachable|not implemented|unimplemented|TODO|BUG|impossible)`).MatchString(ctx.content) {
				continue
			}
			return &verdict{candidate.code, candidate.message}
		}
	}
	return nil
}

// ze point: architecture/directives/load-ze-context-before-any-design-decision
// ze point: testing/temporary-files/use-project-tmp-for-scratch-files
// ze point: commands/write-ad-hoc-scratch-under-your-per-session-dir/write-ad-hoc-scratch-under-this-session-s-private-directory
// ze point: quality/linting/fix-lint-issues-never-disable-a-linter
// ze point: config/directives/manipulate-config-only-by-the-two-approved-methods
// writeFilePatterns refuses the file-level patterns the rules ban, by path.
func writeFilePatterns(ctx context) *verdict {
	path := filepath.ToSlash(ctx.path)
	base := filepath.Base(path)
	if ctx.tool == toolWrite {
		if strings.Contains(path, ".claude/plans/") {
			return &verdict{2, "❌ BLOCKED: Do not use .claude/plans/\n  Write plans to .claude/plan/ze-plan-<name> instead."}
		}
		if strings.Contains(path, ".claude/plan/") && !strings.HasPrefix(base, "ze-plan-") {
			return &verdict{2, "❌ BLOCKED: Plan file must be named 'ze-plan-<name>'\n  Got: " + base}
		}
		if strings.HasSuffix(path, ".go") && (strings.Contains(path, "/utils/") || strings.Contains(path, "/helpers/") || strings.Contains(path, "/common/") || strings.Contains(path, "/misc/") || regexp.MustCompile(`(?m)^package[ \t]+(utils|helpers|common|misc)[ \t]*$`).MatchString(ctx.content)) {
			return &verdict{2, red + bold + "❌ BLOCKED: Forbidden package pattern" + reset}
		}
		if _, err := os.Stat(absolutePath(ctx)); os.IsNotExist(err) {
			if strings.HasSuffix(base, ".md") && (strings.Contains(base, "_") || regexp.MustCompile(`[A-Z]`).MatchString(base)) && !regexp.MustCompile(`^(README|INDEX|CLAUDE|LICENSE|CONTRIBUTING|CHANGELOG)\.md$`).MatchString(base) {
				return &verdict{1, red + bold + "❌ BLOCKED: Naming convention violation" + reset + "\n  File: " + base}
			}
			if strings.HasSuffix(base, ".go") && (strings.Contains(base, "-") || regexp.MustCompile(`^[A-Z]`).MatchString(base)) {
				return &verdict{1, red + bold + "❌ BLOCKED: Naming convention violation" + reset + "\n  File: " + base}
			}
		}
	}
	if strings.HasPrefix(path, "/tmp/") || path == "/tmp" {
		return &verdict{2, "❌ Blocked: /tmp access is forbidden\nUse this session's own scratch dir instead."}
	}
	if isAdHocScratch(path, ctx.root) {
		return &verdict{2, scratchMessage(path) + "\n  Use this session's private scratch directory: ./le session scratch ensure"}
	}
	if strings.HasSuffix(path, ".ci") && strings.Contains(ctx.content, "sys.exit(1)") && !strings.Contains(ctx.content, "runtime_fail") && !regexp.MustCompile(`(?m)^(expect|reject)=stderr`).MatchString(ctx.content) {
		return &verdict{1, yellow + bold + "WARN: observer-exit antipattern in " + path + reset}
	}
	if oneOf(ctx.tool, toolWrite, "Edit") && (strings.Contains(path, ".golangci") || strings.Contains(path, "golangci.yml") || strings.Contains(path, "golangci.yaml")) && regexp.MustCompile(`exclude-rules:|issues-exclude:|skip-files:|skip-dirs:`).MatchString(ctx.content) {
		return &verdict{2, red + bold + "❌ BLOCKED: Adding linter exclusions" + reset}
	}
	if oneOf(ctx.tool, toolWrite, "Edit") && (strings.Contains(path, "/config/") || strings.HasSuffix(path, ".conf") || strings.Contains(base, "config")) && regexp.MustCompile(`(?i)(config.?version|schema.?version|"version"[ \t]*:|version[ \t]*[=:][ \t]*[0-9])`).MatchString(ctx.content) {
		return &verdict{2, red + bold + "❌ BLOCKED: Version in config" + reset}
	}
	return nil
}

// ze point: testing/rfc-tagged-tests-blocking/never-edit-an-rfc-tagged-test-to-match-the-code
// ze point: testing/directives/write-the-test-first-and-never-weaken-it
// ze point: testing/fix-code-not-tests/fix-the-code-when-a-test-fails-not-the-test
// writeWeakening refuses a proposed edit that lowers what a test proves.
func writeWeakening(ctx context) *verdict {
	if !oneOf(ctx.tool, toolWrite, "Edit", "MultiEdit") || strings.Contains(filepath.ToSlash(ctx.path), "test/draft/") {
		return nil
	}
	request := testweakened.ProposedRequest{Path: ctx.path, Tool: ctx.tool, ToolInput: testweakened.ProposedToolInput{
		FilePath: ctx.path, Content: stringInput(ctx.input, "content"), OldString: stringInput(ctx.input, "old_string"), NewString: stringInput(ctx.input, "new_string"),
	}}
	if value, ok := ctx.input["replace_all"].(bool); ok {
		request.ToolInput.ReplaceAll = value
	}
	edits, _ := ctx.input["edits"].([]any)
	for _, raw := range edits {
		edit, _ := raw.(map[string]any)
		request.ToolInput.Edits = append(request.ToolInput.Edits, testweakened.ProposedEdit{OldString: stringInput(edit, "old_string"), NewString: stringInput(edit, "new_string")})
	}
	encoded, err := json.Marshal(request)
	if err != nil {
		return &verdict{2, red + bold + "BLOCKED: native weakening check could not run" + reset}
	}
	report, err := testweakened.Proposed(ctx.root, bytes.NewReader(encoded))
	if err != nil {
		return &verdict{2, red + bold + "BLOCKED: native weakening check could not judge " + ctx.path + reset + "\n  " + err.Error()}
	}
	if report.Blocking {
		return &verdict{2, red + bold + "BLOCKED: proposed test evidence change is not authorized" + reset + "\n" + report.Text()}
	}
	if report.Notice {
		return &verdict{1, yellow + bold + "NOTICE: proposed edit lowers a test count" + reset + "\n" + report.Text()}
	}
	return nil
}

// ze point: testing/ci-sleep-justification/justify-every-sleep-in-a-ci-test
// writeCISleep refuses a sleep in a .ci test that names no sleep kind.
func writeCISleep(ctx context) *verdict {
	path := filepath.ToSlash(ctx.path)
	if !strings.HasSuffix(path, ".ci") || !strings.Contains(path, "/test/") {
		return nil
	}
	marker := regexp.MustCompile(`#\s*sleep\(\s*(poll-interval|timer|timeout-under-test|needs-linux|no-signal)\s*\)\s*:\s*\S`)
	lines := strings.Split(ctx.content, "\n")
	bad := make([]string, 0, 4)
	for index, line := range lines {
		if !strings.Contains(line, "time.sleep(") || strings.HasPrefix(strings.TrimSpace(line), "#") || marker.MatchString(line) {
			continue
		}
		if index > 0 && marker.MatchString(lines[index-1]) {
			continue
		}
		bad = append(bad, fmt.Sprintf("  +%d: %s", index+1, strings.TrimSpace(line)))
	}
	if len(bad) == 0 {
		return nil
	}
	return &verdict{2, red + bold + "BLOCKED: time.sleep( with no sleep(<kind>) marker in " + path + reset + "\n" + strings.Join(bad, "\n")}
}
