// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import (
	configyang "github.com/ze-software/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-bgp-cmd-announce-api.yang", ZeBGPCmdAnnounceAPIYANG)
	configyang.RegisterModule("ze-cli-announce-cmd.yang", ZeCliAnnounceCmdYANG)
}
