// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-bgp-cmd-monitor-api.yang
var ZeBGPCmdMonitorAPIYANG string

//go:embed ze-monitor-cmd.yang
var ZeMonitorCmdYANG string
