// Code generated by scripts/codegen/yang_glue.go; DO NOT EDIT.

package yang

import (
	configyang "codeberg.org/thomas-mangin/ze/internal/component/config/yang"
)

func init() {
	configyang.RegisterModule("ze-rsvp-te-cmd.yang", ZeRSVPTECmdYANG)
	configyang.RegisterModule("ze-rsvp-te-conf.yang", ZeRSVPTEConfYANG)
}
