// Design: docs/architecture/command-ownership.md -- the generated composition root
//
// Package pluginimports generates internal/component/plugin/all, the product's
// composition root, from what the tree REGISTERS. It scans for the four kinds
// of package whose init() has to run for a feature to exist:
//
//   - a plugin: any register.go under a plugin search root
//   - a schema package: a yang/ or schema/ register.go importing config/yang
//   - an RPC command package: a file calling pluginserver.RegisterRPCs
//   - an event namespace: a file calling .RegisterNamespace(
//
// A package feature-gates.txt gates leaves the universal all.go for a generated
// all_<tag>.go carrying that tag's //go:build line, so a build without the tag
// drops the package entirely.
//
// EVERY READ FAILURE STOPS THE RUN. A file that the walk lists but cannot read
// cannot safely be treated as a file that imports nothing: doing so can silently
// drop a schema package, RPC package, or event namespace from the composition
// root.
package pluginimports

import (
	"bufio"
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/ze-software/ze/internal/core/textbuf"
	"github.com/ze-software/ze/internal/le/lepath"
)

// allDir is the composition root's package directory, relative to the tree.
const allDir = "internal/component/plugin/all"

// allFile is the universal composition root, relative to the tree.
const allFile = allDir + "/all.go"

// generatedMarker opens every file this tool writes and names the native
// command that reproduces it.
const generatedMarker = "// Code generated by ./le plugin-imports write; DO NOT EDIT."

// pluginDirs are the existing plugin search roots, relative to the tree. A root
// that does not exist is passed over; a root that exists and cannot be walked
// stops the run.
var pluginDirs = []string{
	"internal/component/bfd",
	"internal/component/bgp/plugin",
	"internal/component/bgp/plugins",
	"internal/component/bgp/reactor/filter",
	"internal/component/firewall/plugins",
	"internal/component/iface",
	"internal/component/sysctl",
	"internal/component/sysrib",
	"internal/component/traffic",
	"internal/component/vpp",
	"internal/plugins",
}

// nestedPluginDomains are component domain roots that may own a plugins/
// subtree. Deriving internal/component/<domain>/plugins from these roots lets
// BNG and VPN clustering move many edge plugins without naming individual
// plugin packages here.
var nestedPluginDomains = []string{
	"ike",
	"l2tp",
}

// rpcRoot is the tree scanned for RPC command packages.
const rpcRoot = "internal/component"

// featureGatesManifest is the single source of truth for the compile-out-able
// features, relative to the tree (ai/rules/plugins.md).
const featureGatesManifest = "feature-gates.txt"

// registryPackage is config/yang itself: the registry a schema package
// registers INTO, so never a schema package of its own.
const registryPackage = "component/config/yang"

// The two directory names a YANG schema package is declared under. A register.go
// in either belongs to discoverSchemas; anywhere else it is a plugin.
const (
	schemaDir = "schema"
	yangDir   = "yang"
)

// PluginSearchRoots answers every directory a plugin register.go can sit under,
// relative to the tree.
//
// It is exported because a second tool needs the same answer: the
// process-boundary gate (internal/le/pluginboundary) scans exactly the packages
// that are subject to the internal/external placement choice, which is this
// list. The script it replaces derived the list by REGEX over this generator's
// source text, so that the two could not disagree; a Go call is the same
// guarantee without the parse, and it survives the deletion of the script.
func PluginSearchRoots() []string { return pluginSearchRoots() }

// pluginSearchRoots answers every directory a plugin register.go can sit under.
func pluginSearchRoots() []string {
	roots := make([]string, 0, len(pluginDirs)+len(nestedPluginDomains))
	seen := make(map[string]bool, len(pluginDirs)+len(nestedPluginDomains))

	for _, rel := range pluginDirs {
		if seen[rel] {
			continue
		}
		seen[rel] = true
		roots = append(roots, rel)
	}
	for _, domain := range nestedPluginDomains {
		rel := path.Join("internal/component", domain, "plugins")
		if seen[rel] {
			continue
		}
		seen[rel] = true
		roots = append(roots, rel)
	}

	return roots
}

// loadFeatureTags reads the gate manifest ("<tag> <pkg>" per line) into the
// import-suffix map the generator needs: <pkg> -> tag and <pkg>/yang -> tag.
// The direct entry gates a registration import; the yang entry gates the config
// schema. A feature without one of those packages never matches the
// corresponding discovery list, so deriving both for every entry is safe.
func loadFeatureTags(root string) (map[string]string, error) {
	pathname := filepath.Join(root, featureGatesManifest)

	f, err := os.Open(pathname) //nolint:gosec // a build tool reads the checkout it was pointed at
	if err != nil {
		var tb textbuf.Buffer
		return nil, errors.New(tb.Str("read ").Str(featureGatesManifest).Str(": ").Err(err).String())
	}
	defer f.Close() //nolint:errcheck // read-only

	tags := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			var tb textbuf.Buffer
			return nil, errors.New(tb.Str(featureGatesManifest).Str(": malformed line ").
				Quoted(line).Str(" (want \"<tag> <pkg>\")").String())
		}
		tags[fields[1]] = fields[0]
		tags[path.Join(fields[1], "yang")] = fields[0]
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return tags, nil
}

// tagFor answers the build tag gating importPath, or "" when it is universal.
func tagFor(tags map[string]string, importPath string) string {
	for suffix, tag := range tags {
		if !strings.HasSuffix(importPath, suffix) {
			continue
		}
		// A path boundary before the suffix, or an exact match, so a suffix
		// such as "lg/yang" cannot match an unrelated "...blg/yang".
		boundary := len(importPath) - len(suffix) - 1
		if boundary < 0 || importPath[boundary] == '/' {
			return tag
		}
	}

	return ""
}

// filterTagged removes the gated imports from imps into byTag, and answers the
// universal remainder.
func filterTagged(tags map[string]string, imps []string, byTag map[string][]string) []string {
	kept := make([]string, 0, len(imps))

	for _, imp := range imps {
		if tag := tagFor(tags, imp); tag != "" {
			byTag[tag] = append(byTag[tag], imp)
			continue
		}
		kept = append(kept, imp)
	}

	return kept
}

// fileHolds reports whether any line of path contains substr.
//
// A file that cannot be opened, or whose scan ends early, is an ERROR. Answering
// false there is the fail-open this port exists to close: it is
// indistinguishable from a file that genuinely does not hold the text, and the
// consequence is a package silently missing from the composition root.
func fileHolds(pathname, substr string) (bool, error) {
	f, err := os.Open(pathname) //nolint:gosec // a build tool reads the checkout it was pointed at
	if err != nil {
		return false, err
	}
	defer f.Close() //nolint:errcheck // read-only

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		if strings.Contains(scanner.Text(), substr) {
			return true, nil
		}
	}

	return false, scanner.Err()
}

// callsRegisterRPCs reports whether path holds a CALL to RegisterRPCs, rather
// than a comment about one or the function's own declaration.
func callsRegisterRPCs(pathname string) (bool, error) {
	f, err := os.Open(pathname) //nolint:gosec // a build tool reads the checkout it was pointed at
	if err != nil {
		return false, err
	}
	defer f.Close() //nolint:errcheck // read-only

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "//") {
			continue
		}
		if strings.Contains(line, "RegisterRPCs(") && !strings.Contains(line, "func ") {
			return true, nil
		}
	}

	return false, scanner.Err()
}

// fileImportsPath reports whether file names fragment inside an import
// statement, ignoring comments.
func fileImportsPath(file, fragment string) (bool, error) {
	f, err := os.Open(file) //nolint:gosec // a build tool reads the checkout it was pointed at
	if err != nil {
		return false, err
	}
	defer f.Close() //nolint:errcheck // read-only

	inImport := false
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		switch {
		case strings.HasPrefix(line, "import ("):
			inImport = true
		case inImport && line == ")":
			inImport = false
		case inImport && strings.Contains(line, fragment) && !strings.HasPrefix(line, "//"):
			return true, nil
		case !inImport && strings.HasPrefix(line, "import ") && strings.Contains(line, fragment):
			return true, nil
		}
	}

	return false, scanner.Err()
}

// pkgImportsPath reports whether any non-test .go file of dir imports fragment.
func pkgImportsPath(dir, fragment string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		holds, readErr := fileImportsPath(filepath.Join(dir, name), fragment)
		if readErr != nil {
			return false, readErr
		}
		if holds {
			return true, nil
		}
	}

	return false, nil
}

// isTestTree says whether a path sits under a fixture tree. Fixture packages
// are parser input, not packages Ze registers.
func isTestTree(pathname string) bool {
	pathname = filepath.ToSlash(pathname)
	return strings.Contains(pathname, "/internal/test/") || strings.Contains(pathname, "/testdata/")
}

// importPathOf answers the import path of the directory holding a file.
func importPathOf(root, module, file string) (string, error) {
	rel, err := filepath.Rel(root, filepath.Dir(file))
	if err != nil {
		return "", err
	}

	var tb textbuf.Buffer

	return tb.Str(module).Byte('/').Str(filepath.ToSlash(rel)).String(), nil
}

// discoverPlugins finds plugin packages by their register.go. Any register.go
// that is not in a schema/ or yang/ subdirectory is a plugin registration:
// that catches plugins registering through plugin/registry as well as those
// registering through a component-local mechanism such as iface.RegisterBackend.
func discoverPlugins(root, module string) ([]string, error) {
	var plugins []string
	seen := map[string]bool{}

	for _, rel := range pluginSearchRoots() {
		dir := filepath.Join(root, rel)
		if _, err := os.Stat(dir); errors.Is(err, fs.ErrNotExist) {
			continue // a search root the tree does not have yet
		}

		err := filepath.WalkDir(dir, func(pathname string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || d.Name() != "register.go" {
				return nil
			}
			// schema/ and yang/ register.go belong to discoverSchemas.
			if base := filepath.Base(filepath.Dir(pathname)); base == schemaDir || base == yangDir {
				return nil
			}
			// A package marked codegen:skip is wired by cmd/ze/main.go and
			// would cycle if the composition root named it.
			skip, readErr := fileHolds(pathname, "codegen:skip")
			if readErr != nil {
				return readErr
			}
			if skip {
				return nil
			}

			imp, relErr := importPathOf(root, module, pathname)
			if relErr != nil {
				return relErr
			}
			if seen[imp] {
				return nil
			}
			seen[imp] = true
			plugins = append(plugins, imp)

			return nil
		})
		if err != nil {
			return nil, err
		}
	}

	slices.Sort(plugins)

	return plugins, nil
}

// discoverSchemas finds the schema packages that register YANG modules: a
// schema/ or yang/ register.go importing config/yang, anywhere under internal/.
// A schema package under internal/plugins is included because its plugin parent
// does not import it.
func discoverSchemas(root, module string) ([]string, error) {
	var imports []string

	err := filepath.WalkDir(filepath.Join(root, "internal"), func(pathname string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if isTestTree(pathname) || d.IsDir() || filepath.Base(pathname) != "register.go" {
			return nil
		}
		if base := filepath.Base(filepath.Dir(pathname)); base != schemaDir && base != yangDir {
			return nil
		}

		imp, relErr := importPathOf(root, module, pathname)
		if relErr != nil {
			return relErr
		}
		// config/yang itself is the registry, not a schema package.
		if strings.HasSuffix(imp, registryPackage) {
			return nil
		}

		holds, readErr := fileHolds(pathname, "config/yang")
		if readErr != nil {
			return readErr
		}
		if holds {
			imports = append(imports, imp)
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	slices.Sort(imports)

	return imports, nil
}

// discoverRPCs finds the packages registering RPCs through
// pluginserver.RegisterRPCs, and drops the ones that would cycle: the plugin
// infrastructure itself, and any package importing the composition root.
func discoverRPCs(root, module string) ([]string, error) {
	var tb textbuf.Buffer
	allPkg := tb.Str(module).Byte('/').Str(allDir).String()
	tb.Reset()
	serverPkg := tb.Str(module).Str("/internal/component/plugin/server").String()

	var found []string

	err := filepath.WalkDir(filepath.Join(root, rpcRoot), func(pathname string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		name := d.Name()
		if d.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			return nil
		}
		if filepath.Base(filepath.Dir(pathname)) == schemaDir {
			return nil
		}

		calls, readErr := callsRegisterRPCs(pathname)
		if readErr != nil {
			return readErr
		}
		if !calls {
			return nil
		}

		imp, relErr := importPathOf(root, module, pathname)
		if relErr != nil {
			return relErr
		}
		found = append(found, imp)

		return nil
	})
	if err != nil {
		return nil, err
	}

	slices.Sort(found)
	found = slices.Compact(found)

	kept := make([]string, 0, len(found))
	for _, imp := range found {
		if imp == allPkg || imp == serverPkg {
			continue
		}
		cycles, readErr := pkgImportsPath(filepath.Join(root, strings.TrimPrefix(imp, module+"/")), "plugin/all")
		if readErr != nil {
			return nil, readErr
		}
		if cycles {
			continue
		}
		kept = append(kept, imp)
	}

	return kept, nil
}

// discoverNamespaces finds the packages calling .RegisterNamespace() through any
// import alias. A package already in the plugin list is left out, because it is
// imported already.
func discoverNamespaces(root, module string, plugins []string) ([]string, error) {
	inPlugins := make(map[string]bool, len(plugins))
	for _, p := range plugins {
		inPlugins[p] = true
	}

	var imports []string
	seen := map[string]bool{}

	err := filepath.WalkDir(filepath.Join(root, "internal"), func(pathname string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		name := d.Name()
		if isTestTree(pathname) || strings.Contains(filepath.ToSlash(pathname), "/internal/le/") ||
			d.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			return nil
		}
		if filepath.Base(filepath.Dir(pathname)) == schemaDir {
			return nil
		}

		holds, readErr := fileHolds(pathname, ".RegisterNamespace(")
		if readErr != nil {
			return readErr
		}
		if !holds {
			return nil
		}

		imp, relErr := importPathOf(root, module, pathname)
		if relErr != nil {
			return relErr
		}
		if inPlugins[imp] || seen[imp] {
			return nil
		}
		seen[imp] = true
		imports = append(imports, imp)

		return nil
	})
	if err != nil {
		return nil, err
	}

	slices.Sort(imports)

	return imports, nil
}

// imports is everything the composition root must blank-import, split into the
// universal file and the per-tag groups.
type imports struct {
	// Plugins, Schemas, RPCs and Namespaces are the universal imports, each
	// sorted, each rendered under its own comment in all.go.
	Plugins    []string
	Schemas    []string
	RPCs       []string
	Namespaces []string
	// ByTag holds the gated imports, keyed by the build tag that gates them.
	ByTag map[string][]string
	// Tags is the manifest, which the constraint of a nested package reads.
	Tags map[string]string
}

// derive reads the tree into what the composition root owes.
func derive(root string) (imports, error) {
	tags, err := loadFeatureTags(root)
	if err != nil {
		return imports{}, err
	}

	module, err := lepath.Module(root)
	if err != nil {
		return imports{}, err
	}

	plugins, err := discoverPlugins(root, module)
	if err != nil {
		return imports{}, err
	}
	schemas, err := discoverSchemas(root, module)
	if err != nil {
		return imports{}, err
	}
	rpcs, err := discoverRPCs(root, module)
	if err != nil {
		return imports{}, err
	}
	namespaces, err := discoverNamespaces(root, module, plugins)
	if err != nil {
		return imports{}, err
	}

	byTag := map[string][]string{}

	return imports{
		Plugins:    filterTagged(tags, plugins, byTag),
		Schemas:    filterTagged(tags, schemas, byTag),
		RPCs:       filterTagged(tags, rpcs, byTag),
		Namespaces: filterTagged(tags, namespaces, byTag),
		ByTag:      byTag,
		Tags:       tags,
	}, nil
}

// allSource renders the universal composition root.
func allSource(in imports) []byte {
	var b textbuf.Buffer

	b.Str(generatedMarker).Str("\n\n")
	b.Str("// Package all imports all internal plugins and schema packages,\n")
	b.Str("// triggering their init() registration.\n")
	b.Str("//\n")
	b.Str("// To add a plugin, create internal/component/bgp/plugins/<name>/register.go with an init()\n")
	b.Str("// that calls registry.Register(). Then run: ./le repository generate\n")
	b.Str("package all\n\n")
	b.Str("import (\n")

	// The schema packages come first: they are infrastructure, and a plugin's
	// config leaves are refused as unknown until its module is registered.
	if len(in.Schemas) > 0 {
		b.Str("\t// Infrastructure schema packages — YANG module registration.\n")
		for _, imp := range in.Schemas {
			b.Str("\t_ \"").Str(imp).Str("\"\n")
		}
		b.Str("\n\t// Plugin packages — plugin + schema registration.\n")
	}

	for _, imp := range in.Plugins {
		b.Str("\t_ \"").Str(imp).Str("\"\n")
	}

	if len(in.Namespaces) > 0 {
		b.Str("\n\t// Event namespace packages -- events.RegisterNamespace registration.\n")
		for _, imp := range in.Namespaces {
			b.Str("\t_ \"").Str(imp).Str("\"\n")
		}
	}

	if len(in.RPCs) > 0 {
		b.Str("\n\t// RPC command packages -- pluginserver.RegisterRPCs registration.\n")
		for _, imp := range in.RPCs {
			b.Str("\t_ \"").Str(imp).Str("\"\n")
		}
	}

	// ")\n", not ")\n\n": a trailing blank line is not gofmt-clean. Keeping the
	// native writer's output formatted means a later formatting pass cannot undo
	// the generated bytes.
	b.Str(")\n")

	return slices.Clone(b.Bytes())
}

// ancestorTagsOfImport answers the tags of every OTHER gated package whose path
// is a segment-aligned ancestor of importPath, sorted.
//
// A gated package nested inside another gate's tree is a DEPENDENT piece: it is
// only ever compiled when the ancestor gate is on, because it imports that
// ancestor's packages. So its blank import must AND every ancestor tag, or a
// build requesting the child tag alone drags the ancestor's whole subtree back
// in. ze_bmp lives at internal/component/bgp/plugins/bmp, under ze_bgp's
// internal/component/bgp, so its import is guarded by ze_bgp && ze_bmp.
//
// EVERY ancestor is collected, not the nearest: a package nested two or more
// gates deep must AND every level, or the constraint fails open at the outer
// ones. Ancestry is per PACKAGE rather than per tag, because a tag can mix
// independent and dependent packages: ze_radius gates internal/component/radius,
// usable alone, and l2tp/plugins/authradius, which needs ze_l2tp.
//
// The result is sorted, so two iteration orders of the tags map answer the same
// set. A tie-break over map order made the chosen ancestor depend on which
// candidate Go yielded first.
func ancestorTagsOfImport(tags map[string]string, importPath, tag string) []string {
	seen := map[string]bool{}

	for suffix, other := range tags {
		if other == tag {
			continue
		}
		at := strings.Index(importPath, suffix)
		if at < 0 {
			continue
		}
		if at > 0 && importPath[at-1] != '/' {
			continue
		}
		rest := importPath[at+len(suffix):]
		if rest != "" && rest[0] != '/' {
			continue
		}
		seen[other] = true
	}

	found := make([]string, 0, len(seen))
	for one := range seen {
		found = append(found, one)
	}
	slices.Sort(found)

	return found
}

// constraintForImport answers the //go:build expression gating one import of a
// tag's group: the tag alone, or "<ancestor> && ... && <tag>" for a package
// nested under one or more OTHER gates. The ancestors come first in sorted
// order with the group's own tag last, so the expression is deterministic and
// closed under every ancestor.
func constraintForImport(tags map[string]string, importPath, tag string) string {
	ancestors := ancestorTagsOfImport(tags, importPath, tag)
	if len(ancestors) == 0 {
		return tag
	}

	var b textbuf.Buffer
	for _, one := range ancestors {
		b.Str(one).Str(" && ")
	}
	b.Str(tag)

	return b.String()
}

// constraintGroups splits a tag's imports by their per-import constraint, and
// answers the constraints in a deterministic order: the plain tag first, then
// the compounds by name. A tag whose packages all share one constraint yields a
// single group.
func constraintGroups(tags map[string]string, tag string, imps []string) (order []string, byConstraint map[string][]string) {
	byConstraint = map[string][]string{}

	for _, imp := range imps {
		c := constraintForImport(tags, imp, tag)
		byConstraint[c] = append(byConstraint[c], imp)
	}

	for c := range byConstraint {
		order = append(order, c)
	}
	slices.SortFunc(order, func(a, b string) int {
		if (a == tag) != (b == tag) {
			if a == tag {
				return -1 // the plain-tag group first
			}
			return 1
		}
		return strings.Compare(a, b)
	})

	return order, byConstraint
}

// taggedFileName answers the generated file of one tag's import group.
func taggedFileName(tag string) string {
	var tb textbuf.Buffer

	return tb.Str("all_").Str(tag).Str(".go").String()
}

// taggedGroupFileName names one constraint group's file. A tag's first (plain,
// or sole) group keeps the historic all_<tag>.go name; a dependent subset of a
// MIXED tag gets all_<tag>_<parent>.go, as all_ze_radius_ze_l2tp.go does for
// authradius under ze_l2tp.
func taggedGroupFileName(tag, constraint string, sole bool) string {
	if sole || constraint == tag {
		return taggedFileName(tag)
	}

	parent, _, _ := strings.Cut(constraint, " && ")

	var tb textbuf.Buffer

	return tb.Str("all_").Str(tag).Byte('_').Str(parent).Str(".go").String()
}

// taggedSource renders one gated group's file: its //go:build constraint and
// the blank imports it carries.
func taggedSource(tag, constraint string, imps []string) []byte {
	var b textbuf.Buffer

	b.Str("// Design: ai/rules/plugins.md -- feature-gated plugin composition\n//\n")
	b.Str(generatedMarker).Str("\n\n")
	b.Str("//go:build ").Str(constraint).Str("\n\n")
	b.Str("// Package all (").Str(tag).Str(" group): build-tag-gated plugin/schema imports,\n")
	b.Str("// dropped from the binary when ").Str(tag).Str(" is absent (per-feature compile-out).\n")
	b.Str("package all\n\n")
	b.Str("import (\n")

	// A package discovered in more than one category is pooled into this group
	// twice. Go tolerates a duplicate blank import; one per package is cleaner,
	// and the caller sorted the list so an adjacent comparison suffices.
	previous := ""
	for i, imp := range imps {
		if i > 0 && imp == previous {
			continue
		}
		previous = imp
		b.Str("\t_ \"").Str(imp).Str("\"\n")
	}

	b.Str(")\n")

	return slices.Clone(b.Bytes())
}

// generated is one file the composition root owes: where it goes, and what it
// must hold.
type generated struct {
	rel  string
	want []byte
}

// files answers every generated file, in the order the check reads them: the
// universal composition root first, then each tag group.
func files(in imports) []generated {
	out := []generated{{rel: allFile, want: allSource(in)}}

	tags := make([]string, 0, len(in.ByTag))
	for tag := range in.ByTag {
		tags = append(tags, tag)
	}
	slices.Sort(tags)

	for _, tag := range tags {
		imps := slices.Clone(in.ByTag[tag])
		slices.Sort(imps)

		order, groups := constraintGroups(in.Tags, tag, imps)
		for _, constraint := range order {
			name := taggedGroupFileName(tag, constraint, len(order) == 1)
			out = append(out, generated{
				rel:  path.Join(allDir, name),
				want: taggedSource(tag, constraint, groups[constraint]),
			})
		}
	}

	return out
}

// isGeneratedTagFile reports whether name is a generated all_<tag>.go carrying
// this tool's marker, which is the only file the write half will remove.
//
// A file that cannot be read is an ERROR rather than "not generated". Answering
// false there leaves a stale composition-root fragment in place, still
// blank-importing a package the manifest no longer gates.
func isGeneratedTagFile(dir, name string) (bool, error) {
	if !strings.HasPrefix(name, "all_") || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
		return false, nil
	}

	return fileHolds(filepath.Join(dir, name), generatedMarker)
}

// strayTagFiles answers every generated all_<tag>.go in the composition root
// that no tag group needs any more.
func strayTagFiles(root string, expected map[string]bool) ([]string, error) {
	dir := filepath.Join(root, allDir)

	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var stray []string
	for _, e := range entries {
		name := e.Name()
		if expected[name] {
			continue
		}
		ours, readErr := isGeneratedTagFile(dir, name)
		if readErr != nil {
			return nil, readErr
		}
		if ours {
			stray = append(stray, name)
		}
	}
	slices.Sort(stray)

	return stray, nil
}

// expectedNames answers the base names of every generated file, for the stray
// comparison.
func expectedNames(owed []generated) map[string]bool {
	names := make(map[string]bool, len(owed))
	for _, one := range owed {
		names[path.Base(one.rel)] = true
	}

	return names
}

// counts answers what the verdict reports about one derivation.
func counts(in imports) Counts {
	return Counts{
		Plugins:     len(in.Plugins),
		Schemas:     len(in.Schemas),
		RPCs:        len(in.RPCs),
		Namespaces:  len(in.Namespaces),
		GatedGroups: len(in.ByTag),
	}
}

// Check reports the FIRST generated file that disagrees with what the tree
// registers. It writes nothing.
//
// It stops at the first because the script does, and the answer is `make
// generate` whichever file it names.
func Check(root string) (CheckReport, error) {
	in, err := derive(root)
	if err != nil {
		return CheckReport{}, err
	}

	owed := files(in)
	report := CheckReport{Counts: counts(in)}
	for _, one := range owed {
		report.Files = append(report.Files, one.rel)
	}

	for i, one := range owed {
		got, readErr := os.ReadFile(filepath.Join(root, filepath.FromSlash(one.rel))) //nolint:gosec // a build tool reads the checkout it was pointed at
		switch {
		case readErr != nil && i == 0:
			// The composition root is the file the whole product needs, and a
			// tree that cannot produce it has a problem the word "stale" does
			// not describe. The read error says what it actually is.
			return report, readErr
		case readErr != nil:
			// A gated group's file, on the other hand, is one this tool writes
			// and removes on its own, so a read failure of any kind is answered
			// by generating it again rather than by stopping. The error is the
			// VERDICT here, not a failure of the check.
			report.Stale, report.Reason = one.rel, reasonMissing

			return report, nil //nolint:nilerr // the read failure IS the verdict this run answers
		case !bytes.Equal(got, one.want):
			report.Stale, report.Reason = one.rel, reasonStale

			return report, nil
		}
	}

	stray, err := strayTagFiles(root, expectedNames(owed))
	if err != nil {
		return report, err
	}
	if len(stray) > 0 {
		report.Stale, report.Reason = path.Join(allDir, stray[0]), reasonUngated
	}

	return report, nil
}

// Write generates the composition root and every tag group, removes the tag
// files no gate needs any more, and answers what it changed.
func Write(root string) (WriteReport, error) {
	in, err := derive(root)
	if err != nil {
		return WriteReport{}, err
	}

	owed := files(in)
	report := WriteReport{Counts: counts(in)}

	for _, one := range owed {
		full := filepath.Join(root, filepath.FromSlash(one.rel))

		got, readErr := os.ReadFile(full) //nolint:gosec // a build tool reads the checkout it was pointed at
		if readErr == nil && bytes.Equal(got, one.want) {
			continue
		}
		if err := os.WriteFile(full, one.want, 0o644); err != nil { //nolint:gosec // generated source
			return WriteReport{}, err
		}
		report.Written = append(report.Written, one.rel)
	}

	stray, err := strayTagFiles(root, expectedNames(owed))
	if err != nil {
		return WriteReport{}, err
	}
	for _, name := range stray {
		if err := os.Remove(filepath.Join(root, allDir, name)); err != nil {
			return WriteReport{}, err
		}
		report.Removed = append(report.Removed, path.Join(allDir, name))
	}

	return report, nil
}
