// Design: docs/architecture/ike/ipsec-9-ikev2-eap-nat.md -- EAP-MSCHAPv2 handler
// Detail: peer.go -- the Peer-Challenge this file pins
//
// VALIDATES: the MS-CHAPv2 Peer-Challenge comes from the operating system's
// cryptographic generator and from nothing else.
// PREVENTS: a Peer-Challenge drawn from a counter or from math/rand.
// TestMSCHAPv2PeerChallengeRandom16 asks only that the field is 16 octets, is not
// all-zero, and differs between two sessions. A per-session counter satisfies all
// three, and a predictable Peer-Challenge lets an attacker precompute the
// NT-Response for a password guess offline.
//
// The test lives beside peer_test.go rather than inside it: that file carries
// `RFC requirement:` tags and the pretool-writeedit hook refuses every edit to a
// tagged test file, an addition included (ai/rules/testing.md).

package eap

import (
	"bytes"
	"crypto/rand"
	"testing"
)

// TestRFC2759PeerChallengeComesFromCryptoRand substitutes the crypto/rand reader
// and requires the Peer-Challenge to be exactly the octets it supplied.
//
// No unit test can prove sixteen octets are random. What a test CAN prove is the
// structural property the requirement rests on: the octets are read from the
// cryptographic generator rather than from any other source.
//
// RFC 2759 Section 4: "The Peer-Challenge field is a 16-octet random number. As
// the name implies, it is generated by the peer and is used in the calculation of
// the NT-Response field, below. Peers need not duplicate Microsoft's algorithm
// for selecting the 16-octet value, but the standard guidelines on randomness
// [1,2,7] SHOULD be observed."
//
// RFC requirement: RFC2759-x-9 positive -- the peer fills its 16-octet
// Peer-Challenge from crypto/rand.Reader: with that reader substituted the field
// is byte for byte what it produced, so no other generator supplies it
// (peer.go handleRequest, MS-CHAPv2 challenge branch).
func TestRFC2759PeerChallengeComesFromCryptoRand(t *testing.T) {
	// The authenticator's own Start draws its 16-octet challenge from the same
	// reader, so the substitution happens after it: what this test judges is the
	// PEER's draw.
	server := &mschapv2Method{password: "pw"}
	challengePkt := server.Start(0x10)
	peer := NewPeerSession(TypeMSCHAPv2, "user", "pw")
	peer.Process(&Packet{Code: CodeRequest, Identifier: 1, Type: TypeIdentity})

	saved := rand.Reader
	t.Cleanup(func() { rand.Reader = saved })

	var marker [16]byte
	for i := range marker {
		marker[i] = byte(0xC0 + i)
	}
	// Filler behind the marker so a draw this test did not expect shows up as a
	// mismatch rather than as an exhausted reader.
	feed := append(bytes.Clone(marker[:]), bytes.Repeat([]byte{0x11}, 256)...)
	rand.Reader = bytes.NewReader(feed)

	res := peer.Process(&Packet{
		Code:       challengePkt.Code,
		Identifier: challengePkt.Identifier,
		Type:       challengePkt.Type,
		TypeData:   challengePkt.TypeData,
	})
	if res.Err != nil {
		t.Fatalf("peer challenge: %v", res.Err)
	}

	if peer.peerChallenge != marker {
		t.Fatalf("Peer-Challenge = % x, want % x (the octets crypto/rand.Reader supplied); it is coming from another source", peer.peerChallenge, marker)
	}

	// The octets the peer put on the wire are the same ones, so the assertion above
	// is about what a server sees and not only about an internal field. The
	// EAP-MSCHAPv2 Response frames OpCode, MS-ID, MS-Length and Value-Size ahead of
	// the 49-octet Value, whose first 16 octets are the Peer-Challenge (RFC 2759
	// Section 4), so it starts at offset 5.
	if res.Response == nil {
		t.Fatal("the peer sent no MS-CHAPv2 Response")
	}
	td := res.Response.TypeData
	if len(td) < 5+16 {
		t.Fatalf("MS-CHAPv2 Response is %d octets, too short to carry the Peer-Challenge", len(td))
	}
	if !bytes.Equal(td[5:5+16], marker[:]) {
		t.Fatalf("the wire Peer-Challenge = % x, want % x", td[5:5+16], marker)
	}
}
