// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-bgp-cmd-cache-api.yang
var ZeBGPCmdCacheAPIYANG string

//go:embed ze-cli-cache-cmd.yang
var ZeCliCacheCmdYANG string
