// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-policyroute-cmd.yang
var ZePolicyrouteCmdYANG string

//go:embed ze-policyroute-conf.yang
var ZePolicyrouteConfYANG string
