// Related: web_assets.go -- the generator these tests drive from its entry point
// Related: plugin_imports_test.go -- repoRoot and the go-run harness reused here

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"io/fs"
	"os"
	osexec "os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

const webAssetsTimeout = 60 * time.Second

// makeRecipe returns the commands `make <target>` would run, without running
// any of them.
//
// The recipe is read from make rather than from the Makefile text, so a target
// moved into an mk/*.mk fragment, or a recipe line built from a variable, still
// answers. `make -n` is safe here because the generate recipe holds no $(MAKE):
// the warning above ze-precommit-verify in the Makefile is about that target alone.
func makeRecipe(t *testing.T, target string) string {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), webAssetsTimeout)
	defer cancel()

	cmd := osexec.CommandContext(ctx, "make", "-n", target)
	cmd.Dir = repoRoot(t)

	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("make -n %s: %v\n%s", target, err, out)
	}

	return string(out)
}

// runWebAssets drives the generator from its entry point and returns its
// combined output with the process error.
func runWebAssets(t *testing.T, args ...string) (string, error) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), webAssetsTimeout)
	defer cancel()

	program := filepath.Join(repoRoot(t), "scripts", "codegen", "web_assets.go")
	cmd := osexec.CommandContext(ctx, "go", append([]string{"run", program}, args...)...)
	cmd.Dir = repoRoot(t)

	out, err := cmd.CombinedOutput()

	return string(out), err
}

// VALIDATES: `make generate` runs scripts/codegen/web_assets.go, so the per-page
// import sets are regenerated by the same command that regenerates every other
// derived file.
// PREVENTS: a generator nobody calls. A page whose component graph changed then
// keeps the import set it had, and the head block loads an asset the page no
// longer uses or drops one it now needs.
func TestGenerateRunsWebAssetsGenerator(t *testing.T) {
	recipe := makeRecipe(t, "generate")

	if !strings.Contains(recipe, "scripts/codegen/web_assets.go") {
		t.Fatalf("`make generate` does not run scripts/codegen/web_assets.go; its recipe is:\n%s", recipe)
	}
}

// VALIDATES: the generated per-page import sets match what the current templ
// component graph derives.
// PREVENTS: a hand edit of the generated file, or a component that gained an
// hx-* attribute after the last generate, shipping a page whose head block
// disagrees with the markup it renders.
func TestGeneratedImportsAreCurrent(t *testing.T) {
	out, err := runWebAssets(t, "--check")
	if err != nil {
		t.Fatalf("scripts/codegen/web_assets.go --check reports the import sets are not current: %v\n%s", err, out)
	}
}

// headBlockFloor is the least number of sources that render a head block. Eight
// render one on 2026-08-15: six templ files in internal/component/web, the one
// looking-glass layout, and the chaos dashboard, which writes its markup in Go.
// A walk that finds fewer has stopped reading the tree, and every assertion
// below it would pass over nothing.
const headBlockFloor = 8

// htmxAttributeInSource finds one htmx attribute in a source file. htmx 4 names
// an extension's attributes with a colon, as hx-sse:connect does.
var htmxAttributeInSource = regexp.MustCompile(`\s(hx-[a-z:-]+)=`)

// derivedPages returns the per-page asset sets the generator prints.
func derivedPages(t *testing.T) map[string][]string {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), webAssetsTimeout)
	defer cancel()

	program := filepath.Join(repoRoot(t), "scripts", "codegen", "web_assets.go")
	cmd := osexec.CommandContext(ctx, "go", "run", program, "--json")
	cmd.Dir = repoRoot(t)

	var errOut bytes.Buffer
	cmd.Stderr = &errOut

	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("scripts/codegen/web_assets.go --json: %v\n%s", err, errOut.String())
	}

	pages := map[string][]string{}
	if err := json.Unmarshal(out, &pages); err != nil {
		t.Fatalf("read the derived per-page asset sets: %v\n%s", err, out)
	}

	return pages
}

// headBlockSources returns every source under internal/ that renders a head
// block, and the markup each one names. A generated file is skipped: it repeats
// what its source already said.
func headBlockSources(t *testing.T) map[string]string {
	t.Helper()

	root := repoRoot(t)
	found := map[string]string{}

	err := filepath.WalkDir(filepath.Join(root, "internal"), func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		name := d.Name()

		switch {
		case d.IsDir(), strings.HasSuffix(name, "_test.go"), strings.HasSuffix(name, "_templ.go"):
			return nil
		case filepath.Ext(name) != ".templ" && filepath.Ext(name) != ".go":
			return nil
		}

		body, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}

		if !strings.Contains(string(body), "<head>") {
			return nil
		}

		relative, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}

		found[filepath.ToSlash(relative)] = string(body)

		return nil
	})
	if err != nil {
		t.Fatalf("walk internal/ for the sources that render a head block: %v", err)
	}

	return found
}

// pagesOf returns the derived sets keyed on one source. A shell serving several
// pages names each one after the # in its key.
func pagesOf(pages map[string][]string, source string) map[string][]string {
	owned := map[string][]string{}

	for key, assets := range pages {
		if key == source || strings.HasPrefix(key, source+"#") {
			owned[key] = assets
		}
	}

	return owned
}

// VALIDATES: the component graph reaches every page ze serves, and a walk that
// parses nothing fails rather than reporting that no page needs an asset.
// PREVENTS: the maintenance tail this design accepts (A-4). The generator reads
// templ syntax, so a templ release that changes a declaration or an invocation
// leaves the walk finding an empty graph. Every set would then be empty, every
// head block would load nothing, and every page would render correctly and do
// nothing in the browser. It also covers A-5: a page whose head block the
// generator never enumerates is a page whose import set nothing checks.
//
// A head block that renders no htmx attribute needs no enumeration, and three
// of them exist: the ze-perf report (internal/perf/report/html.go), the Swagger
// UI page (internal/component/api/rest/server.go) and the head marker this
// package's own scanner declares (internal/test/markupcheck/head.go). None
// loads htmx, and the moment one of them renders an attribute this fails and
// asks for it to be enumerated.
func TestComponentGraphReachesEveryPage(t *testing.T) {
	pages := derivedPages(t)
	sources := headBlockSources(t)

	if len(sources) < headBlockFloor {
		t.Fatalf("the walk found %d sources rendering a head block, want at least %d; it has stopped reading the tree",
			len(sources), headBlockFloor)
	}

	for source, body := range sources {
		named := htmxAttributeInSource.MatchString(body)
		owned := pagesOf(pages, source)

		if len(owned) == 0 {
			if named {
				t.Errorf("%s renders a head block and an htmx attribute, and the generator derives no page "+
					"for it, so nothing checks what that page imports", source)
			}

			continue
		}

		if !named {
			continue
		}

		// The source names an htmx attribute itself, so every page whose head
		// it renders reaches that attribute. An empty set here is the parse
		// finding nothing.
		for key, assets := range owned {
			if len(assets) == 0 {
				t.Errorf("%s names an htmx attribute and the set derived for %s is empty; "+
					"the walk over the templ sources has stopped reading them", source, key)
			}
		}
	}
}

// VALIDATES: a page that renders no htmx attribute imports no htmx asset.
// PREVENTS: the union shipping to every page. The L2TP list and detail pages,
// the sign-in page and the snapshot page render no htmx attribute at all, and
// each one loaded the library until the sets were derived.
func TestPageWithNoHtmxImportsNothing(t *testing.T) {
	pages := derivedPages(t)
	sources := headBlockSources(t)

	empty := 0

	for key, assets := range pages {
		if len(assets) > 0 {
			continue
		}

		empty++

		source, _, _ := strings.Cut(key, "#")

		body, known := sources[source]
		if !known {
			t.Errorf("%s is derived from %s, which renders no head block", key, source)

			continue
		}

		if match := htmxAttributeInSource.FindStringSubmatch(body); match != nil {
			t.Errorf("the set derived for %s is empty and %s renders %s, "+
				"so the page would load nothing and the attribute would do nothing", key, source, match[1])
		}
	}

	if empty == 0 {
		t.Error("no page carries an empty asset set, so this check read nothing; " +
			"every page ze serves would be loading the library whether it uses it or not")
	}
}
