// Code generated by ./le yang glue write; DO NOT EDIT.

package yang

import _ "embed"

//go:embed ze-firewall-cmd.yang
var ZeFirewallCmdYANG string

//go:embed ze-firewall-conf.yang
var ZeFirewallConfYANG string
